/** TOOL_ONLY synthetic HTTP/component data, never a financial execution or ledger proof. */
import type { DynamicGoalReserve, DynamicReserve } from '../api/dynamic-goal-reserve';
import { modelGoal, versionId } from './full-goal-fixture';
export const dynamicGoal = modelGoal;
export const dynamicMoneyKeys = ['current_owned_cents', 'current_month_contributed_cents', 'remaining_goal_cents', 'excess_owned_cents', 'uncapped_gross_pace_cents', 'dynamic_month_total_cents', 'nominal_month_target_cents', 'pace_delta_from_nominal_cents', 'eligible_available_income_cents', 'independently_protected_budget_cents', 'desired_additional_cents', 'suggested_additional_cents', 'minimum_shortfall_cents', 'guarantee_shortfall_cents', 'overdue_days', 'deferral_cost_to_date_cents', 'progress_basis_points', 'remaining_calendar_month_slots'] as const;
export function dynamicGoalFixture(state: DynamicGoalReserve['state'] = 'COMPUTED', status: DynamicReserve['status'] = 'READY'): DynamicGoalReserve {
  const reserve: DynamicReserve = { algorithm_version: 'remaining-month-gross-pacing-v1', goal_id: modelGoal.id, policy_version_id: versionId, period: '2026-10', status, grants_authority: false, preview_only: true, future_income_included_cents: 0, input_hash: 'd'.repeat(64), current_owned_cents: 20003, current_month_contributed_cents: 10001, remaining_goal_cents: 180027, excess_owned_cents: 0, progress_basis_points: 1000, remaining_calendar_month_slots: 3, uncapped_gross_pace_cents: 63343, dynamic_month_total_cents: 40007, nominal_month_target_cents: 30001, pace_delta_from_nominal_cents: 10006, eligible_available_income_cents: 50009, independently_protected_budget_cents: 49007, desired_additional_cents: 30006, suggested_additional_cents: 30006, minimum_shortfall_cents: 0, guarantee_shortfall_cents: 0, overdue_days: 0, deferral_cost_to_date_cents: 0, actual_completion_date: null, reasons: ['HTTP_UNIT_FIXTURE_NOT_FINANCIAL_PROOF', 'OWNED_FUNDS_ARE_NOT_NEW_INCOME'] };
  if (['EXPIRED_POLICY', 'INACTIVE_POLICY', 'LIQUIDITY_RISK', 'INSUFFICIENT_EVIDENCE'].includes(status)) for (const key of dynamicMoneyKeys) reserve[key] = null;
  if (['HARD_GUARANTEE_SHORTFALL', 'DEADLINE_BLOCKED'].includes(status)) { reserve.suggested_additional_cents = null; reserve.guarantee_shortfall_cents = 9994; }
  return { schema_version: 'verified-dynamic-goal-reserve-v1', simulation: true, grants_authority: false, user_id: '10000000-0000-0000-0000-000000000001', goal_id: modelGoal.id, as_of: '2026-10-05T12:00:00Z', policy_effective_status: state === 'EXPIRED' ? 'EXPIRED' : state === 'INACTIVE' ? 'SUSPENDED' : 'ACTIVE', state, reserve: state === 'COMPUTED' ? reserve : null, protection_scope: 'ALL_ORIGINAL_365_DAY_RESERVES_RETAINED', source_evidence_ids: ['10000000-0000-0000-0000-000000000011'], source_issues: state === 'COMPUTED' ? [] : [{ code: 'UNIT_DYNAMIC_SOURCE_NOT_PROVEN', source_ref: 'synthetic-current-goal-original', message: 'HTTP夹具：缺原模型或贡献证据，不是实测金融结果' }], input_hash: 'c'.repeat(64), limitations: ['HTTP_UNIT_FIXTURE_NOT_PRODUCT_ACCEPTANCE', '保留全部原365日目标最小保护；尚未释放重复保护。', '动态金额未接入执行；只读规划不消费实际收入。'] };
}
