/** TOOL/HTTP synthetic arithmetic fixture. No bank, PostgreSQL or actual financial projection. */
import type { FinancialChangePreview, FinancialPreviewBody } from '../api/full-policy-financial-preview';
import { spendingHash } from '../api/spending-evidence';
import { annualFixture } from './annual-fixture';
export const financialPolicy = '77000000-0000-0000-0000-000000000001';
export const financialVersion = '77000000-0000-0000-0000-000000000002';
export const financialUser = '77000000-0000-0000-0000-000000000003';
export const financialProduct = '77000000-0000-0000-0000-000000000004';
const position = '77000000-0000-0000-0000-000000000005';
export const financialCandidate = () => ({ type: 'dated_expense', window: { start: '2026-10-12', end: '2026-10-15' }, amount: { min_cents: 0, target_cents: 175, max_cents: 350 } });
export const financialBody = (): FinancialPreviewBody => ({ expected_version_id: financialVersion, configuration: financialCandidate() });
export async function financialPreviewFixture(unknown = false): Promise<FinancialChangePreview> {
  const before = annualFixture().annual_projection; before.max_allocatable_by_product = { [financialProduct]: 79001 };
  const trace = before.calculation_trace.map((row) => ({ ...structuredClone(row), cash_cents: row.cash_cents - 150, margin_cents: row.margin_cents - 150 }));
  const input = 'b'.repeat(64); const beforeConfig = financialCandidate(); beforeConfig.amount = { min_cents: 0, target_cents: 100, max_cents: 200 };
  return { simulation: true, hypothetical: true, grants_authority: false, policy_id: financialPolicy, epoch_id: '77000000-0000-0000-0000-000000000006', expected_version_id: financialVersion, as_of: '2026-10-05T12:00:00Z', configuration_hash: await spendingHash(financialCandidate()), current_configuration_hash: await spendingHash(beforeConfig), before_configuration: beforeConfig, after_configuration: financialCandidate(), changed_fields: ['amount.max_cents', 'amount.target_cents'], current_fact_digest: 'c'.repeat(64), reference_snapshots: [], original_action_ids: ['77000000-0000-0000-0000-000000000007'], original_position_ids: [position], action_impact: 'ORIGINAL_ACTIONS_UNCHANGED_REQUIRES_FRESH_RECOMPUTATION_AFTER_CONFIRMATION',
    financial_impact: { protocol: 'full-policy-financial-impact-v1', simulation: true, hypothetical: true, grants_authority: false, writes_policy_or_bank: false, future_income_cents: 0, horizon_days: 365, initial_day_and_365_future_days: true, status: unknown ? 'UNKNOWN' : 'PROJECTED', basis: 'FUTURE_ONLY_CONSERVATIVE_UNPAID_REPLACEMENT', before, after: unknown ? null : { status: 'READY', minimum_margin_cents: 78851, safe_idle_cents: 78851, max_allocatable_by_product: { [financialProduct]: 78851 }, calculation_trace: trace, source_account_limitations: [], curve_hash: await spendingHash({ protocol: 'hypothetical-full-curve-v1', input_hash: input, trace }), financial_capacity_is_authority: false }, delta_safe_idle_cents: unknown ? null : -150, delta_minimum_margin_cents: unknown ? null : -150, delta_max_allocatable_by_product: unknown ? null : { [financialProduct]: -150 },
      goals: unknown ? [] : [{ goal_id: '77000000-0000-0000-0000-000000000008', current_owned_cash_cents: 15007, current_owned_principal_cents: 23009, current_allocation_delta_cents: 0, current_principal_delta_cents: 0, future_allocation_cents: null, future_allocation_status: 'UNKNOWN_NO_CANDIDATE_GOAL_SOLVER', original_evidence_ids: ['77000000-0000-0000-0000-000000000009'] }],
      positions: unknown ? [] : [{ position_id: position, goal_id: null, original_recorded_principal_cents: 23009, current_outstanding_principal_cents: 0, current_principal_delta_cents: 0, original_status: 'REDEEMED', original_principal_available_at: null, original_evidence_ids: [], future_disposition_status: 'UNKNOWN_NO_CANDIDATE_ACTION_GENERATION' }], candidate_commitments: [], retained_original_occurrence_ids: [], reasons: unknown ? ['TEMPLATE_OR_SOURCE_NOT_PROVEN_SYNTHETIC'] : [], input_hash: input, limitations: ['HTTP_SYNTHETIC_NOT_FINANCIAL_PROOF'] } };
}
