/** SYNTHETIC_HTTP_UNIT_ONLY. No bank/PG/USER/browser result was observed. */
import type { PaymentAction, PaymentConsent, PaymentIntent, PaymentLookup, PaymentPrepared, PaymentPreview, PaymentReceipt, PaymentScope } from '../api/full-payment-relations';
import { preparePaymentIntent, scopeRequest } from '../api/full-payment-relations';
import { releaseHash, releaseUUID5 } from '../api/goal-release-authorizations';
import { localActorFixture } from './local-actor-fixture';
import { fullPolicyFixture, fullPolicyId, fullVersionId, fullEpochId, fullUserId } from './full-policy-fixture';
import { policyFixture, policyId, versionId } from './policy-fixture';
import { boundaryFixture } from './demo-fixture';
export const paymentTime = '2026-10-05T12:01:00Z', paymentAccount = '61000000-0000-4000-8000-000000000001', paymentEvidence = '61000000-0000-4000-8000-000000000002', paymentActionId = '61000000-0000-4000-8000-000000000003';
export async function paymentFixture(auto = false) {
  const identity = localActorFixture(Date.parse('2026-10-05T12:00:00Z')); identity.principal.user_id = fullUserId;
  const common = { payee_id: 'SYNTHETIC_BANK_KNOWN_LANDLORD', amount_rule: { kind: 'exact' as const, amount_cents: 10003 }, due_day: 5, prepare_days_before: 0, auto_execute: auto };
  const original = policyFixture('recurring_obligation'); original.name = '合成原周期关系'; original.current_version!.configuration = { type: 'recurring_obligation', name: original.name, ...common, priority: { importance: 100, minimum_cents: 10003, reducible: false, deferrable: false }, valid_from: null, valid_until: '2026-12-01' }; original.current_version!.content_hash = await releaseHash(original.current_version!.configuration);
  const full = fullPolicyFixture(); full.template_name = 'PeriodicTransferPolicy'; full.name = '合成Full周期关系'; full.current_version.configuration = { type: 'periodic_transfer', name: full.name, ...common, source_account_id: paymentAccount, single_action_cap_cents: 10003, valid_from: null, valid_until: '2026-12-01' }; full.current_version.content_hash = await releaseHash(full.current_version.configuration); full.current_version.valid_until = '2026-12-01T00:00:00Z';
  const scope: PaymentScope = { user_id: fullUserId, epoch_id: fullEpochId, full_policy_id: fullPolicyId, full_version_id: fullVersionId, full_configuration_hash: full.current_version.content_hash, original_policy_id: policyId, original_version_id: versionId, original_configuration_hash: original.current_version!.content_hash, payee_id: common.payee_id, payee_evidence_id: paymentEvidence, payee_evidence_hash: 'a'.repeat(64), source_account_id: paymentAccount, source_account_identity_hash: 'b'.repeat(64), amount_rule: common.amount_rule, due_day: 5, single_action_cap_cents: 10003, auto_execute: auto, timezone: 'Asia/Shanghai', valid_from: '2026-10-05T12:00:00Z', valid_until: '2026-12-01T00:00:00Z', full_planning_bank_authority: false, creates_original_mvp_permission: false };
  const preview: PaymentPreview = { simulation: true, scope, scope_hash: await releaseHash(scope), preview_only: true, grants_authority: false, original_mvp_permission_reused: true };
  return { identity, original, full, scope, preview };
}
export async function paymentIntentFixture(kind: PaymentIntent['kind'] = 'START', auto = false): Promise<PaymentIntent> {
  const f = await paymentFixture(auto), start = await releaseUUID5('d4d1c4a1-bc4b-5a12-b073-aafdfc133e8f', `${f.scope.user_id}:${f.scope.epoch_id}:UNIT_START`), authorization = await releaseUUID5('d4d1c4a1-bc4b-5a12-b073-aafdfc133e8f', `${f.scope.user_id}:${f.scope.epoch_id}:UNIT_CONFIRM`);
  if (kind === 'START') return preparePaymentIntent(kind, f.scope, { ...scopeRequest(f.scope), idempotency_key: 'UNIT_START' });
  if (kind === 'CONFIRM') return preparePaymentIntent(kind, f.scope, { expected_epoch_id: f.scope.epoch_id, reviewed_scope_hash: f.preview.scope_hash, accepted: true, reason: '合成明确关系复核', idempotency_key: 'UNIT_CONFIRM' }, { start_command_id: start });
  if (kind === 'PREPARE') return preparePaymentIntent(kind, f.scope, { expected_epoch_id: f.scope.epoch_id, period: '2026-10', idempotency_key: 'UNIT_PREPARE' }, { authorization_id: authorization });
  const action = await paymentActionFixture(f.scope);
  return preparePaymentIntent(kind, f.scope, kind === 'ACTION_CONFIRM' ? { expected_epoch_id: f.scope.epoch_id, reviewed_effect_hash: action.effect_hash, accepted: true } : { expected_epoch_id: f.scope.epoch_id }, { authorization_id: authorization, action });
}
export async function paymentReceiptFixture(intent: PaymentIntent, status: PaymentReceipt['current_scope_status'] = 'CURRENT'): Promise<PaymentReceipt> {
  const f = await paymentFixture(intent.scope.auto_execute), original_request = intent.kind === 'START' ? intent.body : { start_command_id: intent.start_command_id, confirmation: intent.body }, key = (intent.body as { idempotency_key: string }).idempotency_key;
  const original: PaymentReceipt['original'] = { protocol: 'full-payment-relation-v1', command_id: await releaseUUID5('d4d1c4a1-bc4b-5a12-b073-aafdfc133e8f', `${intent.user_id}:${intent.epoch_id}:${key}`), user_id: intent.user_id, epoch_id: intent.epoch_id, kind: intent.kind as 'START' | 'CONFIRM', idempotency_key: key, start_command_id: intent.start_command_id, original_request, request_hash: await releaseHash({ user_id: intent.user_id, kind: intent.kind, request: original_request }), principal_at_command: f.identity.principal, scope: intent.scope, scope_hash: await releaseHash(intent.scope), recorded_at: paymentTime, creates_original_mvp_permission: false, transfers_funds: false };
  return { simulation: true, original, evidence_id: await releaseUUID5(original.command_id, 'evidence'), evidence_hash: await releaseHash(original), trace_hash: 'f'.repeat(64), idempotent_replay: false, current_scope_status: status, receipt_is_current_authority: false, economic_effect_verified: false, transfers_funds: false };
}
export async function paymentLookupFixture(intent: PaymentIntent, found = true): Promise<PaymentLookup> { return { simulation: true, user_id: intent.user_id, epoch_id: intent.epoch_id, idempotency_key: (intent.body as { idempotency_key: string }).idempotency_key, status: found ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', original: found ? await paymentReceiptFixture(intent) : null, replacement_allowed: false }; }
export async function paymentActionFixture(scope: PaymentScope, state: 'PLANNED' | 'UNKNOWN' | 'SUCCEEDED' = 'PLANNED'): Promise<PaymentAction> {
  const effect: PaymentAction['effect'] = { simulation: true, operation_id: paymentActionId, user_id: scope.user_id, business_key: `PAY_RECURRING:${scope.original_policy_id}:2026-10`, action_type: 'PAY_RECURRING', amount_cents: 10003, cash_uses: [{ account_id: scope.source_account_id, amount_cents: 10003 }], income_uses: [], destination_account_id: null, goal_id: null, policy_id: scope.original_policy_id, policy_version_id: scope.original_version_id, policy_version_ids: [scope.original_version_id], liability: { kind: 'occurrence', policy_id: scope.original_policy_id, period: '2026-10', final_total_cents: null, evidence_ids: [paymentEvidence] }, payee_id: scope.payee_id, payee_evidence_id: paymentEvidence, product_id: null, product_version_number: null, terms_digest: null, position_id: null, position_account_id: null, return_account_id: null, purchase_exit: null, original_policy_version_id: null, fee_cents: 0, loss_cents: 0, net_cents: null, quote_id: null, settlement_delay_days: 0, latest_arrival_at: null, valid_from: paymentTime, expires_at: '2026-10-05T12:06:00Z' };
  const hash = await releaseHash(effect);
  return { simulation: true, user_id: scope.user_id, action_id: paymentActionId, decision_run_id: '61000000-0000-4000-8000-000000000004', status: state, autonomy_level: scope.auto_execute ? 'AUTO_EXECUTE' : 'ASK_ONCE', effect, effect_hash: hash, prepared_at: paymentTime, as_of: paymentTime, prepared_validation: { simulation: true, financial_only: true, status: 'CONFIRMATION_REQUIRED', effect_hash: hash, baseline_boundary: boundaryFixture(), reasons: ['SYNTHETIC_HTTP_ONLY'] }, bank_status: state === 'SUCCEEDED' ? 'SETTLED' : state === 'UNKNOWN' ? 'UNKNOWN' : null, receipt: state === 'SUCCEEDED' ? { simulation: true, receipt_id: '61000000-0000-4000-8000-000000000005', action_id: paymentActionId, bank_operation_id: paymentActionId, status: 'SUCCEEDED', executed_cents: 10003, fee_cents: 0, loss_cents: 0, posting_ids: [6, 7, 8].map((v) => `61000000-0000-4000-8000-00000000000${v}`), occurred_at: paymentTime, reconciled_at: null } : null };
}
export async function paymentPreparedFixture(intent: PaymentIntent, found = true): Promise<PaymentPrepared> {
  const action = await paymentActionFixture(intent.scope), authorization = await paymentReceiptFixture(await paymentIntentFixture('CONFIRM', intent.scope.auto_execute));
  return { simulation: true, user_id: intent.user_id, authorization_id: intent.authorization_id!, idempotency_key: (intent.body as { idempotency_key: string }).idempotency_key, status: found ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', original_binding: found ? { protocol: 'full-payment-action-binding-v1', user_id: intent.user_id, epoch_id: intent.epoch_id, action_id: action.action_id, authorization_id: intent.authorization_id!, authorization_evidence_id: await releaseUUID5(intent.authorization_id!, 'evidence'), authorization_evidence_hash: authorization.evidence_hash, scope: intent.scope, scope_hash: await releaseHash(intent.scope), period: (intent.body as { period: string }).period, original_prepare_request: intent.body as NonNullable<PaymentPrepared['original_binding']>['original_prepare_request'], original_effect_hash: action.effect_hash, recorded_at: paymentTime } : null, original_action: found ? action : null, replacement_allowed: false };
}
export async function paymentConsentFixture(intent: PaymentIntent, found = true): Promise<PaymentConsent> {
  const f = await paymentFixture(); return { simulation: true, action_id: intent.action!.action_id, status: found ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', original: found ? { protocol: 'full-payment-user-action-consent-v1', user_id: intent.user_id, epoch_id: intent.epoch_id, action_id: intent.action!.action_id, original_effect_hash: intent.action!.effect_hash, original_confirmation_evidence_id: await releaseUUID5(intent.action!.action_id, `confirmation:${intent.action!.effect_hash}`), principal_at_confirmation: f.identity.principal, confirmed_at: paymentTime, accepted: true } : null, original_request: found ? intent.body as NonNullable<PaymentConsent['original_request']> : null, replacement_allowed: false };
}
