/** TOOL_ONLY synthetic HTTP records. Never a PG, bank or experiment result. */
import { createHash } from 'node:crypto';
import type { AssetConfirm, AssetExecute, AssetIntent, AssetLookup, AssetPortfolio, AssetPrepare, AssetPreview, AssetResponse } from '../api/full-asset-execution';
import { assetCanonicalJson } from '../api/full-asset-execution';
import { annualFixture } from './annual-fixture';
import { assetPlanFixture, productBinding } from './full-products-fixture';
import { fullAnnualFixture } from './full-annual-fixture';
import { actionFixture } from './demo-fixture';
export const assetId = (number: number) => `91000000-0000-4000-8000-${String(number).padStart(12, '0')}`;
export const assetUser = annualFixture().user_id;
export const assetEpoch = assetId(1), assetPortfolioId = assetId(2), assetMvpId = assetId(3), assetMvpVersion = assetId(4);
export const assetFixtureHash = (value: unknown) => createHash('sha256').update(assetCanonicalJson(value), 'utf8').digest('hex');
export function assetPrepareFixture(): AssetPrepare { const planning = assetPlanFixture(); return { full_policy_id: planning.policy_id, expected_full_policy_version_id: planning.allocation!.policy_version_id, mvp_asset_policy_id: assetMvpId, expected_mvp_policy_version_id: assetMvpVersion, goal_id: null, expected_goal_policy_version_id: null, expected_epoch_id: assetEpoch, idempotency_key: 'TOOL_ONLY_PORTFOLIO_001', planning_mode: 'PORTFOLIO' }; }
export function assetFullConfiguration(): AssetPortfolio['full_configuration'] {
  return { type: 'asset_authorization', name: 'TOOL_ONLY 原整组范围', valid_from: null, valid_until: null, scope: 'general_idle_funds', goal_id: null, allowed_asset_classes: ['FIXED_DEPOSIT_30D'], max_auto_managed_cents: 79001, single_action_cap_cents: 67003, max_redemption_delay_days: 0, max_lock_days: 30, max_principal_risk_level: 0, allow_auto_recovery_without_penalty: true, allow_early_withdrawal_with_penalty: false };
}
export function assetPlanningFixture(portfolio = assetPortfolioFixture()) {
  const planning = assetPlanFixture(); planning.user_id = assetUser;
  const firstTerms = planning.catalogue.products[0]!, firstCandidate = planning.allocation!.candidates[0]!, firstPlan = planning.allocation!.batches[0]!;
  planning.catalogue.products = portfolio.batches.map((batch) => ({ ...firstTerms, product_id: batch.catalogue.product_id, terms_digest: batch.catalogue.terms_digest }));
  planning.catalogue.bindings = portfolio.batches.map((batch) => ({ ...batch.catalogue }));
  planning.allocation!.candidates = portfolio.batches.map((batch) => ({ ...firstCandidate, product_id: batch.catalogue.product_id, terms_digest: batch.catalogue.terms_digest, exit_plan: structuredClone(batch.command.effect.purchase_exit!) }));
  planning.allocation!.batches = portfolio.batches.map((batch) => ({ ...firstPlan, product_id: batch.catalogue.product_id, terms_digest: batch.catalogue.terms_digest, amount_cents: batch.command.effect.amount_cents, cash_uses: structuredClone(batch.command.effect.cash_uses!), exit_plan: structuredClone(batch.command.effect.purchase_exit!), net_simulated_yield_cents: 1 }));
  planning.allocation!.total_purchase_cents = portfolio.total_purchase_cents; planning.allocation!.purchase_count = portfolio.batches.length; planning.allocation!.net_simulated_yield_cents = portfolio.batches.length;
  return planning;
}
export function assetPortfolioFixture(request = assetPrepareFixture()): AssetPortfolio {
  const time = annualFixture().as_of; const expires = new Date(Date.parse(time) + 900_000).toISOString();
  const batches = [1, 2].map((number) => {
    const catalogue = productBinding(); if (number === 2) { catalogue.product_id = assetId(20); catalogue.catalogue_version_id = assetId(21); }
    const base = actionFixture().effect;
    const effect = { ...base, operation_id: assetId(10 + number), user_id: assetUser, business_key: `TOOL_ONLY_PURCHASE_${number}`, action_type: 'PURCHASE_ASSET' as const, amount_cents: 10001 + number, cash_uses: [{ account_id: assetId(30), amount_cents: 10001 + number }], income_uses: [], goal_id: null, policy_id: assetMvpId, policy_version_id: assetMvpVersion, policy_version_ids: [assetMvpVersion], product_id: catalogue.product_id, terms_digest: catalogue.terms_digest, position_id: assetId(40 + number), position_account_id: assetId(50), return_account_id: assetId(30), product_version_number: 1, valid_from: time, expires_at: expires, fee_cents: 0, loss_cents: 0, net_cents: null, quote_id: null, original_policy_version_id: null, purchase_exit: { kind: 'FIXED_MATURITY' as const, request_at: null, principal_available_at: '2026-11-04T12:00:00Z', earning_days: 30, liquidity_days: 30, terms_digest: catalogue.terms_digest }, latest_arrival_at: '2026-11-04T12:15:00Z' };
    return { batch_number: number, action_id: effect.operation_id, bank_idempotency_key: `full-asset:${assetPortfolioId}:batch:${number}`, catalogue, command: { effect, effect_hash: assetFixtureHash(effect) } };
  });
  const value = { protocol: 'full-asset-execution-portfolio-v1' as const, simulation: true as const, portfolio_id: assetPortfolioId, user_id: assetUser, epoch_id: assetEpoch, prepared_at: time, expires_at: expires, original_request: request, client_request_hash: assetFixtureHash(request), full_policy_content_hash: assetFixtureHash(assetFullConfiguration()), original_mvp_configuration_hash: 'b'.repeat(64), original_planning_response_hash: 'd'.repeat(64), original_planning_input_hash: 'd'.repeat(64), full_configuration: assetFullConfiguration(), total_purchase_cents: batches.reduce((sum, batch) => sum + batch.command.effect.amount_cents, 0), batches, combined_original_boundary: annualFixture().annual_projection, combined_full_protection_hash: 'e'.repeat(64), source_evidence_ids: [], bank_authority: false as const, funds_reserved: false as const, cross_operation_atomicity: 'NOT_AVAILABLE' as const, financial_experiment_verified: false as const };
  return { ...value, portfolio_hash: assetFixtureHash(value) } as unknown as AssetPortfolio;
}
export function assetConfirmFixture(portfolio = assetPortfolioFixture()): AssetConfirm { return { accepted: true, expected_epoch_id: assetEpoch, reviewed_portfolio_hash: portfolio.portfolio_hash, idempotency_key: 'TOOL_ONLY_CONFIRM_001' }; }
export function assetExecuteFixture(number = 1, portfolio = assetPortfolioFixture()): AssetExecute { return { accepted: true, expected_epoch_id: assetEpoch, reviewed_portfolio_hash: portfolio.portfolio_hash, expected_batch_number: number, expected_action_id: portfolio.batches[number - 1]!.action_id }; }
export function assetResponseFixture(stage: 'PREPARED' | 'CONFIRMED' | 'UNKNOWN' | 'SETTLED' = 'PREPARED', portfolio = assetPortfolioFixture(), consentBody = assetConfirmFixture(portfolio)): AssetResponse {
  const content = { protocol: 'full-asset-portfolio-consent-v1', simulation: true, user_id: assetUser, portfolio_id: assetPortfolioId, epoch_id: assetEpoch, portfolio_hash: portfolio.portfolio_hash, client_request_hash: portfolio.client_request_hash, accepted: true, confirmed_at: portfolio.prepared_at, valid_until: portfolio.expires_at };
  const evidenceHash = assetFixtureHash(content); const confirmed = stage !== 'PREPARED';
  return { schema_version: 'full-asset-execution-v1', simulation: true, user_id: assetUser, epoch_id: assetEpoch, as_of: portfolio.prepared_at, original_portfolio: portfolio, original_request_hash: portfolio.client_request_hash, state: stage === 'PREPARED' ? 'PREPARED_UNRESERVED' : stage === 'UNKNOWN' ? 'UNRESOLVED' : stage === 'SETTLED' ? 'PARTIALLY_SETTLED' : 'CONFIRMED_UNRESERVED', original_consent_id: confirmed ? assetId(60) : null, original_consent_evidence_id: confirmed ? assetId(61) : null, original_consent_verified: confirmed, original_consent_evidence_status: confirmed ? 'CURRENT_EVIDENCE_MATCHED' : 'NOT_RECORDED', original_consent: confirmed ? { consent_id: assetId(60), user_id: assetUser, epoch_id: assetEpoch, portfolio_id: assetPortfolioId, idempotency_key: consentBody.idempotency_key, original_request: consentBody, request_hash: assetFixtureHash(consentBody), portfolio_hash: portfolio.portfolio_hash, evidence_id: assetId(61), evidence_hash: evidenceHash, original_evidence: { id: assetId(61), user_id: assetUser, source_type: 'USER_FULL_ASSET_PORTFOLIO_CONFIRMATION', source_ref: assetPortfolioId, evidence_level: 'USER_CONFIRMED_ACTION', content, content_hash: evidenceHash }, current_evidence_status: 'CURRENT_EVIDENCE_MATCHED', current_evidence_verified: true, receipt_is_current_authority: false, current_authority_assessed: false } : null, current_epoch_open: true,
    batches: portfolio.batches.map((batch) => { const action = actionFixture(); action.user_id = assetUser; action.action_id = batch.action_id; action.decision_run_id = assetId(70 + batch.batch_number); action.effect = structuredClone(batch.command.effect); action.effect_hash = batch.command.effect_hash; action.prepared_at = portfolio.prepared_at; action.as_of = portfolio.prepared_at; action.prepared_validation.effect_hash = action.effect_hash; action.status = confirmed ? 'AUTHORIZED' : 'PLANNED'; action.bank_status = null; action.receipt = null;
      if (batch.batch_number === 1 && stage === 'UNKNOWN') { action.status = 'UNKNOWN'; action.bank_status = 'UNKNOWN'; }
      if (batch.batch_number === 1 && stage === 'SETTLED') { action.status = 'SUCCEEDED'; action.bank_status = 'SETTLED'; action.receipt = { simulation: true, receipt_id: assetId(80), action_id: batch.action_id, bank_operation_id: assetId(81), status: 'SETTLED', executed_cents: batch.command.effect.amount_cents, fee_cents: 0, loss_cents: 0, posting_ids: [assetId(82)], occurred_at: portfolio.prepared_at, reconciled_at: null }; }
      return { batch_number: batch.batch_number, action_id: batch.action_id, bank_idempotency_key: batch.bank_idempotency_key, original_action: action, original_request_hash: 'f'.repeat(64), original_trace_verified: true, current_action_missing: false, receipt_is_current_authority: false }; }), all_original_service_receipts_verified: false, bank_authority: false, funds_reserved: false, reservation_scope: 'WHOLE_UNRESERVED_CHILD_CLAIMS_USE_ORIGINAL_PIPELINE', cross_operation_atomicity: 'NOT_AVAILABLE', current_authority_assessed: false, receipt_is_current_authority: false, economic_experiment_verified: false };
}
export function assetPreviewFixture(unknown = false, body = assetPrepareFixture()): AssetPreview { const portfolio = assetPortfolioFixture(body); return { schema_version: 'full-asset-execution-preview-v1', simulation: true, user_id: assetUser, epoch_id: assetEpoch, as_of: portfolio.prepared_at, original_request: portfolio.original_request, state: unknown ? 'UNKNOWN' : 'READY_TO_REVIEW', original_full_planning: assetPlanningFixture(portfolio), original_full_protection: fullAnnualFixture(), portfolio: unknown ? null : portfolio, reasons: unknown ? ['TOOL_ONLY_SOURCE_NOT_PROVEN'] : [], bank_authority: false, funds_reserved: false, persisted: false, financial_experiment_verified: false, execution_support: 'DURABLE_ORIGINAL_PURCHASE_CONSUMER_REQUIRES_SHARED_GUARDS', limitations: ['TOOL_ONLY_SYNTHETIC_NO_BANK_EXECUTION'] } as unknown as AssetPreview; }
export function assetLookupFixture(intent: AssetIntent, found = true, stage: 'PREPARED' | 'CONFIRMED' = intent.kind === 'CONFIRM' ? 'CONFIRMED' : 'PREPARED'): AssetLookup {
  if (!('idempotency_key' in intent.body)) throw new Error('TOOL_ONLY_FIXED_EXECUTE_HAS_NO_COMMAND_KEY');
  return { simulation: true, user_id: assetUser, epoch_id: assetEpoch, idempotency_key: intent.body.idempotency_key, status: found ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', command_kind: found ? intent.kind as 'PREPARE' | 'CONFIRM' : null, original_request: found ? intent.body as AssetPrepare | AssetConfirm : null, request_hash: found ? intent.request_hash : null, original: found ? assetResponseFixture(stage) : null, not_found_is_final: false, replacement_allowed: false };
}
