/** TOOL_ONLY synthetic HTTP/component inputs. No FULL financial, PG or bank evidence. */
import type { FullAnnualPlanning } from '../api/full-annual';
import { annualFixture } from './annual-fixture';
export const fullDatedId = '20000000-0000-0000-0000-000000000001';
export const fullPeriodicId = '20000000-0000-0000-0000-000000000002';
export const fullSeasonalId = '20000000-0000-0000-0000-000000000003';
export const periodicAccountId = '20000000-0000-0000-0000-000000000020';
export function fullAnnualFixture(unknown = false, sourceRisk = false): FullAnnualPlanning {
  const original = annualFixture(); const digest = 'c'.repeat(64); const datedVersion = '20000000-0000-0000-0000-000000000011'; const periodicVersion = '20000000-0000-0000-0000-000000000012'; const seasonalVersion = '20000000-0000-0000-0000-000000000013'; const evidence = '20000000-0000-0000-0000-000000000030';
  const source = (policy_id: string, version_id: string, template_name: FullAnnualPlanning['full_policy_sources'][number]['template_name'], configuration: Record<string, unknown>): FullAnnualPlanning['full_policy_sources'][number] => ({ policy_id, version_id, template_name, version_number: 1, configuration, content_hash: digest, confirmation: { accepted: true, reviewed_hash: digest, fixture: 'TOOL_ONLY_NOT_PRODUCT_PROOF' }, reference_snapshots: [], confirmed_at: '2026-10-05T11:00:00Z', valid_from: '2026-10-05T11:00:00Z', valid_until: null, effective_status: 'ACTIVE', planning_confirmation_valid: true, references_current: true, evidence_ids: [evidence], protected_references: [] });
  const sources = [source(fullDatedId, datedVersion, 'DatedExpensePolicy', { type: 'dated_expense', window: { start: '2026-12-31', end: '2027-01-02' }, amount: { min_cents: 3001, target_cents: 5001, max_cents: 7001 }, must_not_reduce_policy_ids: [] }), source(fullPeriodicId, periodicVersion, 'PeriodicTransferPolicy', { type: 'periodic_transfer', source_account_id: periodicAccountId, payee_id: 'SYNTHETIC_RECEIVER', amount_rule: { kind: 'exact', amount_cents: 5003 }, due_day: 31, prepare_days_before: 3, single_action_cap_cents: 5003, auto_execute: false }), source(fullSeasonalId, seasonalVersion, 'SeasonalReservePolicy', { type: 'seasonal_reserve', holiday_code: 'SYNTHETIC_YEAR', window: { start: '2027-01-01', end: '2027-01-02' }, lookback_days: 365, minimum_historical_windows: 2, quantile: 0.9, essential_categories: ['OTHER'], adjustment_cap_cents: 8001, requires_confirmation: true })];
  const full = structuredClone(original.annual_projection); full.algorithm_version = 'registered-full-protection-v1';
  for (const point of full.calculation_trace) { point.protected_cents_by_reason = { ...point.protected_cents_by_reason, full_dated_expense: 7001, full_periodic_transfer: 5003, pending_cash_reservations: 0 }; point.margin_cents -= 12004; }
  full.safe_idle_cents = sourceRisk ? 0 : 66997; full.minimum_margin_cents = 66997; full.deficit_cents = 0; full.status = sourceRisk ? 'LIQUIDITY_RISK' : 'READY'; full.protected_cents_by_reason = { ...full.calculation_trace[0]!.protected_cents_by_reason }; full.boundary_hash = digest;
  if (sourceRisk) full.blocking_constraints = [{ code: 'PERIODIC_SOURCE_LIQUIDITY_LIMIT', entity_id: periodicAccountId, date: null, required_cents: 5003, available_cents: 4001 }];
  const checkpoints = [original.initial_checkpoint, ...original.daily_checkpoints].map((point) => ({ day: point.day, date: point.date, status: unknown ? 'NOT_PROVEN' as const : 'PROVEN' as const, before_payment: unknown ? null : structuredClone(full.calculation_trace[point.day * 3]!), after_payment: unknown ? null : structuredClone(full.calculation_trace[point.day * 3 + 1]!), after_principal: unknown ? null : structuredClone(full.calculation_trace[point.day * 3 + 2]!), minimum_intraday_margin_cents: unknown ? null : 66997 }));
  const occurrence = (periodic: boolean): FullAnnualPlanning['projection']['occurrences'][number] => ({ occurrence_id: periodic ? `FULL:${fullPeriodicId}:${periodicVersion}:MONTH:2026-12` : `FULL:${fullDatedId}:${datedVersion}:DATED:2026-12-31:2027-01-02`, policy_id: periodic ? fullPeriodicId : fullDatedId, policy_version_id: periodic ? periodicVersion : datedVersion, kind: periodic ? 'PERIODIC_TRANSFER' : 'DATED_EXPENSE', earliest_due_date: '2026-12-31', latest_due_date: periodic ? '2026-12-31' : '2027-01-02', hypothetical_payment_date: '2026-12-31', prepare_start_date: periodic ? '2026-12-28' : '2026-12-31', protection_starts_today: true, conservative_unpaid_cents: periodic ? 5003 : 7001, amount_basis: periodic ? 'REGISTERED_EXACT' : 'REGISTERED_MAX', original_paid_cents: null, settlement_status: 'UNSUPPORTED_CONSERVATIVE_UNPAID', source_account_id: periodic ? periodicAccountId : null, payee_id: periodic ? 'SYNTHETIC_RECEIVER' : null, evidence_ids: [evidence], overdue: false, bank_authority: false });
  return { schema_version: 'full-annual-protection-v1', user_id: original.user_id, as_of: original.as_of, simulation: true, planning_only: true, grants_authority: false, execution_support: 'NOT_IMPLEMENTED', horizon_days: 365, projection: { algorithm_version: 'registered-full-protection-v1', planning_only: true, bank_authority: false, execution_support: 'NOT_IMPLEMENTED', basis: 'REGISTERED_UPPER_BOUND_UNPAID_CONDITIONAL_CASH', original_execution_view: original.execution_view, original_annual_projection: original.annual_projection, full_annual_projection: unknown ? null : full, occurrences: [occurrence(false), occurrence(true)], policy_states: sources.map((row) => ({ policy_id: row.policy_id, version_id: row.version_id, template_name: row.template_name, state: row.template_name === 'SeasonalReservePolicy' ? 'ADVICE_ONLY' : unknown ? 'UNKNOWN' : 'INCLUDED', reasons: [row.template_name === 'SeasonalReservePolicy' ? 'ADOPTED_EXTRA_AMOUNT_NOT_PROVIDED_NOT_DERIVED_FROM_QUANTILE' : 'HTTP_UNIT_FIXTURE_NOT_FINANCIAL_PROOF'] })), source_account_checks: [{ account_id: periodicAccountId, actual_cash_cents: sourceRisk ? 4001 : 100003, goal_owned_cash_cents: 0, reserved_cash_cents: 0, registered_periodic_required_cents: 5003, remaining_current_cash_cents: sourceRisk ? -1002 : 95000, state: sourceRisk ? 'SOURCE_LIQUIDITY_RISK' : 'CURRENT_SOURCE_SUFFICIENT', future_account_debits_complete: false }], status: unknown ? 'UNKNOWN' : sourceRisk ? 'LIQUIDITY_RISK' : 'READY', full_obligations_complete_within_registered_current_scope: !unknown, historical_full_settlement_complete: false, seasonal_adopted_adjustment_cents: null, seasonal_status: 'ADVICE_ONLY_NO_ADOPTED_AMOUNT', future_income_in_current_cash_cents: 0, future_income_in_original_execution_cents: 0, future_income_status: 'NO_REGISTERED_PLANNING_INCOME_SOURCE', reasons: unknown ? ['FULL_ORIGINAL_OR_HISTORICAL_COVERAGE_NOT_PROVEN'] : [], input_hash: digest }, initial_checkpoint: checkpoints[0]!, daily_checkpoints: checkpoints.slice(1), full_policy_sources: sources, future_income: original.future_income, source_evidence_ids: [...original.source_evidence_ids, evidence], source_issues: unknown ? [{ code: 'UNIT_FULL_ORIGINAL_NOT_PROVEN', source_ref: 'synthetic-full-original', message: 'HTTP夹具：FULL原件不足，不是产品实证' }] : [], input_digest: digest, audit: original.audit, limitations: ['CONSERVATIVE_MAX_IS_NOT_ACTUAL_INVOICE_OR_BANK_PAYMENT', 'FULL_SETTLEMENT_BINDING_AND_OLD_EXPIRED_UNPAID_HISTORY_NOT_IMPLEMENTED', 'CURRENT_SOURCE_ACCOUNT_CHECK_DOES_NOT_ALLOCATE_ALL_FUTURE_MVP_DEBITS', 'SEASONAL_ADOPTED_EXTRA_AMOUNT_NOT_PROVIDED', 'ORIGINAL_EXECUTION_CONSUMERS_HAVE_NOT_ADOPTED_THIS_NEW_FULL_CURVE'] };
}
