/** Synthetic HTTP/component fixtures; not current income, model confirmation or solver evidence. */
import type { FullGoalConfiguration, FullGoalLookup, FullGoalModel, FullGoalPreview, FullGoalReceipt } from '../api/full-goals';
import type { FullGoalIntent } from '../features/full-goal-operation';
import type { JointPlanning } from '../api/joint-planning';
import { dashboardFixture } from './dashboard-fixture';
export const goalId = '70000000-0000-4000-8000-000000000001';
export const policyId = '70000000-0000-4000-8000-000000000002';
export const versionId = '70000000-0000-4000-8000-000000000003';
export const epochId = '70000000-0000-4000-8000-000000000004';
export const evidenceId = '70000000-0000-4000-8000-000000000005';
export const userId = '70000000-0000-4000-8000-000000000006';
export const fragmentId = '70000000-0000-4000-8000-000000000007';
export const originId = '70000000-0000-4000-8000-000000000008';
export const accountId = '70000000-0000-4000-8000-000000000009';
export const otherGoalId = '70000000-0000-4000-8000-000000000010';
export const modelGoal = { id: goalId, name: 'HTTP夹具目标', policy_id: policyId, policy_version_id: versionId };
export function fullConfiguration(): FullGoalConfiguration {
  return { type: 'long_term_goal', name: 'HTTP夹具目标', valid_from: null, valid_until: null, target_cents: 550001, deadline: '2027-10-05', monthly_contribution: { min_cents: 10001, target_cents: 20003, max_cents: 30007 }, importance: 67, minimum_guarantee_cents: 10001, allow_partial: true, allow_deferral: true, deferral_cost_cents_per_day: 101, asset_policy_id: null, cross_goal_reallocation_allowed: false, cross_goal_reallocation_policy_id: null };
}
export function fullModelFixture(missing = false): FullGoalModel {
  return { simulation: true, goal_id: goalId, policy_id: policyId, base_policy_version_id: versionId, epoch_id: epochId, status: missing ? 'MODEL_MISSING' : 'VERIFIED', policy_effective_status: missing ? null : 'ACTIVE', evidence_id: missing ? null : evidenceId, evidence_hash: missing ? null : 'a'.repeat(64), full_configuration: missing ? null : { ...fullConfiguration() }, full_configuration_hash: missing ? null : 'b'.repeat(64), base_configuration_hash: missing ? null : 'c'.repeat(64), confirmed_at: missing ? null : '2026-10-05T12:00:00Z', bank_authority: false, dedicated_audit_event: false };
}
export function fullPreviewFixture(): FullGoalPreview {
  const full = fullConfiguration(); const base = { type: 'goal_saving', name: full.name, valid_from: full.valid_from, valid_until: full.valid_until, target_cents: full.target_cents, deadline: full.deadline, monthly_contribution: full.monthly_contribution, priority: { importance: full.importance, minimum_cents: full.minimum_guarantee_cents, reducible: full.allow_partial, deferrable: full.allow_deferral }, cross_goal_reallocation_allowed: false, asset_policy_id: null };
  return { simulation: true, preview_only: true, grants_authority: false, goal_id: goalId, epoch_id: epochId, expected_version_id: versionId, full_configuration: { ...full }, full_configuration_hash: 'b'.repeat(64), base_configuration: base, base_configuration_hash: 'c'.repeat(64), extra_fields_in_base_impact: false, notes: ['SYNTHETIC_HTTP_PREVIEW_NOT_CONFIRMATION'],
    base_policy_impact: { schema_version: 'policy-change-preview-v1', simulation: true, preview_only: true, financial_only: true, user_id: userId, as_of: '2026-10-05T12:00:00Z', timezone: 'UTC', policy_id: policyId, expected_version_id: versionId, configuration: base, configuration_hash: 'c'.repeat(64), assumed_status: 'ACTIVE', assumed_valid_from: '2026-10-05T12:00:00Z', assumed_valid_until: null, assumption_digest: 'd'.repeat(64), current_fact_input_digest: 'e'.repeat(64), hypothetical_input_digest: 'f'.repeat(64), before: dashboardFixture().boundary, after: { ...dashboardFixture().boundary, safe_idle_cents: null, minimum_margin_cents: null, deficit_cents: null, status: 'INSUFFICIENT_EVIDENCE', state: 'NOT_PROVEN' }, delta_safe_idle_cents: null, delta_minimum_margin_cents: null, notes: [] } };
}
export function jointFixture(state: 'OPTIMAL' | 'UNKNOWN' | 'INFEASIBLE' | 'CAPACITY' = 'OPTIMAL'): JointPlanning {
  const unknown = state === 'UNKNOWN'; const capacity = state === 'CAPACITY'; const optimal = state === 'OPTIMAL';
  return { schema_version: 'verified-joint-goal-planning-v1', simulation: true, user_id: userId, as_of: '2026-10-05T12:00:00Z', grants_authority: false, funds_scope: 'ACTUAL_CURRENT_UNASSIGNED_INCOME_ONLY', protection_scope: 'ALL_ORIGINAL_365_DAY_RESERVES_RETAINED', full_model_rules_have_dedicated_audit_event: false, independent_bank_projection_matched: true, registered_goal_count: capacity ? 9 : unknown ? 2 : 1,
    included_goal_ids: capacity ? Array.from({ length: 9 }, (_, index) => `70000000-0000-4000-8000-${String(index + 20).padStart(12, '0')}`) : [goalId], uncovered_goal_ids: capacity ? Array.from({ length: 9 }, (_, index) => `70000000-0000-4000-8000-${String(index + 20).padStart(12, '0')}`) : unknown ? [otherGoalId] : [],
    state: unknown || capacity ? 'UNKNOWN' : 'COMPUTED', source_evidence_ids: [evidenceId], source_issues: unknown ? [{ code: 'MISSING_FULL_GOAL_MODEL', source_ref: otherGoalId, message: 'Synthetic missing model' }] : capacity ? [{ code: 'JOINT_GOAL_CAPACITY', source_ref: 'goals', message: '最多8个完整目标' }] : [], input_hash: 'd'.repeat(64), limitations: ['CURRENT_PERIOD_ONLY_SYNTHETIC_FIXTURE'],
    allocation: capacity ? null : { algorithm_version: 'critical-flow-lexicographic-v1', status: unknown ? 'UNKNOWN' : optimal ? 'OPTIMAL' : 'INFEASIBLE', purpose: 'CURRENT_PERIOD_PLANNING_ONLY', grants_authority: false, input_hash: 'e'.repeat(64), objective_vector: optimal ? [0, 0, 0, 0, 0, 0, 0, 1] : null, budget_cents: 20003, visited_nodes: 17, reasons: ['SYNTHETIC_SOLVER_VIEW_NOT_RESULT'], delay_scope: 'ACTIVE_INCOMPLETE_GOALS_CURRENT_DECISION_LOWER_BOUND',
      goals: [{ goal_id: goalId, effective_policy_version_id: versionId, amount_cents: optimal ? 20003 : null, minimum_shortfall_cents: optimal ? 0 : null, projected_owned_cents: optimal ? 120004 : null, completion_date: null, delay_lower_bound_days: optimal ? 0 : null, delay_censored: true, deferral_cost_lower_bound_cents: optimal ? 0 : null }], income_uses: optimal ? [{ fragment_id: fragmentId, origin_transaction_id: originId, source_account_id: accountId, goal_id: goalId, amount_cents: 20003 }] : [] },
    conflict: state === 'INFEASIBLE' ? { status: 'MINIMAL_CONFLICT', scope: 'GOAL_POLICIES_WITH_IMMUTABLE_FINANCIAL_BASE', grants_authority: false, input_hash: 'e'.repeat(64), constraint_ids: [`MONTHLY_MAX:${goalId}`], deletion_checks: [{ removed_constraint_id: `MONTHLY_MAX:${goalId}`, remaining_feasible: true, counterfactual_only: true, witness_amounts_cents: { [goalId]: 30007 } }], reasons: [] } : null };
}
export const confirmedVersionId = '70000000-0000-4000-8000-000000000011';
export async function fullGoalIntentFixture(key = 'FULL_GOAL_UNIT_ORIGINAL/1'): Promise<FullGoalIntent> { const { prepareFullGoalIntent } = await import('../features/full-goal-operation'); const preview = fullPreviewFixture(); return prepareFullGoalIntent({ user_id: userId, goal_id: goalId, policy_id: policyId, body: { expected_version_id: versionId, expected_epoch_id: epochId, configuration: preview.full_configuration, reviewed_full_hash: preview.full_configuration_hash, reviewed_base_hash: preview.base_configuration_hash, accepted: true, reason: 'SYNTHETIC_EXPLICIT_REASON', idempotency_key: key } }); }
export function fullGoalReceiptFixture(intent: FullGoalIntent, replay = false): FullGoalReceipt { return { simulation: true, goal_id: intent.goal_id, epoch_id: intent.body.expected_epoch_id, lifecycle: { simulation: true, policy_id: intent.policy_id, previous_version_id: intent.body.expected_version_id, current_version_id: confirmedVersionId, status: 'ACTIVE', effective_status: 'ACTIVE', invalidated_action_ids: [], inflight_action_ids: [], requires_recompute: true }, evidence_id: evidenceId, evidence_hash: 'a'.repeat(64), full_configuration: structuredClone(intent.body.configuration), full_configuration_hash: intent.body.reviewed_full_hash, base_configuration_hash: intent.body.reviewed_base_hash, confirmed_at: '2026-10-05T12:00:00Z', idempotent_replay: replay, receipt_is_current_authority: false, bank_authority: false, dedicated_audit_event: false }; }
export function fullGoalLookupFixture(intent: FullGoalIntent, found = true): FullGoalLookup { return { simulation: true, goal_id: intent.goal_id, idempotency_key: intent.body.idempotency_key, status: found ? 'RECORDED' : 'NOT_FOUND', record: found ? { original_request: structuredClone(intent.body), request_hash: intent.request_hash, receipt: fullGoalReceiptFixture(intent, true), original_verified: true, audit_chain_verified: true, configuration_is_server_canonical: true, epoch_archive_verified: false } : null, not_found_is_final: false, receipt_is_current_authority: false, bank_authority: false, dedicated_audit_event: false }; }
