/** SYNTHETIC_HTTP_FIXTURE_ONLY: checks client boundaries, never financial or lifecycle acceptance. */
import type { FullCommand, FullPolicy, FullPolicyLookup, FullPolicyPreview, FullPolicyReceipt, TemplateCandidate, TemplateCatalog, TemplateSchema } from '../api/full-policies';
import type { FullPolicyIntent } from '../features/full-policy-operation';
import { prepareFullPolicyIntent } from '../features/full-policy-operation';
import { dashboardFixture } from './dashboard-fixture';
export const fullPolicyId = '71000000-0000-4000-8000-000000000001';
export const fullVersionId = '71000000-0000-4000-8000-000000000002';
export const nextFullVersionId = '71000000-0000-4000-8000-000000000003';
export const fullEpochId = '71000000-0000-4000-8000-000000000004';
export const fullUserId = '71000000-0000-4000-8000-000000000005';
export const fullCommandId = '71000000-0000-4000-8000-000000000006';
export const fullEvidenceId = '71000000-0000-4000-8000-000000000007';
export const fullHash = 'a'.repeat(64); export const nextFullHash = 'b'.repeat(64); export const fullRequestHash = 'c'.repeat(64);
const time = '2026-10-05T12:00:00Z'; export const fullFlags = { simulation: true as const, bank_authority: false as const, dedicated_audit_event: false as const };
export const fullConfig = () => ({ type: 'dated_expense', name: 'HTTP夹具支出', valid_from: null, valid_until: null, due_date: '2027-01-03', amount_cents: 123007, priority: { importance: 100, minimum_cents: 123007, reducible: false, deferrable: false }, must_not_reduce: true });
export function createFullIntent(requestKey = 'unit/original-create-key'): FullPolicyIntent { return prepareFullPolicyIntent({ kind: 'CREATE', policy_id: null, original_epoch_id: null, original_configuration_hash: fullHash, path: '/full-policies/confirm', body: { template_name: 'DatedExpensePolicy', configuration: fullConfig(), reviewed_hash: fullHash, accepted: true, reason: 'SYNTHETIC_CONFIRMATION', idempotency_key: requestKey } }); }
export function stateFullIntent(kind: 'SUSPEND' | 'REVOKE' | 'RESUME' | 'CHANGE'): FullPolicyIntent {
  const common = { expected_version_id: fullVersionId, reason: 'SYNTHETIC_USER_REASON', idempotency_key: `unit/original-${kind}-key` };
  return prepareFullPolicyIntent({ kind, policy_id: fullPolicyId, original_epoch_id: fullEpochId, original_configuration_hash: kind === 'CHANGE' ? nextFullHash : fullHash, path: `/full-policies/${fullPolicyId}/${kind.toLowerCase()}`, body: kind === 'CHANGE' ? { ...common, accepted: true, reviewed_hash: nextFullHash, configuration: { ...fullConfig(), name: '修改后的HTTP夹具支出' } } : kind === 'RESUME' ? { ...common, accepted: true, reviewed_hash: fullHash } : common });
}
export function fullReceiptFixture(intent = createFullIntent()): FullPolicyReceipt {
  return { ...fullFlags, receipt_is_current_authority: false, policy_id: fullPolicyId, epoch_id: fullEpochId, version_id: ['CHANGE', 'RESUME'].includes(intent.kind) ? nextFullVersionId : fullVersionId, command_id: fullCommandId, command_number: intent.kind === 'CREATE' ? 1 : 2, previous_command_hash: intent.kind === 'CREATE' ? null : 'd'.repeat(64), status: intent.kind === 'SUSPEND' ? 'SUSPENDED' : intent.kind === 'REVOKE' ? 'REVOKED' : 'ACTIVE', configuration_hash: intent.original_configuration_hash, invalidated_action_ids: [], inflight_action_ids: [], action_dependencies_supported: false, requires_recompute: true };
}
export function fullCommandFixture(intent = createFullIntent()): FullCommand { const receipt = fullReceiptFixture(intent); return { ...fullFlags, command_id: fullCommandId, policy_id: fullPolicyId, version_id: receipt.version_id, kind: intent.kind, command_number: receipt.command_number, previous_hash: receipt.previous_command_hash ?? null, idempotency_key: intent.body.idempotency_key, request_hash: fullRequestHash, previous_status: intent.kind === 'CREATE' ? null : intent.kind === 'RESUME' ? 'SUSPENDED' : 'ACTIVE', resulting_status: receipt.status, result: { ...receipt }, result_hash: 'd'.repeat(64), created_at: time }; }
export function fullLookupFixture(intent = createFullIntent(), found = true): FullPolicyLookup { return { ...fullFlags, status: found ? 'RECORDED' : 'NOT_FOUND', idempotency_key: intent.body.idempotency_key, original_request: found ? { protocol: 'full-policy-command-v1', kind: intent.kind, user_id: fullUserId, policy_id: intent.policy_id, body: JSON.parse(intent.body_json) } : null, request_hash: found ? fullRequestHash : null, command: found ? fullCommandFixture(intent) : null, receipt_is_current_authority: false, not_found_is_final: false }; }
export function fullPolicyFixture(status: FullPolicy['status'] = 'ACTIVE'): FullPolicy { return { ...fullFlags, policy_id: fullPolicyId, epoch_id: fullEpochId, template_name: 'DatedExpensePolicy', name: 'HTTP夹具支出', status, effective_status: status, planning_confirmation_valid: status === 'ACTIVE' || status === 'CONFIRMED', reference_validation: 'CURRENT', execution_support: 'NOT_IMPLEMENTED', updated_at: time,
  current_version: { ...fullFlags, version_id: fullVersionId, policy_id: fullPolicyId, version_number: 1, configuration: fullConfig(), content_hash: fullHash, previous_hash: null, summary: 'SYNTHETIC_CURRENT_VERSION_SUMMARY', confirmed_at: time, valid_from: time, valid_until: null, change_reason: 'SYNTHETIC_CONFIRMATION', evidence_ids: [fullEvidenceId], confirmation_evidence_status: 'CURRENT_EVIDENCE_MATCHED', impact_analysis: { bank_authority: false, dedicated_audit_event: false, action_dependencies_supported: false, candidate_financial_status: 'NOT_IMPLEMENTED', candidate_financial_delta_cents: null, reference_snapshots: [] }, confirmation: { protocol: 'full-policy-confirmation-v1', user_id: fullUserId, epoch_id: fullEpochId, policy_id: fullPolicyId, version_id: fullVersionId, template_name: 'DatedExpensePolicy', reviewed_hash: fullHash, confirmed_at: time, accepted: true, bank_authority: false, confirmation_evidence_id: fullEvidenceId, request_key: 'unit/original-create-key', request_hash: fullRequestHash } } }; }
export function fullPreviewFixture(): FullPolicyPreview { return { ...fullFlags, preview_only: true, policy_id: fullPolicyId, epoch_id: fullEpochId, expected_version_id: fullVersionId, as_of: time, before_configuration: fullConfig(), after_configuration: { ...fullConfig(), name: '修改后的HTTP夹具支出' }, configuration_hash: nextFullHash, changed_fields: ['name'], current_financial_boundary: dashboardFixture().boundary, current_fact_digest: 'e'.repeat(64), reference_snapshots: [], relevant_goal_ids: [], relevant_position_ids: [], relevant_current_action_ids: [], candidate_financial_status: 'NOT_IMPLEMENTED', delta_safe_idle_cents: null, delta_goal_allocation_cents: null, delta_position_principal_cents: null, future_action_impact: 'NOT_IMPLEMENTED_NO_FULL_EXECUTION_ADAPTER', limitations: ['SYNTHETIC_PREVIEW_NOT_FINANCIAL_EFFECT'] }; }
export function fullCatalogFixture(): TemplateCatalog { return { candidate_only: true, authority_granted: false, templates: ['RecurringObligationPolicy', 'LivingReservePolicy', 'EmergencyBufferPolicy', 'DatedExpensePolicy', 'LongTermGoalPolicy', 'PeriodicTransferPolicy', 'AssetAuthorizationPolicy', 'RecoveryPolicy', 'GoalAllocationPolicy', 'CrossGoalReallocationPolicy', 'SeasonalReservePolicy', 'InterventionPolicy'].map((template_name) => ({ template_name: template_name as TemplateCandidate['template_name'], full_configuration_type: `SYNTHETIC_${template_name}`, mvp_configuration_type: null, available_versions: ['FULL_V1'] })) }; }
export function fullSchemaFixture(template: TemplateCandidate['template_name'] = 'DatedExpensePolicy'): TemplateSchema { return { template_name: template, dsl_version: 'FULL_V1', json_schema: { type: 'object', required: ['name', 'amount_cents'], additionalProperties: false }, schema_sha256: 'f'.repeat(64), cross_field_validation_required: true, candidate_only: true, authority_granted: false }; }
export function fullCandidateFixture(): TemplateCandidate { return { template_name: 'DatedExpensePolicy', dsl_version: 'FULL_V1', normalized_configuration: fullConfig(), configuration_hash: fullHash, candidate_only: true, authority_granted: false, reference_validation_pending: true }; }
