/** Hand-worked synthetic wire fixtures only; no bank, solver or economic proof. */
import type { FullJointPlanning, FullJointSource, FullJointInput } from '../api/full-joint-planning';
import type { Goal } from '../api/goals';
import { jointFixture, goalId, versionId, policyId, accountId, userId, evidenceId, fragmentId, originId } from './full-goal-fixture';
import { annualFixture } from './annual-fixture';

export function fullJointFixture(state: 'OPTIMAL' | 'UNKNOWN' | 'CAPACITY' | 'INFEASIBLE' = 'OPTIMAL'): FullJointPlanning {
  const old = jointFixture(state === 'CAPACITY' ? 'CAPACITY' : 'OPTIMAL');
  const annual = annualFixture(); annual.user_id = userId; annual.as_of = old.as_of;
  const bankId = '70000000-0000-4000-8000-000000000112'; const fullId = '70000000-0000-4000-8000-000000000113'; const fullVersion = '70000000-0000-4000-8000-000000000114'; const fullEvidence = '70000000-0000-4000-8000-000000000115';
  const refs: FullJointSource[] = [{ user_id: userId, evidence_id: evidenceId, content_hash: 'a'.repeat(64) }, { user_id: userId, evidence_id: bankId, content_hash: 'b'.repeat(64) }, { user_id: userId, evidence_id: fullEvidence, content_hash: 'c'.repeat(64) }];
  const change = (boundary: typeof annual.annual_projection) => {
    for (const point of boundary.calculation_trace) { point.cash_cents = point.phase === 'BEFORE_PAYMENT' ? 40003 : point.phase === 'AFTER_PAYMENT' ? 39003 : 39503; point.protected_cents_by_reason = { obligations: 2000, living: 4000, emergency: 3000, goal_cash: 10000, goal_minimum: 1000 }; point.margin_cents = point.cash_cents-20000; }
    boundary.safe_idle_cents = 19003; boundary.minimum_margin_cents = 19003; boundary.deficit_cents = 0; boundary.protected_cents_by_reason = { ...boundary.calculation_trace[0]!.protected_cents_by_reason };
  };
  change(annual.annual_projection); change(annual.execution_view);
  const curve = structuredClone(annual.annual_projection); curve.algorithm_version = 'registered-full-protection-v1';
  for (const point of curve.calculation_trace) { const paid = point.day > 7 || point.day === 7 && point.phase !== 'BEFORE_PAYMENT'; point.cash_cents -= paid ? 7001 : 0; point.protected_cents_by_reason = { ...point.protected_cents_by_reason, full_dated_expense: paid ? 0 : 7001, full_periodic_transfer: 0, pending_cash_reservations: 0 }; point.margin_cents = point.cash_cents-Object.values(point.protected_cents_by_reason).reduce((total, amount) => total+amount, 0); }
  curve.safe_idle_cents = 12002; curve.minimum_margin_cents = 12002; curve.deficit_cents = 0; curve.protected_cents_by_reason = { ...curve.calculation_trace[0]!.protected_cents_by_reason };
  const unknown = state === 'UNKNOWN';
  const checkpoints = Array.from({ length: 366 }, (_, day) => ({ day, date: curve.calculation_trace[day*3]!.date, status: unknown ? 'NOT_PROVEN' as const : 'PROVEN' as const, before_payment: unknown ? null : structuredClone(curve.calculation_trace[day*3]!), after_payment: unknown ? null : structuredClone(curve.calculation_trace[day*3+1]!), after_principal: unknown ? null : structuredClone(curve.calculation_trace[day*3+2]!), minimum_intraday_margin_cents: unknown ? null : Math.min(...curve.calculation_trace.slice(day*3, day*3+3).map((row) => row.margin_cents)) }));
  const full: FullJointPlanning['full_protection'] = { schema_version: 'full-annual-protection-v1', user_id: userId, as_of: old.as_of, simulation: true, planning_only: true, grants_authority: false, execution_support: 'NOT_IMPLEMENTED', horizon_days: 365,
    projection: { algorithm_version: 'registered-full-protection-v1', planning_only: true, bank_authority: false, execution_support: 'NOT_IMPLEMENTED', basis: 'REGISTERED_UPPER_BOUND_UNPAID_CONDITIONAL_CASH', original_execution_view: annual.execution_view, original_annual_projection: annual.annual_projection, full_annual_projection: unknown ? null : curve,
      occurrences: [{ occurrence_id: `FULL:${fullId}:${fullVersion}:DATED:2026-10-12:2026-10-14`, policy_id: fullId, policy_version_id: fullVersion, kind: 'DATED_EXPENSE', earliest_due_date: '2026-10-12', latest_due_date: '2026-10-14', hypothetical_payment_date: '2026-10-12', prepare_start_date: '2026-10-12', protection_starts_today: true, conservative_unpaid_cents: 7001, amount_basis: 'REGISTERED_MAX', original_paid_cents: null, settlement_status: 'UNSUPPORTED_CONSERVATIVE_UNPAID', source_account_id: null, payee_id: null, evidence_ids: [fullEvidence], overdue: false, bank_authority: false }],
      policy_states: [{ policy_id: fullId, version_id: fullVersion, template_name: 'DatedExpensePolicy', state: unknown ? 'UNKNOWN' : 'INCLUDED', reasons: unknown ? ['FULL_HISTORY_MISSING'] : [] }], source_account_checks: [], status: unknown ? 'UNKNOWN' : 'READY', full_obligations_complete_within_registered_current_scope: !unknown, historical_full_settlement_complete: false, seasonal_adopted_adjustment_cents: null, seasonal_status: 'NO_SEASONAL_POLICY', future_income_in_current_cash_cents: 0, future_income_in_original_execution_cents: 0, future_income_status: 'NO_REGISTERED_PLANNING_INCOME_SOURCE', reasons: unknown ? ['FULL_HISTORY_MISSING'] : [], input_hash: 'c'.repeat(64) },
    initial_checkpoint: checkpoints[0]!, daily_checkpoints: checkpoints.slice(1), full_policy_sources: [{ policy_id: fullId, version_id: fullVersion, version_number: 1, template_name: 'DatedExpensePolicy', configuration: { type: 'dated_expense', window: { start: '2026-10-12', end: '2026-10-14' }, amount: { min_cents: 0, target_cents: 7001, max_cents: 7001 } }, content_hash: 'c'.repeat(64), confirmation: { accepted: true, reviewed_hash: 'c'.repeat(64) }, reference_snapshots: [], confirmed_at: '2026-10-05T11:00:00Z', valid_from: '2026-10-05T11:00:00Z', valid_until: null, effective_status: 'ACTIVE', planning_confirmation_valid: true, references_current: true, evidence_ids: [fullEvidence], protected_references: [] }],
    future_income: annual.future_income, source_evidence_ids: refs.map((row) => row.evidence_id), source_issues: unknown ? [{ code: 'FULL_HISTORY_MISSING', source_ref: fullId, message: 'Synthetic unavailable history' }] : [], input_digest: 'c'.repeat(64), audit: annual.audit, limitations: ['SYNTHETIC_FIXTURE_NOT_FINANCIAL_PROOF'] };
  if (old.allocation) { old.allocation.budget_cents = 19003; old.allocation.goals[0]!.amount_cents = 19003; old.allocation.goals[0]!.projected_owned_cents = 29003; old.allocation.income_uses[0]!.amount_cents = 19003; }
  old.source_evidence_ids = refs.slice(0, 2).map((row) => row.evidence_id);
  const candidate: FullJointInput = { schema_version: 'multi-goal-current-period-v1', user_id: userId, as_of: old.as_of, timezone: 'UTC', source_issues: unknown ? ['FULL_HISTORY_MISSING'] : [], solver_node_budget: 200000,
    goals: [{ goal_id: goalId, account_id: accountId, policy_id: policyId, effective_policy_version_id: versionId, policy_status: 'ACTIVE', target_cents: 550001, current_owned_cents: 10000, current_month_contributed_cents: 0, monthly_min_cents: 10001, monthly_target_cents: 20003, monthly_max_cents: 30007, minimum_guarantee_cents: 10001, importance: 67, deadline: '2027-10-05', allow_partial: true, allow_deferral: true, deferral_cost_cents_per_day: 101, confirmed_at: '2026-10-04T00:00:00Z', valid_from: '2026-10-04T00:00:00Z', valid_until: null, negotiable_fields: [], source_refs: refs.slice(0, 1) }],
    income_lots: [{ fragment_id: fragmentId, origin_transaction_id: originId, account_id: accountId, received_cents: 20003, available_cents: 20003, occurred_at: '2026-10-05T10:00:00Z', observed_at: '2026-10-05T10:00:00Z', owner_goal_id: null, bank_evidence_id: bankId, bank_evidence_hash: 'b'.repeat(64), source_refs: refs.slice(0, 2) }],
    hard_protection_points: (unknown ? annual.annual_projection : curve).calculation_trace.map((point) => ({ date: point.date, cash_cents: point.cash_cents, obligation_floor_cents: point.protected_cents_by_reason.obligations!, living_floor_cents: point.protected_cents_by_reason.living!, emergency_floor_cents: point.protected_cents_by_reason.emergency!, owned_goal_cash_cents: point.protected_cents_by_reason.goal_cash!, other_protection_floor_cents: point.protected_cents_by_reason.goal_minimum!+(unknown ? 0 : point.protected_cents_by_reason.full_dated_expense!), source_refs: unknown ? refs.slice(0, 2) : refs })) };
  const allocation = state === 'CAPACITY' ? null : structuredClone(old.allocation)!;
  if (allocation) { allocation.input_hash = 'f'.repeat(64); allocation.budget_cents = unknown ? 19003 : 12002; allocation.status = state === 'INFEASIBLE' ? 'INFEASIBLE' : unknown ? 'UNKNOWN' : 'OPTIMAL'; if (allocation.status === 'OPTIMAL') { allocation.goals[0]!.amount_cents = 12002; allocation.goals[0]!.projected_owned_cents = 22002; allocation.income_uses[0]!.amount_cents = 12002; } else { allocation.objective_vector = null; allocation.income_uses = []; for (const goal of allocation.goals) { goal.amount_cents = null; goal.projected_owned_cents = null; goal.minimum_shortfall_cents = null; goal.delay_lower_bound_days = null; goal.deferral_cost_lower_bound_cents = null; } } }
  // Model independent JSON wire objects: changing one response ref cannot mutate another.
  return JSON.parse(JSON.stringify({ schema_version: 'full-current-joint-goal-planning-v1', user_id: userId, as_of: old.as_of, simulation: true, planning_only: true, grants_authority: false, execution_support: 'NOT_IMPLEMENTED', funds_scope: 'ACTUAL_CURRENT_UNASSIGNED_INCOME_ONLY', planning_scope: 'CURRENT_PERIOD_WITH_ALL_365_DAY_ORIGINAL_AND_FULL_PROTECTION', original_joint: old, full_protection: full,
    binding: state === 'CAPACITY' ? null : { status: unknown ? 'UNKNOWN' : 'VERIFIED', original_point_count: 1098, full_point_count: unknown ? 0 : 1098, bound_point_count: unknown ? 0 : 1098, original_input_hash: old.allocation!.input_hash, full_projection_input_hash: full.projection.input_hash, verified_source_refs: refs, reasons: unknown ? ['FULL_HISTORY_MISSING'] : [], binding_hash: 'b'.repeat(64), candidate }, allocation, conflict: null, state: unknown || state === 'CAPACITY' ? 'UNKNOWN' : 'COMPUTED', reasons: unknown ? ['FULL_HISTORY_MISSING'] : state === 'CAPACITY' ? ['JOINT_GOAL_CAPACITY'] : [], input_hash: 'd'.repeat(64), limitations: ['当前期，不证明多期全局最优', '未来账户扣款未核', '未授予银行执行权限'] } satisfies FullJointPlanning)) as FullJointPlanning;
}

export function fullJointGoalFixture(): Goal { const input = fullJointFixture().binding!.candidate.goals[0]!; return { id: goalId, name: '合成UI目标', policy_id: policyId, policy_version_id: versionId, account_id: input.account_id, target_cents: input.target_cents, allocated_cents: input.current_owned_cents, deadline: input.deadline, monthly_min_cents: input.monthly_min_cents, monthly_target_cents: input.monthly_target_cents, monthly_max_cents: input.monthly_max_cents, importance: input.importance, minimum_protection_cents: input.minimum_guarantee_cents, reducible: true, deferrable: true, cross_goal_reallocation_allowed: false, asset_policy_id: null }; }
