/** TOOL_ONLY synthetic API/component records; no PG, bank, permission or product acceptance proof. */
import { createHash } from 'node:crypto';
import type { DynamicAction, DynamicIntent, DynamicLookup, DynamicPrepare, DynamicPreview, DynamicProof } from '../api/full-dynamic-goal-execution';
import { dynamicCanonicalJson } from '../api/full-dynamic-goal-execution';
import { fullModelFixture, modelGoal, goalId, policyId, versionId, evidenceId, epochId, userId, accountId, fragmentId, originId } from './full-goal-fixture';
import { dynamicGoalFixture } from './dynamic-goal-fixture';
import { boundaryFixture } from './demo-fixture';
export const dynamicExecutionGoal = modelGoal;
export const dynamicExecutionUser = userId;
export const dynamicExecutionEpoch = epochId;
export const dynamicExecutionId = '92000000-0000-4000-8000-000000000001';
export const dynamicRunId = '92000000-0000-4000-8000-000000000002';
export const dynamicConfirmationId = '92000000-0000-4000-8000-000000000003';
export const dynamicFixtureHash = (value: unknown) => createHash('sha256').update(dynamicCanonicalJson(value), 'utf8').digest('hex');
export function dynamicPrepareFixture(): DynamicPrepare { return { goal_id: goalId, expected_policy_version_id: versionId, expected_model_evidence_id: evidenceId, expected_model_evidence_hash: 'a'.repeat(64), expected_epoch_id: epochId, idempotency_key: 'TOOL_ONLY_DYNAMIC_001' }; }
export function dynamicModelFixture(missing = false) { const v = fullModelFixture(missing); if (v.full_configuration) Object.assign(v.full_configuration, { target_cents: 200030, monthly_contribution: { min_cents: 10001, target_cents: 30001, max_cents: 40007 } }); return v; }
export function dynamicProofFixture(body = dynamicPrepareFixture(), status: DynamicProof['status'] = 'VERIFIED_RANGE', effectHash: string | null = null): DynamicProof {
  const reserve = dynamicGoalFixture().reserve!;
  const value = { protocol: 'full-dynamic-goal-execution-v1' as const, simulation: true as const, bank_authority: false as const, preserves_original_permission_checks: true as const, user_id: userId, goal_id: body.goal_id, epoch_id: body.expected_epoch_id, policy_version_id: body.expected_policy_version_id, model_evidence_id: body.expected_model_evidence_id, model_evidence_hash: body.expected_model_evidence_hash, as_of: '2026-10-05T12:00:00Z', status, minimum_cents: status === 'UNKNOWN' ? null : 0, dynamic_cap_cents: status === 'UNKNOWN' ? null : 30006, remaining_max_cents: status === 'UNKNOWN' ? null : 30006, nominal_remaining_target_cents: status === 'UNKNOWN' ? null : 20000, context_hash: 'b'.repeat(64), input_hash: 'c'.repeat(64), full_projection_input_hash: status === 'UNKNOWN' ? null : 'd'.repeat(64), effect_hash: effectHash, reserve: status === 'UNKNOWN' ? null : reserve, reasons: status === 'VERIFIED_RANGE' ? [] : ['TOOL_ONLY_UNPROVEN_OR_BLOCKED'] };
  return { ...value, proof_hash: dynamicFixtureHash(value) };
}
export function dynamicPreviewFixture(body = dynamicPrepareFixture(), status: DynamicProof['status'] = 'VERIFIED_RANGE'): DynamicPreview { return { simulation: true, bank_authority: false, grants_authority: false, preview_only: true, user_id: userId, request: body, proof: dynamicProofFixture(body, status), execution_pipeline: 'ORIGINAL_ALLOCATE_GOAL_REQUIRES_INSTALLED_TYPED_HOOK', limitations: ['TOOL_ONLY_SYNTHETIC_NOT_FINANCIAL_PROOF'] }; }
export function dynamicActionFixture(stage: 'PREPARED' | 'CONFIRMED' | 'UNKNOWN' | 'SETTLED' = 'PREPARED'): DynamicAction {
  const effect: DynamicAction['effect'] = { simulation: true, operation_id: dynamicExecutionId, user_id: userId, business_key: `goal:${goalId}:2026-10`, action_type: 'ALLOCATE_GOAL', amount_cents: 30006, cash_uses: [{ account_id: accountId, amount_cents: 30006 }], income_uses: [{ fragment_id: fragmentId, origin_transaction_id: originId, account_id: accountId, amount_cents: 30006 }], destination_account_id: accountId, goal_id: goalId, policy_id: policyId, policy_version_id: versionId, policy_version_ids: [versionId], liability: null, payee_id: null, payee_evidence_id: null, product_id: null, product_version_number: null, terms_digest: null, position_id: null, position_account_id: null, return_account_id: null, purchase_exit: null, original_policy_version_id: null, fee_cents: 0, loss_cents: 0, net_cents: null, quote_id: null, settlement_delay_days: 0, latest_arrival_at: null, valid_from: '2026-10-05T12:00:00Z', expires_at: '2026-10-05T12:15:00Z' };
  const effectHash = dynamicFixtureHash(effect);
  return { simulation: true, user_id: userId, action_id: dynamicExecutionId, decision_run_id: dynamicRunId, status: stage === 'PREPARED' ? 'PLANNED' : stage === 'CONFIRMED' ? 'AUTHORIZED' : stage === 'UNKNOWN' ? 'UNKNOWN' : 'SUCCEEDED', autonomy_level: 'ASK_ONCE', effect, effect_hash: effectHash, prepared_at: effect.valid_from, as_of: effect.valid_from, prepared_validation: { simulation: true, financial_only: true, status: 'CONFIRMATION_REQUIRED', effect_hash: effectHash, baseline_boundary: boundaryFixture(), reasons: ['TOOL_ONLY_SYNTHETIC'] }, bank_status: stage === 'UNKNOWN' ? 'SETTLED' : stage === 'SETTLED' ? 'SETTLED' : null, receipt: stage === 'SETTLED' ? { simulation: true, action_id: dynamicExecutionId, receipt_id: '92000000-0000-4000-8000-000000000004', bank_operation_id: '92000000-0000-4000-8000-000000000005', status: 'SETTLED', executed_cents: 30006, fee_cents: 0, loss_cents: 0, posting_ids: ['92000000-0000-4000-8000-000000000006'], occurred_at: effect.valid_from, reconciled_at: null } : null };
}
export function dynamicLookupFixture(intent: DynamicIntent, stage: 'NOT_FOUND' | 'PREPARED' | 'CONFIRMED' | 'UNKNOWN' | 'SETTLED' | 'MISSING_CONFIRM' = 'PREPARED'): DynamicLookup {
  const value: DynamicLookup = { simulation: true, bank_authority: false, grants_authority: false, current_authority: false, not_found_is_final: false, user_id: userId, idempotency_key: intent.prepare_request.idempotency_key, status: stage === 'NOT_FOUND' ? 'NOT_FOUND' : 'RECORDED', original_request: null, original_action_request: null, client_request_hash: null, server_request_hash: null, epoch_state: 'MISSING', historical: false, action: null, confirmation: null, confirmation_status: 'ABSENT', confirmation_verified_at: null, confirmation_is_current_authority: false };
  if (stage === 'NOT_FOUND') return value;
  const action = dynamicActionFixture(stage === 'MISSING_CONFIRM' ? 'CONFIRMED' : stage); const body = intent.prepare_request;
  const original = { intent: { kind: 'allocate_goal', goal_id: goalId }, execution: { effect: action.effect, effect_hash: action.effect_hash }, prepared_validation: action.prepared_validation, confirmation_evidence_id: dynamicConfirmationId, full_dynamic_goal_execution: { protocol: 'full-dynamic-goal-execution-v1', user_id: userId, epoch_id: epochId, request: body, request_hash: dynamicFixtureHash(body), effect_hash: action.effect_hash, original_proof: dynamicProofFixture(body, 'VERIFIED_RANGE', action.effect_hash) } };
  Object.assign(value, { original_request: body, original_action_request: original, client_request_hash: dynamicFixtureHash(body), server_request_hash: dynamicFixtureHash(original), epoch_state: 'OPEN', action });
  if (stage !== 'PREPARED') { value.confirmation_status = stage === 'MISSING_CONFIRM' ? 'MISSING' : 'VERIFIED_AT_CONFIRMATION'; if (stage !== 'MISSING_CONFIRM') { value.confirmation = { user_id: userId, operation_id: action.action_id, effect_hash: action.effect_hash, evidence_id: dynamicConfirmationId, confirmed_at: action.prepared_at, expires_at: action.effect.expires_at }; value.confirmation_verified_at = action.prepared_at; } }
  return value;
}
