/** TOOL_ONLY synthetic command/receipt responses; no bank, PG or human evidence. */
import { createHash } from 'node:crypto';
import { recoveryCanonicalJson } from '../api/full-recovery-execution';
import { maturityActionId, maturityBankKey } from '../api/full-maturity-execution';
import type { MaturityAction, MaturityIntent, MaturityLookup, MaturityPrepare, MaturityPreview } from '../api/full-maturity-execution';
const id = (n: number) => `00000000-0000-0000-0000-${n.toString(16).padStart(12, '0')}`;
export const maturityUser = id(1), maturityEpoch = id(981), maturityAt = '2026-04-01T00:00:00Z';
export const maturityHash = (v: unknown) => createHash('sha256').update(recoveryCanonicalJson(v)).digest('hex');
export const maturityPrepareFixture = (): MaturityPrepare => ({ policy_id: id(901), expected_version_id: id(902), expected_epoch_id: maturityEpoch, position_id: id(903), idempotency_key: 'TOOL_ONLY_MATURE' });
export const maturityCommandFixture = () => ({ user_id: maturityUser, position_id: id(903), position_account_id: id(904), product_id: id(905), goal_id: null, original_policy_version_id: id(906), destination_account_id: id(907), principal_cents: 10001, requested_at: maturityAt, available_at: maturityAt, expires_at: '2026-04-01T00:15:00Z', kind: 'MATURE' as const });
const commandHash = (body: MaturityPrepare) => maturityHash({ protocol: 'full-maturity-user-execution-v1', request: body, bank_request: maturityCommandFixture() });
export function maturityPreviewFixture(body = maturityPrepareFixture(), unknown = false): MaturityPreview {
  const proof = { protocol: 'full-maturity-user-execution-v1' as const, simulation: true as const, grants_authority: false as const, receipt_is_current_authority: false as const, bank_receipt_proven: false as const, projected_cash_is_current_cash: false as const, user_id: maturityUser, epoch_id: body.expected_epoch_id, position_id: body.position_id, as_of: maturityAt, status: unknown ? 'UNKNOWN' as const : 'VERIFIED_SCOPE' as const, reasons: unknown ? ['TOOL_ONLY_UNKNOWN'] : [], command: unknown ? null : maturityCommandFixture(), candidate_denominator: 1, input_hash: 'a'.repeat(64), command_hash: unknown ? null : commandHash(body), conditional_protection_hash: unknown ? null : 'b'.repeat(64), remaining_negative_checkpoints: unknown ? null : 3, proof_hash: '' };
  const { proof_hash: _old, ...compact } = proof; void _old; proof.proof_hash = maturityHash(compact);
  return { simulation: true, bank_authority: false, grants_authority: false, read_only: true, user_id: maturityUser, original_request: body, proof, limitations: ['TOOL_ONLY_NOT_FINANCIAL_EVIDENCE'] };
}
export async function maturityActionFixture(body = maturityPrepareFixture(), stage: 'PREPARED' | 'CONFIRMED' | 'UNKNOWN' | 'SETTLED' = 'PREPARED'): Promise<MaturityAction> {
  const actionId = await maturityActionId(body), bankKey = await maturityBankKey(body.idempotency_key), command = maturityCommandFixture(), reviewed = commandHash(body), principal = { user_id: maturityUser, role: 'USER' as const, session_id: id(910), issued_at: maturityAt, expires_at: command.expires_at, authentication_source: 'LOCAL_SIGNED_SESSION' as const, authenticated: true as const, human_identity_verified: false as const };
  const original = { bank_request: command, contract_terms_digest: 'c'.repeat(64), contract_evidence_ids: [id(911)], full_maturity_execution: { protocol: 'full-maturity-user-execution-v1', user_id: maturityUser, epoch_id: body.expected_epoch_id, action_id: actionId, request: body, client_request_hash: maturityHash(body), command_hash: reviewed, original_proof_hash: maturityPreviewFixture(body).proof.proof_hash } };
  const status = stage === 'PREPARED' ? 'PLANNED' : stage === 'CONFIRMED' ? 'AUTHORIZED' : stage === 'UNKNOWN' ? 'UNKNOWN' : 'SUCCEEDED';
  const row = { id: actionId, user_id: maturityUser, action_type: 'ASSET_MATURITY', status, idempotency_key: bankKey, request: original, request_hash: maturityHash(original), position_id: body.position_id, product_id: command.product_id, policy_version_id: command.original_policy_version_id, goal_id: null, amount_cents: command.principal_cents, source_account_id: command.position_account_id, destination_account_id: command.destination_account_id };
  const bank = { id: id(912), user_id: maturityUser, action_plan_id: actionId, position_id: body.position_id, destination_account_id: command.destination_account_id, product_id: command.product_id, goal_id: null, principal_cents: command.principal_cents, idempotency_key: bankKey, request: command, request_hash: maturityHash(command), requested_at: '2026-04-01T00:00:00.000000Z', available_at: '2026-04-01T00:00:00.000000Z', settled_at: maturityAt, status: 'SETTLED' };
  const received = stage === 'SETTLED', hasBank = received || stage === 'UNKNOWN';
  const originals = { action: row, bank_requests: hasBank ? [bank] : [], bank_operations: hasBank ? [{ ...bank, legacy_redemption_id: bank.id }] : [], receipts: received ? [{ id: id(913), user_id: maturityUser, action_plan_id: actionId, executed_cents: command.principal_cents, fee_cents: 0, loss_cents: 0, status: 'SUCCEEDED', occurred_at: maturityAt, response: { bank_request_id: bank.id, posting_ids: [id(914), id(915)] } }] : [], position: { id: body.position_id, user_id: maturityUser, status: received ? 'REDEEMED' : 'HELD' } };
  const event = { action_id: actionId, position_id: body.position_id, original_product_id: command.product_id, original_policy_version_id: command.original_policy_version_id, goal_id: null, destination_account_id: command.destination_account_id, original_action_status: status, bank_operation_id: hasBank ? bank.id : null, original_bank_status: hasBank ? 'SETTLED' : null, original_receipt_id: received ? id(913) : null, principal_cents: command.principal_cents, settled_at: hasBank ? maturityAt : null, proof_status: received ? 'VERIFIED' : stage === 'UNKNOWN' ? 'UNKNOWN' : 'NOT_RECEIVED', service_receipt_verified: received, receipt_is_current_authority: false, economic_verified: false, absence_is_final: false, originals_hash: maturityHash(originals), originals, issues: received ? [] : ['TOOL_ONLY_NOT_RECEIVED'] };
  return { simulation: true, bank_authority: false, receipt_is_current_authority: false, user_id: maturityUser, action_id: actionId, epoch_id: body.expected_epoch_id, original_request: body, original_action_request: original, client_request_hash: maturityHash(body), server_request_hash: maturityHash(original), reviewed_command_hash: reviewed, bank_key: bankKey, autonomy_level: 'ASK_ONCE', status, command, original_consent: stage === 'PREPARED' ? null : { protocol: 'full-maturity-user-execution-v1', simulation: true, grants_authority: false, user_id: maturityUser, epoch_id: body.expected_epoch_id, action_id: actionId, reviewed_command_hash: reviewed, original_confirmation: { expected_epoch_id: body.expected_epoch_id, reviewed_command_hash: reviewed, accepted: true }, principal_at_confirmation: principal, confirmed_at: maturityAt }, original_event: event, economic_verified: false, service_receipt_verified: received, epoch_state: 'OPEN', historical: false };
}
export async function maturityLookupFixture(intent: MaturityIntent, stage: 'NOT_FOUND' | 'PREPARED' | 'CONFIRMED' | 'UNKNOWN' | 'SETTLED' = 'PREPARED'): Promise<MaturityLookup> { return { simulation: true, grants_authority: false, not_found_is_final: false, user_id: maturityUser, idempotency_key: intent.prepare_request.idempotency_key, status: stage === 'NOT_FOUND' ? 'NOT_FOUND_NOT_FINAL' : 'RECORDED', action: stage === 'NOT_FOUND' ? null : await maturityActionFixture(intent.prepare_request, stage) }; }
export const maturityPositionsFixture = () => ({ simulation: true, items: [{ id: id(903), account_id: id(904), product_id: id(905), goal_id: null, policy_version_id: id(906), principal_cents: 10001, accrued_yield_cents: 0, purchased_at: '2026-03-01T00:00:00Z', maturity_at: maturityAt, available_at: null, status: 'MATURED' }] });
export const maturityLocalSessionFixture = () => ({ simulation: true, bank_authority: false, confirms_financial_action: false, principal: { user_id: maturityUser, role: 'USER', session_id: id(910), issued_at: maturityAt, expires_at: '2026-04-01T00:15:00Z', authentication_source: 'LOCAL_SIGNED_SESSION', authenticated: true, human_identity_verified: false } });
