/** SYNTHETIC_HTTP_ONLY. Real cryptographic formatting checks, no financial execution evidence. */
import type { Goal } from '../api/goals';
import type { ReleaseIntent, ReleaseLookup, ReleasePreview, ReleaseResponse, ReleaseReview, ReleaseScope } from '../api/goal-release-authorizations';
import { releaseHash, releaseUUID5 } from '../api/goal-release-authorizations';
import { prepareGoalReleaseIntent } from '../features/goal-release-authorization-operation';
import { repairPolicyFixture } from './goal-reallocation-fixture';
import { accountId, epochId, fullModelFixture, goalId, modelGoal, otherGoalId, userId } from './full-goal-fixture';
export const releaseBinding = { goal: modelGoal, userId, epochId };
const secondaryPolicy = '76000000-0000-4000-8000-000000000001', secondaryVersion = '76000000-0000-4000-8000-000000000002', secondaryEvidence = '76000000-0000-4000-8000-000000000003';
export async function releaseReviewFixture(): Promise<ReleaseReview> {
  const policy = repairPolicyFixture(); const config = policy.current_version.configuration; config.source_goal_ids = [goalId, otherGoalId];
  policy.current_version.content_hash = await releaseHash(config); policy.current_version.confirmation.reviewed_hash = policy.current_version.content_hash; policy.current_version.valid_until = '2026-12-01T00:00:00Z';
  const goal: Goal = { ...modelGoal, account_id: accountId, target_cents: 550001, allocated_cents: 40001, deadline: '2027-10-05', monthly_min_cents: 10001, monthly_target_cents: 20003, monthly_max_cents: 30007, importance: 67, minimum_protection_cents: 10001, reducible: true, deferrable: true, cross_goal_reallocation_allowed: false, asset_policy_id: null };
  const secondary: Goal = { ...goal, id: otherGoalId, name: '合成第二来源目标', policy_id: secondaryPolicy, policy_version_id: secondaryVersion, minimum_protection_cents: 23003 };
  const model = fullModelFixture(); model.full_configuration_hash = await releaseHash(model.full_configuration);
  const secondModel = fullModelFixture(); secondModel.goal_id = secondary.id; secondModel.policy_id = secondary.policy_id; secondModel.base_policy_version_id = secondary.policy_version_id; secondModel.evidence_id = secondaryEvidence; secondModel.confirmed_at = '2026-10-05T12:01:00Z'; secondModel.full_configuration!.minimum_guarantee_cents = secondary.minimum_protection_cents; secondModel.full_configuration_hash = await releaseHash(secondModel.full_configuration);
  const sources = [{ goal, model }, { goal: secondary, model: secondModel }];
  const scope: ReleaseScope = { protocol: 'full-goal-release-authorization-v1', simulation: true, user_id: userId, epoch_id: epochId, policy_id: policy.policy_id, policy_version_id: policy.current_version.version_id, policy_configuration_hash: policy.current_version.content_hash, source_goals: sources.map((s) => ({ goal_id: s.goal.id, original_policy_id: s.goal.policy_id, original_policy_version_id: s.goal.policy_version_id, full_model_evidence_id: s.model.evidence_id!, full_model_evidence_hash: s.model.evidence_hash!, full_configuration_hash: s.model.full_configuration_hash!, minimum_guarantee_cents: s.goal.minimum_protection_cents })), emergency_conditions: ['EMERGENCY_BUFFER_SHORTFALL', 'HARD_OBLIGATION_SHORTFALL', 'LIVING_RESERVE_SHORTFALL'], destination_scope: 'PROTECTED_CASH', single_action_cap_cents: 30007, total_cap_cents: 70001, valid_from: '2026-10-05T12:01:00Z', valid_until: policy.current_version.valid_until!, principal_release_allowed: false, ordinary_goal_redistribution_allowed: false, creates_new_income: false, changes_original_assigned_income: false, cumulative_scope: 'POLICY_ID_ALL_VERSIONS', overrides_default_lock_only_for_listed_emergencies: true };
  const preview: ReleasePreview = { simulation: true, scope, scope_hash: await releaseHash(scope), financial_permission_recorded: false, current_financial_amount_verified: false, execution_support: 'NOT_IMPLEMENTED' };
  return { policy, sources, preview, originals: { policy: JSON.stringify(policy), goals: JSON.stringify({ simulation: true, items: sources.map((s) => s.goal) }), models: sources.map((s) => JSON.stringify(s.model)) } };
}
export async function releaseIntentFixture(key = 'UNIT_ORIGINAL_RELEASE:1'): Promise<ReleaseIntent> { const review = await releaseReviewFixture(); return prepareGoalReleaseIntent(userId, goalId, review.preview.scope, { expected_epoch_id: epochId, expected_policy_version_id: review.policy.current_version.version_id, reviewed_scope_hash: review.preview.scope_hash, accepted: true, idempotency_key: key }); }
export async function releaseResponseFixture(intent: ReleaseIntent, status: ReleaseResponse['current_scope_status'] = 'CURRENT', replay = false): Promise<ReleaseResponse> {
  const authorizationId = await releaseUUID5('c341ff79-6c74-5fc9-a892-b9f5a53ac303', `${intent.user_id}:${intent.body.expected_epoch_id}:${intent.body.idempotency_key}`);
  const original: ReleaseResponse['original_authorization'] = { protocol: 'full-goal-release-authorization-v1', authorization_id: authorizationId, user_id: intent.user_id, epoch_id: intent.body.expected_epoch_id, policy_id: intent.policy_id, policy_version_id: intent.body.expected_policy_version_id, scope: structuredClone(intent.reviewed_scope), scope_hash: intent.body.reviewed_scope_hash, accepted: true, idempotency_key: intent.body.idempotency_key, original_request: structuredClone(intent.body), request_hash: intent.request_hash, confirmed_at: '2026-10-05T12:02:00Z', valid_until: intent.reviewed_scope.valid_until, permission_kind: 'EMERGENCY_GOAL_CASH_RELEASE' };
  return { simulation: true, original_authorization: original, evidence_id: await releaseUUID5(authorizationId, 'authorization-evidence'), evidence_hash: await releaseHash(original), original_trace_hash: 'f'.repeat(64), idempotent_replay: replay, current_scope_status: status, current_financial_amount_verified: false, execution_support: 'NOT_IMPLEMENTED', submits_bank_operation: false };
}
export async function releaseLookupFixture(intent: ReleaseIntent, found = true, status: ReleaseResponse['current_scope_status'] = 'CURRENT'): Promise<ReleaseLookup> { return { simulation: true, user_id: intent.user_id, epoch_id: intent.body.expected_epoch_id, idempotency_key: intent.body.idempotency_key, status: found ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', original: found ? await releaseResponseFixture(intent, status, true) : null, replacement_allowed: false }; }
