/** SYNTHETIC_HTTP_ONLY. Never a real authorization, bank leg or financial outcome. */
import type { CashAction, CashCandidate, CashIntent, CashLookup, CashUse } from '../api/goal-cash-releases';
import { createCashIntent } from '../api/goal-cash-releases';
import { releaseHash, releaseUUID5 } from '../api/goal-release-authorizations';
import { releaseIntentFixture, releaseResponseFixture, releaseReviewFixture } from './goal-release-authorization-fixture';
import { repairFixture } from './goal-reallocation-fixture';
import { modelGoal, userId, epochId, accountId } from './full-goal-fixture';
export const cashBinding = { goal: modelGoal, userId, epochId };
export const cashDestination = '96000000-0000-4000-8000-000000000001';
export const cashAsOf = '2026-10-05T12:04:00Z';
export async function cashIntentFixture(key = 'SYNTHETIC_ORIGINAL_CASH:1'): Promise<CashIntent> {
  const intent = await releaseIntentFixture(); return createCashIntent(cashBinding, await releaseResponseFixture(intent), cashDestination, key);
}
export async function cashUseFixture(): Promise<CashUse> {
  const origin = '96000000-0000-4000-8000-000000000002';
  return { allocation_action_id: '96000000-0000-4000-8000-000000000003', original_policy_version_id: modelGoal.policy_version_id, origin_transaction_id: origin, income_location_account_id: cashDestination, fragment_id: await releaseUUID5(origin, `income-location:${cashDestination}`), allocation_effect_hash: 'a'.repeat(64), allocation_bank_request_hash: 'b'.repeat(64), allocation_action_request_hash: 'c'.repeat(64), amount_cents: 24001 };
}
export async function cashActionFixture(intent: CashIntent, state: 'PLANNED' | 'UNKNOWN' | 'SUCCEEDED' = 'PLANNED'): Promise<CashAction> {
  const a = intent.authorization.original_authorization, source = a.scope.source_goals.find((g) => g.goal_id === intent.body.source_goal_id)!;
  const actionId = await releaseUUID5('321c7149-2db6-5338-a4de-0166d6cdf303', `${intent.user_id}:${intent.body.expected_epoch_id}:${intent.body.idempotency_key}`);
  const effect: CashAction['original_command']['effect'] = {
    protocol: 'full-goal-release-effect-v1', simulation: true, action_type: 'RELEASE_GOAL', operation_id: actionId, user_id: intent.user_id, epoch_id: intent.body.expected_epoch_id, business_key: `goal-release:${actionId}`, bank_idempotency_key: 'goal-release:' + await releaseHash({ user_id: intent.user_id, epoch_id: intent.body.expected_epoch_id, key: intent.body.idempotency_key }),
    policy_id: a.policy_id, policy_version_id: a.policy_version_id, policy_configuration_hash: a.scope.policy_configuration_hash, authorization_id: a.authorization_id, authorization_evidence_id: intent.authorization.evidence_id, authorization_evidence_hash: intent.authorization.evidence_hash, authorization_scope_hash: a.scope_hash, authorization_request_hash: a.request_hash,
    source_goal_id: source.goal_id, original_goal_policy_id: source.original_policy_id, original_goal_policy_version_id: source.original_policy_version_id, full_model_evidence_id: source.full_model_evidence_id, full_model_evidence_hash: source.full_model_evidence_hash, full_configuration_hash: source.full_configuration_hash, minimum_guarantee_cents: source.minimum_guarantee_cents,
    source_account_id: accountId, destination_account_id: intent.body.destination_account_id, destination_scope: 'PROTECTED_CASH', amount_cents: 24001, emergency_conditions: [...a.scope.emergency_conditions], release_uses: [await cashUseFixture()], source_provenance_hash: 'd'.repeat(64), financial_input_hash: 'e'.repeat(64), valid_from: cashAsOf, expires_at: '2026-10-05T12:19:00Z', cumulative_scope: 'POLICY_ID_ALL_VERSIONS', fee_cents: 0, loss_cents: 0, principal_change_cents: 0, other_goal_change_cents: 0, available_income_increase_cents: 0, assigned_income_decrease_cents: 0,
  };
  const effectHash = await releaseHash(effect), settled = state !== 'PLANNED', complete = state === 'SUCCEEDED';
  const receiptId = await releaseUUID5(actionId, 'receipt'), legRefs = [`cash:${accountId}`, `cash:${cashDestination}`, 'goal_cash'];
  return { schema_version: 'goal-release-action-v1', simulation: true, user_id: intent.user_id, as_of: cashAsOf, action_id: actionId, original_action_status: state, original_command: { protocol: 'full-goal-release-bank-v1', effect, effect_hash: effectHash }, original_request_hash: 'f'.repeat(64), original_prepare_request: structuredClone(intent.body), decision_run_id: await releaseUUID5(actionId, 'decision'), action_confirmation_evidence_id: settled ? await releaseUUID5(actionId, 'release-confirmation:' + effectHash) : null, action_confirmation_verified: settled, bank_operation_id: settled ? actionId : null, original_bank_status: settled ? 'SETTLED' : null, bank_settlement_legs_verified: settled, receipt_id: complete ? receiptId : null, service_receipt_verified: complete,
    original_receipt: complete ? { id: receiptId, user_id: intent.user_id, created_at: cashAsOf, action_plan_id: actionId, attempt_number: 1, receipt_ref: `bank-operation:${actionId}`, status: 'SUCCEEDED', executed_cents: effect.amount_cents, fee_cents: 0, loss_cents: 0, occurred_at: cashAsOf, reconciled_at: cashAsOf, response: { bank_operation_id: actionId, posting_ids: await Promise.all(legRefs.map((l) => releaseUUID5(actionId, 'posting:' + l))), transaction_ids: await Promise.all(legRefs.slice(0, 2).map((l) => releaseUUID5(actionId, 'transaction:' + l))) } } : null,
    unresolved: state === 'UNKNOWN', read_only_response: true, current_authority_assessed: false, receipt_is_current_authority: false, economic_experiment_verified: false, grants_new_authority: false,
  };
}
export async function cashCandidateFixture(intent: CashIntent, unknown = false): Promise<CashCandidate> {
  const preview = repairFixture(), review = await releaseReviewFixture(); preview.as_of = cashAsOf; preview.policy = review.policy; preview.goal_model = review.sources[0]!.model; preview.goal_ownership!.allocated_cents = 67003; preview.goal_ownership!.principal.application_cents = preview.goal_ownership!.principal.bank_cents = 0;
  const use = await cashUseFixture();
  const inventory = { schema_version: 'goal-release-inventory-v1', user_id: intent.user_id, epoch_id: epochId, as_of: cashAsOf, goal_id: modelGoal.id, goal_policy_version_id: modelGoal.policy_version_id, full_policy_id: intent.body.policy_id, state: 'VERIFIED', original_basis: { state: 'VERIFIED_CASH_ONLY', user_id: intent.user_id, epoch_id: epochId, goal_id: modelGoal.id, goal_account_id: accountId, reasons: [] }, residual: { state: 'VERIFIED' }, release_uses_available: [use], policy_usage: { state: 'VERIFIED', cap_occupied_cents: 0 }, inventory: ['action_plans', 'action_receipts', 'bank_operations', 'simulated_bank_postings'].map((table) => ({ table, actual_count: 0, captured_count: 0, complete: true, original_refs: [] })), release_originals: [], financial_truth_verified: true, application_projection_matched: true, source_binding_hash: 'd'.repeat(64), reasons: [], bank_authority: false, funds_released: false, creates_new_income: false, changes_original_assigned_income: false };
  // Deliberately synthetic partial nested inventory: reader assertions are tested,
  // no producer/financial completeness or domain oracle is claimed by this cast.
  return { user_id: intent.user_id, epoch_id: epochId, as_of: cashAsOf, original_request: structuredClone(intent.body), state: unknown ? 'UNKNOWN' : 'READY', amount_cents: unknown ? null : 24001, actual_preview: preview, actual_inventory: inventory as unknown as CashCandidate['actual_inventory'], original_authorization: structuredClone(intent.authorization), protection: { status: 'VERIFIED_NONWORSENING', actual_before_input_hash: 'a'.repeat(64), hypothetical_after_input_hash: 'b'.repeat(64), compared_point_count: 1098, expected_point_count: 1098, reasons: [], source_hash: 'c'.repeat(64), bank_authority: false, hypothetical_is_bank_fact: false }, selected_release_uses: unknown ? [] : [structuredClone(use)], reasons: unknown ? ['SYNTHETIC_MISSING_ORIGINALS'] : [], input_hash: 'e'.repeat(64), bank_authority: false, creates_new_income: false };
}
export const cashAccountsFixture = () => ({ simulation: true, user_id: userId, timezone: 'UTC', oldest_account_observed_at: cashAsOf, latest_account_observed_at: cashAsOf, accounts: [{ id: cashDestination, external_ref: 'SYNTHETIC', name: '合成保护现金账户', account_type: 'CASH', bank_code: 'ICBC', currency: 'CNY', balance_cents: 100001, observed_at: cashAsOf }], credit_card_bills: [], cash_balance_cents: 100001, position_principal_cents: 0, unknown_position_principal_cents: 0, credit_card_unpaid_cents: 0 });
export const cashLookupFixture = (intent: CashIntent, action: CashAction | null): CashLookup => ({ user_id: intent.user_id, epoch_id: intent.body.expected_epoch_id, idempotency_key: intent.body.idempotency_key, status: action ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', original: action, not_found_is_final: false, replacement_allowed: false });
