/** SYNTHETIC_HTTP_ONLY: exact representation fixtures, not ownership/grant/PG/repair evidence. */
import type { ReallocationBinding, ReallocationPreview, ReallocationRequest } from '../api/goal-reallocation';
import type { FullPolicy } from '../api/full-policies';
import { fullPolicyFixture } from './full-policy-fixture';
import { accountId, epochId, fullModelFixture, goalId, modelGoal, userId, versionId } from './full-goal-fixture';
export const repairBinding: ReallocationBinding = { goal: modelGoal, userId, epochId };
const originalTime = '2026-10-05T12:00:00Z';
export function repairPolicyFixture(disabled = false): FullPolicy {
  const policy = fullPolicyFixture(); policy.epoch_id = epochId; policy.template_name = 'CrossGoalReallocationPolicy'; policy.name = '合成明确回拨规则'; policy.current_version.configuration = { type: 'cross_goal_reallocation', name: policy.name, enabled: !disabled, source_goal_ids: [goalId], emergency_conditions: disabled ? [] : ['HARD_OBLIGATION_SHORTFALL', 'LIVING_RESERVE_SHORTFALL', 'EMERGENCY_BUFFER_SHORTFALL'], destination_scope: 'PROTECTED_CASH', single_action_cap_cents: disabled ? 0 : 30007, total_cap_cents: disabled ? 0 : 70001, valid_from: disabled ? null : '2026-10-01', valid_until: disabled ? null : '2026-11-30' }; policy.current_version.confirmation = { ...policy.current_version.confirmation, epoch_id: epochId, user_id: userId, template_name: policy.template_name }; return policy;
}
export function repairRequestFixture(policy = repairPolicyFixture()): ReallocationRequest { return { policy_id: policy.policy_id, source_goal_id: goalId, expected_policy_version_id: policy.current_version.version_id, expected_goal_policy_version_id: versionId, expected_epoch_id: epochId }; }
export function repairFixture(mode: 'UNKNOWN_USAGE' | 'UNKNOWN_MATH' | 'DISABLED' | 'NO_EMERGENCY' | 'MODEL_MISSING' | 'OWNERSHIP_MISSING' = 'UNKNOWN_USAGE'): ReallocationPreview {
  const policy = repairPolicyFixture(mode === 'DISABLED'), model = fullModelFixture(); model.full_configuration!.minimum_guarantee_cents = 50005;
  const unknown = mode === 'UNKNOWN_MATH', noEmergency = mode === 'NO_EMERGENCY', floors = { HARD_OBLIGATION_SHORTFALL: noEmergency ? 0 : 40001, LIVING_RESERVE_SHORTFALL: noEmergency ? 0 : 12001, EMERGENCY_BUFFER_SHORTFALL: noEmergency ? 0 : 5003 }, shortfall = { HARD_OBLIGATION_SHORTFALL: noEmergency ? 0 : 6997, LIVING_RESERVE_SHORTFALL: noEmergency ? 0 : 12001, EMERGENCY_BUFFER_SHORTFALL: noEmergency ? 0 : 5003 };
  const amount = (kind: 'GOAL_CASH' | 'GOAL_PRINCIPAL', cents: number): NonNullable<ReallocationPreview['goal_ownership']>['cash'] => ({ entity_id: goalId, kind, application_cents: cents, bank_cents: cents, difference_cents: 0, state: 'MATCHED', bank_head: { posting_id: kind === 'GOAL_CASH' ? '93000000-0000-4000-8000-000000000001' : '93000000-0000-4000-8000-000000000002', ledger_key: `${kind}:${goalId}`, sequence_number: 1, occurred_at: originalTime } });
  const reasons = ['LIFETIME_POLICY_USAGE_ORIGINALS_MISSING', 'DEDICATED_ORIGINAL_GOAL_GRANT_AND_EXECUTION_NOT_IMPLEMENTED'];
  const source_issues: ReallocationPreview['source_issues'] = [];
  if (unknown) { reasons.push('CURRENT_BANK_APPLICATION_OR_AUDIT_NOT_VERIFIED', 'CURRENT_CORE_REPAIR_MATH_NOT_VERIFIED'); source_issues.push({ code: 'CURRENT_BANK_APPLICATION_OR_AUDIT_NOT_VERIFIED', entity_type: 'reconciliation', entity_id: 'fixture' }); }
  if (mode === 'DISABLED') reasons.unshift('CROSS_GOAL_REALLOCATION_DEFAULT_DISABLED', 'ACTUAL_EMERGENCY_CONDITION_NOT_ALLOWED', 'MINIMUM_REPAIR_EXCEEDS_SINGLE_CAP');
  if (mode === 'MODEL_MISSING') { reasons.push('FULL_GOAL_MINIMUM_MODEL_MISSING', 'FULL_GOAL_MINIMUM_GUARANTEE_NOT_VERIFIED'); source_issues.push({ code: 'FULL_GOAL_MINIMUM_MODEL_MISSING', entity_type: 'goal', entity_id: goalId }); }
  if (mode === 'OWNERSHIP_MISSING') reasons.push('ORIGINAL_GOAL_CASH_OWNERSHIP_NOT_VERIFIED');
  return { schema_version: 'full-goal-reallocation-preview-v1', user_id: userId, epoch_id: epochId, as_of: originalTime, simulation: true, read_only: true, bank_authority: false, financial_grant_created: false, original_goal_bridge_cross_enabled: false, execution_support: 'NOT_IMPLEMENTED', original_request: repairRequestFixture(policy), policy,
    goal_model: mode === 'MODEL_MISSING' ? fullModelFixture(true) : model, goal_ownership: mode === 'OWNERSHIP_MISSING' ? null : { goal_id: goalId, account_id: accountId, allocated_cents: 100009, position_ids: [], ownership_evidence_id: '93000000-0000-4000-8000-000000000003', ownership_evidence_hash: 'd'.repeat(64), current_ownership_proof_verified: true, cash: amount('GOAL_CASH', 67003), principal: amount('GOAL_PRINCIPAL', 33006) },
    original_current_protection_point: unknown ? null : { day: 0, date: '2026-10-05', phase: 'BEFORE_PAYMENT', cash_cents: 100007, protected_cents_by_reason: { obligations: floors.HARD_OBLIGATION_SHORTFALL, living: floors.LIVING_RESERVE_SHORTFALL, emergency: floors.EMERGENCY_BUFFER_SHORTFALL, goal_cash: 67003, goal_minimum: 0 }, margin_cents: noEmergency ? 33004 : -24001, obligation_occurrence_ids: [], principal_position_ids: [] },
    decision: { algorithm_version: 'current-core-cash-ownership-repair-v1', state: noEmergency ? 'NO_EMERGENCY' : mode === 'DISABLED' ? 'BLOCKED' : 'UNKNOWN', math: { status: unknown ? 'UNKNOWN' : 'COMPUTED', cash_cents: unknown ? null : 100007, locked_goal_cash_cents: unknown ? null : 67003, reserved_cash_cents: unknown ? null : 0, unowned_unreserved_cash_cents: unknown ? null : 33004, required_by_condition: unknown ? null : floors, shortfall_by_condition: unknown ? null : shortfall, minimum_repair_cents: unknown ? null : noEmergency ? 0 : 24001, source_cash_releasable_above_minimum_cents: ['MODEL_MISSING', 'OWNERSHIP_MISSING'].includes(mode) ? null : 50004, unique_minimum_for_registered_current_scope: !unknown, principal_release_cents: 0, future_income_used_cents: 0 }, triggered_conditions: unknown || noEmergency ? [] : ['HARD_OBLIGATION_SHORTFALL', 'LIVING_RESERVE_SHORTFALL', 'EMERGENCY_BUFFER_SHORTFALL'], candidate_amount_cents: null, cumulative_used_cents: null, cumulative_remaining_cents: null, source_goal_id: goalId, destination_scope: 'PROTECTED_CASH', planning_only: true, bank_authority: false, dedicated_confirmation_required: true, execution_support: 'NOT_IMPLEMENTED', preserves_principal_placement: true, repairs_performed: false, reasons, input_hash: 'a'.repeat(64) }, reconciliation_input_hash: 'b'.repeat(64), full_protection_input_hash: 'c'.repeat(64), source_binding_hash: 'd'.repeat(64), source_issues, limitations: ['SYNTHETIC_HTTP_ONLY_NOT_FINANCIAL_PROOF', '原桥不启跨目标，独立目标授权/累计用量/资金执行未接'] };
}
