/** SYNTHETIC_HTTP_FIXTURE_ONLY. No bank, history estimate, candidate or browser acceptance is evidenced. */
import type { Compilation, Proposal } from '../api/policies';
import type { DeclarationRecord, Discovery, Reserve, Transactions } from '../api/onboarding';
import type { CandidateRef, OnboardingBinding, OnboardingIntent } from '../features/onboarding-draft';
import { dashboardFixture } from './dashboard-fixture';
import { epochId } from './demo-fixture';
export const onboardingUser = '10000000-0000-0000-0000-000000000001';
export const onboardingAccount = '10000000-0000-0000-0000-000000000002';
export const emergencyCompilation = '72000000-0000-4000-8000-000000000001';
export const goalCompilation = '72000000-0000-4000-8000-000000000002';
export const emergencyProposal = '72000000-0000-4000-8000-000000000003';
export const goalProposal = '72000000-0000-4000-8000-000000000004';
export const obligationProposal = '72000000-0000-4000-8000-000000000005';
export const onboardingBinding = (): OnboardingBinding => ({ user_id: onboardingUser, epoch_id: epochId, reference_date: '2026-10-04', timezone: 'Asia/Shanghai' });
export const emergencyText = '保留3000元应急金';
export const goalText = '旅行目标1.2万元，截止2027-06-30，每月固定储备1000元。';
export function compilationFixture(goal = false, incomplete = false): Compilation {
  const config = goal ? { type: 'goal_saving', name: 'HTTP夹具旅行', valid_from: null, valid_until: null, target_cents: 1200000, deadline: '2027-06-30', monthly_contribution: { min_cents: 100000, target_cents: 100000, max_cents: 100000 }, priority: { importance: 50, minimum_cents: 0, reducible: false, deferrable: false }, asset_policy_id: null, cross_goal_reallocation_allowed: false } : { type: 'emergency_buffer', name: 'HTTP夹具应急金', valid_from: null, valid_until: null, amount_cents: 300000 };
  return { simulation: true, user_id: onboardingUser, compilation_id: goal ? goalCompilation : emergencyCompilation, compilation: { compiler_version: 'offline-policy-rules-v1', reference_date: '2026-10-04', timezone: 'Asia/Shanghai', draft: config, configuration: incomplete ? null : config, issues: incomplete ? [{ code: 'SYNTHETIC_MISSING_FIELD', field: 'amount_cents', message: 'SYNTHETIC_REQUIRED', source_fragment: '' }] : [], assumptions: ['SYNTHETIC_CANDIDATE_NOT_AUTHORITY'] }, configuration: incomplete ? null : config, configuration_hash: incomplete ? null : (goal ? 'b' : 'a').repeat(64), proposal_id: incomplete ? null : goal ? goalProposal : emergencyProposal, proposal_status: incomplete ? null : 'PROPOSED' };
}
export function proposalFixtures(): Proposal[] { return [
  { id: obligationProposal, status: 'PROPOSED', source_type: 'DETERMINISTIC_POLICY_DISCOVERY', source_text: 'SYNTHETIC_RENT_HISTORY', compiler_version: 'mvp-104-v1', evidence_ids: [], configuration: { type: 'recurring_obligation', name: 'HTTP夹具房租', payee_id: 'UNIT_PAYEE', due_day: 5, amount_rule: { kind: 'exact', amount_cents: 200000 }, prepare_days_before: 0, auto_execute: false, priority: { importance: 50, minimum_cents: 0, reducible: false, deferrable: false }, valid_from: null, valid_until: null }, configuration_hash: 'c'.repeat(64), validation_ready: true, confirmed_policy_id: null, compilation_id: null },
  ...([false, true] as const).map((goal) => { const actual = compilationFixture(goal); return { id: actual.proposal_id!, status: 'PROPOSED', source_type: 'POLICY_COMPILATION', source_text: goal ? goalText : emergencyText, compiler_version: 'offline-policy-rules-v1', evidence_ids: [], configuration: actual.configuration!, configuration_hash: actual.configuration_hash!, validation_ready: true, confirmed_policy_id: null, compilation_id: actual.compilation_id }; }),
]; }
export function discoveryFixture(): Discovery { return { simulation: true, user_id: onboardingUser, rule_version: 'mvp-104-v1', as_of: dashboardFixture().as_of, created_proposal_ids: [obligationProposal], reused_proposal_ids: [], skipped: [{ reason_code: 'SYNTHETIC_NO_LOAN_RULE', source_ref: 'TOOL_ONLY' }] }; }
export function transactionFixture(offset = 0): Transactions {
  return { simulation: true, total: 61, limit: 50, offset, items: Array.from({ length: offset === 0 ? 50 : offset === 50 ? 11 : 0 }, (_, index) => ({ id: `73000000-0000-4000-8000-${String(offset + index + 1).padStart(12, '0')}`, account_id: onboardingAccount, source_ref: `UNIT_ORIGINAL_ROW_${offset + index}`, evidence_id: null, direction: 'DEBIT' as const, amount_cents: 10001 + index, balance_after_cents: null, category: 'food', counterparty_ref: null, is_one_off: index === 0, category_confirmed: true, occurred_at: '2026-10-03T04:00:00Z', observed_at: '2026-10-03T04:00:00Z' })) };
}
export function reserveFixture(ready = false): Reserve {
  const config = { type: 'living_reserve', name: null, valid_from: null, valid_until: null, horizon_days: 14, method: { name: 'rolling_window_quantile', lookback_days: 56, quantile: .8, essential_categories: ['food', 'transport', 'daily_necessities'], exclude_one_off: true }, extra_buffer_cents: 50000, reconfirm_on_boundary_crossing: true };
  const days = Array.from({ length: 56 }, (_, index) => new Date(Date.parse('2026-08-09T00:00:00Z') + index * 86400000).toISOString().slice(0, 10));
  return { simulation: true, user_id: onboardingUser, as_of: dashboardFixture().as_of, source_evidence_ids: [], input_digest: 'd'.repeat(64), source_issues: ready ? [] : [{ code: 'SYNTHETIC_MISSING_COVERAGE', source_ref: onboardingAccount, message: 'HTTP fixture coverage incomplete' }], candidate_configuration: ready ? config : null, candidate_configuration_hash: ready ? 'e'.repeat(64) : null,
    estimation: { algorithm_version: 'living-reserve-nearest-rank-v1', status: ready ? 'READY' : 'INSUFFICIENT_HISTORY', reference_date: '2026-10-04', timezone: 'Asia/Shanghai', history_start: days[0]!, history_end: days.at(-1)!, lookback_days: 56, horizon_days: 14, quantile: .8, quantile_fraction: '4/5', rank: ready ? 35 : null, window_count: ready ? 43 : 0, base_reserve_cents: ready ? 120003 : null, extra_buffer_cents: 50000, recommended_reserve_cents: ready ? 170003 : null, selected_categories: ['daily_necessities', 'food', 'transport'], account_ids: [onboardingAccount], normalized_configuration: config, daily_amounts: days.map((day) => ({ day, covered: ready, amount_cents: ready ? 10001 : null })), windows: ready ? Array.from({ length: 43 }, (_, index) => ({ start_date: days[index]!, end_date: days[index + 13]!, amount_cents: 120003 })) : [], included_transaction_ids: [], excluded_transactions: [], coverage_gaps: ready ? [] : [{ account_id: onboardingAccount, missing_dates: days }], issues: ready ? [] : ['SYNTHETIC_INCOMPLETE_HISTORY'] } };
}
export function candidateRefFixture(intent: OnboardingIntent): CandidateRef { const actual = compilationFixture(intent.kind === 'GOAL'); return { compilation_id: actual.compilation_id, proposal_id: actual.proposal_id, configuration_hash: actual.configuration_hash, configuration_type: String(actual.configuration!.type), input_text: JSON.parse(intent.body_json).text, binding: intent.binding }; }
export function declarationFixture(intent: OnboardingIntent): DeclarationRecord { const body = JSON.parse(intent.body_json); return { simulation: true, protocol: 'user-policy-declaration-v1', grants_authority: false, dedicated_audit_event_recorded: false, receipt_is_current_authority: false, status: 'PROPOSED', current_proposal_status: 'PROPOSED', proposal_id: '75000000-0000-4000-8000-000000000001', evidence_id: '75000000-0000-4000-8000-000000000002', epoch_id: intent.binding.epoch_id, admitted_at: '2026-10-04T02:00:00Z', configuration: body.configuration, configuration_hash: 'f'.repeat(64), original_request: body, request_hash: '1'.repeat(64) }; }
