/** TOOL_ONLY synthetic protocol fixtures; no PG, bank, browser or financial measurement. */
import type { QuestionBody, QuestionIntent, QuestionKind, QuestionLookup, QuestionResponse, QuestionRevision, QuestionStart, QuestionVariable, QuestionWorld } from '../api/question-workflow';
import { prepareOneQuestionIntent } from '../features/one-question-operation';
export const questionUser = '10000000-0000-0000-0000-000000000001';
export const questionEpoch = '10000000-0000-0000-0000-000000000002';
export const questionSession = '10000000-0000-0000-0000-000000000003';
export const questionBase = '10000000-0000-0000-0000-000000000004';
export const questionRun = '10000000-0000-0000-0000-000000000005';
export const pendingQuestionId = '10000000-0000-0000-0000-000000000006';
export const questionVariables: QuestionVariable[] = [{ variable_id: 'amount', field: 'TRANSFER_AMOUNT', choices: [{ key: 'small', value: { kind: 'money', amount_cents: 10001 } }, { key: 'large', value: { kind: 'money', amount_cents: 20003 } }], completeness: 'COMPLETE', source: 'USER_REQUEST', evidence_id: null, impact_scope: 'ORIGINAL_MVP_PLANNING_REQUEST' }];
export const questionStartBody = (key = 'UNIT_START_001'): QuestionStart => ({ base_action_id: questionBase, variables: structuredClone(questionVariables), expected_epoch_id: questionEpoch, idempotency_key: key });
export async function questionIntentFixture(kind: QuestionKind = 'START', key = `UNIT_${kind}_001`): Promise<QuestionIntent> {
  const body: QuestionBody = kind === 'START' ? questionStartBody(key) : { expected_epoch_id: questionEpoch, expected_revision: 1, idempotency_key: key, ...(kind === 'ANSWER' ? { question_id: pendingQuestionId, choice_key: 'small' } : {}) };
  return prepareOneQuestionIntent({ kind, user_id: questionUser, session_id: kind === 'START' ? null : questionSession, base_action_id: questionBase, variables: questionVariables, previous_run_id: kind === 'START' ? null : questionRun, body });
}
export function questionRevisionFixture(): QuestionRevision {
  const worlds: QuestionWorld[] = questionVariables[0]!.choices.map((choice, index) => ({ world_key: String(index + 1).repeat(64), assignments: { amount: choice.key }, intent: null, outcome: { status: 'KNOWN', decision: { simulation: true, evaluation_only: true, level: 'ASK_ONCE' }, effect: { simulation: true, user_id: questionUser, operation_id: questionBase, amount_cents: choice.value.kind === 'money' ? choice.value.amount_cents : 0 }, validation: { simulation: true, financial_only: true, effect_hash: 'e'.repeat(64) }, signature: String(index + 3).repeat(64), source_context_hash: 'd'.repeat(64), source_evidence_ids: [questionBase], reasons: ['TOOL_ONLY_NOT_FINANCIAL_PROOF'] }, planning_only: true, execution_eligible: false }));
  const candidate = { variable_id: 'amount', field: 'TRANSFER_AMOUNT', worst_residual_signature_count: 1, partitions: worlds.map((world) => ({ choice_key: world.assignments.amount, world_keys: [world.world_key], signatures: [world.outcome.signature], residual_signature_count: 1 })) };
  const evaluation = { algorithm_version: 'full-finite-planning-minimax-v1' as const, planning_only: true, authority_granted: false, execution_eligible: false, probability_model: 'NONE', answer_state_machine: 'NOT_IMPLEMENTED', restart_deduplication: 'NOT_IMPLEMENTED', status: 'DIVERGENT' as const, complete_within_declared_domain: true, expected_world_count: 2, evaluated_world_count: 2, known_world_count: 2, unknown_or_unsupported_world_count: 0, stable: false, should_ask: true, worlds, distinct_signatures: worlds.map((world) => world.outcome.signature as string), question: candidate, minimax_candidates: [candidate], full_confirmation_baseline_question_count: 1, affected_action_types: ['TRANSFER_INTERNAL'], explanation: 'TOOL_ONLY 合成原协议夹具，不是金融计算实测', reasons: [] };
  return { protocol: 'full-one-question-v1', user_id: questionUser, session_id: questionSession, epoch_id: questionEpoch, revision: 1, run_id: questionRun, previous_run_id: null, as_of: '2026-10-05T12:00:00Z', base_action_id: questionBase, variables: structuredClone(questionVariables), answers: {}, evaluation, pending_question: { question_id: pendingQuestionId, variable_id: 'amount', choices: [...questionVariables[0]!.choices].sort((a, b) => a.key.localeCompare(b.key)), worst_residual_signature_count: 1, affected_action_types: ['TRANSFER_INTERNAL'], bank_authority: false }, state: 'PENDING_ANSWER', command_kind: 'START', command_key: 'UNIT_START_001', command_hash: 'a'.repeat(64), source_fingerprint: 'f'.repeat(64), answer_applied: false, old_candidates_execution_eligible: false, inherited_confirmation: false, authority_granted: false, execution_eligible: false };
}
export function questionResponseFixture(): QuestionResponse { const current = questionRevisionFixture(); return { protocol: 'full-one-question-v1', simulation: true, planning_only: true, authority_granted: false, execution_eligible: false, original_receipt: current, current_revision: structuredClone(current), effective_state: current.state, pending_question: structuredClone(current.pending_question), replayed_original_receipt: false, current_source_fingerprint: current.source_fingerprint, fresh_evaluation_at: current.as_of, persisted_workflow: true, legacy_analyzer_flags_apply_only_to_stateless_analysis: true, current_old_candidates_eligible: false, old_confirmation_inherited: false, bank_submission_support: 'NOT_IMPLEMENTED' }; }
export function questionLookupFixture(intent: QuestionIntent, recorded = true): QuestionLookup {
  const receipt = questionRevisionFixture(); receipt.command_key = intent.body.idempotency_key; receipt.command_hash = intent.request_hash; receipt.user_id = intent.user_id; receipt.epoch_id = intent.body.expected_epoch_id; receipt.base_action_id = intent.base_action_id; receipt.variables = structuredClone(intent.variables);
  if (intent.kind !== 'START') { receipt.revision = 2; receipt.previous_run_id = questionRun; receipt.run_id = '10000000-0000-0000-0000-000000000009'; receipt.command_kind = intent.kind === 'ANSWER' ? 'REBASE' : intent.kind; if (intent.kind === 'CLOSE') { receipt.state = 'CLOSED'; receipt.pending_question = null; } }
  return { protocol: 'full-question-command-lookup-v1', simulation: true, status: recorded ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', epoch_id: intent.body.expected_epoch_id, idempotency_key: intent.body.idempotency_key, session_id: recorded ? questionSession : null, original_command: recorded ? { kind: intent.kind, user_id: intent.user_id, ...(intent.kind === 'START' ? {} : { session_id: questionSession }), request: structuredClone(intent.body) } : null, request_hash: recorded ? intent.request_hash : null, original_receipt: recorded ? receipt : null, current_revision: recorded ? structuredClone(receipt) : null, original_start_request: recorded && intent.kind === 'START' ? structuredClone(intent.body as QuestionStart) : null, authority_granted: false, execution_eligible: false, replacement_allowed: false, client_match_required: true };
}
