/** HTTP unit fixtures only. These are never saved bank/financial acceptance evidence. */
import { createHash } from 'node:crypto';
import { spendingCanonicalJson, spendingCommand } from '../api/spending-evidence';
import type { CategoryBody, CategoryResult, CategoryReview, Periodic, Seasonal, SpendingIntent } from '../api/spending-evidence';
import type { Accounts, Transactions } from '../api/onboarding';

export const spendingUser = '81000000-0000-4000-8000-000000000001';
export const spendingAccount = '81000000-0000-4000-8000-000000000002';
export const spendingTransaction = '81000000-0000-4000-8000-000000000003';
export const spendingEpoch = '81000000-0000-4000-8000-000000000004';
export const spendingEvidence = '81000000-0000-4000-8000-000000000005';
export const spendingAsOf = '2026-10-05T08:00:00Z';
const hash = (value: unknown) => createHash('sha256').update(spendingCanonicalJson(value), 'utf8').digest('hex');
export function spendingAccountsFixture(): Accounts {
  return { simulation: true, user_id: spendingUser, timezone: 'Asia/Shanghai', oldest_account_observed_at: spendingAsOf, latest_account_observed_at: spendingAsOf, accounts: [{ id: spendingAccount, external_ref: 'TOOL_ONLY_CASH', name: 'HTTP 夹具现金账户', account_type: 'CASH', bank_code: 'ICBC', currency: 'CNY', balance_cents: 180001, observed_at: spendingAsOf }], credit_card_bills: [], cash_balance_cents: 180001, position_principal_cents: 0, unknown_position_principal_cents: 0, credit_card_unpaid_cents: 0 };
}
export function spendingTransactionsFixture(confirmed = false): Transactions {
  return { simulation: true, total: 1, limit: 50, offset: 0, items: [{ id: spendingTransaction, account_id: spendingAccount, source_ref: 'TOOL_ONLY_CONSUMPTION', evidence_id: spendingEvidence, direction: 'DEBIT', amount_cents: 10001, balance_after_cents: 180001, category: confirmed ? 'food' : 'other', counterparty_ref: 'TOOL_ONLY_BANK_PAYEE', is_one_off: false, category_confirmed: confirmed, occurred_at: '2026-10-04T08:00:00Z', observed_at: '2026-10-04T08:00:00Z' }] };
}
export function categoryReviewFixture(confirmed = false): CategoryReview {
  const tx = { ...spendingTransactionsFixture(confirmed).items[0]!, user_id: spendingUser, created_at: '2026-10-04T08:00:00.000000Z' };
  const bank = { transaction_id: tx.id, user_id: spendingUser, account_id: tx.account_id, direction: tx.direction, amount_cents: tx.amount_cents, balance_after_cents: tx.balance_after_cents, occurred_at: tx.occurred_at, observed_at: tx.observed_at, counterparty_ref: tx.counterparty_ref, source_ref: tx.source_ref, economic_role: 'CONSUMPTION', evidence_id: tx.evidence_id, evidence_level: 'BANK_CONFIRMED', evidence_source_type: 'SIMULATED_BANK_TRANSACTION', evidence_source_ref: 'TOOL_ONLY_BANK_FACT', evidence_hash: 'a'.repeat(64), evidence_observed_at: tx.observed_at, evidence_valid_from: tx.observed_at, evidence_valid_to: null, evidence_status: 'VALID' };
  return { protocol: 'transaction-category-review-v1', simulation: true, user_id: spendingUser, transaction_id: spendingTransaction, epoch_id: spendingEpoch, as_of: spendingAsOf, transaction: tx, bank_fact: bank, reviewed_transaction_hash: hash({ protocol: 'transaction-category-review-v1', epoch_id: spendingEpoch, transaction: tx, bank_fact: bank }), first_confirmation_supported: !confirmed, grants_authority: false, bank_facts_changed: false };
}
export function categoryBodyFixture(key = 'TOOL_ONLY_FIRST_CATEGORY'): CategoryBody { return { category: 'food', accepted: true, reviewed_transaction_hash: categoryReviewFixture().reviewed_transaction_hash, reason: 'HTTP 单元夹具明确食品分类', idempotency_key: key, expected_epoch_id: spendingEpoch }; }
export function spendingIntentFixture(key = 'TOOL_ONLY_FIRST_CATEGORY'): SpendingIntent {
  const body = categoryBodyFixture(key); const review = categoryReviewFixture(); const partial = { user_id: spendingUser, transaction_id: spendingTransaction, body };
  return { protocol: 'spending-category-browser-command-v1', ...partial, path: `/transactions/${spendingTransaction}/category-confirmation`, body_json: JSON.stringify(body), request_hash: hash(spendingCommand(partial)), bank_evidence_id: spendingEvidence, bank_evidence_hash: 'a'.repeat(64), before_category: String(review.transaction.category) };
}
export function categoryResultFixture(intent = spendingIntentFixture(), found = true): CategoryResult {
  return { protocol: 'transaction-category-command-result-v1', simulation: true, status: found ? 'RECORDED' : 'NOT_FOUND_NOT_FINAL', user_id: intent.user_id, transaction_id: intent.transaction_id, epoch_id: intent.body.expected_epoch_id, idempotency_key: intent.body.idempotency_key, original_command: found ? structuredClone(spendingCommand(intent)) : null, request_hash: found ? intent.request_hash : null, original_receipt: found ? { transaction_id: intent.transaction_id, before_category: intent.before_category, category: intent.body.category, before_confirmed: false, confirmed: true, bank_evidence_id: intent.bank_evidence_id, bank_evidence_hash: intent.bank_evidence_hash, confirmed_at: spendingAsOf } : null, evidence_id: found ? '81000000-0000-4000-8000-000000000006' : null, audit_event_id: found ? '81000000-0000-4000-8000-000000000007' : null, audit_event_hash: found ? 'b'.repeat(64) : null, replayed_original: true, grants_authority: false, receipt_is_current_authority: false, bank_facts_changed: false, replacement_allowed: false };
}
const proof = (verified: boolean) => ({ verified, period_start: '2026-08-10', period_end: '2026-10-04', account_ids: [spendingAccount], evidence_ids: [spendingEvidence], reason_codes: verified ? [] : ['TOOL_ONLY_MISSING_COVERAGE'] });
export function periodicFixture(ready = false): Periodic {
  return { simulation: true, user_id: spendingUser, as_of: spendingAsOf, rule_version: 'full-monthly-pattern-variance-v1', history_start: '2026-08-10', history_end: '2026-10-04', history_proof: proof(ready), patterns: [{ pattern_id: 'c'.repeat(64), kind: 'RENT', account_id: spendingAccount, payee_ref: 'TOOL_ONLY_RENT', status: ready ? 'READY' : 'UNKNOWN', reason_codes: ready ? [] : ['TOOL_ONLY_MISSING_COVERAGE'], cycle_count: 2, sample_count: 2, months: ['2026-08', '2026-09'], day_spread: 1, suggested_due_day: ready ? 20 : null, amount_min_cents: 100003, amount_max_cents: 100003, mean_fraction_cents: '100003', variance_fraction_cents_squared: '0', cv_squared_fraction: '0', template_name: ready ? 'RecurringObligationPolicy' : null, candidate_configuration: ready ? { type: 'recurring_obligation', auto_execute: false } : null, candidate_configuration_hash: ready ? 'd'.repeat(64) : null, sources: [], advice_only: true, requires_confirmation: true, bank_authority: false, future_obligation_guaranteed: false }], source_issues: ready ? [] : [{ code: 'TOOL_ONLY_MISSING_COVERAGE', source_ref: spendingAccount, message: 'HTTP 夹具未有完整历史覆盖' }], excluded_transaction_count: 3, source_evidence_ids: [spendingEvidence], source_digest: 'e'.repeat(64), bank_authority: false, hard_protection_changed: false };
}
export function seasonalFixture(selected = 'CN-2026-NATIONAL_DAY'): Seasonal {
  const target = { window_id: 'CN-2026-NATIONAL_DAY', year: 2026, holiday_code: 'NATIONAL_DAY', start: '2026-10-01', end: '2026-10-07', notice_reference: '国办发明电〔2025〕7号', notice_date: '2025-11-04', source_url: 'https://www.beijing.gov.cn/zhengce/zhengcefagui/202511/t20251104_4258873.html', source_verification: 'OFFICIAL_NOTICE_MANUAL_EXTRACTION' as const };
  return { simulation: true, user_id: spendingUser, as_of: spendingAsOf, rule_version: 'full-same-festival-excess-nearest-rank-v1', public_windows: [target], calendar_extraction_hash: 'f'.repeat(64), calendar_verified_on: '2026-10-05', history_proof: proof(false), suggestion: { status: 'UNKNOWN', reason_codes: selected === target.window_id ? ['TOOL_ONLY_MISSING_COVERAGE'] : ['UNSUPPORTED_OR_NOT_YET_PUBLISHED_WINDOW'], target: selected === target.window_id ? target : null, effective_window_start: selected === target.window_id ? '2026-10-05' : null, effective_window_end: selected === target.window_id ? '2026-10-07' : null, window_count: 0, required_window_count: 2, comparisons: [], quantile_fraction: '4/5', rank: null, required_adjustment_cents: null, proposed_adjustment_cents: null, cap_limited: null, candidate_configuration: null, candidate_configuration_hash: null, advice_only: true, requires_confirmation: true, bank_authority: false, hard_protection_changed: false }, sources: [], source_issues: [{ code: 'TOOL_ONLY_MISSING_COVERAGE', source_ref: spendingAccount, message: 'HTTP 夹具缺同节日历史' }], source_evidence_ids: [], source_digest: 'e'.repeat(64), bank_authority: false, hard_protection_changed: false };
}
