import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { AssetPreview } from '../api/full-asset-execution';
import type { LocalActorSession } from '../api/local-actor';
import type { NextState } from './api';
import type { PaymentRecovery } from './payment-recovery';
import type { JointRecovery } from './joint-recovery';
import type { AssetRecovery, AssetRequest } from './asset-recovery';
import { getNextAsset, previewNextAsset, readAssetView, wrapperAssetRequest, type AssetUpdate, type AssetView } from './assets';
import { getAssetsState, assetSourceOpen } from './assets-state';
import { businessText, money, userError } from './display';
import LocalUserPanel from './LocalUserPanel';
import type { MaturityRecovery } from './maturity-recovery';
import type { MaturityUpdate } from './maturity';
import MaturityPanel from './MaturityPanel';
import AssetPermissionPanel from './AssetPermissionPanel';
import type { PermissionUpdate } from './asset-permissions';
import type { ReinvestmentRecovery } from './reinvestment-recovery';
import type { ReinvestmentUpdate } from './reinvestments';
import ReinvestmentPanel from './ReinvestmentPanel';
import type { LossRecovery } from './loss-recovery';
import type { LossRevisionRecovery } from './loss-revision-recovery';
import type { LossRevisionUpdate } from './loss-revisions';
import type { LossUpdate } from './loss';
import LossPanel from './LossPanel';
import QuestionPanel from './QuestionPanel';
import type { QuestionRecovery } from './question-recovery';
import type { QuestionUpdate } from './questions';
import type { StandingRecovery } from './standing-recovery';

export type AssetPerform = (path: string, body: Record<string, unknown>, payment?: PaymentRecovery, joint?: JointRecovery, asset?: AssetRecovery, maturity?: MaturityRecovery, reinvestment?: ReinvestmentRecovery, loss?: LossRecovery, question?: QuestionRecovery, standing?: StandingRecovery, revision?: LossRevisionRecovery) => Promise<void>;
const stages: Record<string, string> = { PREPARED_UNRESERVED: '原组合仅已准备，尚未确认或占用资金', CONFIRMED_UNRESERVED: '整体同意已核实，原批次待执行', PARTIALLY_SETTLED: '部分原回执已核实', SERVICE_RECEIPTS_VERIFIED: '全部原购买回执已核实', UNRESOLVED: '同一原批次正在核实', STOPPED: '原组合已停止后续执行', RETAINED_HISTORY: '历史原组合，仅供查看' };
export default function AssetsPanel({ environment, blocked, update, perform, runRead, recovering = false, retryOriginal, resumeOriginal, maturityUpdate = null, maturityRecovering = false, resumeMaturityOriginal, permissionUpdate = null, permissionEdited = () => {}, permissionRecovering = false, reinvestmentUpdate = null, reinvestmentRecovering = false, resumeReinvestmentOriginal, lossUpdate = null, lossRecovering = false, resumeLossOriginal, revisionUpdate = null, revisionRecovering = false, resumeRevisionOriginal, questionUpdate = null, questionRecovering = false, openGoalLink }: { environment: NextState; blocked: boolean; update: AssetUpdate | null; perform: AssetPerform; runRead: <T>(work: () => Promise<T>) => Promise<T>; recovering?: boolean; retryOriginal?: () => Promise<void>; resumeOriginal?: () => Promise<void>; maturityUpdate?: MaturityUpdate | null; maturityRecovering?: boolean; resumeMaturityOriginal?: () => Promise<void>; permissionUpdate?: PermissionUpdate | null; permissionEdited?: () => void; permissionRecovering?: boolean; reinvestmentUpdate?: ReinvestmentUpdate | null; reinvestmentRecovering?: boolean; resumeReinvestmentOriginal?: () => Promise<void>; revisionUpdate?: LossRevisionUpdate | null; revisionRecovering?: boolean; resumeRevisionOriginal?: () => Promise<void>; lossUpdate?: LossUpdate | null; lossRecovering?: boolean; resumeLossOriginal?: () => Promise<void>; questionUpdate?: QuestionUpdate | null; questionRecovering?: boolean; openGoalLink?: () => void }) {
  const [open, setOpen] = useState(false); const [fullId, setFullId] = useState(''); const [mvpId, setMvpId] = useState(''); const [mode, setMode] = useState<'PORTFOLIO' | 'FIXED_LADDER'>('PORTFOLIO'); const [session, setSession] = useState<LocalActorSession | null>(null); const [preview, setPreview] = useState<AssetPreview | null>(null); const [loaded, setLoaded] = useState<AssetView | null>(null); const [working, setWorking] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (update || recovering || maturityUpdate || maturityRecovering || permissionUpdate || permissionRecovering || reinvestmentUpdate || reinvestmentRecovering || lossUpdate || lossRecovering || revisionUpdate || revisionRecovering || questionUpdate || questionRecovering) setOpen(true); }, [update, recovering, maturityUpdate, maturityRecovering, permissionUpdate, permissionRecovering, reinvestmentUpdate, reinvestmentRecovering, lossUpdate, lossRecovering, revisionUpdate, revisionRecovering, questionUpdate, questionRecovering]);
  useEffect(() => { if (update) setLoaded(null); }, [update]);
  useEffect(() => {
    if (!open || blocked || loaded?.portfolio.state !== 'UNRESOLVED') return;
    let active = true; const id = loaded.portfolio.original_portfolio.portfolio_id;
    const timer = window.setTimeout(() => { void getNextAsset(id, environment).then((view) => { if (active) setLoaded(view); }).catch((cause: unknown) => { if (active) setError(userError(cause)); }); }, 15000);
    return () => { active = false; window.clearTimeout(timer); };
  }, [open, blocked, loaded, environment]);
  const identity = [environment.environment_id, environment.epoch_id];
  const records = useQuery({ queryKey: ['zhiyu-next-assets-state', ...identity], queryFn: () => getAssetsState(environment), enabled: open && (!blocked || recovering || maturityRecovering || permissionRecovering || reinvestmentRecovering || lossRecovering || revisionRecovering || questionRecovering), retry: false, staleTime: Infinity });
  const original = useQuery({ queryKey: ['zhiyu-next-asset-view', ...identity], queryFn: () => readAssetView(environment), enabled: open && !blocked && !update, retry: false, staleTime: Infinity, refetchInterval: (q) => !blocked && !update && q.state.data?.portfolio.state === 'UNRESOLVED' ? 15000 : false });
  const rules = records.data?.policies.filter((p) => p.template_name === 'AssetAuthorizationPolicy' && p.planning_confirmation_valid && ['ACTIVE', 'CONFIRMED'].includes(p.effective_status)) ?? [];
  const fulls = rules.filter((p) => p.source_kind === 'FULL_POLICY'); const mvps = rules.filter((p) => p.source_kind === 'MVP_POLICY');
  const full = fulls.find((p) => p.policy_id === fullId) ?? (fulls.length === 1 ? fulls[0] : undefined); const mvp = mvps.find((p) => p.policy_id === mvpId) ?? (mvps.length === 1 ? mvps[0] : undefined);
  const goal = full?.configuration.scope === 'goal' ? environment.goals.find((g) => g.id === full.configuration.goal_id) : null;
  const scopeAvailable = !!full && !!mvp && (full.configuration.scope === 'general_idle_funds' || full.configuration.scope === 'goal' && !!goal);
  const signed = !!session && session.principal.role === 'USER' && session.principal.user_id === environment.dashboard.user_id && Date.parse(session.principal.expires_at) > Date.now();
  const verified = update ?? original.data; const response = loaded?.portfolio ?? verified?.portfolio; const p = response?.original_portfolio; const available = assetSourceOpen(records.data?.source_validation_status);
  const current = p && fulls.some((r) => r.policy_id === p.original_request.full_policy_id && r.current_version_id === p.original_request.expected_full_policy_version_id) && mvps.some((r) => r.policy_id === p.original_request.mvp_asset_policy_id && r.current_version_id === p.original_request.expected_mvp_policy_version_id);
  const signedOriginal = loaded ? loaded.signed : verified?.signed ?? null;
  const canConfirm = !!p && current && available && p.original_request.idempotency_key.startsWith(`zhiyu-next:${p.epoch_id}:asset-prepare:`) && response?.state === 'PREPARED_UNRESERVED' && response.original_consent === null && signedOriginal === null && Date.parse(response.as_of) < Date.parse(p.expires_at);
  const outstanding = records.data?.portfolios.some((p) => !['SERVICE_RECEIPTS_VERIFIED', 'STOPPED', 'RETAINED_HISTORY'].includes(p.state)) ?? false;
  function requestBody(): AssetRequest { if (!scopeAvailable || !full || !mvp) throw new Error('先选择当前资产范围；目标范围须与现有目标关联。'); return { expected_epoch_id: environment.epoch_id, full_policy_id: full.policy_id, expected_full_policy_version_id: full.current_version_id, mvp_asset_policy_id: mvp.policy_id, expected_mvp_policy_version_id: mvp.current_version_id, goal_id: goal?.id ?? null, expected_goal_policy_version_id: goal?.policy_version_id ?? null, planning_mode: mode, client_request_id: crypto.randomUUID() }; }
  async function inspect() { if (blocked || working || !scopeAvailable) return; setWorking(true); setError(''); try { setPreview(await runRead(() => previewNextAsset(requestBody(), environment))); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  async function prepare() { if (blocked || working || !signed || !available || !scopeAvailable || outstanding || response && !['SERVICE_RECEIPTS_VERIFIED', 'STOPPED', 'RETAINED_HISTORY'].includes(response.state)) return; setWorking(true); setError(''); try { const body = requestBody(); await perform('/zhiyu-next/assets/portfolios/prepare', body, undefined, undefined, { protocol: 'zhiyu-next-asset-recovery-v1', user_id: environment.dashboard.user_id, prepare_request: body, portfolio_id: null, reviewed_portfolio_hash: null }); setPreview(null); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  async function confirm() { if (blocked || working || !signed || !canConfirm || !p) return; setWorking(true); setError(''); try { const recovery: AssetRecovery = { protocol: 'zhiyu-next-asset-recovery-v1', user_id: p.user_id, prepare_request: wrapperAssetRequest(p.original_request), portfolio_id: p.portfolio_id, reviewed_portfolio_hash: p.portfolio_hash }; const fresh = await runRead(() => getNextAsset(p.portfolio_id, environment, recovery)); if (fresh.portfolio.state !== 'PREPARED_UNRESERVED' || fresh.signed !== null || fresh.portfolio.original_consent !== null || Date.parse(fresh.portfolio.as_of) >= Date.parse(p.expires_at)) throw new Error('原组合状态变化，请保留已审原件并核实。'); await perform(`/zhiyu-next/assets/portfolios/${p.portfolio_id}/confirm-and-execute`, { expected_epoch_id: p.epoch_id, reviewed_portfolio_hash: p.portfolio_hash, accepted: true, client_request_id: crypto.randomUUID() }, undefined, undefined, recovery); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  async function inspectOriginal(id: string) { if (blocked || working) return; setWorking(true); setError(''); try { setLoaded(await runRead(() => getNextAsset(id, environment))); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  const source = (ids: string[]) => [...new Set(ids.map((id) => environment.dashboard.account_facts.facts.accounts.find((a) => a.id === id)?.name ?? '原来源账户'))].map(businessText).join('、');
  return <section aria-label="资产安排与原组合"><section className="zy-card"><div className="zy-section-heading"><h2>资产安排与原组合</h2><button className="zy-secondary" disabled={blocked || working} onClick={() => setOpen((v) => !v)}>{open ? '收起资产安排' : '查看资产安排'}</button></div><p>在全年保护范围内比较有限产品与到期组合，准备和规划均不等于购买成功。</p></section>
    {open && <><LocalUserPanel environment={environment} session={session} update={setSession} inputId="zyn-asset-confirm-secret" />
      {!available && <p className="zy-message">资产执行尚待本轮真实闭环验收，当前不会新增资产购买或回收动作。</p>}
      {(error || records.isError || original.isError) && <p role="alert" className="zy-message zy-error">{error || userError(records.error ?? original.error)}</p>}
      <AssetPermissionPanel environment={environment} state={records.data} blocked={blocked} signed={signed} update={permissionUpdate} edited={permissionEdited} perform={perform} recovering={permissionRecovering} retryOriginal={retryOriginal} openGoalLink={openGoalLink} />
      {recovering && !response && <section className="zy-card"><h3>正在核实同一资产原请求</h3><p>原定位保留；尚未找到原件不表示拒绝，也不会生成替代组合。</p>{retryOriginal && signed && <button className="zy-secondary" onClick={() => void retryOriginal()}>按原请求恢复会话后的续接</button>}</section>}
      <section className="zy-card"><h3>采用当前规则范围</h3><label className="zy-field" htmlFor="zyn-asset-full">资产偏好与完整保护<select id="zyn-asset-full" value={full?.policy_id ?? ''} disabled={blocked || working} onChange={(e) => { setFullId(e.target.value); setPreview(null); }}><option value="">请选择</option>{fulls.map((r) => <option key={r.policy_id} value={r.policy_id}>{businessText(r.name)}</option>)}</select></label><label className="zy-field" htmlFor="zyn-asset-mvp">原购买授权范围<select id="zyn-asset-mvp" value={mvp?.policy_id ?? ''} disabled={blocked || working} onChange={(e) => { setMvpId(e.target.value); setPreview(null); }}><option value="">请选择</option>{mvps.map((r) => <option key={r.policy_id} value={r.policy_id}>{businessText(r.name)}</option>)}</select></label><label className="zy-field" htmlFor="zyn-asset-mode">安排偏好<select id="zyn-asset-mode" value={mode} disabled={blocked || working} onChange={(e) => { setMode(e.target.value as typeof mode); setPreview(null); }}><option value="PORTFOLIO">有限产品组合</option><option value="FIXED_LADDER">分期到期定期阶梯</option></select></label><p>服务端将重检这两个范围是否匹配，目录存在不代表已获执行权限。{goal ? `目标来源：${businessText(goal.name)}。` : full?.configuration.scope === 'goal' ? '目标关联尚未核实。' : '采用通用闲置资金范围。'}</p><div className="zy-buttons"><button className="zy-secondary" disabled={blocked || working || !scopeAvailable} onClick={() => void inspect()}>比较当前保护下的方案</button><button className="zy-secondary" disabled={blocked || working || !signed || !available || !scopeAvailable || outstanding || !!response && !['SERVICE_RECEIPTS_VERIFIED', 'STOPPED', 'RETAINED_HISTORY'].includes(response.state)} onClick={() => void prepare()}>保存可审阅原组合</button></div><p className="zy-muted">比较是非持久化规划；保存原组合只准备固定批次，尚未确认、扣款或预留整笔资金。</p></section>
      {records.data && <section className="zy-card"><h3>当前产品与原持仓</h3><p>{records.data.catalogue_status === 'VERIFIED' ? '已核实当前产品目录；名称或收益参数不授予购买权限。' : '当前目录来源待核实，不能推断可执行产品。'}</p><ul>{records.data.products.map((product) => <li key={product.product_id}>{businessText(product.name)} · 起购 {money(product.minimum_purchase_cents)} · 锁定 {product.lock_days} 天 · 赎回延迟 {product.redemption_delay_days} 天 · 模拟年化 {(product.annual_yield_bps / 100).toFixed(2)}%。</li>)}</ul>{records.data.positions.length === 0 ? <p>本轮当前没有已核持仓。</p> : <ul>{records.data.positions.map((position) => <li key={position.position_id}><strong>{businessText(position.product_name)} · 原本金 {money(position.principal_cents)}</strong><p>已计提收益 {money(position.accrued_yield_cents)}；合同到期 {position.maturity_at?.slice(0, 10) ?? '当前无固定到期日期'}。到期日期和持仓投影不等于已收到兑付资金。</p></li>)}</ul>}{records.data.portfolios.length > 0 && <><h4>本轮已保存的组合原件</h4><div className="zy-buttons">{records.data.portfolios.map((row, i) => <button key={row.portfolio_id} className="zy-secondary" disabled={blocked || working} onClick={() => void inspectOriginal(row.portfolio_id)}>查看原组合 {i + 1} · {stages[row.state] ?? '待核实'}</button>)}</div></>}</section>}
      {preview && <section className="zy-card"><h3>{preview.state === 'READY_TO_REVIEW' ? '当前可比较的规划' : preview.state === 'UNKNOWN' ? '来源与规划待核实' : '当前保护阻止新购买'}</h3><p>规划金额 {money(preview.portfolio?.total_purchase_cents)}。此比较结果不能代替随后独立核实的已准备原件。</p>{preview.reasons.length > 0 && <ul>{preview.reasons.map((r, i) => <li key={i}>{businessText(r)}</li>)}</ul>}</section>}
      {p && response && <section className="zy-card" aria-label="已准备资产原件"><h3>{stages[response.state]}</h3><strong className="zy-amount zy-amount-small">{money(p.total_purchase_cents)}</strong><p>共 {p.batches.length} 个原批次；有效至 {p.expires_at.replace('T', ' ').slice(0, 19)}。整笔资金未预留，各批次之间没有整体原子性。</p><ol>{p.batches.map((b, i) => { const effect = b.command.effect; const product = records.data?.products.find((x) => x.product_id === effect.product_id && x.version_number === effect.product_version_number && x.terms_digest === effect.terms_digest); const action = response.batches[i]!.original_action; return <li key={b.action_id}><strong>{businessText(product?.name ?? `第 ${i + 1} 项原产品（当前名称未核实）`)} · {money(effect.amount_cents)}</strong><p>来源 {source(effect.cash_uses!.map((u) => u.account_id))}，费用 {money(effect.fee_cents)}，损失 {money(effect.loss_cents)}。本金可用时间 {effect.purchase_exit?.principal_available_at?.slice(0, 10) ?? '仍需核实'}。</p><p>{action?.receipt ? `实际原购买回执已核实 ${money(action.receipt.executed_cents)}。` : action && ['UNKNOWN', 'SUBMITTED'].includes(action.status) ? '同一原批次正在核实，后续批次保持停止。' : '尚无完成回执。'}</p></li>; })}</ol>{canConfirm && <><p>确认上述整组必要后果后，系统使用原组合依次执行；未决结果停止后续批次。</p><button className="zy-primary" disabled={blocked || working || !signed} onClick={() => void confirm()}>确认并执行原组合</button></>}{resumeOriginal && signed && available && <button className="zy-secondary" disabled={working} onClick={() => void resumeOriginal()}>继续同一原组合</button>}{retryOriginal && signed && <button className="zy-secondary" disabled={working} onClick={() => void retryOriginal()}>按原请求恢复会话后的续接</button>}</section>}
      <QuestionPanel environment={environment} state={records.data} signed={signed} blocked={blocked} perform={perform} runRead={runRead} update={questionUpdate} recovering={questionRecovering} retryOriginal={retryOriginal} />
      <MaturityPanel environment={environment} state={records.data} blocked={blocked} signed={signed} perform={perform} runRead={runRead} update={maturityUpdate} recovering={maturityRecovering} resumeOriginal={resumeMaturityOriginal} retryOriginal={retryOriginal} />
      <ReinvestmentPanel environment={environment} state={records.data} blocked={blocked} signed={signed} maturity={maturityUpdate} update={reinvestmentUpdate} recovering={reinvestmentRecovering} perform={perform} runRead={runRead} resumeOriginal={resumeReinvestmentOriginal} retryOriginal={retryOriginal} />
      <LossPanel revisionUpdate={revisionUpdate} revisionRecovering={revisionRecovering} resumeRevisionOriginal={resumeRevisionOriginal} environment={environment} state={records.data} blocked={blocked} signed={signed} update={lossUpdate} recovering={lossRecovering} perform={perform} runRead={runRead} resumeOriginal={resumeLossOriginal} retryOriginal={retryOriginal} />
    </>}
  </section>;
}

