import { request } from '../api/http';
import { object } from '../features/policy-form';
import { spendingHash as hash, spendingUUID as uuid, spendingDigest as digest } from '../api/spending-evidence';
import { assetCheck as check, assetExact as exact } from './asset-recovery';
import { context, safeConfiguration } from './policies';
import type { NextState } from './api';

export const assetSourceValidation = 'DEVELOPMENT_PENDING_ACTUAL_ASSET_ACCEPTANCE';
export const assetSourceOpen = (status: unknown) => status === 'VERIFIED_ACTUAL_ASSET_ACCEPTANCE';
const time = (v: unknown): v is string => typeof v === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(v) && Number.isFinite(Date.parse(v));
const cents = (v: unknown): v is number => Number.isSafeInteger(v) && Number(v) >= 0;
const label = (v: unknown): v is string => typeof v === 'string' && !!v.trim();
export type AssetPolicy = { name: string; template_name: 'AssetAuthorizationPolicy' | 'RecoveryPolicy' | 'LongTermGoalPolicy'; source_kind: 'MVP_POLICY' | 'FULL_POLICY' | 'GOAL_BRIDGE'; dsl_version: 'MVP_V1' | 'FULL_V1'; policy_id: string; current_version_id: string; configuration_hash: string; goal_id: string | null; effective_status: string; planning_confirmation_valid: boolean; configuration: Record<string, unknown> };
export type AssetProduct = { product_id: string; name: string; product_code: string; version_number: number; asset_class: string; terms_digest: string; minimum_purchase_cents: number; lock_days: number; redemption_delay_days: number; annual_yield_bps: number; early_withdrawal_loss_bps: number };
export type AssetPosition = { position_id: string; account_id: string; product_id: string; product_name: string; status: string; principal_cents: number; accrued_yield_cents: number; purchased_at: string; maturity_at: string | null; goal_id: string | null; original_policy_version_id: string | null };
export type AssetParentSummary = { portfolio_id: string; epoch_id: string; portfolio_hash: string; state: string; all_original_service_receipts_verified: boolean; original_consent_verified: boolean; has_signed_acceptance: boolean };
export type AssetsState = { simulation: true; variant: 'zhiyu-next'; environment_id: string; epoch_id: string; protocol: 'zhiyu-next-assets-state-v1'; server_as_of: string; source_validation_status: string; catalogue_status: 'VERIFIED' | 'UNKNOWN'; catalogue_issues: string[]; policies: AssetPolicy[]; products: AssetProduct[]; positions: AssetPosition[]; portfolios: AssetParentSummary[]; position_projection_status: 'VERIFIED_CURRENT_BANK_PROJECTION'; bank_authority: false };
export async function parseAssetsState(v: unknown, environment: NextState): Promise<AssetsState> {
  context(v, environment); check(exact(v, ['simulation', 'variant', 'environment_id', 'epoch_id', 'protocol', 'server_as_of', 'source_validation_status', 'catalogue_status', 'catalogue_issues', 'policies', 'products', 'positions', 'portfolios', 'position_projection_status', 'bank_authority']) && v.protocol === 'zhiyu-next-assets-state-v1' && time(v.server_as_of) && [assetSourceValidation, 'VERIFIED_ACTUAL_ASSET_ACCEPTANCE'].includes(String(v.source_validation_status)) && ['VERIFIED', 'UNKNOWN'].includes(String(v.catalogue_status)) && Array.isArray(v.catalogue_issues) && v.catalogue_issues.every(label) && v.position_projection_status === 'VERIFIED_CURRENT_BANK_PROJECTION' && v.bank_authority === false);
  for (const field of ['policies', 'products', 'positions', 'portfolios']) check(Array.isArray(v[field]) && v[field].length <= 1000);
  const unique = (rows: unknown[], field: string) => { check(rows.every((r) => object(r) && uuid(r[field])) && new Set(rows.map((r) => (r as Record<string, unknown>)[field])).size === rows.length); };
  unique(v.policies as unknown[], 'policy_id'); unique(v.products as unknown[], 'product_id'); unique(v.positions as unknown[], 'position_id'); unique(v.portfolios as unknown[], 'portfolio_id');
  for (const p of v.policies as unknown[]) {
    check(object(p) && exact(p, ['name', 'template_name', 'source_kind', 'dsl_version', 'policy_id', 'current_version_id', 'configuration_hash', 'goal_id', 'effective_status', 'planning_confirmation_valid', 'configuration']) && label(p.name) && ['AssetAuthorizationPolicy', 'RecoveryPolicy', 'LongTermGoalPolicy'].includes(String(p.template_name)) && ['MVP_POLICY', 'FULL_POLICY', 'GOAL_BRIDGE'].includes(String(p.source_kind)) && ['MVP_V1', 'FULL_V1'].includes(String(p.dsl_version)) && uuid(p.current_version_id) && digest(p.configuration_hash) && (p.goal_id === null || uuid(p.goal_id)) && label(p.effective_status) && typeof p.planning_confirmation_valid === 'boolean' && safeConfiguration(p.configuration) && p.configuration_hash === await hash(p.configuration));
    check(p.source_kind === 'MVP_POLICY' ? p.dsl_version === 'MVP_V1' : p.dsl_version === 'FULL_V1');
  }
  for (const p of v.products as unknown[]) check(object(p) && exact(p, ['product_id', 'name', 'product_code', 'version_number', 'asset_class', 'terms_digest', 'minimum_purchase_cents', 'lock_days', 'redemption_delay_days', 'annual_yield_bps', 'early_withdrawal_loss_bps']) && label(p.name) && label(p.product_code) && label(p.asset_class) && cents(p.version_number) && p.version_number > 0 && digest(p.terms_digest) && ['minimum_purchase_cents', 'lock_days', 'redemption_delay_days', 'annual_yield_bps', 'early_withdrawal_loss_bps'].every((k) => cents(p[k])));
  for (const p of v.positions as unknown[]) check(object(p) && exact(p, ['position_id', 'account_id', 'product_id', 'product_name', 'status', 'principal_cents', 'accrued_yield_cents', 'purchased_at', 'maturity_at', 'goal_id', 'original_policy_version_id']) && uuid(p.account_id) && uuid(p.product_id) && label(p.product_name) && label(p.status) && cents(p.principal_cents) && cents(p.accrued_yield_cents) && time(p.purchased_at) && (p.maturity_at === null || time(p.maturity_at) && Date.parse(p.maturity_at) >= Date.parse(p.purchased_at)) && (p.goal_id === null || uuid(p.goal_id)) && (p.original_policy_version_id === null || uuid(p.original_policy_version_id)));
  for (const p of v.portfolios as unknown[]) check(object(p) && exact(p, ['portfolio_id', 'epoch_id', 'portfolio_hash', 'state', 'all_original_service_receipts_verified', 'original_consent_verified', 'has_signed_acceptance']) && p.epoch_id === environment.epoch_id && digest(p.portfolio_hash) && ['PREPARED_UNRESERVED', 'CONFIRMED_UNRESERVED', 'PARTIALLY_SETTLED', 'SERVICE_RECEIPTS_VERIFIED', 'UNRESOLVED', 'STOPPED', 'RETAINED_HISTORY'].includes(String(p.state)) && ['all_original_service_receipts_verified', 'original_consent_verified', 'has_signed_acceptance'].every((k) => typeof p[k] === 'boolean') && (p.state !== 'SERVICE_RECEIPTS_VERIFIED' || p.all_original_service_receipts_verified === true));
  check(v.catalogue_status !== 'VERIFIED' || v.catalogue_issues.length === 0);
  return v as AssetsState;
}
export async function getAssetsState(environment: NextState): Promise<AssetsState> { const v = await request('/zhiyu-next/assets/state', 'GET', undefined, (v) => { context(v, environment); return v; }); return parseAssetsState(v, environment); }
