import { request } from '../api/http';
import { object } from '../features/policy-form';
import { annualDayNumber } from '../api/planning';
import { spendingHash as hash, spendingDigest as digest, spendingUUID as uuid } from '../api/spending-evidence';
import { parseLocalActorSession, type LocalActorSession } from '../api/local-actor';
import type { NextState, OperationResult } from './api';
import type { PendingOperation } from './operation';
import { context, safeConfiguration, same } from './policies';

export type HistoricalSource = { fact_type: 'transactions' | 'credit_card_bills'; fact_id: string; source_ref: string; account_id: string; evidence_id: string; evidence_hash: string; evidence_source_type: string; evidence_source_ref: string; evidence_observed_at: string; fact: Record<string, unknown> };
export type HistoricalObservation = { simulation: true; rule_version: 'mvp-104-v1'; rule: 'monthly_rent' | 'credit_card_cycle'; object_key: string; revision: string; sources: HistoricalSource[]; matched_rule: string; future_obligation_guaranteed: false; limitation: string; observation_window: { start_date: string; end_date: string; timezone: 'UTC' | 'Asia/Shanghai'; days: 60 }; configuration_hash: string };
export type DiscoveredProposal = { proposal_id: string; configuration: Record<string, unknown>; configuration_hash: string; status: 'PROPOSED' | 'CONFIRMED' | 'EXPIRED'; source_status: 'VERIFIED_HISTORICAL_OBSERVATION' | 'UNKNOWN'; source_error_code: string | null; observations: HistoricalObservation[]; evidence_ids: string[]; created_at: string; confirmed_policy_id: string | null; confirmation_required: true; future_obligation_guaranteed: false; bank_authority: false };
export type DiscoveryRead = { proposals: DiscoveredProposal[]; statistics?: { as_of: string; created_proposal_ids: string[]; reused_proposal_ids: string[]; skipped: { reason_code: string; source_ref: string }[] } };
export type DiscoveryConfirmation = { proposal_id: string; reviewed_hash: string; original_result: { simulation: true; policy_id: string; current_version_id: string; previous_version_id: null; status: string; effective_status: string; invalidated_action_ids: string[]; inflight_action_ids: string[]; requires_recompute: true }; principal: LocalActorSession['principal'] };
export type DiscoveryUpdate = { kind: 'DISCOVER'; read: DiscoveryRead } | { kind: 'CONFIRM'; confirmation: DiscoveryConfirmation };
export const isDiscoveryPath = (path: string) => ['/zhiyu-next/policy-discovery', '/zhiyu-next/policy-discovery/confirm'].includes(path);
const exact = (v: Record<string, unknown>, f: string[]) => Object.keys(v).sort().join('|') === f.sort().join('|');
const ids = (v: unknown): v is string[] => Array.isArray(v) && v.every(uuid) && new Set(v).size === v.length;
const time = (v: unknown): v is string => typeof v === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(v) && Number.isFinite(Date.parse(v));
const cents = (v: unknown): v is number => Number.isSafeInteger(v) && Number(v) >= 0;
function check(v: unknown): asserts v { if (!v) throw new Error('历史候选的原来源、配置或明确确认未通过核实，请保留原请求。'); }
export function canConfirmDiscovery(p: DiscoveredProposal): boolean { return p.source_status === 'VERIFIED_HISTORICAL_OBSERVATION' && p.status === 'PROPOSED' && p.confirmed_policy_id === null; }
export async function parseDiscoveryRead(v: unknown, environment: NextState): Promise<DiscoveryRead> {
  context(v, environment); check(v.bank_authority === false && Array.isArray(v.proposals) && v.proposals.length <= 512 && ids(v.proposals.map((p) => object(p) ? p.proposal_id : null)));
  const proposals = v.proposals;
  for (const p of proposals) {
    check(object(p) && exact(p, ['proposal_id', 'configuration', 'configuration_hash', 'status', 'source_status', 'source_error_code', 'observations', 'evidence_ids', 'created_at', 'confirmed_policy_id', 'confirmation_required', 'future_obligation_guaranteed', 'bank_authority']) && safeConfiguration(p.configuration) && p.configuration.type === 'recurring_obligation' && p.configuration.auto_execute === false && digest(p.configuration_hash) && p.configuration_hash === await hash(p.configuration) && ['PROPOSED', 'CONFIRMED', 'EXPIRED'].includes(String(p.status)) && ['VERIFIED_HISTORICAL_OBSERVATION', 'UNKNOWN'].includes(String(p.source_status)) && ids(p.evidence_ids) && p.evidence_ids.length > 0 && time(p.created_at) && (p.status === 'CONFIRMED' ? uuid(p.confirmed_policy_id) : p.confirmed_policy_id === null) && p.confirmation_required === true && p.future_obligation_guaranteed === false && p.bank_authority === false && Array.isArray(p.observations) && p.observations.length <= 1 && (p.source_status === 'VERIFIED_HISTORICAL_OBSERVATION' ? p.observations.length === 1 && p.source_error_code === null : typeof p.source_error_code === 'string' && !!p.source_error_code));
    const c = p.configuration, rule = c.amount_rule; check(typeof c.payee_id === 'string' && c.payee_id.length > 0 && cents(c.due_day) && c.due_day >= 1 && c.due_day <= 31 && object(rule));
    check(rule.kind === 'range' ? exact(rule, ['kind', 'min_cents', 'max_cents']) && cents(rule.min_cents) && cents(rule.max_cents) && rule.min_cents > 0 && rule.min_cents <= rule.max_cents : rule.kind === 'bill_balance' && exact(rule, ['kind', 'account_id']) && uuid(rule.account_id));
    for (const o of p.observations) {
      check(object(o) && exact(o, ['simulation', 'rule_version', 'rule', 'object_key', 'revision', 'sources', 'matched_rule', 'future_obligation_guaranteed', 'limitation', 'observation_window', 'configuration_hash']) && o.simulation === true && o.rule_version === 'mvp-104-v1' && ['monthly_rent', 'credit_card_cycle'].includes(String(o.rule)) && digest(o.object_key) && digest(o.revision) && o.configuration_hash === p.configuration_hash && o.future_obligation_guaranteed === false && typeof o.matched_rule === 'string' && typeof o.limitation === 'string' && object(o.observation_window) && exact(o.observation_window, ['start_date', 'end_date', 'timezone', 'days']) && o.observation_window.days === 60 && ['UTC', 'Asia/Shanghai'].includes(String(o.observation_window.timezone)) && annualDayNumber(o.observation_window.end_date) - annualDayNumber(o.observation_window.start_date) === 59 && Array.isArray(o.sources) && o.sources.length >= 2 && o.sources.length <= 60 && ids(o.sources.map((s) => object(s) ? s.fact_id : null)) && ids(o.sources.map((s) => object(s) ? s.evidence_id : null)));
      for (const s of o.sources) {
        check(object(s) && exact(s, ['fact_type', 'fact_id', 'source_ref', 'account_id', 'evidence_id', 'evidence_hash', 'evidence_source_type', 'evidence_source_ref', 'evidence_observed_at', 'fact']) && s.fact_type === (o.rule === 'monthly_rent' ? 'transactions' : 'credit_card_bills') && uuid(s.account_id) && uuid(s.evidence_id) && digest(s.evidence_hash) && p.evidence_ids.includes(s.evidence_id) && ['source_ref', 'evidence_source_type', 'evidence_source_ref'].every((f) => typeof s[f] === 'string' && !!s[f]) && time(s.evidence_observed_at) && Date.parse(s.evidence_observed_at) <= Date.parse(p.created_at) && object(s.fact));
        if (o.rule === 'monthly_rent') check(exact(s.fact, ['transaction_id', 'account_id', 'direction', 'amount_cents', 'balance_after_cents', 'occurred_at', 'counterparty_ref']) && s.fact.transaction_id === s.fact_id && s.fact.account_id === s.account_id && s.fact.direction === 'DEBIT' && cents(s.fact.amount_cents) && s.fact.amount_cents > 0 && Number.isSafeInteger(s.fact.balance_after_cents) && time(s.fact.occurred_at) && Date.parse(s.fact.occurred_at) <= Date.parse(p.created_at) && s.fact.counterparty_ref === c.payee_id);
        else { check(exact(s.fact, ['total_cents', 'paid_cents', 'statement_date', 'due_date', 'status']) && cents(s.fact.total_cents) && cents(s.fact.paid_cents) && s.fact.paid_cents <= s.fact.total_cents && typeof s.fact.status === 'string'); annualDayNumber(s.fact.statement_date); annualDayNumber(s.fact.due_date); }
      }
      const sources = o.sources; check(new Set(sources.map((s) => s.account_id)).size === 1 && o.object_key === await hash({ user_id: environment.dashboard.user_id, rule: o.rule, account_id: sources[0].account_id, payee_id: c.payee_id }) && o.revision === await hash({ rule_version: o.rule_version, sources, configuration_hash: p.configuration_hash }));
      check(o.rule === 'monthly_rent' ? rule.kind === 'range' && sources.every((s) => s.fact.amount_cents === rule.min_cents && s.fact.amount_cents === rule.max_cents) : rule.kind === 'bill_balance' && rule.account_id === sources[0].account_id && c.payee_id === `credit-card:${String(rule.account_id)}`);
    }
  }
  let statistics: DiscoveryRead['statistics'];
  if (v.discovery !== undefined) { const d = v.discovery; check(object(d) && exact(d, ['simulation', 'user_id', 'rule_version', 'as_of', 'created_proposal_ids', 'reused_proposal_ids', 'skipped']) && d.simulation === true && d.user_id === environment.dashboard.user_id && d.rule_version === 'mvp-104-v1' && time(d.as_of) && ids(d.created_proposal_ids) && ids(d.reused_proposal_ids) && new Set([...d.created_proposal_ids, ...d.reused_proposal_ids]).size === d.created_proposal_ids.length + d.reused_proposal_ids.length && [...d.created_proposal_ids, ...d.reused_proposal_ids].every((id) => proposals.some((p) => p.proposal_id === id)) && Array.isArray(d.skipped) && d.skipped.every((s) => object(s) && exact(s, ['reason_code', 'source_ref']) && typeof s.reason_code === 'string' && typeof s.source_ref === 'string')); statistics = d as DiscoveryRead['statistics']; }
  return { proposals: v.proposals as DiscoveredProposal[], ...(statistics ? { statistics } : {}) };
}
export async function getDiscovery(environment: NextState): Promise<DiscoveryRead> { return request('/zhiyu-next/policy-discovery', 'GET', undefined, (v) => { context(v, environment); check(v.protocol === 'zhiyu-next-historical-discovery-read-v1'); return parseDiscoveryRead(v, environment); }); }
export async function readDiscoveryOriginal(original: PendingOperation, environment: NextState): Promise<OperationResult> {
  check(isDiscoveryPath(original.path)); const v = await request(`/zhiyu-next/policy-commands/${original.client_request_id}`, 'GET', undefined, (v) => { context(v, environment); return v; });
  check(v.client_request_id === original.client_request_id && ['COMPLETED', 'REJECTED', 'PENDING'].includes(String(v.status)) && object(v.original_request) && v.original_request.path === `/api/v1${original.path}` && same(v.original_request.body, original.body));
  if (v.status !== 'COMPLETED') return v as unknown as OperationResult;
  const r = v.result; context(r, environment); check(r.bank_authority === false && r.client_request_id === original.client_request_id);
  let update: DiscoveryUpdate;
  if (original.path === '/zhiyu-next/policy-discovery') update = { kind: 'DISCOVER', read: await parseDiscoveryRead(r, environment) };
  else {
    const life = r.original_result; check(object(life) && exact(life, ['simulation', 'policy_id', 'current_version_id', 'previous_version_id', 'status', 'effective_status', 'invalidated_action_ids', 'inflight_action_ids', 'requires_recompute']) && life.simulation === true && uuid(life.policy_id) && uuid(life.current_version_id) && life.previous_version_id === null && ['ACTIVE', 'CONFIRMED'].includes(String(life.status)) && ['ACTIVE', 'CONFIRMED'].includes(String(life.effective_status)) && ids(life.invalidated_action_ids) && ids(life.inflight_action_ids) && life.requires_recompute === true);
    const principal = parseLocalActorSession({ simulation: true, principal: r.authenticated_principal, bank_authority: false, confirms_financial_action: false }).principal; check(principal && principal.role === 'USER' && principal.user_id === environment.dashboard.user_id && original.body.accepted === true && uuid(original.body.proposal_id) && digest(original.body.reviewed_hash));
    // The audited exact original body binds proposal/hash. A lifecycle receipt is a rule result, never bank proof.
    update = { kind: 'CONFIRM', confirmation: { proposal_id: original.body.proposal_id, reviewed_hash: original.body.reviewed_hash, original_result: life as DiscoveryConfirmation['original_result'], principal } };
  }
  return { ...(v as unknown as OperationResult), result: update as unknown as Record<string, unknown> };
}
