import { request } from '../api/http';
import { object } from '../features/policy-form';
import { spendingHash as hash, spendingUUID as uuid, spendingDigest as digest } from '../api/spending-evidence';
import { annualDayNumber } from '../api/planning';
import type { FullJointGoalInput } from '../api/full-joint-planning';
import type { JointAllocation, JointPlanning } from '../api/joint-planning';
import { jointCheck as check, jointCanonical, parseJointBinding, parseJointConfirm, parseJointExecute, parseJointPrepare, type JointPrepare, type JointReviewBinding, type JointResponse } from '../api/full-joint-goal-execution';
import { parseDynamicAction } from '../api/full-dynamic-goal-execution';
import { parseLocalActorSession } from '../api/local-actor';
import type { NextState } from './api';
import { context } from './policies';

const exact = (v: Record<string, unknown>, fields: string[]) => Object.keys(v).sort().join('|') === fields.sort().join('|');
const cents = (v: unknown): v is number => Number.isSafeInteger(v) && Number(v) >= 0;
const integer = (v: unknown): v is number => Number.isSafeInteger(v);
const strings = (v: unknown): v is string[] => Array.isArray(v) && v.every((x) => typeof x === 'string');
const ids = (v: unknown): v is string[] => Array.isArray(v) && v.every(uuid) && new Set(v).size === v.length;
const time = (v: unknown): v is string => typeof v === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(v) && Number.isFinite(Date.parse(v));
const same = (a: unknown, b: unknown) => jointCanonical(a) === jointCanonical(b);
const sum = (rows: number[]) => rows.reduce((n, x) => n + BigInt(x), 0n);
export const jointValidation = 'DEVELOPMENT_PENDING_ACTUAL_JOINT_ACCEPTANCE' as const;
// Deliberately no broad AVAILABLE/ENABLED alias for a financial acceptance gate.
export function jointExecutionOpen(validation: string): boolean { return validation === 'VERIFIED_ACTUAL_JOINT_ACCEPTANCE'; }
export type GoalPoint = { day: number; date: string; phase: 'BEFORE_PAYMENT' | 'AFTER_PAYMENT' | 'AFTER_PRINCIPAL'; cash_cents: number; protected_cents_by_reason: Record<string, number>; margin_cents: number; obligation_occurrence_ids: string[]; principal_position_ids: string[] };
export type GoalMonth = { month: string; points_count: number; minimum_margin_cents: number; maximum_protected_cents: number; minimum_cash_cents: number };
export type NextGoalPlanning = { protocol: 'zhiyu-next-joint-planning-read-v1'; planning_only: true; grants_authority: false; as_of: string; state: 'COMPUTED' | 'UNKNOWN'; reasons: string[]; input_hash: string; funds_scope: 'ACTUAL_CURRENT_UNASSIGNED_INCOME_ONLY'; registered_goal_count: number; included_goal_ids: string[]; uncovered_goal_ids: string[]; goals: FullJointGoalInput[]; allocation: JointAllocation | null; conflict: JointPlanning['conflict']; annual: { horizon_days: 365; calculation_points_total: number; all_points_used_for_safety: true; boundary_hash: string | null; state: 'READY' | 'LIQUIDITY_RISK' | 'UNKNOWN'; safe_idle_cents: number | null; minimum_margin_cents: number | null; future_income_in_current_cash_cents: 0; future_income_status: 'NO_REGISTERED_PLANNING_INCOME_SOURCE'; months: GoalMonth[]; point_offset: number; point_limit: number; points: GoalPoint[]; display_pagination_only: true }; limitations: string[]; current_execution_goal_limit: 8; current_execution_validation: string };

/** Display DTO only. Complete source/audit/1098-point safety stays on the server. */
export function parseGoalAllocation(value: unknown, goalIds: string[]): JointAllocation {
  check(object(value) && exact(value, ['algorithm_version', 'status', 'purpose', 'grants_authority', 'input_hash', 'objective_vector', 'budget_cents', 'goals', 'income_uses', 'visited_nodes', 'reasons', 'delay_scope']) && value.algorithm_version === 'critical-flow-lexicographic-v1' && value.purpose === 'CURRENT_PERIOD_PLANNING_ONLY' && value.grants_authority === false && digest(value.input_hash) && ['OPTIMAL', 'INFEASIBLE', 'UNKNOWN'].includes(String(value.status)) && cents(value.budget_cents) && cents(value.visited_nodes) && strings(value.reasons) && value.delay_scope === 'ACTIVE_INCOMPLETE_GOALS_CURRENT_DECISION_LOWER_BOUND' && Array.isArray(value.goals) && value.goals.length <= 8 && ids(value.goals.map((g) => object(g) ? g.goal_id : null)) && Array.isArray(value.income_uses));
  const optimal = value.status === 'OPTIMAL';
  check(optimal ? Array.isArray(value.objective_vector) && value.objective_vector.length === 8 && value.objective_vector.every(cents) : value.objective_vector === null);
  for (const g of value.goals) {
    check(object(g) && exact(g, ['goal_id', 'effective_policy_version_id', 'amount_cents', 'minimum_shortfall_cents', 'projected_owned_cents', 'completion_date', 'delay_lower_bound_days', 'delay_censored', 'deferral_cost_lower_bound_cents']) && uuid(g.effective_policy_version_id) && typeof g.delay_censored === 'boolean');
    for (const field of ['amount_cents', 'minimum_shortfall_cents', 'projected_owned_cents', 'delay_lower_bound_days', 'deferral_cost_lower_bound_cents']) check(optimal ? cents(g[field]) : g[field] === null);
    if (g.completion_date !== null) annualDayNumber(g.completion_date);
    check(!g.delay_censored || g.completion_date === null);
    check(optimal ? Number(g.projected_owned_cents) >= Number(g.amount_cents) : g.completion_date === null && g.delay_censored);
  }
  check(same(value.goals.map((g) => g.goal_id).sort(), [...goalIds].sort()));
  const uses = value.income_uses;
  for (const u of uses) check(object(u) && exact(u, ['fragment_id', 'origin_transaction_id', 'source_account_id', 'goal_id', 'amount_cents']) && ['fragment_id', 'origin_transaction_id', 'source_account_id', 'goal_id'].every((f) => uuid(u[f])) && goalIds.includes(String(u.goal_id)) && cents(u.amount_cents) && u.amount_cents > 0);
  check(optimal || uses.length === 0);
  if (optimal) { check(sum(uses.map((u) => u.amount_cents)) <= BigInt(value.budget_cents)); for (const g of value.goals) check(sum(uses.filter((u) => u.goal_id === g.goal_id).map((u) => u.amount_cents)) === BigInt(g.amount_cents)); }
  return value as JointAllocation;
}
function parseConflict(v: unknown, allocation: JointAllocation | null, goals: string[]) {
  if (v === null) return;
  check(object(v) && exact(v, ['status', 'scope', 'input_hash', 'constraint_ids', 'deletion_checks', 'grants_authority', 'reasons']) && allocation?.status === 'INFEASIBLE' && v.input_hash === allocation.input_hash && v.scope === 'GOAL_POLICIES_WITH_IMMUTABLE_FINANCIAL_BASE' && v.grants_authority === false && ['MINIMAL_CONFLICT', 'NO_CONFLICT', 'BASE_INFEASIBLE', 'UNKNOWN'].includes(String(v.status)) && strings(v.constraint_ids) && new Set(v.constraint_ids).size === v.constraint_ids.length && strings(v.reasons) && Array.isArray(v.deletion_checks));
  const removed = new Set<string>();
  for (const row of v.deletion_checks) { check(object(row) && exact(row, ['removed_constraint_id', 'remaining_feasible', 'witness_amounts_cents', 'counterfactual_only']) && typeof row.removed_constraint_id === 'string' && v.constraint_ids.includes(row.removed_constraint_id) && !removed.has(row.removed_constraint_id) && row.remaining_feasible === true && row.counterfactual_only === true && object(row.witness_amounts_cents) && same(Object.keys(row.witness_amounts_cents).sort(), [...goals].sort()) && Object.values(row.witness_amounts_cents).every(cents)); removed.add(row.removed_constraint_id); }
  if (v.status === 'MINIMAL_CONFLICT') check(removed.size > 0 && removed.size === v.constraint_ids.length);
}
export function parseNextGoalPlanning(value: unknown, environment: NextState, offset: number, limit: number): NextGoalPlanning {
  context(value, environment);
  check(value.protocol === 'zhiyu-next-joint-planning-read-v1' && value.planning_only === true && value.grants_authority === false && time(value.as_of) && ['COMPUTED', 'UNKNOWN'].includes(String(value.state)) && strings(value.reasons) && digest(value.input_hash) && value.funds_scope === 'ACTUAL_CURRENT_UNASSIGNED_INCOME_ONLY' && cents(value.registered_goal_count) && ids(value.included_goal_ids) && ids(value.uncovered_goal_ids) && new Set([...value.included_goal_ids, ...value.uncovered_goal_ids]).size === value.registered_goal_count && strings(value.limitations) && value.current_execution_goal_limit === 8 && typeof value.current_execution_validation === 'string' && Array.isArray(value.goals) && value.goals.length <= 8);
  for (const g of value.goals) {
    check(object(g) && exact(g, ['goal_id', 'account_id', 'policy_id', 'effective_policy_version_id', 'policy_status', 'target_cents', 'current_owned_cents', 'current_month_contributed_cents', 'monthly_min_cents', 'monthly_target_cents', 'monthly_max_cents', 'minimum_guarantee_cents', 'importance', 'deadline', 'allow_partial', 'allow_deferral', 'deferral_cost_cents_per_day', 'confirmed_at', 'valid_from', 'valid_until', 'negotiable_fields', 'source_refs']) && ['goal_id', 'account_id', 'policy_id', 'effective_policy_version_id'].every((f) => uuid(g[f])) && ['ACTIVE', 'CONFIRMED', 'SUSPENDED', 'REVOKED', 'EXPIRED'].includes(String(g.policy_status)) && ['target_cents', 'current_owned_cents', 'current_month_contributed_cents', 'monthly_min_cents', 'monthly_target_cents', 'monthly_max_cents', 'minimum_guarantee_cents', 'importance', 'deferral_cost_cents_per_day'].every((f) => cents(g[f])) && Number(g.target_cents) > 0 && Number(g.monthly_min_cents) <= Number(g.monthly_target_cents) && Number(g.monthly_target_cents) <= Number(g.monthly_max_cents) && Number(g.minimum_guarantee_cents) <= Number(g.target_cents) && Number(g.importance) <= 100 && typeof g.allow_partial === 'boolean' && typeof g.allow_deferral === 'boolean' && (g.allow_deferral || g.deferral_cost_cents_per_day === 0) && time(g.confirmed_at) && Date.parse(g.confirmed_at) <= Date.parse(value.as_of) && time(g.valid_from) && (g.valid_until === null || time(g.valid_until) && Date.parse(g.valid_until) >= Date.parse(g.valid_from)) && strings(g.negotiable_fields) && new Set(g.negotiable_fields).size === g.negotiable_fields.length && g.negotiable_fields.every((f) => ['monthly_min_cents', 'monthly_max_cents', 'deadline'].includes(f)) && Array.isArray(g.source_refs) && g.source_refs.length > 0 && g.source_refs.every((r) => object(r) && exact(r, ['user_id', 'evidence_id', 'content_hash']) && r.user_id === environment.dashboard.user_id && uuid(r.evidence_id) && digest(r.content_hash)));
    annualDayNumber(g.deadline);
  }
  check(ids(value.goals.map((g) => g.goal_id)) && (value.goals.length === 0 && value.state === 'UNKNOWN' || same(value.goals.map((g) => g.goal_id).sort(), [...value.included_goal_ids].sort())));
  const allocation = value.allocation === null ? null : parseGoalAllocation(value.allocation, value.included_goal_ids);
  check(allocation === null ? value.state === 'UNKNOWN' && value.conflict === null : value.state === (allocation.status === 'UNKNOWN' ? 'UNKNOWN' : 'COMPUTED'));
  if (allocation?.status === 'OPTIMAL') { check(value.uncovered_goal_ids.length === 0); for (const g of allocation.goals) { const original = value.goals.find((x) => x.goal_id === g.goal_id); check(original && g.effective_policy_version_id === original.effective_policy_version_id && BigInt(g.projected_owned_cents!) === BigInt(original.current_owned_cents) + BigInt(g.amount_cents!)); } }
  parseConflict(value.conflict, allocation, value.included_goal_ids);
  const a = value.annual; check(object(a) && exact(a, ['horizon_days', 'calculation_points_total', 'all_points_used_for_safety', 'boundary_hash', 'state', 'safe_idle_cents', 'minimum_margin_cents', 'future_income_in_current_cash_cents', 'future_income_status', 'months', 'point_offset', 'point_limit', 'points', 'display_pagination_only']) && a.horizon_days === 365 && [0, 1098].includes(Number(a.calculation_points_total)) && a.all_points_used_for_safety === true && ['READY', 'LIQUIDITY_RISK', 'UNKNOWN'].includes(String(a.state)) && (a.boundary_hash === null || digest(a.boundary_hash)) && (a.safe_idle_cents === null || cents(a.safe_idle_cents)) && (a.minimum_margin_cents === null || integer(a.minimum_margin_cents)) && a.future_income_in_current_cash_cents === 0 && a.future_income_status === 'NO_REGISTERED_PLANNING_INCOME_SOURCE' && a.point_offset === offset && a.point_limit === limit && a.display_pagination_only === true && Array.isArray(a.points) && a.points.length === Math.max(0, Math.min(limit, Number(a.calculation_points_total) - offset)) && Array.isArray(a.months));
  const phases = ['BEFORE_PAYMENT', 'AFTER_PAYMENT', 'AFTER_PRINCIPAL'];
  for (const [index, p] of a.points.entries()) { check(object(p) && exact(p, ['day', 'date', 'phase', 'cash_cents', 'protected_cents_by_reason', 'margin_cents', 'obligation_occurrence_ids', 'principal_position_ids']) && p.day === Math.floor((offset + index) / 3) && p.phase === phases[(offset + index) % 3] && integer(p.cash_cents) && integer(p.margin_cents) && object(p.protected_cents_by_reason) && Object.values(p.protected_cents_by_reason).every(cents) && BigInt(p.margin_cents) === BigInt(p.cash_cents) - sum(Object.values(p.protected_cents_by_reason) as number[]) && strings(p.obligation_occurrence_ids) && ids(p.principal_position_ids)); annualDayNumber(p.date); if (index > 0) check(annualDayNumber(p.date) === annualDayNumber(a.points[0].date) + Math.floor((offset + index) / 3) - Math.floor(offset / 3)); }
  for (const m of a.months) check(object(m) && exact(m, ['month', 'points_count', 'minimum_margin_cents', 'maximum_protected_cents', 'minimum_cash_cents']) && typeof m.month === 'string' && /^\d{4}-(0[1-9]|1[0-2])$/.test(m.month) && cents(m.points_count) && m.points_count > 0 && m.points_count <= 93 && m.points_count % 3 === 0 && integer(m.minimum_margin_cents) && cents(m.maximum_protected_cents) && integer(m.minimum_cash_cents));
  const months = a.months;
  check(new Set(months.map((m) => m.month)).size === months.length && months.every((m, i) => i === 0 || m.month > months[i - 1].month) && sum(months.map((m) => m.points_count)) === BigInt(Number(a.calculation_points_total)));
  if (a.calculation_points_total === 0) check(a.boundary_hash === null && a.safe_idle_cents === null && a.minimum_margin_cents === null && a.state === 'UNKNOWN');
  else check(digest(a.boundary_hash) && integer(a.minimum_margin_cents) && cents(a.safe_idle_cents) && a.minimum_margin_cents === Math.min(...a.months.map((m) => m.minimum_margin_cents)) && a.safe_idle_cents === Math.max(0, a.minimum_margin_cents));
  return value as unknown as NextGoalPlanning;
}
export function getNextGoalPlanning(environment: NextState, offset = 0, limit = 93): Promise<NextGoalPlanning> { check(cents(offset) && offset <= 1098 && cents(limit) && limit > 0 && limit <= 366); return request(`/zhiyu-next/goals/planning?point_offset=${offset}&point_limit=${limit}`, 'GET', undefined, (v) => parseNextGoalPlanning(v, environment, offset, limit)); }

export type ThinJointPlan = { protocol: 'registered-joint-goal-execution-v2' | 'registered-joint-goal-execution-archive-v3' | 'registered-joint-goal-execution-source-dag-v4'; simulation: true; bank_authority: false; funds_reserved: false; execution_mode: 'USER_ASK_FIXED_ORDER'; cross_operation_atomicity: 'NOT_AVAILABLE'; plan_id: string; user_id: string; epoch_id: string; prepared_at: string; expires_at: string; original_request: JointPrepare; total_allocation_cents: number; children: JointReviewBinding['children']; allocation: JointAllocation; full_binding_hash: string; plan_hash: string; complete_original_retained: true; current_execution_goal_limit: 8; current_execution_validation: string };
export type ThinJointResponse = Omit<JointResponse, 'original_plan'> & { protocol: 'zhiyu-next-joint-execution-read-v1'; original_plan: ThinJointPlan };
export function thinJointBinding(plan: ThinJointPlan): JointReviewBinding { return { protocol: 'joint-goal-original-read-locator-v2', plan_id: plan.plan_id, user_id: plan.user_id, epoch_id: plan.epoch_id, plan_hash: plan.plan_hash, prepared_at: plan.prepared_at, expires_at: plan.expires_at, original_request: structuredClone(plan.original_request), total_allocation_cents: plan.total_allocation_cents, children: structuredClone(plan.children), grants_authority: false }; }
export async function parseThinJointPlan(v: unknown, environment: NextState): Promise<ThinJointPlan> {
  check(object(v) && exact(v, ['protocol', 'simulation', 'bank_authority', 'funds_reserved', 'execution_mode', 'cross_operation_atomicity', 'plan_id', 'user_id', 'epoch_id', 'prepared_at', 'expires_at', 'original_request', 'total_allocation_cents', 'children', 'allocation', 'full_binding_hash', 'plan_hash', 'complete_original_retained', 'current_execution_goal_limit', 'current_execution_validation']) && ['registered-joint-goal-execution-v2', 'registered-joint-goal-execution-archive-v3', 'registered-joint-goal-execution-source-dag-v4'].includes(String(v.protocol)) && v.simulation === true && v.bank_authority === false && v.funds_reserved === false && v.execution_mode === 'USER_ASK_FIXED_ORDER' && v.cross_operation_atomicity === 'NOT_AVAILABLE' && v.user_id === environment.dashboard.user_id && v.epoch_id === environment.epoch_id && digest(v.full_binding_hash) && v.complete_original_retained === true && v.current_execution_goal_limit === 8 && typeof v.current_execution_validation === 'string');
  const plan = v as unknown as ThinJointPlan; await parseJointBinding(thinJointBinding(plan));
  check(object(v.allocation) && Array.isArray(v.allocation.goals)); const allocation = parseGoalAllocation(v.allocation, v.allocation.goals.map((g) => object(g) ? String(g.goal_id) : ''));
  check(allocation.status === 'OPTIMAL' && allocation.goals.length >= 2 && allocation.goals.filter((g) => g.amount_cents! > 0).length === plan.children.length);
  for (const c of plan.children) { const g = allocation.goals.find((g) => g.goal_id === c.goal_id); check(g && g.effective_policy_version_id === c.command.effect.policy_version_id && g.amount_cents === c.command.effect.amount_cents); const uses = allocation.income_uses.filter((u) => u.goal_id === c.goal_id).map((u) => ({ fragment_id: u.fragment_id, origin_transaction_id: u.origin_transaction_id, account_id: u.source_account_id, amount_cents: u.amount_cents })); check(same(uses, c.command.effect.income_uses)); }
  return plan;
}
/** Lean economic effects are complete; compressed source/math originals are checked by the server. */
export async function parseThinJointResponse(v: unknown, environment: NextState, expected?: ThinJointPlan | null): Promise<ThinJointResponse> {
  check(object(v) && exact(v, ['protocol', 'simulation', 'bank_authority', 'current_authority_assessed', 'receipt_is_current_authority', 'economic_experiment_verified', 'funds_reserved', 'reservation_scope', 'user_id', 'epoch_id', 'as_of', 'original_plan', 'original_request_hash', 'original_consent', 'children', 'state']) && v.protocol === 'zhiyu-next-joint-execution-read-v1' && v.simulation === true && v.bank_authority === false && v.current_authority_assessed === false && v.receipt_is_current_authority === false && v.economic_experiment_verified === false && v.funds_reserved === false && v.reservation_scope === 'WHOLE_UNRESERVED_CHILDREN_USE_ORIGINAL_CLAIMS' && time(v.as_of) && ['PARTIALLY_PREPARED', 'PREPARED_UNRESERVED', 'CONFIRMED_UNRESERVED', 'PARTIALLY_SETTLED', 'UNRESOLVED', 'ORIGINAL_SERVICE_RECEIPTS_VERIFIED', 'STOPPED', 'RETAINED_HISTORY'].includes(String(v.state)));
  const plan = await parseThinJointPlan(v.original_plan, environment); check(v.user_id === plan.user_id && v.epoch_id === plan.epoch_id && v.original_request_hash === await hash(plan.original_request) && (!expected || same(plan, expected)) && Array.isArray(v.children) && v.children.length === plan.children.length);
  for (const [index, row] of v.children.entries()) {
    const child = plan.children[index]!; check(object(row) && exact(row, ['child_number', 'action_id', 'bank_idempotency_key', 'state', 'original_action', 'original_request_hash']) && row.child_number === child.child_number && row.action_id === child.action_id && row.bank_idempotency_key === child.bank_idempotency_key && ['MISSING', 'PLANNED_UNRESERVED', 'AUTHORIZED', 'SUBMITTED', 'UNKNOWN', 'ORIGINAL_RECEIPT_VERIFIED', 'STOPPED'].includes(String(row.state)));
    if (row.original_action === null) { check(row.state === 'MISSING' && row.original_request_hash === null); continue; }
    check(digest(row.original_request_hash) && object(row.original_action) && same(row.original_action.effect, child.command.effect) && row.original_action.effect_hash === child.command.effect_hash && row.original_action.autonomy_level === 'ASK_ONCE');
    await parseDynamicAction(row.original_action, { goal_id: child.goal_id, expected_policy_version_id: child.command.effect.policy_version_id!, expected_model_evidence_id: child.original_model_evidence_id, expected_model_evidence_hash: child.original_model_evidence_hash, expected_epoch_id: plan.epoch_id, idempotency_key: plan.original_request.idempotency_key }, plan.user_id);
    const a = row.original_action; const settled = ['SUCCEEDED', 'RECONCILED'].includes(String(a.status)) && a.bank_status === 'SETTLED' && a.receipt !== null;
    if (a.receipt !== null) check(settled && object(a.receipt) && a.receipt.status === 'SUCCEEDED' && Array.isArray(a.receipt.posting_ids) && a.receipt.posting_ids.length >= 2);
    check((row.state === 'ORIGINAL_RECEIPT_VERIFIED') === settled);
    if (row.state === 'PLANNED_UNRESERVED') check(a.status === 'PLANNED' && a.bank_status === null);
    if (row.state === 'AUTHORIZED') check(a.status === 'AUTHORIZED' && a.bank_status === null);
    if (row.state === 'SUBMITTED') check(a.status === 'SUBMITTED' && a.bank_status === null);
    if (row.state === 'UNKNOWN') check(!settled && (a.status === 'UNKNOWN' || a.status === 'SUBMITTED' || a.bank_status !== null));
  }
  if (v.original_consent !== null) {
    const c = v.original_consent; check(object(c) && exact(c, ['consent_id', 'user_id', 'plan_id', 'epoch_id', 'original_request', 'request_hash', 'original_evidence', 'evidence_id', 'evidence_hash', 'current_evidence_verified', 'current_evidence_status', 'receipt_is_current_authority']) && uuid(c.consent_id) && c.user_id === plan.user_id && c.plan_id === plan.plan_id && c.epoch_id === plan.epoch_id && uuid(c.evidence_id) && digest(c.evidence_hash) && c.receipt_is_current_authority === false && typeof c.current_evidence_verified === 'boolean' && ['CURRENT_EVIDENCE_MATCHED', 'RETAINED_ORIGINAL_CURRENT_EVIDENCE_MISSING'].includes(String(c.current_evidence_status)) && c.current_evidence_verified === (c.current_evidence_status === 'CURRENT_EVIDENCE_MATCHED'));
    const body = parseJointConfirm(c.original_request); check(body.expected_epoch_id === plan.epoch_id && body.reviewed_plan_hash === plan.plan_hash && c.request_hash === await hash(body) && object(c.original_evidence));
    const e = c.original_evidence, content = e.content; check(e.id === c.evidence_id && e.user_id === plan.user_id && e.source_type === 'USER_JOINT_GOAL_CONFIRMATION' && e.source_ref === plan.plan_id && e.evidence_level === 'USER_CONFIRMED_ACTION' && e.content_hash === c.evidence_hash && object(content) && content.protocol === 'joint-goal-whole-consent-v2' && content.simulation === true && content.user_id === plan.user_id && content.plan_id === plan.plan_id && content.epoch_id === plan.epoch_id && content.plan_hash === plan.plan_hash && content.accepted === true && same(content.original_request, body) && content.request_hash === c.request_hash && time(content.confirmed_at) && time(content.valid_until) && Date.parse(content.confirmed_at) >= Date.parse(plan.prepared_at) && Date.parse(content.confirmed_at) < Date.parse(plan.expires_at) && Date.parse(content.valid_until) === Date.parse(plan.expires_at) && content.actor_role === 'USER' && content.authentication_source === 'LOCAL_SIGNED_SESSION' && content.human_identity_verified === false && object(content.actor));
    const principal = parseLocalActorSession({ simulation: true, principal: content.actor, bank_authority: false, confirms_financial_action: false }).principal; check(principal && principal.user_id === plan.user_id && principal.role === 'USER' && principal.session_id === content.actor_session_id && Date.parse(principal.issued_at) <= Date.parse(content.confirmed_at) && Date.parse(principal.expires_at) > Date.parse(content.confirmed_at) && c.evidence_hash === await hash(content));
  }
  const states = v.children.map((r) => r.state);
  if (v.state !== 'RETAINED_HISTORY') { const wanted = states.some((s) => ['UNKNOWN', 'SUBMITTED'].includes(s)) ? 'UNRESOLVED' : states.includes('STOPPED') ? 'STOPPED' : states.includes('MISSING') ? 'PARTIALLY_PREPARED' : states.every((s) => s === 'ORIGINAL_RECEIPT_VERIFIED') ? 'ORIGINAL_SERVICE_RECEIPTS_VERIFIED' : states.includes('ORIGINAL_RECEIPT_VERIFIED') ? 'PARTIALLY_SETTLED' : object(v.original_consent) && v.original_consent.current_evidence_verified ? 'CONFIRMED_UNRESERVED' : 'PREPARED_UNRESERVED'; check(v.state === wanted); }
  return v as ThinJointResponse;
}

export async function previewNextJoint(body: JointPrepare, environment: NextState) {
  parseJointPrepare(body); const value = await request('/zhiyu-next/goals/joint/preview?archive_protocol=V4', 'POST', body, (v) => { context(v, environment); return v; });
  const p = value.preview; check(object(p) && exact(p, ['simulation', 'bank_authority', 'grants_authority', 'preview_only', 'user_id', 'epoch_id', 'as_of', 'request', 'status', 'registered_goal_ids', 'unresolved_original_action_ids', 'plan', 'input_hash', 'reasons', 'limitations']) && p.simulation === true && p.bank_authority === false && p.grants_authority === false && p.preview_only === true && p.user_id === environment.dashboard.user_id && p.epoch_id === environment.epoch_id && time(p.as_of) && same(p.request, body) && ['READY_TO_REVIEW', 'BLOCKED', 'UNKNOWN'].includes(String(p.status)) && ids(p.registered_goal_ids) && ids(p.unresolved_original_action_ids) && digest(p.input_hash) && strings(p.reasons) && strings(p.limitations));
  if (p.status === 'READY_TO_REVIEW') { const plan = await parseThinJointPlan(p.plan, environment); check(plan.protocol === 'registered-joint-goal-execution-source-dag-v4' && plan.prepared_at === p.as_of && same(plan.original_request, body) && p.reasons.length === 0 && p.unresolved_original_action_ids.length === 0 && same([...p.registered_goal_ids].sort(), plan.allocation.goals.map((g) => g.goal_id).sort())); }
  else check(p.plan === null && p.reasons.length > 0);
  return p as { status: 'READY_TO_REVIEW' | 'BLOCKED' | 'UNKNOWN'; plan: ThinJointPlan | null; reasons: string[]; limitations: string[] };
}
export async function getNextJoint(id: string, environment: NextState, expected?: ThinJointPlan | null): Promise<ThinJointResponse> { check(uuid(id)); const v = await request(`/zhiyu-next/goals/joint/${id}`, 'GET', undefined, (v) => { context(v, environment); return v; }); const response = await parseThinJointResponse(v.execution, environment, expected); check(response.original_plan.plan_id === id); return response; }
export { parseJointConfirm, parseJointExecute, parseJointPrepare };
