import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { NextState } from './api';
import type { AssetsState } from './assets-state';
import { assetSourceOpen } from './assets-state';
import type { AssetPerform } from './AssetsPanel';
import { getNextLoss, quoteNextLoss, readLossView, type LossBinding, type LossUpdate } from './loss';
import type { LossRecovery } from './loss-recovery';
import type { LossRevisionUpdate } from './loss-revisions';
import LossRevisionPanel from './LossRevisionPanel';
import { businessText, money, userError } from './display';

export default function LossPanel({ environment, state, blocked, signed, update, recovering, perform, runRead, resumeOriginal, retryOriginal, revisionUpdate = null, revisionRecovering = false, resumeRevisionOriginal }: { environment: NextState; state?: AssetsState; blocked: boolean; signed: boolean; update: LossUpdate | null; recovering: boolean; perform: AssetPerform; runRead: <T>(work: () => Promise<T>) => Promise<T>; revisionUpdate?: LossRevisionUpdate | null; revisionRecovering?: boolean; resumeRevisionOriginal?: () => Promise<void>; resumeOriginal?: () => Promise<void>; retryOriginal?: () => Promise<void> }) {
  const [hasRevision, setHasRevision] = useState(false); const [positionId, setPositionId] = useState(''); const [quote, setQuote] = useState<LossBinding['quote'] | null>(null); const [error, setError] = useState(''); const [working, setWorking] = useState(false);
  const previous = useQuery({ queryKey: ['zhiyu-next-loss-view', environment.environment_id, environment.epoch_id], queryFn: () => readLossView(environment), enabled: !blocked && !update, retry: false, staleTime: Infinity, refetchInterval: (q) => !blocked && !update && ['UNKNOWN', 'SUBMITTED'].includes(q.state.data?.view?.action.status ?? '') ? 15000 : false });
  const current = update ?? previous.data; const view = current?.view; const binding = view?.binding; const available = assetSourceOpen(state?.source_validation_status);
  const positions = state?.positions.filter((position) => position.status === 'HELD' && position.accrued_yield_cents === 0 && position.maturity_at !== null && Date.parse(position.maturity_at) > Date.parse(state.server_as_of)) ?? [];
  const position = positions.find((p) => p.position_id === positionId) ?? (positions.length === 1 ? positions[0] : undefined);
  const hasCurrentPermission = (goal: string | null | undefined) => state?.policies.some((policy) => policy.source_kind === 'MVP_POLICY' && policy.template_name === 'AssetAuthorizationPolicy' && policy.planning_confirmation_valid && ['ACTIVE', 'CONFIRMED'].includes(policy.effective_status) && policy.configuration.allow_early_withdrawal_with_penalty === true && (goal === null ? policy.configuration.scope === 'general_idle_funds' && policy.configuration.goal_id === null : policy.configuration.scope === 'goal' && policy.configuration.goal_id === goal)) ?? false;
  const canConfirm = !hasRevision && !revisionUpdate && !!view && !current?.partial_preparation && available && hasCurrentPermission(view.action.effect.goal_id) && view.action.status === 'PLANNED' && view.action.receipt === null && view.action.bank_status === null && view.signed === null && Date.parse(view.action.as_of) < Math.min(Date.parse(view.binding.quote.expires_at), Date.parse(view.action.effect.expires_at));
  async function inspect() { if (blocked || working || !signed || !available || !position || !hasCurrentPermission(position.goal_id) || current?.view || current?.partial_preparation) return; setWorking(true); setError(''); try { setQuote(await runRead(() => quoteNextLoss(position.position_id, environment))); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  async function prepare() { if (blocked || working || !signed || !available || !position || !hasCurrentPermission(position.goal_id) || current?.view || current?.partial_preparation) return; setWorking(true); setError(''); try { const body = { expected_epoch_id: environment.epoch_id, position_id: position.position_id, client_request_id: crypto.randomUUID() }; const locator: LossRecovery = { protocol: 'zhiyu-next-loss-recovery-v1', user_id: environment.dashboard.user_id, prepare_request: body, action_id: null, reviewed_quote_hash: null, reviewed_effect_hash: null }; await perform('/zhiyu-next/assets/lossy/prepare', body, undefined, undefined, undefined, undefined, undefined, locator); setQuote(null); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  async function confirm() { if (blocked || working || !signed || !canConfirm || !current || !binding) return; setWorking(true); setError(''); try { const fresh = await runRead(() => getNextLoss(current.recovery, environment)); if (fresh.action.status !== 'PLANNED' || fresh.action.bank_status !== null || fresh.action.receipt !== null || fresh.signed !== null || fresh.binding.quote_hash !== binding.quote_hash || fresh.binding.effect_hash !== binding.effect_hash || Date.parse(fresh.action.as_of) >= Math.min(Date.parse(binding.quote.expires_at), Date.parse(fresh.action.effect.expires_at))) throw new Error('原报价或动作状态变化，请保留已审原件核实。'); await perform(`/zhiyu-next/assets/lossy/actions/${binding.action_id}/confirm-and-execute`, { expected_epoch_id: environment.epoch_id, reviewed_quote_hash: binding.quote_hash, reviewed_effect_hash: binding.effect_hash, accepted: true, client_request_id: crypto.randomUUID() }, undefined, undefined, undefined, undefined, undefined, current.recovery); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  const cost = binding?.quote ?? quote;
  return <section className="zy-card" aria-label="明确损失的提前支取"><h3>明确损失的提前支取</h3><p>仅支持原定期持仓的整笔本金报价；原购买权限和当前权限均须允许有损退出。零损失回收保护继续按原规则执行。</p>
    {(error || previous.isError) && <p role="alert" className="zy-message zy-error">{error || userError(previous.error)}</p>}
    <label className="zy-field" htmlFor="zyn-loss-position">核实原持仓<select id="zyn-loss-position" disabled={blocked || working || !!current?.view || !!current?.partial_preparation} value={position?.position_id ?? ''} onChange={(e) => { setPositionId(e.target.value); setQuote(null); }}><option value="">请选择</option>{positions.map((p) => <option key={p.position_id} value={p.position_id}>{businessText(p.product_name)} · 本金 {money(p.principal_cents)}</option>)}</select></label>
    {positions.length === 0 && !view && <p>当前没有本版可报价的未到期、未计提利息持仓。持仓投影不会替代服务器原报价。</p>}
    {position && !hasCurrentPermission(position.goal_id) && <p>当前原购买权限未明确允许有损退出；先审阅并确认独立原权限，不能用资产规划代替授权。</p>}
    <div className="zy-buttons"><button className="zy-secondary" disabled={blocked || working || !signed || !available || !position || !hasCurrentPermission(position.goal_id) || !!current?.view || !!current?.partial_preparation} onClick={() => void inspect()}>核实服务器提前支取报价</button><button className="zy-secondary" disabled={blocked || working || !signed || !available || !position || !hasCurrentPermission(position.goal_id) || !!current?.view || !!current?.partial_preparation} onClick={() => void prepare()}>保存可审阅支取原件</button></div><p className="zy-muted">保存原件仅准备动作；之后以实际固定原报价及完整必要后果一次确认。比较报价不能替换已审原件。</p>
    {cost && <section aria-label="提前支取必要后果"><h4>{binding ? '保留的原报价与完整后果' : '当前服务器本金报价'}</h4><dl className="zy-facts"><div><dt>支取原本金</dt><dd>{money(cost.principal_cents)}</dd></div><div><dt>费用</dt><dd>{money(cost.fee_cents)}</dd></div><div><dt>明确本金损失</dt><dd>{money(cost.loss_cents)}</dd></div><div><dt>净到账</dt><dd>{money(cost.net_cents)}</dd></div></dl><p>损失按本金计算并向上取整到分；本金可用时间 {cost.principal_available_at.replace('T', ' ').slice(0, 19)}，原报价有效至 {cost.expires_at.replace('T', ' ').slice(0, 19)}。</p><p>本版不支付已计提利息，不把未来放弃收益估算为零。{view ? `到账账户：${businessText(environment.dashboard.account_facts.facts.accounts.find((account) => account.id === view.action.effect.destination_account_id)?.name ?? '原兑付账户')}。` : ''}</p></section>}
    {recovering && !view && <p role="status">同一原支取请求正在核实；未找到原件或网络拒绝不能证明未受理，不会换请求。</p>}
    {current?.partial_preparation && <p role="status">原支取准备或动作已留存，绑定尚未完整。只能续接同一准备，不能确认或执行。</p>}
    {view?.action.receipt ? <p className="zy-result">原银行与实际回执已核实：支取本金 {money(view.action.receipt.executed_cents)}，费用 {money(view.action.receipt.fee_cents)}，损失 {money(view.action.receipt.loss_cents)}，原净到账 {money(view.action.effect.net_cents)}。</p> : view && <p>{['UNKNOWN', 'SUBMITTED'].includes(view.action.status) ? '原支取银行结果正在核实，原报价、动作和请求保持不变。' : view.signed ? '原明确同意已核实，尚无完成回执。' : '原件尚未确认，尚无完成回执。'}</p>}
    {canConfirm && <><p>确认后将按上述原本金损失和净到账，处理同一整笔持仓。</p><button className="zy-primary" disabled={blocked || working || !signed} onClick={() => void confirm()}>接受上述损失并支取原本金</button></>}
    {resumeOriginal && current?.resume_original && signed && available && <button className="zy-secondary" disabled={working} onClick={() => void resumeOriginal()}>{current.partial_preparation ? '续接同一原支取准备' : '继续核实同一原支取'}</button>}
    {retryOriginal && recovering && signed && <button className="zy-secondary" disabled={working} onClick={() => void retryOriginal()}>恢复会话后续接原支取请求</button>}
    <LossRevisionPanel environment={environment} state={state} blocked={blocked} signed={signed} old={current} oldQuote={quote} update={revisionUpdate} recovering={revisionRecovering} perform={perform} runRead={runRead} resumeOriginal={resumeRevisionOriginal} retryOriginal={retryOriginal} onPresence={() => setHasRevision(true)} />
    {!available && <p className="zy-muted">有损动作尚待本轮真实验收；当前不会生成或执行有损支取。</p>}
  </section>;
}
