import type { components } from '../../../../packages/contracts/schema';
import { request } from '../api/http';
import { spendingHash as hash, spendingCanonicalJson as canonical, spendingUUID as uuid, spendingDigest as digest } from '../api/spending-evidence';
import { releaseUUID5 } from '../api/goal-release-authorizations';
import { parseLocalActorSession, type LocalActorSession } from '../api/local-actor';
import { object } from '../features/policy-form';
import { parseAction, type Action } from '../zhiyu/api';
import type { NextState, OperationResult } from './api';
import { context } from './policies';
import { assetCheck as check, assetExact as exact } from './asset-recovery';
import { lossPath, parseLossPrepare, parseLossRecovery, type LossPrepare, type LossRecovery } from './loss-recovery';
import type { PendingOperation } from './operation';

type Quote = Required<components['schemas']['RecoveryQuote']>;
export type LossBinding = { protocol: 'lossy-early-redemption-v1'; user_id: string; epoch_id: string; action_id: string; source_request: LossPrepare; effect: Action['effect']; effect_hash: string; quote: Quote; quote_hash: string; quote_evidence_hash: string; loss_basis: 'principal_cents'; rounding: 'CEIL_CENT'; accrued_interest_cents: 0; foregone_interest_cents: null; interest_treatment: 'NO_ACCRUED_INTEREST_NO_YIELD_PAYMENT'; bank_authority: false };
export type SignedLoss = { protocol: 'lossy-early-redemption-v1'; user_id: string; epoch_id: string; action_id: string; original_request: { expected_epoch_id: string; reviewed_quote_hash: string; reviewed_effect_hash: string; accepted: true; client_request_id: string }; principal_at_acceptance: LocalActorSession['principal']; accepted_at: string; expires_at: string; bank_authority: false };
export type LossView = { binding: LossBinding; action: Action; signed: SignedLoss | null };
export type LossUpdate = { phase: 'PREPARE' | 'CONFIRM' | 'EXECUTE'; view: LossView | null; recovery: LossRecovery; partial_preparation: boolean; resume_original: boolean };
const protocol = 'lossy-early-redemption-v1', base = '/zhiyu-next/assets/lossy';
const time = (value: unknown): value is string => typeof value === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(value) && Number.isFinite(Date.parse(value));
const integer = (value: unknown): value is number => Number.isSafeInteger(value) && Number(value) >= 0;
const same = (left: unknown, right: unknown) => canonical(left) === canonical(right);
export async function parseLossQuote(value: unknown, environment: NextState, position: string): Promise<Quote> {
  check(object(value) && exact(value, ['evidence_ids', 'quote_id', 'user_id', 'position_id', 'product_id', 'product_version_number', 'terms_digest', 'kind', 'principal_cents', 'fee_cents', 'loss_cents', 'net_cents', 'request_at', 'principal_available_at', 'expires_at']) && value.user_id === environment.dashboard.user_id && value.position_id === position && uuid(value.product_id) && digest(value.terms_digest) && integer(value.product_version_number) && value.product_version_number > 0 && value.kind === 'EARLY_WITHDRAW' && integer(value.principal_cents) && value.principal_cents > 0 && value.fee_cents === 0 && integer(value.loss_cents) && value.loss_cents > 0 && integer(value.net_cents) && value.net_cents === value.principal_cents - value.loss_cents && ['request_at', 'principal_available_at', 'expires_at'].every((key) => time(value[key])));
  check(time(value.request_at) && time(value.principal_available_at) && time(value.expires_at) && Date.parse(value.expires_at) - Date.parse(value.request_at) === 900000 && Date.parse(value.principal_available_at) >= Date.parse(value.request_at) && value.quote_id === await releaseUUID5(position, 'simulated-fixed-early-price-v1') && same(value.evidence_ids, [value.quote_id])); return value as Quote;
}
export async function quoteNextLoss(position: string, environment: NextState): Promise<Quote> {
  check(uuid(position)); const raw = await request(`${base}/positions/${position}/quote`, 'POST', { expected_epoch_id: environment.epoch_id }, (value) => { context(value, environment); check(object(value) && exact(value, ['simulation', 'variant', 'environment_id', 'epoch_id', 'quote', 'quote_hash', 'loss_basis', 'rounding', 'interest_treatment', 'bank_authority']) && value.loss_basis === 'principal_cents' && value.rounding === 'CEIL_CENT' && value.interest_treatment === 'NO_ACCRUED_INTEREST_NO_YIELD_PAYMENT' && value.bank_authority === false); return value; }); const quote = await parseLossQuote(raw.quote, environment, position); check(raw.quote_hash === await hash(quote)); return quote;
}
export async function strictLossAction(value: unknown, environment: NextState): Promise<Action> {
  check(object(value) && exact(value, ['simulation', 'user_id', 'action_id', 'decision_run_id', 'status', 'autonomy_level', 'effect', 'effect_hash', 'prepared_at', 'as_of', 'prepared_validation', 'bank_status', 'receipt'])); const action = parseAction(value); const effect = action.effect;
  check(action.user_id === environment.dashboard.user_id && uuid(action.decision_run_id) && action.autonomy_level === 'ASK_ONCE' && ['PLANNED', 'AUTHORIZED', 'SUBMITTED', 'UNKNOWN', 'SUCCEEDED', 'RECONCILED', 'FAILED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'INVALIDATED', 'BLOCKED'].includes(action.status) && (action.bank_status === null || ['ACCEPTED', 'PENDING', 'SETTLED', 'UNKNOWN', 'REJECTED'].includes(action.bank_status ?? '')) && time(action.as_of) && time(action.prepared_at) && Date.parse(action.as_of) >= Date.parse(action.prepared_at) && object(effect) && exact(effect as unknown as Record<string, unknown>, ['simulation', 'operation_id', 'user_id', 'business_key', 'action_type', 'amount_cents', 'cash_uses', 'income_uses', 'destination_account_id', 'goal_id', 'policy_id', 'policy_version_id', 'policy_version_ids', 'liability', 'payee_id', 'payee_evidence_id', 'product_id', 'product_version_number', 'terms_digest', 'position_id', 'position_account_id', 'return_account_id', 'purchase_exit', 'original_policy_version_id', 'fee_cents', 'loss_cents', 'net_cents', 'quote_id', 'settlement_delay_days', 'latest_arrival_at', 'valid_from', 'expires_at']));
  check(effect.action_type === 'REDEEM_ASSET' && typeof effect.business_key === 'string' && effect.business_key === `redeem:${effect.position_id}` && ['position_id', 'position_account_id', 'product_id', 'policy_id', 'policy_version_id', 'original_policy_version_id', 'destination_account_id', 'quote_id'].every((key) => uuid((effect as unknown as Record<string, unknown>)[key])) && (effect.goal_id === null || uuid(effect.goal_id)) && effect.liability === null && effect.payee_id === null && effect.payee_evidence_id === null && effect.purchase_exit === null && effect.return_account_id === null && same(effect.cash_uses, []) && same(effect.income_uses, []) && Array.isArray(effect.policy_version_ids) && effect.policy_version_ids.length > 0 && effect.policy_version_ids.every(uuid) && new Set(effect.policy_version_ids).size === effect.policy_version_ids.length && effect.policy_version_ids.includes(effect.policy_version_id!) && integer(effect.settlement_delay_days));
  check(action.effect_hash === await hash({ ...effect, cash_uses: [], income_uses: [], policy_version_ids: [...effect.policy_version_ids!].sort() }));
  if (action.receipt !== null) { const receipt = action.receipt; check(receipt && object(receipt) && exact(receipt as unknown as Record<string, unknown>, ['simulation', 'receipt_id', 'action_id', 'bank_operation_id', 'status', 'executed_cents', 'fee_cents', 'loss_cents', 'posting_ids', 'occurred_at', 'reconciled_at'])); check(['SUCCEEDED', 'RECONCILED'].includes(action.status) && action.bank_status === 'SETTLED' && receipt.status === 'SUCCEEDED' && receipt.executed_cents === effect.amount_cents && receipt.fee_cents === effect.fee_cents && receipt.loss_cents === effect.loss_cents && Array.isArray(receipt.posting_ids) && receipt.posting_ids.length >= 3 && receipt.posting_ids.every(uuid) && new Set(receipt.posting_ids).size === receipt.posting_ids.length && time(receipt.occurred_at) && Date.parse(receipt.occurred_at) >= Date.parse(effect.valid_from) && Date.parse(receipt.occurred_at) <= Date.parse(action.as_of) && (receipt.reconciled_at === null || time(receipt.reconciled_at) && Date.parse(receipt.reconciled_at) >= Date.parse(receipt.occurred_at) && Date.parse(receipt.reconciled_at) <= Date.parse(action.as_of))); }
  if (['SUCCEEDED', 'RECONCILED'].includes(action.status)) check(action.receipt !== null && action.bank_status === 'SETTLED'); return action;
}
export async function parseLossView(value: unknown, environment: NextState, recovery: LossRecovery): Promise<LossView> {
  context(value, environment); check(object(value) && value.protocol === protocol && value.bank_authority === false && value.replacement_allowed === false);
  const action = await strictLossAction(value.action, environment); const binding = value.binding;
  check(object(binding) && exact(binding, ['protocol', 'user_id', 'epoch_id', 'action_id', 'source_request', 'effect', 'effect_hash', 'quote', 'quote_hash', 'quote_evidence_hash', 'loss_basis', 'rounding', 'accrued_interest_cents', 'foregone_interest_cents', 'interest_treatment', 'bank_authority']) && binding.protocol === protocol && binding.user_id === recovery.user_id && binding.epoch_id === environment.epoch_id && binding.action_id === action.action_id && same(binding.source_request, recovery.prepare_request) && same(binding.effect, action.effect) && binding.effect_hash === action.effect_hash && digest(binding.quote_evidence_hash) && binding.loss_basis === 'principal_cents' && binding.rounding === 'CEIL_CENT' && binding.accrued_interest_cents === 0 && binding.foregone_interest_cents === null && binding.interest_treatment === 'NO_ACCRUED_INTEREST_NO_YIELD_PAYMENT' && binding.bank_authority === false);
  const quote = await parseLossQuote(binding.quote, environment, recovery.prepare_request.position_id); const effect = action.effect;
  check(binding.quote_hash === await hash(quote) && effect.position_id === quote.position_id && effect.product_id === quote.product_id && effect.product_version_number === quote.product_version_number && effect.terms_digest === quote.terms_digest && effect.quote_id === quote.quote_id && effect.amount_cents === quote.principal_cents && effect.fee_cents === quote.fee_cents && effect.loss_cents === quote.loss_cents && effect.net_cents === quote.net_cents && Date.parse(effect.valid_from) >= Date.parse(quote.request_at) && Date.parse(action.prepared_at) >= Date.parse(quote.request_at) && Date.parse(action.prepared_at) < Date.parse(quote.expires_at) && Date.parse(effect.expires_at) <= Date.parse(quote.expires_at) && Date.parse(effect.expires_at) > Date.parse(effect.valid_from) && time(effect.latest_arrival_at) && Date.parse(effect.latest_arrival_at) >= Date.parse(quote.principal_available_at));
  if (recovery.action_id !== null) check(action.action_id === recovery.action_id && binding.quote_hash === recovery.reviewed_quote_hash && binding.effect_hash === recovery.reviewed_effect_hash);
  const signed = value.original_signed_acceptance;
  if (signed !== null) {
    check(object(signed) && exact(signed, ['protocol', 'user_id', 'epoch_id', 'action_id', 'original_request', 'principal_at_acceptance', 'accepted_at', 'expires_at', 'bank_authority']) && signed.protocol === protocol && signed.user_id === action.user_id && signed.epoch_id === environment.epoch_id && signed.action_id === action.action_id && signed.bank_authority === false && time(signed.accepted_at) && time(signed.expires_at));
    const body = signed.original_request; check(object(body) && exact(body, ['expected_epoch_id', 'reviewed_quote_hash', 'reviewed_effect_hash', 'accepted', 'client_request_id']) && body.expected_epoch_id === environment.epoch_id && body.reviewed_quote_hash === binding.quote_hash && body.reviewed_effect_hash === binding.effect_hash && body.accepted === true && uuid(body.client_request_id));
    const actor = parseLocalActorSession({ simulation: true, principal: signed.principal_at_acceptance, bank_authority: false, confirms_financial_action: false }).principal;
    check(actor.role === 'USER' && actor.user_id === action.user_id && Date.parse(actor.issued_at) <= Date.parse(signed.accepted_at) && Date.parse(signed.accepted_at) < Date.parse(actor.expires_at) && Date.parse(effect.valid_from) <= Date.parse(signed.accepted_at) && Date.parse(signed.accepted_at) <= Date.parse(action.as_of) && Date.parse(signed.expires_at) > Date.parse(signed.accepted_at) && Date.parse(signed.expires_at) <= Math.min(Date.parse(actor.expires_at), Date.parse(quote.expires_at), Date.parse(effect.expires_at)));
  }
  return { binding: binding as LossBinding, action, signed: signed as SignedLoss | null };
}
export async function getNextLoss(recovery: LossRecovery, environment: NextState): Promise<LossView> { check(uuid(recovery.action_id)); const raw = await request(`${base}/actions/${recovery.action_id}`, 'GET', undefined, (value) => { context(value, environment); check(object(value) && exact(value, ['simulation', 'variant', 'environment_id', 'epoch_id', 'protocol', 'binding', 'action', 'original_signed_acceptance', 'bank_authority', 'replacement_allowed'])); return value; }); return parseLossView(raw, environment, recovery); }
function lossUpdate(view: LossView, phase: LossUpdate['phase'], recovery: LossRecovery): LossUpdate {
  const accepted = ['SUBMITTED', 'UNKNOWN'].includes(view.action.status) && view.action.bank_status !== null && view.action.bank_status !== 'REJECTED';
  const unaccepted = ['PLANNED', 'AUTHORIZED'].includes(view.action.status) && view.action.bank_status === null && !!view.signed && Date.parse(view.action.as_of) < Date.parse(view.signed.expires_at);
  return { phase, view, recovery: { ...recovery, action_id: view.action.action_id, reviewed_quote_hash: view.binding.quote_hash, reviewed_effect_hash: view.binding.effect_hash }, partial_preparation: false, resume_original: !!view.signed && !view.action.receipt && (accepted || unaccepted) };
}
export async function validateLossOriginal(pending: PendingOperation, environment: NextState): Promise<void> {
  const recovery = parseLossRecovery(pending.loss_recovery, pending.path, pending.body, pending.epoch_id, pending.client_request_id); check(pending.environment_id === environment.environment_id && pending.epoch_id === environment.epoch_id && recovery.user_id === environment.dashboard.user_id);
  if (lossPath(pending.path)?.kind === 'PREPARE') return; const view = await getNextLoss(recovery, environment);
  if (pending.path.endsWith('/confirm-and-execute')) check(view.action.status === 'PLANNED' && view.signed === null && view.action.receipt === null && view.action.bank_status === null && Date.parse(view.action.as_of) < Math.min(Date.parse(view.binding.quote.expires_at), Date.parse(view.action.effect.expires_at)));
  else check(view.signed !== null && ['AUTHORIZED', 'SUBMITTED', 'UNKNOWN'].includes(view.action.status) && view.action.receipt === null);
}
export async function readLossOriginal(pending: PendingOperation, environment: NextState): Promise<OperationResult & { loss?: LossUpdate }> {
  const recovery = parseLossRecovery(pending.loss_recovery, pending.path, pending.body, pending.epoch_id, pending.client_request_id); check(pending.environment_id === environment.environment_id && pending.epoch_id === environment.epoch_id && recovery.user_id === environment.dashboard.user_id);
  const result: OperationResult & { loss?: LossUpdate } = { simulation: true, environment_id: pending.environment_id, epoch_id: pending.epoch_id, client_request_id: pending.client_request_id, status: 'PENDING' }; const phase = lossPath(pending.path)!.kind;
  let view: LossView;
  if (phase === 'PREPARE') {
    const raw = await request(`${base}/positions/${recovery.prepare_request.position_id}/requests/${recovery.prepare_request.client_request_id}`, 'GET', undefined, (value) => { context(value, environment); check(object(value) && value.protocol === protocol && value.replacement_allowed === false); return value; });
    if (raw.status === 'NOT_FOUND_NOT_FINAL' && raw.original_request === undefined) { check(exact(raw, ['simulation', 'variant', 'environment_id', 'epoch_id', 'protocol', 'status', 'replacement_allowed'])); return result; }
    const requestBody = raw.original_request; check(object(requestBody) && exact(requestBody, ['path', 'body']) && requestBody.path === `/api/v1${pending.path}` && same(requestBody.body, pending.body));
    if (raw.status !== 'RECORDED') {
      const partial = raw.status === 'PARTIAL_BINDING_NOT_FINAL'; check(['NOT_FOUND_NOT_FINAL', 'PARTIAL_BINDING_NOT_FINAL'].includes(String(raw.status)) && raw.bank_execute_allowed === false && exact(raw, ['simulation', 'variant', 'environment_id', 'epoch_id', 'protocol', 'original_request', 'replacement_allowed', 'status', 'bank_execute_allowed', ...(partial ? ['original_action'] : [])]));
      const action = partial ? await strictLossAction(raw.original_action, environment) : null; if (action) check(action.effect.position_id === recovery.prepare_request.position_id);
      result.loss = { phase, view: null, recovery, partial_preparation: true, resume_original: action === null || ['PLANNED', 'AUTHORIZED'].includes(action.status) && action.bank_status === null && action.receipt === null }; return result;
    }
    check(exact(raw, ['simulation', 'variant', 'environment_id', 'epoch_id', 'protocol', 'original_request', 'replacement_allowed', 'status', 'binding', 'action', 'original_signed_acceptance', 'bank_authority'])); view = await parseLossView(raw, environment, recovery);
  } else view = await getNextLoss(recovery, environment);
  if (phase === 'CONFIRM' && view.signed) check(same(view.signed.original_request, pending.body));
  result.loss = lossUpdate(view, phase, recovery);
  if (phase === 'PREPARE' || ['SUCCEEDED', 'RECONCILED'].includes(view.action.status) && view.action.bank_status === 'SETTLED' && view.action.receipt !== null && view.signed !== null) result.status = 'COMPLETED'; return result;
}
export function sameLossUpdate(update: LossUpdate | null, pending: PendingOperation): boolean { return !!update && !!pending.loss_recovery && update.recovery.user_id === pending.loss_recovery.user_id && same(update.recovery.prepare_request, pending.loss_recovery.prepare_request) && (pending.loss_recovery.action_id === null || pending.loss_recovery.action_id === update.recovery.action_id && pending.loss_recovery.reviewed_quote_hash === update.recovery.reviewed_quote_hash && pending.loss_recovery.reviewed_effect_hash === update.recovery.reviewed_effect_hash); }
const viewKey = (environment: NextState) => `zhiyu-next-loss-read-locator-v1:${environment.environment_id}:${environment.epoch_id}`;
export function rememberLossView(update: LossUpdate, environment: NextState): void { localStorage.setItem(viewKey(environment), JSON.stringify({ protocol: 'zhiyu-next-loss-read-locator-v1', environment_id: environment.environment_id, epoch_id: environment.epoch_id, user_id: environment.dashboard.user_id, prepare_request: update.recovery.prepare_request })); }
export async function readLossView(environment: NextState): Promise<LossUpdate | null> {
  const raw = localStorage.getItem(viewKey(environment)); if (raw === null) return null; const value: unknown = JSON.parse(raw); check(object(value) && exact(value, ['protocol', 'environment_id', 'epoch_id', 'user_id', 'prepare_request']) && value.protocol === 'zhiyu-next-loss-read-locator-v1' && value.environment_id === environment.environment_id && value.epoch_id === environment.epoch_id && value.user_id === environment.dashboard.user_id); const body = parseLossPrepare(value.prepare_request);
  const pending: PendingOperation = { protocol: 'zhiyu-next-original-v1', environment_id: environment.environment_id, epoch_id: environment.epoch_id, client_request_id: body.client_request_id, path: `${base}/prepare`, body, body_json: JSON.stringify(body), loss_recovery: { protocol: 'zhiyu-next-loss-recovery-v1', user_id: environment.dashboard.user_id, prepare_request: body, action_id: null, reviewed_quote_hash: null, reviewed_effect_hash: null } };
  return (await readLossOriginal(pending, environment)).loss ?? null;
}
