import type { components } from '../../../../packages/contracts/schema';
import { request } from '../api/http';
import { parseAssetPrepare, parseAssetPreview, type AssetPreview } from '../api/full-asset-execution';
import { parseLocalActorSession, type LocalActorSession } from '../api/local-actor';
import { multiConfigurationHash } from '../api/full-policy-change-multi';
import { releaseUUID5 } from '../api/goal-release-authorizations';
import { spendingCanonicalJson as canonical, spendingHash as hash, spendingDigest as digest, spendingUUID as uuid } from '../api/spending-evidence';
import { object } from '../features/policy-form';
import { assertMoneyFields } from '../features/money';
import type { NextState, OperationResult } from './api';
import { context } from './policies';
import { assetExact as exact } from './asset-recovery';
import { QUESTION_PREFIX, questionCheck as check, parseQuestionRecovery, parseQuestionStart, questionPath, type QuestionRecovery, type Mode } from './question-recovery';
import type { PendingOperation } from './operation';

export const QUESTION_PROTOCOL = 'zhiyu-full-asset-mode-question-v1';
const time = (v: unknown): v is string => typeof v === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(v) && Number.isFinite(Date.parse(v));
const strings = (v: unknown): v is string[] => Array.isArray(v) && v.every((x) => typeof x === 'string');
type Facts = components['schemas']['AutonomyFacts']; type Decision = components['schemas']['AutonomyDecision'];
export type ModeWorld = { mode: Mode; status: 'KNOWN' | 'UNKNOWN'; native_preview: AssetPreview; ordered_children: { batch_number: number; facts: Facts; decision: Decision }[]; native_whole_check: { remaining_batch_numbers: number[]; remaining_purchase_cents: number; original_boundary_hash: string; full_protection_hash: string; checked_point_count: number } | null; permission_boundary: Record<string, unknown>; reasons: string[]; vector_signature: string | null; bank_authority: false; old_confirmation_inherited: false };
export type ModeEvaluation = { protocol: typeof QUESTION_PROTOCOL; worlds: ModeWorld[]; selected_mode: Mode | null; status: 'STABLE' | 'DIVERGENT' | 'UNKNOWN'; stable: boolean | null; should_ask: boolean | null; partitions: { choice_key: Mode; world_keys: string[]; signatures: string[]; residual_signature_count: number }[]; bank_authority: false; execution_eligible: false; old_confirmation_inherited: false; requires_separate_whole_financial_confirmation: true };
export type ModeReceipt = { protocol: typeof QUESTION_PROTOCOL; user_id: string; epoch_id: string; session_id: string; revision: number; previous_receipt_hash: string | null; command_id: string; command_kind: 'START' | 'ANSWER' | 'REFRESH' | 'REBASE' | 'CLOSE'; authenticated_actor: LocalActorSession['principal']; original_request: { kind: string; path: string; body: Record<string, unknown> }; as_of: string; valid_until: string; source_manifest: Record<string, unknown>; source_fingerprint: string; evaluation: ModeEvaluation; state: 'PENDING_ANSWER' | 'READY_FOR_REVIEW' | 'UNKNOWN' | 'CLOSED'; question_id: string | null; answer_applied: boolean; receipt_hash: string; bank_authority: false; old_confirmation_inherited: false };
export type QuestionView = { receipt: ModeReceipt; effective_state: ModeReceipt['state'] | 'ARCHIVED' | 'STALE_RECOMPUTATION_REQUIRED'; current_source_fingerprint: string | null; evaluation: ModeEvaluation | null; current_error: { code: string; message: string } | null; recovery: QuestionRecovery };
export type QuestionUpdate = QuestionView & { original_receipt: ModeReceipt };

async function parseWorld(v: unknown, environment: NextState, session: string): Promise<ModeWorld> {
  check(object(v) && exact(v, ['mode', 'status', 'native_preview', 'ordered_children', 'native_whole_check', 'permission_boundary', 'reasons', 'vector_signature', 'bank_authority', 'old_confirmation_inherited']) && ['PORTFOLIO', 'FIXED_LADDER'].includes(String(v.mode)) && ['KNOWN', 'UNKNOWN'].includes(String(v.status)) && v.bank_authority === false && v.old_confirmation_inherited === false && strings(v.reasons) && Array.isArray(v.ordered_children) && v.ordered_children.length <= 64 && object(v.native_preview));
  const body = parseAssetPrepare(v.native_preview.original_request); check(body.expected_epoch_id === environment.epoch_id && body.planning_mode === v.mode && uuid(body.goal_id) && uuid(body.expected_goal_policy_version_id) && body.idempotency_key === `x05-mode:${session.replaceAll('-', '')}`);
  const preview = await parseAssetPreview(v.native_preview, body, environment.dashboard.user_id); check(object(v.permission_boundary));
  const permission = v.permission_boundary; check(exact(permission, ['full_policy_id', 'full_policy_version_id', 'full_policy_content_hash', 'full_configuration', 'mvp_asset_policy_id', 'mvp_asset_policy_version_id', 'mvp_configuration_hash', 'goal_id', 'goal_policy_version_id', 'whole_confirmation_required', 'old_confirmation_inherited', 'bank_authority', 'cross_operation_atomicity']) && permission.full_policy_id === body.full_policy_id && permission.full_policy_version_id === body.expected_full_policy_version_id && permission.mvp_asset_policy_id === body.mvp_asset_policy_id && permission.mvp_asset_policy_version_id === body.expected_mvp_policy_version_id && permission.goal_id === body.goal_id && permission.goal_policy_version_id === body.expected_goal_policy_version_id && permission.whole_confirmation_required === true && permission.old_confirmation_inherited === false && permission.bank_authority === false && permission.cross_operation_atomicity === 'NOT_AVAILABLE' && digest(permission.full_policy_content_hash) && object(permission.full_configuration) && await hash(permission.full_configuration) === permission.full_policy_content_hash);
  check(permission.full_configuration.scope === 'goal' && permission.full_configuration.goal_id === body.goal_id);
  if (preview.portfolio) check(permission.full_policy_content_hash === preview.portfolio.full_policy_content_hash && permission.mvp_configuration_hash === preview.portfolio.original_mvp_configuration_hash);
  else check(permission.mvp_configuration_hash === null);
  for (const [i, c] of v.ordered_children.entries()) {
    check(object(c) && exact(c, ['batch_number', 'facts', 'decision']) && c.batch_number === i + 1 && object(c.facts) && object(c.decision)); const f = c.facts, d = c.decision;
    check(exact(f, ['user_id', 'as_of', 'action_type', 'initiation', 'authority', 'effect', 'validation', 'payee', 'source_evidence_ids', 'source_issues', 'hard_block_reasons', 'confirmation_reasons', 'confirmation', 'source_context_hash']) && f.user_id === environment.dashboard.user_id && f.as_of === preview.as_of && f.action_type === 'PURCHASE_ASSET' && f.confirmation === null && object(f.authority) && object(f.payee) && Array.isArray(f.source_evidence_ids) && f.source_evidence_ids.every(uuid) && new Set(f.source_evidence_ids).size === f.source_evidence_ids.length && Array.isArray(f.source_issues) && strings(f.hard_block_reasons) && strings(f.confirmation_reasons));
    check(exact(d, ['algorithm_version', 'simulation', 'evaluation_only', 'level', 'execution_eligible', 'financial_evaluation', 'reasons', 'confirmation_required', 'confirmation_satisfied', 'effect_hash', 'economic_signature', 'uncertainty_status', 'candidate_signatures']) && d.simulation === true && d.evaluation_only === true && d.confirmation_satisfied === false && strings(d.reasons) && ['AUTO_EXECUTE', 'ASK_ONCE', 'ADVISE_ONLY', 'BLOCKED'].includes(String(d.level)) && typeof d.execution_eligible === 'boolean' && typeof d.confirmation_required === 'boolean');
    const batch = preview.portfolio?.batches[i]; check(batch && canonical(f.effect) === canonical(batch.command.effect));
    if (v.status === 'KNOWN') check(f.authority.status === 'AUTHORIZED' && f.source_evidence_ids.length > 0 && f.source_issues.length === 0 && object(f.validation) && ['READY', 'CONFIRMATION_REQUIRED'].includes(String(f.validation.status)) && f.validation.effect_hash === batch.command.effect_hash && d.financial_evaluation === 'VERIFIED');
  }
  if (v.native_whole_check !== null) check(object(v.native_whole_check) && exact(v.native_whole_check, ['remaining_batch_numbers', 'remaining_purchase_cents', 'original_boundary_hash', 'full_protection_hash', 'checked_point_count']) && digest(v.native_whole_check.original_boundary_hash) && digest(v.native_whole_check.full_protection_hash) && Number.isSafeInteger(v.native_whole_check.remaining_purchase_cents) && Array.isArray(v.native_whole_check.remaining_batch_numbers));
  if (v.status === 'UNKNOWN') check(v.vector_signature === null);
  else check(preview.state === 'READY_TO_REVIEW' && preview.portfolio && v.reasons.length === 0 && digest(v.vector_signature) && v.ordered_children.length === preview.portfolio.batches.length && object(v.native_whole_check) && v.native_whole_check.checked_point_count === 1098 && v.native_whole_check.remaining_purchase_cents === preview.portfolio.total_purchase_cents && canonical(v.native_whole_check.remaining_batch_numbers) === canonical(preview.portfolio.batches.map((b) => b.batch_number)));
  return v as ModeWorld;
}
export async function parseModeEvaluation(v: unknown, environment: NextState, session: string): Promise<ModeEvaluation> {
  check(object(v) && exact(v, ['protocol', 'worlds', 'selected_mode', 'status', 'stable', 'should_ask', 'partitions', 'bank_authority', 'execution_eligible', 'old_confirmation_inherited', 'requires_separate_whole_financial_confirmation']) && v.protocol === QUESTION_PROTOCOL && v.bank_authority === false && v.execution_eligible === false && v.old_confirmation_inherited === false && v.requires_separate_whole_financial_confirmation === true && Array.isArray(v.worlds) && v.worlds.length === 2 && Array.isArray(v.partitions) && (v.selected_mode === null || ['PORTFOLIO', 'FIXED_LADDER'].includes(String(v.selected_mode))));
  const worlds = await Promise.all(v.worlds.map((w) => parseWorld(w, environment, session))); check(worlds[0]!.mode === 'PORTFOLIO' && worlds[1]!.mode === 'FIXED_LADDER');
  const firstRequest = worlds[0]!.native_preview.original_request; const secondRequest = worlds[1]!.native_preview.original_request;
  check(canonical({ ...firstRequest, planning_mode: null }) === canonical({ ...secondRequest, planning_mode: null }));
  // Validate the server outcome; never turn UI equality or a preference into financial permission.
  if (v.status === 'UNKNOWN') check(worlds.some((w) => w.status === 'UNKNOWN') && v.stable === null && v.should_ask === null && v.partitions.length === 0);
  else { check(['STABLE', 'DIVERGENT'].includes(String(v.status)) && worlds.every((w) => w.status === 'KNOWN') && v.stable === (v.status === 'STABLE') && v.should_ask === (v.status === 'DIVERGENT') && v.partitions.length === 2); check(v.status === (v.selected_mode !== null || worlds[0]!.vector_signature === worlds[1]!.vector_signature ? 'STABLE' : 'DIVERGENT')); for (const [i, p] of v.partitions.entries()) check(object(p) && exact(p, ['choice_key', 'world_keys', 'signatures', 'residual_signature_count']) && p.choice_key === worlds[i]!.mode && canonical(p.world_keys) === canonical([await hash({ asset_mode: worlds[i]!.mode })]) && canonical(p.signatures) === canonical([worlds[i]!.vector_signature]) && p.residual_signature_count === 1); }
  return v as ModeEvaluation;
}
export async function parseModeReceipt(v: unknown, environment: NextState, expectedSession?: string): Promise<ModeReceipt> {
  check(object(v) && exact(v, ['protocol', 'user_id', 'epoch_id', 'session_id', 'revision', 'previous_receipt_hash', 'command_id', 'command_kind', 'authenticated_actor', 'original_request', 'as_of', 'valid_until', 'source_manifest', 'source_fingerprint', 'evaluation', 'state', 'question_id', 'answer_applied', 'receipt_hash', 'bank_authority', 'old_confirmation_inherited']) && v.protocol === QUESTION_PROTOCOL && v.user_id === environment.dashboard.user_id && v.epoch_id === environment.epoch_id && uuid(v.session_id) && (!expectedSession || v.session_id === expectedSession) && uuid(v.command_id) && Number.isSafeInteger(v.revision) && Number(v.revision) >= 1 && Number(v.revision) <= 17 && (v.previous_receipt_hash === null || digest(v.previous_receipt_hash)) && time(v.as_of) && time(v.valid_until) && v.bank_authority === false && v.old_confirmation_inherited === false && typeof v.answer_applied === 'boolean' && object(v.source_manifest) && digest(v.source_fingerprint) && await multiConfigurationHash(v.source_manifest) === v.source_fingerprint && digest(v.receipt_hash));
  const { receipt_hash: _digest, ...unhashed } = v; void _digest; check(await multiConfigurationHash(unhashed) === v.receipt_hash);
  const actor = parseLocalActorSession({ simulation: true, principal: v.authenticated_actor, bank_authority: false, confirms_financial_action: false }).principal; check(actor.role === 'USER' && actor.user_id === v.user_id && Date.parse(actor.issued_at) <= Date.parse(v.as_of) && Date.parse(v.as_of) < Date.parse(actor.expires_at));
  check(object(v.original_request) && exact(v.original_request, ['kind', 'path', 'body']) && typeof v.original_request.path === 'string' && object(v.original_request.body)); const info = questionPath(v.original_request.path.replace(/^\/api\/v1/, '')); check(info && v.original_request.kind === `FULL_ASSET_MODE_${info.kind}` && v.original_request.body.expected_epoch_id === v.epoch_id && v.original_request.body.client_request_id === v.command_id && (info.session_id === null || info.session_id === v.session_id));
  if (v.command_kind === 'START') { const b = parseQuestionStart(v.original_request.body); check(info.kind === 'START' && v.revision === 1 && v.previous_receipt_hash === null && v.session_id === await releaseUUID5('7812e5f0-f26d-44aa-b9ce-45dc1fe6a55c', `${v.user_id}:${v.epoch_id}:${b.client_request_id}`)); }
  else { const b = v.original_request.body; check(['ANSWER', 'REFRESH', 'REBASE', 'CLOSE'].includes(String(v.command_kind)) && exact(b, ['expected_epoch_id', 'client_request_id', 'expected_revision', ...(info.kind === 'ANSWER' ? ['question_id', 'mode'] : [])]) && Number.isSafeInteger(b.expected_revision) && Number(b.expected_revision) >= 1 && Number(b.expected_revision) <= 16 && Number(v.revision) === Number(b.expected_revision) + 1 && digest(v.previous_receipt_hash) && (v.command_kind === 'REBASE' ? ['ANSWER', 'REFRESH'].includes(info.kind) : v.command_kind === info.kind)); if (info.kind === 'ANSWER') check(uuid(b.question_id) && ['PORTFOLIO', 'FIXED_LADDER'].includes(String(b.mode))); }
  const evaluation = await parseModeEvaluation(v.evaluation, environment, v.session_id);
  const declaredBody = v.original_request.body;
  if (info.kind === 'START') check(evaluation.worlds.every((w) => w.native_preview.original_request.full_policy_id === declaredBody.full_policy_id && w.native_preview.original_request.expected_full_policy_version_id === declaredBody.expected_full_policy_version_id));
  if (v.state === 'CLOSED') check(v.command_kind === 'CLOSE' && v.question_id === null && !v.answer_applied);
  else { check(Date.parse(v.as_of) < Date.parse(v.valid_until) && Date.parse(v.valid_until) <= Date.parse(v.as_of) + 900000 && v.state === (evaluation.status === 'UNKNOWN' ? 'UNKNOWN' : evaluation.should_ask ? 'PENDING_ANSWER' : 'READY_FOR_REVIEW')); check(v.question_id === (v.state === 'PENDING_ANSWER' ? await releaseUUID5(v.session_id, `asset_mode:${v.revision}:${v.source_fingerprint}`) : null)); }
  check(!v.answer_applied || v.command_kind === 'ANSWER' && v.original_request.body.mode === evaluation.selected_mode); if (v.command_kind === 'REBASE') check(!v.answer_applied && evaluation.selected_mode === null);
  return v as ModeReceipt;
}
export async function getQuestionView(recovery: QuestionRecovery, environment: NextState): Promise<QuestionView> {
  check(uuid(recovery.session_id) && recovery.user_id === environment.dashboard.user_id && recovery.start_request.expected_epoch_id === environment.epoch_id);
  const v = await request(`${QUESTION_PREFIX}/sessions/${recovery.session_id}`, 'GET', undefined, (v) => { context(v, environment); return v; });
  const fields = ['simulation', 'variant', 'environment_id', 'epoch_id', 'protocol', 'current_revision', 'effective_state', 'current_source_fingerprint', 'current_evaluation', 'bank_authority', 'old_confirmation_inherited', 'current_read_required', 'receipt_is_current_authority', 'requires_separate_whole_financial_confirmation'];
  check(exact(v, [...fields, ...(v.current_read_error === undefined ? [] : ['current_read_error'])]) && v.protocol === QUESTION_PROTOCOL && v.bank_authority === false && v.old_confirmation_inherited === false && v.current_read_required === true && v.receipt_is_current_authority === false && v.requires_separate_whole_financial_confirmation === true);
  const receipt = await parseModeReceipt(v.current_revision, environment, recovery.session_id); check(['PENDING_ANSWER', 'READY_FOR_REVIEW', 'UNKNOWN', 'CLOSED', 'ARCHIVED', 'STALE_RECOMPUTATION_REQUIRED'].includes(String(v.effective_state)));
  check(receipt.evaluation.worlds.every((w) => w.native_preview.original_request.full_policy_id === recovery.start_request.full_policy_id));
  const evaluation = v.current_evaluation === null ? null : await parseModeEvaluation(v.current_evaluation, environment, recovery.session_id); check(v.current_source_fingerprint === null || digest(v.current_source_fingerprint));
  if (['PENDING_ANSWER', 'READY_FOR_REVIEW', 'UNKNOWN'].includes(String(v.effective_state))) check(v.effective_state === receipt.state && v.current_source_fingerprint === receipt.source_fingerprint && evaluation && evaluation.selected_mode === receipt.evaluation.selected_mode && evaluation.status === receipt.evaluation.status && evaluation.worlds.every((w) => Date.parse(w.native_preview.as_of) >= Date.parse(receipt.as_of) && Date.parse(w.native_preview.as_of) < Date.parse(receipt.valid_until)));
  if (['CLOSED', 'ARCHIVED'].includes(String(v.effective_state))) check(evaluation === null && v.current_source_fingerprint === null);
  if (v.current_read_error !== undefined) check(v.effective_state === 'STALE_RECOMPUTATION_REQUIRED' && object(v.current_read_error) && exact(v.current_read_error, ['code', 'message']) && typeof v.current_read_error.code === 'string' && typeof v.current_read_error.message === 'string');
  return { receipt, effective_state: v.effective_state as QuestionView['effective_state'], current_source_fingerprint: v.current_source_fingerprint as string | null, evaluation, current_error: v.current_read_error as QuestionView['current_error'] ?? null, recovery: { ...recovery, previous_receipt_hash: receipt.receipt_hash } };
}
export async function readQuestionOriginal(original: PendingOperation, environment: NextState): Promise<OperationResult & { question?: QuestionUpdate }> {
  const recovery = parseQuestionRecovery(original.question_recovery, original.path, original.body, original.epoch_id, original.client_request_id); check(recovery.user_id === environment.dashboard.user_id && original.environment_id === environment.environment_id && original.epoch_id === environment.epoch_id); const info = questionPath(original.path)!;
  const v = await request(`${QUESTION_PREFIX}/commands/${original.epoch_id}/by-key/${original.client_request_id}`, 'GET', undefined, (v) => { context(v, environment); return v; });
  check(exact(v, ['simulation', 'variant', 'environment_id', 'epoch_id', 'protocol', 'status', 'client_request_id', 'original_request', 'original_receipt', 'not_found_is_final', 'replacement_allowed', 'bank_authority', 'old_confirmation_inherited', 'current_read_required', 'receipt_is_current_authority']) && v.protocol === QUESTION_PROTOCOL && v.client_request_id === original.client_request_id && ['RECORDED', 'NOT_FOUND_NOT_FINAL'].includes(String(v.status)) && v.not_found_is_final === false && v.replacement_allowed === false && v.bank_authority === false && v.old_confirmation_inherited === false && v.current_read_required === true && v.receipt_is_current_authority === false);
  const result: OperationResult & { question?: QuestionUpdate } = { simulation: true, client_request_id: original.client_request_id, environment_id: original.environment_id, epoch_id: original.epoch_id, status: 'PENDING' };
  if (v.status === 'NOT_FOUND_NOT_FINAL') { check(v.original_request === null && v.original_receipt === null); return result; }
  const receipt = await parseModeReceipt(v.original_receipt, environment, recovery.session_id ?? undefined); check(canonical(v.original_request) === canonical(receipt.original_request) && receipt.original_request.path === `/api/v1${original.path}` && canonical(receipt.original_request.body) === canonical(original.body) && receipt.command_id === original.client_request_id && receipt.previous_receipt_hash === recovery.previous_receipt_hash);
  if (info.kind !== 'START') check(receipt.session_id === recovery.session_id && receipt.revision === Number(original.body.expected_revision) + 1);
  const current = await getQuestionView({ ...recovery, session_id: receipt.session_id }, environment); check(current.receipt.revision >= receipt.revision);
  result.question = { ...current, original_receipt: receipt }; result.status = 'COMPLETED'; return result;
}
const viewKey = (env: NextState) => `zhiyu-next-question-read-locator-v1:${env.environment_id}:${env.epoch_id}`;
export function rememberQuestionView(view: QuestionUpdate, environment: NextState) { check(view.receipt.user_id === environment.dashboard.user_id && view.receipt.epoch_id === environment.epoch_id); localStorage.setItem(viewKey(environment), JSON.stringify({ protocol: 'zhiyu-next-question-read-locator-v1', environment_id: environment.environment_id, epoch_id: environment.epoch_id, recovery: view.recovery })); }
export async function readQuestionView(environment: NextState): Promise<QuestionView | null> { const raw = localStorage.getItem(viewKey(environment)); if (!raw) return null; const v: unknown = JSON.parse(raw); check(object(v) && exact(v, ['protocol', 'environment_id', 'epoch_id', 'recovery']) && v.protocol === 'zhiyu-next-question-read-locator-v1' && v.environment_id === environment.environment_id && v.epoch_id === environment.epoch_id && object(v.recovery) && exact(v.recovery, ['protocol', 'user_id', 'start_request', 'session_id', 'previous_receipt_hash']) && v.recovery.protocol === 'zhiyu-next-question-recovery-v1' && uuid(v.recovery.session_id) && digest(v.recovery.previous_receipt_hash)); parseQuestionStart(v.recovery.start_request); assertMoneyFields(v.recovery); return getQuestionView(v.recovery as QuestionRecovery, environment); }
