import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { AssetPreview } from '../api/full-asset-execution';
import type { NextState } from './api';
import type { AssetsState } from './assets-state';
import { assetSourceOpen } from './assets-state';
import type { AssetPerform } from './AssetsPanel';
import type { MaturityUpdate } from './maturity';
import { readMaturityView } from './maturity';
import type { ReinvestmentRecovery } from './reinvestment-recovery';
import { getNextReinvestment, previewNextReinvestment, readReinvestmentView, receivedMaturityEvent, type ReinvestmentUpdate } from './reinvestments';
import { businessText, money, userError } from './display';

export default function ReinvestmentPanel({ environment, state, blocked, signed, maturity, update, recovering, perform, runRead, resumeOriginal, retryOriginal }: { environment: NextState; state?: AssetsState; blocked: boolean; signed: boolean; maturity: MaturityUpdate | null; update: ReinvestmentUpdate | null; recovering: boolean; perform: AssetPerform; runRead: <T>(work: () => Promise<T>) => Promise<T>; resumeOriginal?: () => Promise<void>; retryOriginal?: () => Promise<void> }) {
  const [fullId, setFullId] = useState(''); const [mvpId, setMvpId] = useState(''); const [mode, setMode] = useState<'PORTFOLIO' | 'FIXED_LADDER'>('PORTFOLIO'); const [preview, setPreview] = useState<AssetPreview | null>(null); const [error, setError] = useState(''); const [working, setWorking] = useState(false);
  const identity = [environment.environment_id, environment.epoch_id];
  const previous = useQuery({ queryKey: ['zhiyu-next-reinvestment-view', ...identity], queryFn: () => readReinvestmentView(environment), enabled: !blocked && !update, retry: false, staleTime: Infinity, refetchInterval: (q) => !blocked && !update && q.state.data?.view?.portfolio.state === 'UNRESOLVED' ? 15000 : false });
  const oldSource = useQuery({ queryKey: ['zhiyu-next-reinvestment-source', ...identity], queryFn: () => readMaturityView(environment), enabled: !blocked && !maturity && !update, retry: false, staleTime: Infinity });
  const current = update ?? previous.data; const source = current?.source ?? maturity?.action ?? oldSource.data?.action;
  const received = !!source?.service_receipt_verified && source.original_event.proof_status === 'VERIFIED' && source.original_event.service_receipt_verified; const event = source ? receivedMaturityEvent(source) : undefined;
  const matchesScope = (configuration: Record<string, unknown>) => event?.goal_id === null ? configuration.scope === 'general_idle_funds' && configuration.goal_id === null : configuration.scope === 'goal' && configuration.goal_id === event?.goal_id;
  const policies = state?.policies.filter((p) => p.template_name === 'AssetAuthorizationPolicy' && p.planning_confirmation_valid && ['ACTIVE', 'CONFIRMED'].includes(p.effective_status) && matchesScope(p.configuration)) ?? [];
  const fulls = policies.filter((p) => p.source_kind === 'FULL_POLICY'); const mvps = policies.filter((p) => p.source_kind === 'MVP_POLICY');
  const full = fulls.find((p) => p.policy_id === fullId) ?? (fulls.length === 1 ? fulls[0] : undefined); const mvp = mvps.find((p) => p.policy_id === mvpId) ?? (mvps.length === 1 ? mvps[0] : undefined); const goal = event?.goal_id ? environment.goals.find((g) => g.id === event.goal_id) : null;
  const scopeAvailable = received && !!full && !!mvp && (event?.goal_id === null || !!goal); const available = assetSourceOpen(state?.source_validation_status); const response = current?.view?.portfolio; const p = response?.original_portfolio;
  const liveScope = p && fulls.some((row) => row.policy_id === p.original_request.full_policy_id && row.current_version_id === p.original_request.expected_full_policy_version_id && row.configuration_hash === p.full_policy_content_hash) && mvps.some((row) => row.policy_id === p.original_request.mvp_asset_policy_id && row.current_version_id === p.original_request.expected_mvp_policy_version_id) && (event?.goal_id === null || goal?.policy_version_id === p.original_request.expected_goal_policy_version_id);
  const canConfirm = !!p && !!liveScope && available && !current?.partial_preparation && response?.state === 'PREPARED_UNRESERVED' && response.original_consent === null && current?.view?.signed === null && Date.parse(response.as_of) < Date.parse(p.expires_at);
  useEffect(() => { if (update) setPreview(null); }, [update]);
  function recovery(): ReinvestmentRecovery {
    if (!scopeAvailable || !source || !full || !mvp) throw new Error('先核实实际兑付回执及当前原用途范围。');
    return { protocol: 'zhiyu-next-reinvestment-recovery-v1', user_id: environment.dashboard.user_id, maturity_prepare_request: source.original_request, prepare_request: { expected_epoch_id: environment.epoch_id, maturity_action_id: source.action_id, full_policy_id: full.policy_id, expected_full_policy_version_id: full.current_version_id, mvp_asset_policy_id: mvp.policy_id, expected_mvp_policy_version_id: mvp.current_version_id, expected_goal_policy_version_id: goal?.policy_version_id ?? null, planning_mode: mode, client_request_id: crypto.randomUUID() }, portfolio_id: null, reviewed_portfolio_hash: null };
  }
  async function inspect() { if (blocked || working || !scopeAvailable) return; setWorking(true); setError(''); try { setPreview(await runRead(() => previewNextReinvestment(recovery(), environment))); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  async function prepare() { if (blocked || working || !signed || !available || !scopeAvailable || current?.view || current?.partial_preparation) return; setWorking(true); setError(''); try { const locator = recovery(); await perform('/zhiyu-next/assets/reinvestments/prepare', locator.prepare_request, undefined, undefined, undefined, undefined, locator); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  async function confirm() { if (blocked || working || !signed || !canConfirm || !current || !p) return; setWorking(true); setError(''); try { const fresh = await runRead(() => getNextReinvestment(current.recovery, environment)); if (fresh.partial_preparation || fresh.view?.portfolio.state !== 'PREPARED_UNRESERVED' || fresh.view.signed !== null || fresh.view.portfolio.original_consent !== null || fresh.recovery.reviewed_portfolio_hash !== p.portfolio_hash || Date.parse(fresh.view.portfolio.as_of) >= Date.parse(p.expires_at)) throw new Error('原再投安排已变化，请保留已审原件核实。'); await perform(`/zhiyu-next/assets/portfolios/${p.portfolio_id}/confirm-and-execute`, { expected_epoch_id: environment.epoch_id, reviewed_portfolio_hash: p.portfolio_hash, accepted: true, client_request_id: crypto.randomUUID() }, undefined, undefined, undefined, undefined, current.recovery); } catch (cause) { setError(userError(cause)); } finally { setWorking(false); } }
  return <section className="zy-card" aria-label="实际兑付后的再投"><h3>实际兑付后的再投</h3><p>只有原本金已实收并核实回执，才能按原用途重新规划。实收来源没有独占预留，每个批次仍会重检当前余额和保护。</p>
    {(error || previous.isError || oldSource.isError) && <p className="zy-message zy-error" role="alert">{error || userError(previous.error ?? oldSource.error)}</p>}
    {!received ? <p>当前尚无可核实的实际兑付回执；到期日期、预期收益和兑付准备均不能触发再投。</p> : <><p>实际原本金 {money(event!.principal_cents)} · 费用与损失均为零。用途：{goal ? businessText(goal.name) : '原通用闲置资金'}。来源：{businessText(environment.dashboard.account_facts.facts.accounts.find((account) => account.id === event!.destination_account_id)?.name ?? '原实收账户')}。</p>
      <label className="zy-field" htmlFor="zyn-reinvest-full">再投完整保护<select id="zyn-reinvest-full" disabled={blocked || working || !!current?.view || !!current?.partial_preparation} value={full?.policy_id ?? ''} onChange={(e) => { setFullId(e.target.value); setPreview(null); }}><option value="">请选择</option>{fulls.map((policy) => <option value={policy.policy_id} key={policy.policy_id}>{businessText(policy.name)}</option>)}</select></label>
      <label className="zy-field" htmlFor="zyn-reinvest-mvp">再投原购买范围<select id="zyn-reinvest-mvp" disabled={blocked || working || !!current?.view || !!current?.partial_preparation} value={mvp?.policy_id ?? ''} onChange={(e) => { setMvpId(e.target.value); setPreview(null); }}><option value="">请选择</option>{mvps.map((policy) => <option value={policy.policy_id} key={policy.policy_id}>{businessText(policy.name)}</option>)}</select></label>
      <label className="zy-field" htmlFor="zyn-reinvest-mode">再投偏好<select id="zyn-reinvest-mode" disabled={blocked || working || !!current?.view || !!current?.partial_preparation} value={mode} onChange={(e) => { setMode(e.target.value as typeof mode); setPreview(null); }}><option value="PORTFOLIO">有限产品组合</option><option value="FIXED_LADDER">分期到期定期阶梯</option></select></label>
      <div className="zy-buttons"><button className="zy-secondary" disabled={blocked || working || !scopeAvailable || !!current?.view || !!current?.partial_preparation} onClick={() => void inspect()}>比较实收后的规划</button><button className="zy-secondary" disabled={blocked || working || !signed || !available || !scopeAvailable || !!current?.view || !!current?.partial_preparation} onClick={() => void prepare()}>保存可审阅再投原件</button></div><p className="zy-muted">保存只准备原批次，尚未确认或购买；同一兑付来源始终续接原组合。</p>
    </>}
    {preview && <p>当前比较：{preview.state === 'READY_TO_REVIEW' ? `可规划 ${money(preview.portfolio?.total_purchase_cents)}` : preview.state === 'UNKNOWN' ? '来源待核实' : '当前保护阻止新购买'}。此比较不能代替已准备原件。{preview.reasons.map(businessText).join('；')}</p>}
    {recovering && !current?.view && <p role="status">正在核实同一再投原请求；未找到原件不表示拒绝，不会另建组合。</p>}
    {current?.partial_preparation && <p role="status">原准备或批次已留存，来源绑定尚未完整；只能续接同一准备，不能确认或执行。</p>}
    {p && response && <><h4>{current?.partial_preparation ? '尚未完整的原准备' : response.state === 'SERVICE_RECEIPTS_VERIFIED' ? '原再投回执已全部核实' : response.state === 'UNRESOLVED' ? '同一原再投结果正在核实' : '已保存的原再投安排'}</h4><strong className="zy-amount zy-amount-small">{money(p.total_purchase_cents)}</strong><p>共 {p.batches.length} 个原批次；整笔资金未预留，批次之间没有整体原子性。有效至 {p.expires_at.replace('T', ' ').slice(0, 19)}。</p><ol>{p.batches.map((batch, i) => { const effect = batch.command.effect; const product = state?.products.find((row) => row.product_id === effect.product_id && row.version_number === effect.product_version_number && row.terms_digest === effect.terms_digest); const action = response.batches[i]!.original_action; return <li key={batch.action_id}><strong>{businessText(product?.name ?? `第 ${i + 1} 项原产品`)} · {money(effect.amount_cents)}</strong><p>来自原实收账户，费用 {money(effect.fee_cents)}，损失 {money(effect.loss_cents)}；本金可用时间 {effect.purchase_exit?.principal_available_at?.slice(0, 10) ?? '待核实'}。</p><p>{action?.receipt ? `实际原购买回执 ${money(action.receipt.executed_cents)} 已核实。` : '尚无完成回执，未决批次会停止后续执行。'}</p></li>; })}</ol>{canConfirm && <button className="zy-primary" disabled={blocked || working || !signed} onClick={() => void confirm()}>确认并执行原再投</button>}</>}
    {resumeOriginal && current?.resume_original && signed && available && <button className="zy-secondary" disabled={working} onClick={() => void resumeOriginal()}>{current.partial_preparation ? '续接同一原再投准备' : '继续核实同一原再投'}</button>}
    {recovering && retryOriginal && signed && <button className="zy-secondary" disabled={working} onClick={() => void retryOriginal()}>恢复会话后续接原再投请求</button>}
    {!available && <p className="zy-muted">再投执行等待本轮资产真实验收，当前不会新增再投资金动作。</p>}
  </section>;
}
