import { request, ApiError } from '../api/http';
import { parseLocalActorSession, type LocalActorSession } from '../api/local-actor';
import { parseFullGoalModel } from '../api/full-goals';
import { multiConfigurationHash as sourceHash } from '../api/full-policy-change-multi';
import { releaseUUID5 } from '../api/goal-release-authorizations';
import { spendingHash as hash, spendingCanonicalJson as canonical, spendingDigest as digest, spendingUUID as uuid } from '../api/spending-evidence';
import { object } from '../features/policy-form';
import { assertMoneyFields } from '../features/money';
import { readAction, type Action } from '../zhiyu/api';
import { assetExact as exact } from './asset-recovery';
import { context, safeConfiguration } from './policies';
import type { NextState, OperationResult } from './api';
import type { PendingOperation } from './operation';
import { STANDING_PREFIX, standingFamilies, standingPath, standingCheck as check, standingIds as ids, parseStandingCandidateRequest, parseStandingRecovery, type StandingFamily, type StandingCandidateRequest, type StandingRecovery } from './standing-recovery';

const identity = ['simulation', 'variant', 'environment_id', 'epoch_id'];
const time = (v: unknown): v is string => typeof v === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(v) && Number.isFinite(Date.parse(v));
const integer = (v: unknown, min = 0, max = Number.MAX_SAFE_INTEGER): v is number => Number.isSafeInteger(v) && Number(v) >= min && Number(v) <= max;
const strings = (v: unknown, max: number): v is string[] => Array.isArray(v) && v.length <= max && v.every((x) => typeof x === 'string' && !!x.trim());
const same = (a: unknown, b: unknown) => canonical(a) === canonical(b);
const sameIds = (a: string[], b: string[]) => same([...a].sort(), [...b].sort());
type Actor = LocalActorSession['principal'];
export type StandingScope = { protocol: 'zhiyu-next-standing-scope-v1'; simulation: true; user_id: string; epoch_id: string; family: StandingFamily; policy_version_ids: string[]; source_account_ids: string[]; goal_ids: string[]; product_ids: string[]; payee_id: string | null; per_action_cap_cents: number; per_event_cap_cents: number; daily_cap_cents: number; maximum_children: number; maximum_principal_unavailable_days: number; maximum_risk_level: number; asset_classes: string[]; max_fee_cents: 0; max_loss_cents: 0; cross_goal_release: false; requires_verified_complete_worlds: true; requires_current_native_guard: true; issued_at: string; expires_at: string };
export type StandingIncomeGoalScope = { protocol: 'zhiyu-next-standing-income-goal-scope-v2'; goal_mode: 'CUMULATIVE_EVENT_TARGET'; native_scope: StandingScope };
export type StandingReviewedScope = StandingScope | StandingIncomeGoalScope;
export type StandingIncomeGoalVariant = { native_protocol: 'zhiyu-standing-income-goal-native-v1'; goal_mode: 'CUMULATIVE_EVENT_TARGET'; source_validation_status: 'DEVELOPMENT_PENDING_ACTUAL_VARIANT_ACCEPTANCE' | 'VERIFIED_ACTUAL_VARIANT_ACCEPTANCE'; candidate_selection_available: boolean; worker_execution_status: 'REQUIRES_EXPLICIT_REVIEWED_SOURCE_PIN' };
export const standingIncomeGoalAvailable = (variant: StandingIncomeGoalVariant | undefined) => variant?.source_validation_status === 'VERIFIED_ACTUAL_VARIANT_ACCEPTANCE' && variant.candidate_selection_available === true;
export function parseStandingIncomeGoalVariant(v: unknown): StandingIncomeGoalVariant { check(object(v) && exact(v, ['native_protocol', 'goal_mode', 'source_validation_status', 'candidate_selection_available', 'worker_execution_status']) && v.native_protocol === 'zhiyu-standing-income-goal-native-v1' && v.goal_mode === 'CUMULATIVE_EVENT_TARGET' && ['DEVELOPMENT_PENDING_ACTUAL_VARIANT_ACCEPTANCE', 'VERIFIED_ACTUAL_VARIANT_ACCEPTANCE'].includes(String(v.source_validation_status)) && typeof v.candidate_selection_available === 'boolean' && v.worker_execution_status === 'REQUIRES_EXPLICIT_REVIEWED_SOURCE_PIN'); return v as StandingIncomeGoalVariant; }
export type StandingGrant<S extends StandingReviewedScope = StandingReviewedScope> = { protocol: 'zhiyu-next-signed-standing-grant-v1' | 'zhiyu-next-signed-income-goal-grant-v2'; grant_id: string; scope: S; reviewed_scope_hash: string; actor_at_confirmation: Actor; confirmed_at: string; accepted: true; native_bank_authority: false };
export type StandingControl = { protocol: 'zhiyu-next-standing-control-v1'; grant_id: string; revision: number; expected_previous_revision: number; state: 'ACTIVE' | 'PAUSED' | 'REVOKED'; previous_record_hash: string | null; client_request_id: string; actor: Actor; recorded_at: string; accepted: true };
export type StandingSource = { protocol: 'zhiyu-next-standing-source-v1'; environment_id: string; user_id: string; epoch_id: string; source_kind: 'SETTLED_INCOME' | 'CURRENT_POLICY_VERSION' | 'SERVER_PERIOD' | 'SETTLED_MATURITY_RECEIPT' | 'ORIGINAL_ACTION_SETTLED' | 'CURRENT_QUESTION_ANSWER'; original_source_id: string; original_source_version: string; original_source_hash: string };
export type StandingRun = { protocol: 'zhiyu-next-standing-run-v1'; source: StandingSource; revision: number; previous_record_hash: string | null; state: 'OBSERVED' | 'WAITING_INFORMATION' | 'WAITING_CONFIRMATION' | 'NO_ACTION' | 'ACCEPTED' | 'UNKNOWN' | 'SETTLED' | 'CANCELLED_BEFORE_ACCEPTANCE'; recorded_at: string; grant_id: string | null; grant_hash: string | null; control_revision_at_acceptance: number | null; whole_plan_hash: string | null; original_action_ids: string[]; original_effect_hashes: string[]; original_bank_keys: string[]; accepted_total_cents: number; accounting_day: string | null; original_receipt_ids: string[]; reasons: string[]; executor_role: 'SYSTEM'; old_one_shot_user_consent_inherited: false };
export type StandingView<S extends StandingReviewedScope = StandingReviewedScope> = { grant: StandingGrant<S>; control: StandingControl; effective_state: 'ACTIVE' | 'PAUSED' | 'REVOKED' | 'EXPIRED'; runs: StandingRun[] };
export type StandingCandidate = { candidate_id: string; original_request: StandingCandidateRequest; scope: StandingReviewedScope; scope_hash: string; original_sources: Record<string, unknown>; created_at: string };
export type StandingCandidateRecord = { protocol: 'zhiyu-next-standing-candidate-record-v1'; candidate: StandingCandidate; candidate_hash: string; native_bank_authority: false };
export type StandingUpdate = { candidate: StandingCandidateRecord | null; view: StandingView | null; original_control: StandingControl | null; partial: boolean; resume_original: boolean };

function signedActor(value: unknown, user: string, at: string): Actor { const p = parseLocalActorSession({ simulation: true, principal: value, bank_authority: false, confirms_financial_action: false }).principal; check(p.role === 'USER' && p.user_id === user && Date.parse(p.issued_at) <= Date.parse(at) && Date.parse(at) < Date.parse(p.expires_at)); return p; }
export function parseStandingScope(v: unknown, env: NextState): StandingScope {
  check(object(v) && exact(v, ['protocol', 'simulation', 'user_id', 'epoch_id', 'family', 'policy_version_ids', 'source_account_ids', 'goal_ids', 'product_ids', 'payee_id', 'per_action_cap_cents', 'per_event_cap_cents', 'daily_cap_cents', 'maximum_children', 'maximum_principal_unavailable_days', 'maximum_risk_level', 'asset_classes', 'max_fee_cents', 'max_loss_cents', 'cross_goal_release', 'requires_verified_complete_worlds', 'requires_current_native_guard', 'issued_at', 'expires_at']) && v.protocol === 'zhiyu-next-standing-scope-v1' && v.simulation === true && v.user_id === env.dashboard.user_id && v.epoch_id === env.epoch_id && standingFamilies.includes(v.family as StandingFamily));
  check(ids(v.policy_version_ids, 1, 100) && ids(v.source_account_ids, 1, 64) && ids(v.goal_ids, 0, 8) && ids(v.product_ids, 0, 64) && (v.payee_id === null || typeof v.payee_id === 'string' && v.payee_id.length > 0 && v.payee_id.length <= 160) && integer(v.per_action_cap_cents, 1) && integer(v.per_event_cap_cents, 1) && integer(v.daily_cap_cents, 1) && v.per_action_cap_cents <= v.per_event_cap_cents && v.per_event_cap_cents <= v.daily_cap_cents && integer(v.maximum_children, 1, 8) && integer(v.maximum_principal_unavailable_days, 0, 3660) && integer(v.maximum_risk_level, 0, 5) && strings(v.asset_classes, 16) && new Set(v.asset_classes).size === v.asset_classes.length && v.max_fee_cents === 0 && v.max_loss_cents === 0 && v.cross_goal_release === false && v.requires_verified_complete_worlds === true && v.requires_current_native_guard === true && time(v.issued_at) && time(v.expires_at) && Date.parse(v.issued_at) < Date.parse(v.expires_at));
  const asset = ['ASSET_PORTFOLIO', 'MATURITY_REINVESTMENT'].includes(String(v.family));
  if (asset) check(v.product_ids.length > 0 && v.asset_classes.length > 0 && v.maximum_principal_unavailable_days >= 1 && v.maximum_children <= 4 && v.payee_id === null);
  else { check(v.asset_classes.length === 0 && v.maximum_risk_level === 0 && v.maximum_principal_unavailable_days === 0 && v.product_ids.length === 0); if (v.family === 'PERIODIC_PAYMENT') check(v.payee_id !== null && v.goal_ids.length === 0 && v.maximum_children === 1); else check(v.goal_ids.length > 0 && v.payee_id === null && (v.family !== 'SINGLE_GOAL' || v.goal_ids.length === 1 && v.maximum_children === 1)); }
  return v as StandingScope;
}
export function standingNativeScope(scope: StandingReviewedScope): StandingScope { return scope.protocol === 'zhiyu-next-standing-income-goal-scope-v2' ? scope.native_scope : scope; }
export function parseStandingReviewedScope(v: unknown, env: NextState): StandingReviewedScope {
  if (object(v) && v.protocol === 'zhiyu-next-standing-income-goal-scope-v2') { check(exact(v, ['protocol', 'goal_mode', 'native_scope']) && v.goal_mode === 'CUMULATIVE_EVENT_TARGET'); const native = parseStandingScope(v.native_scope, env); check(native.family === 'SINGLE_GOAL'); return v as StandingIncomeGoalScope; }
  return parseStandingScope(v, env);
}
export async function parseStandingGrant(v: unknown, env: NextState): Promise<StandingGrant> { check(object(v) && exact(v, ['protocol', 'grant_id', 'scope', 'reviewed_scope_hash', 'actor_at_confirmation', 'confirmed_at', 'accepted', 'native_bank_authority']) && ['zhiyu-next-signed-standing-grant-v1', 'zhiyu-next-signed-income-goal-grant-v2'].includes(String(v.protocol)) && uuid(v.grant_id) && digest(v.reviewed_scope_hash) && time(v.confirmed_at) && v.accepted === true && v.native_bank_authority === false); const reviewed = parseStandingReviewedScope(v.scope, env); const scope = standingNativeScope(reviewed); check(v.protocol === (reviewed.protocol === 'zhiyu-next-standing-income-goal-scope-v2' ? 'zhiyu-next-signed-income-goal-grant-v2' : 'zhiyu-next-signed-standing-grant-v1') && v.reviewed_scope_hash === await hash(reviewed) && Date.parse(scope.issued_at) <= Date.parse(v.confirmed_at) && Date.parse(v.confirmed_at) < Date.parse(scope.expires_at)); signedActor(v.actor_at_confirmation, scope.user_id, v.confirmed_at); return v as StandingGrant; }
export function parseStandingControl(v: unknown, env: NextState, grant: string): StandingControl { check(object(v) && exact(v, ['protocol', 'grant_id', 'revision', 'expected_previous_revision', 'state', 'previous_record_hash', 'client_request_id', 'actor', 'recorded_at', 'accepted']) && v.protocol === 'zhiyu-next-standing-control-v1' && v.grant_id === grant && integer(v.revision, 1, 128) && v.expected_previous_revision === v.revision - 1 && ['ACTIVE', 'PAUSED', 'REVOKED'].includes(String(v.state)) && (v.revision === 1 ? v.state === 'ACTIVE' && v.previous_record_hash === null : digest(v.previous_record_hash)) && uuid(v.client_request_id) && time(v.recorded_at) && v.accepted === true); signedActor(v.actor, env.dashboard.user_id, v.recorded_at); return v as StandingControl; }
async function parseRun(v: unknown, env: NextState, grant: StandingGrant, control: StandingControl): Promise<StandingRun> {
  check(object(v) && exact(v, ['protocol', 'source', 'revision', 'previous_record_hash', 'state', 'recorded_at', 'grant_id', 'grant_hash', 'control_revision_at_acceptance', 'whole_plan_hash', 'original_action_ids', 'original_effect_hashes', 'original_bank_keys', 'accepted_total_cents', 'accounting_day', 'original_receipt_ids', 'reasons', 'executor_role', 'old_one_shot_user_consent_inherited']) && v.protocol === 'zhiyu-next-standing-run-v1' && object(v.source) && exact(v.source, ['protocol', 'environment_id', 'user_id', 'epoch_id', 'source_kind', 'original_source_id', 'original_source_version', 'original_source_hash']));
  const s = v.source; check(s.protocol === 'zhiyu-next-standing-source-v1' && s.environment_id === env.environment_id && s.user_id === env.dashboard.user_id && s.epoch_id === env.epoch_id && ['SETTLED_INCOME', 'CURRENT_POLICY_VERSION', 'SERVER_PERIOD', 'SETTLED_MATURITY_RECEIPT', 'ORIGINAL_ACTION_SETTLED', 'CURRENT_QUESTION_ANSWER'].includes(String(s.source_kind)) && ['original_source_id', 'original_source_version'].every((k) => typeof s[k] === 'string' && s[k].length > 0 && s[k].length <= 160) && digest(s.original_source_hash));
  check(integer(v.revision, 1, 128) && (v.revision === 1 ? v.previous_record_hash === null : digest(v.previous_record_hash)) && ['OBSERVED', 'WAITING_INFORMATION', 'WAITING_CONFIRMATION', 'NO_ACTION', 'ACCEPTED', 'UNKNOWN', 'SETTLED', 'CANCELLED_BEFORE_ACCEPTANCE'].includes(String(v.state)) && time(v.recorded_at) && v.grant_id === grant.grant_id && ids(v.original_action_ids, 0, 8) && Array.isArray(v.original_effect_hashes) && v.original_effect_hashes.every(digest) && strings(v.original_bank_keys, 8) && new Set(v.original_bank_keys).size === v.original_bank_keys.length && v.original_action_ids.length === v.original_effect_hashes.length && v.original_action_ids.length === v.original_bank_keys.length && ids(v.original_receipt_ids, 0, v.original_action_ids.length) && integer(v.accepted_total_cents) && strings(v.reasons, 64) && v.executor_role === 'SYSTEM' && v.old_one_shot_user_consent_inherited === false);
  if (['ACCEPTED', 'UNKNOWN', 'SETTLED'].includes(String(v.state))) check(v.original_action_ids.length > 0 && v.accepted_total_cents > 0 && digest(v.grant_hash) && v.grant_hash === await hash(grant) && digest(v.whole_plan_hash) && integer(v.control_revision_at_acceptance, 1, control.revision) && typeof v.accounting_day === 'string' && /^\d{4}-\d\d-\d\d$/.test(v.accounting_day) && Number.isFinite(Date.parse(v.accounting_day)) && new Date(v.accounting_day).toISOString().slice(0, 10) === v.accounting_day);
  else check(v.original_action_ids.length === 0 && v.accepted_total_cents === 0 && v.original_receipt_ids.length === 0 && v.grant_hash === null && v.whole_plan_hash === null && v.accounting_day === null && v.control_revision_at_acceptance === null);
  if (v.state === 'SETTLED') check(v.original_receipt_ids.length === v.original_action_ids.length);
  return v as StandingRun;
}
function standingMetadataFields(v: Record<string, unknown>) { return 'native_protocol' in v || 'worker_execution_status' in v ? ['native_protocol', 'worker_execution_status'] : []; }
function standingMetadata(v: Record<string, unknown>, grant: StandingGrant) { const extended = standingMetadataFields(v).length > 0; check((grant.protocol !== 'zhiyu-next-signed-income-goal-grant-v2' || extended) && (!extended || v.native_protocol === (grant.protocol === 'zhiyu-next-signed-income-goal-grant-v2' ? 'zhiyu-standing-income-goal-native-v1' : 'zhiyu-standing-delegated-native-v2') && v.worker_execution_status === 'REQUIRES_EXPLICIT_REVIEWED_SOURCE_PIN')); }
export async function parseStandingView(v: unknown, env: NextState): Promise<StandingView> { check(object(v) && exact(v, ['grant', 'control', 'effective_state', 'runs', ...standingMetadataFields(v)]) && Array.isArray(v.runs) && v.runs.length <= 2048); const grant = await parseStandingGrant(v.grant, env); standingMetadata(v, grant); const control = parseStandingControl(v.control, env, grant.grant_id); check(Date.parse(control.recorded_at) >= Date.parse(grant.confirmed_at) && ['ACTIVE', 'PAUSED', 'REVOKED', 'EXPIRED'].includes(String(v.effective_state)) && (v.effective_state === 'EXPIRED' ? control.state === 'ACTIVE' : v.effective_state === control.state)); if (control.revision === 1) check(control.recorded_at === grant.confirmed_at && same(control.actor, grant.actor_at_confirmation)); const runs: StandingRun[] = []; const events = new Set<string>(); for (const r of v.runs) { const run = await parseRun(r, env, grant, control); const event = await hash(run.source); check(!events.has(event)); events.add(event); runs.push(run); } return { grant, control, effective_state: v.effective_state as StandingView['effective_state'], runs }; }
export async function getStandingGrant(id: string, env: NextState): Promise<StandingView> { check(uuid(id)); const v = await request(`${STANDING_PREFIX}/grants/${id}`, 'GET', undefined, (v) => { context(v, env); return v; }); check(exact(v, [...identity, 'grant', 'control', 'effective_state', 'runs', 'native_bank_authority', 'executor_role', ...standingMetadataFields(v)]) && v.native_bank_authority === false && v.executor_role === 'SYSTEM'); const view = await parseStandingView({ grant: v.grant, control: v.control, effective_state: v.effective_state, runs: v.runs, ...Object.fromEntries(standingMetadataFields(v).map((k) => [k, v[k]])) }, env); check(view.grant.grant_id === id); return view; }
export async function getStandingViews(env: NextState): Promise<StandingView[]> { const v = await request(STANDING_PREFIX, 'GET', undefined, (v) => { context(v, env); return v; }); check(exact(v, [...identity, 'grants', 'native_bank_authority', 'executor_role', ...('income_goal_variant' in v ? ['income_goal_variant'] : [])]) && v.native_bank_authority === false && v.executor_role === 'SYSTEM' && Array.isArray(v.grants) && v.grants.length <= 1000); if ('income_goal_variant' in v) parseStandingIncomeGoalVariant(v.income_goal_variant); const views: StandingView[] = []; for (const r of v.grants) views.push(await parseStandingView(r, env)); check(new Set(views.map((r) => r.grant.grant_id)).size === views.length); return views; }

async function parseSources(v: unknown, scope: StandingScope, env: NextState): Promise<Record<string, unknown>> {
  check(object(v) && exact(v, ['policies', 'native_configurations', 'source_accounts', 'goals', 'catalogue']) && Array.isArray(v.policies) && v.policies.length === scope.policy_version_ids.length && Array.isArray(v.native_configurations) && Array.isArray(v.source_accounts) && v.source_accounts.length === scope.source_account_ids.length && Array.isArray(v.goals) && v.goals.length === scope.goal_ids.length); assertMoneyFields(v);
  const versions: string[] = [], natives: Record<string, unknown>[] = [];
  for (const p of v.policies) { check(object(p) && ['MVP', 'FULL'].includes(String(p.kind)) && exact(p, ['kind', 'version_id', 'policy_id', 'content_hash', 'configuration', ...(p.kind === 'FULL' ? ['template_name'] : [])]) && uuid(p.version_id) && uuid(p.policy_id) && digest(p.content_hash) && safeConfiguration(p.configuration) && await sourceHash(p.configuration) === p.content_hash && (p.kind !== 'FULL' || typeof p.template_name === 'string' && !!p.template_name)); versions.push(p.version_id); if (p.kind === 'MVP') natives.push(p.configuration); }
  check(sameIds(versions, scope.policy_version_ids) && await sourceHash({ configurations: natives }) === await sourceHash({ configurations: v.native_configurations }));
  const accounts: string[] = []; for (const a of v.source_accounts) { check(object(a) && exact(a, ['account_id', 'user_id', 'account_type', 'currency', 'bank_code', 'external_ref']) && uuid(a.account_id) && a.user_id === scope.user_id && a.account_type === 'CASH' && ['currency', 'bank_code', 'external_ref'].every((k) => typeof a[k] === 'string' && a[k].length > 0)); accounts.push(a.account_id); } check(sameIds(accounts, scope.source_account_ids));
  const goals: string[] = []; for (const g of v.goals) { check(object(g) && exact(g, ['goal_id', 'policy_version_id', 'monthly_max_cents', 'full_model']) && uuid(g.goal_id) && uuid(g.policy_version_id) && scope.policy_version_ids.includes(g.policy_version_id) && integer(g.monthly_max_cents) && object(g.full_model)); const policy = v.policies.find((p) => object(p) && p.version_id === g.policy_version_id); check(object(policy) && policy.kind === 'MVP'); const model = parseFullGoalModel(g.full_model, { id: g.goal_id, policy_id: String(policy.policy_id), policy_version_id: g.policy_version_id }); check(model.status === 'VERIFIED' && model.epoch_id === env.epoch_id && await hash(model.full_configuration) === model.full_configuration_hash && model.base_configuration_hash === policy.content_hash); goals.push(g.goal_id); } check(sameIds(goals, scope.goal_ids));
  if (scope.product_ids.length === 0) check(v.catalogue === null);
  else { check(object(v.catalogue) && exact(v.catalogue, ['products', 'bindings']) && Array.isArray(v.catalogue.products) && Array.isArray(v.catalogue.bindings) && v.catalogue.products.length === scope.product_ids.length && v.catalogue.bindings.length === scope.product_ids.length); const products: string[] = []; const bound: string[] = []; for (const p of v.catalogue.products) { check(object(p) && exact(p, ['product_id', 'product_code', 'version_number', 'asset_class', 'risk_level', 'principal_fluctuation', 'minimum_purchase_cents', 'lock_days', 'redemption_delay_days', 'annual_yield_bps', 'early_withdrawal_loss_bps', 'auto_purchase_allowed', 'auto_redeem_allowed', 'created_at', 'effective_from', 'effective_until', 'maturity_rule', 'terms_digest']) && uuid(p.product_id) && typeof p.product_code === 'string' && !!p.product_code && integer(p.version_number, 1) && typeof p.asset_class === 'string' && scope.asset_classes.includes(p.asset_class) && integer(p.risk_level, 0, scope.maximum_risk_level) && ['principal_fluctuation', 'auto_purchase_allowed', 'auto_redeem_allowed'].every((k) => typeof p[k] === 'boolean') && ['minimum_purchase_cents', 'lock_days', 'redemption_delay_days', 'annual_yield_bps', 'early_withdrawal_loss_bps'].every((k) => integer(p[k])) && time(p.created_at) && time(p.effective_from) && (p.effective_until === null || time(p.effective_until) && Date.parse(p.effective_until) >= Date.parse(p.effective_from)) && safeConfiguration(p.maturity_rule) && digest(p.terms_digest) && await hash(p.maturity_rule) === p.terms_digest); products.push(p.product_id); } for (const b of v.catalogue.bindings) { check(object(b) && exact(b, ['product_id', 'catalogue_version_id', 'product_record_hash', 'terms_digest']) && uuid(b.product_id) && uuid(b.catalogue_version_id) && digest(b.product_record_hash) && digest(b.terms_digest)); const product = v.catalogue.products.find((p) => object(p) && p.product_id === b.product_id); check(object(product) && b.terms_digest === product.terms_digest); bound.push(b.product_id); } check(sameIds(products, scope.product_ids) && sameIds(bound, scope.product_ids)); }
  return v;
}
export async function parseStandingCandidate(v: unknown, env: NextState, requestBody: StandingCandidateRequest, posted = false): Promise<StandingCandidateRecord> {
  context(v, env); check(exact(v, [...identity, 'protocol', 'candidate', 'candidate_hash', 'native_bank_authority', ...(posted ? ['client_request_id'] : [])]) && v.protocol === 'zhiyu-next-standing-candidate-record-v1' && v.native_bank_authority === false && digest(v.candidate_hash) && object(v.candidate) && (!posted || v.client_request_id === requestBody.client_request_id)); const c = v.candidate; check(exact(c, ['candidate_id', 'original_request', 'scope', 'scope_hash', 'original_sources', 'created_at']) && uuid(c.candidate_id) && c.candidate_id === await releaseUUID5(env.epoch_id, `standing-candidate:${requestBody.client_request_id}`) && time(c.created_at) && digest(c.scope_hash)); const body = parseStandingCandidateRequest(c.original_request); check(same(body, requestBody) && body.expected_epoch_id === env.epoch_id); const reviewed = parseStandingReviewedScope(c.scope, env); const scope = standingNativeScope(reviewed); check((body.goal_mode === 'CUMULATIVE_EVENT_TARGET' ? reviewed.protocol === 'zhiyu-next-standing-income-goal-scope-v2' : reviewed.protocol === 'zhiyu-next-standing-scope-v1') && scope.family === body.family && ['policy_version_ids', 'source_account_ids', 'goal_ids', 'product_ids'].every((k) => sameIds(scope[k as 'goal_ids'], body[k as 'goal_ids'])) && Date.parse(scope.issued_at) === Date.parse(c.created_at) && Date.parse(scope.expires_at) - Date.parse(scope.issued_at) === ({ ONE_DAY: 1, SEVEN_DAYS: 7, THIRTY_DAYS: 30 }[body.validity_preset]) * 86400000 && await hash(reviewed) === c.scope_hash && await sourceHash(c) === v.candidate_hash); await parseSources(c.original_sources, scope, env); return { protocol: v.protocol, candidate: c as StandingCandidate, candidate_hash: v.candidate_hash, native_bank_authority: false };
}
export async function getStandingCandidate(body: StandingCandidateRequest, env: NextState) { const id = await releaseUUID5(env.epoch_id, `standing-candidate:${body.client_request_id}`); return request(`${STANDING_PREFIX}/candidates/${id}`, 'GET', undefined, (v) => parseStandingCandidate(v, env, body)); }
function schemaShape(v: unknown, properties: string[]) { check(object(v) && v.type === 'object' && v.additionalProperties === false && object(v.properties) && exact(v.properties, properties) && Array.isArray(v.required) && v.required.every((k) => typeof k === 'string' && properties.includes(k))); }
export async function getStandingSchema(): Promise<Record<string, unknown> & { income_goal_variant?: StandingIncomeGoalVariant }> {
  return request(`${STANDING_PREFIX}/schema`, 'GET', undefined, (v) => {
    check(object(v)); const extended = 'income_goal_variant' in v || 'income_goal_scope_schema' in v;
    check(exact(v, ['simulation', 'protocol', 'native_bank_authority', 'candidate_schema', 'scope_schema', 'confirmation_schema', 'control_schema', 'requires_separate_current_native_auto_permission', ...(extended ? ['income_goal_scope_schema', 'income_goal_variant'] : [])]) && v.simulation === true && v.protocol === 'zhiyu-next-standing-schema-v1' && v.native_bank_authority === false && v.requires_separate_current_native_auto_permission === true);
    schemaShape(v.candidate_schema, ['client_request_id', 'expected_epoch_id', 'family', 'policy_version_ids', 'source_account_ids', 'goal_ids', 'product_ids', 'validity_preset', ...(extended ? ['goal_mode'] : [])]);
    schemaShape(v.confirmation_schema, ['client_request_id', 'expected_epoch_id', 'accepted', 'candidate_id', 'reviewed_scope_hash', 'reviewed_candidate_hash']); schemaShape(v.control_schema, ['client_request_id', 'expected_epoch_id', 'accepted', 'grant_id', 'expected_revision', 'command']); check(object(v.scope_schema) && v.scope_schema.additionalProperties === false && object(v.scope_schema.properties));
    if (extended) { schemaShape(v.income_goal_scope_schema, ['protocol', 'goal_mode', 'native_scope']); parseStandingIncomeGoalVariant(v.income_goal_variant); }
    return v as Record<string, unknown> & { income_goal_variant?: StandingIncomeGoalVariant };
  });
}
function originalBinding(v: unknown, original: PendingOperation) { check(object(v) && exact(v, ['kind', 'path', 'body']) && v.kind === `STANDING_${standingPath(original.path)}` && v.path === `/api/v1${original.path}` && same(v.body, original.body)); }
function controlMatches(c: StandingControl, original: PendingOperation, recovery: StandingRecovery) { check(c.client_request_id === original.client_request_id && c.grant_id === original.body.grant_id && c.expected_previous_revision === original.body.expected_revision && c.previous_record_hash === recovery.previous_control_hash && c.state === ({ PAUSE: 'PAUSED', RESUME: 'ACTIVE', REVOKE: 'REVOKED' }[String(original.body.command) as 'PAUSE'])); }
export async function readStandingOriginal(original: PendingOperation, env: NextState): Promise<OperationResult & { standing?: StandingUpdate }> {
  const recovery = parseStandingRecovery(original.standing_recovery, original.path, original.body, original.epoch_id, original.client_request_id); check(recovery.user_id === env.dashboard.user_id && original.environment_id === env.environment_id && original.epoch_id === env.epoch_id); const kind = standingPath(original.path)!; const result: OperationResult & { standing?: StandingUpdate } = { simulation: true, client_request_id: original.client_request_id, environment_id: env.environment_id, epoch_id: env.epoch_id, status: 'PENDING' };
  let v: Record<string, unknown>; try { v = await request(`${STANDING_PREFIX}/commands/${original.client_request_id}`, 'GET', undefined, (v) => { context(v, env); return v; }); } catch (cause) { if (cause instanceof ApiError && cause.status === 404) return result; throw cause; }
  check(v.client_request_id === original.client_request_id && v.native_bank_authority === false);
  if (v.status === 'PARTIAL_WRAPPER_RESULT') { check(exact(v, [...identity, 'status', 'original_control', 'original_request', 'client_request_id', 'native_bank_authority'])); if (v.original_request === null) { check(kind === 'CONFIRM' && object(v.original_control) && v.original_control.revision === 1); return result; } originalBinding(v.original_request, original); check(kind === 'CONTROL' && recovery.grant_id); const c = parseStandingControl(v.original_control, env, recovery.grant_id); controlMatches(c, original, recovery); const view = await getStandingGrant(c.grant_id, env); check(view.control.revision >= c.revision && (view.control.revision !== c.revision || same(view.control, c))); result.standing = { candidate: null, view, original_control: c, partial: true, resume_original: true }; return result; }
  check(v.status === 'RECORDED' && exact(v, [...identity, 'status', 'operation', 'original_request', 'client_request_id', 'native_bank_authority'])); originalBinding(v.original_request, original); const op = v.operation; check(object(op) && exact(op, ['simulation', 'client_request_id', 'status', 'environment_id', 'epoch_id', 'result']) && op.simulation === true && op.client_request_id === original.client_request_id && op.environment_id === env.environment_id && op.epoch_id === env.epoch_id && ['COMPLETED', 'PENDING'].includes(String(op.status))); if (op.status === 'PENDING') return result; check(object(op.result));
  const r = op.result; let candidate: StandingCandidateRecord | null = null; let view: StandingView | null = null; let c: StandingControl | null = null;
  if (kind === 'CANDIDATE') { const posted = await parseStandingCandidate(r, env, recovery.candidate_request!, true); candidate = await getStandingCandidate(recovery.candidate_request!, env); check(posted.candidate_hash === candidate.candidate_hash); }
  else if (kind === 'CONFIRM') { context(r, env); check(exact(r, [...identity, 'grant', 'control', 'native_bank_authority', 'client_request_id', 'original_request', ...standingMetadataFields(r)]) && r.native_bank_authority === false && r.client_request_id === original.client_request_id); originalBinding(r.original_request, original); candidate = await getStandingCandidate(recovery.candidate_request!, env); }
  if (kind === 'CONFIRM') { check(candidate && candidate.candidate.candidate_id === recovery.candidate_id && candidate.candidate_hash === recovery.reviewed_candidate_hash && candidate.candidate.scope_hash === recovery.reviewed_scope_hash); const g = await parseStandingGrant(r.grant, env); standingMetadata(r, g); check(g.grant_id === await releaseUUID5(env.epoch_id, `standing-grant:${recovery.candidate_id}`) && same(g.scope, candidate.candidate.scope) && g.reviewed_scope_hash === recovery.reviewed_scope_hash); c = parseStandingControl(r.control, env, g.grant_id); check(c.revision === 1 && c.client_request_id === original.client_request_id && same(c.actor, g.actor_at_confirmation) && c.recorded_at === g.confirmed_at); view = await getStandingGrant(g.grant_id, env); check(same(view.grant, g) && view.control.revision >= c.revision && (view.control.revision !== c.revision || same(view.control, c))); candidate = null; }
  else if (kind === 'CONTROL') { check(exact(r, ['simulation', 'control', 'native_bank_authority', 'client_request_id', 'original_request']) && r.simulation === true && r.native_bank_authority === false && r.client_request_id === original.client_request_id && recovery.grant_id); originalBinding(r.original_request, original); c = parseStandingControl(r.control, env, recovery.grant_id); controlMatches(c, original, recovery); view = await getStandingGrant(c.grant_id, env); check(view.control.revision >= c.revision && (view.control.revision !== c.revision || same(view.control, c))); }
  result.standing = { candidate, view, original_control: c, partial: false, resume_original: false }; result.status = 'COMPLETED'; return result;
}
export async function validateStandingOriginal(original: PendingOperation, env: NextState) { const recovery = parseStandingRecovery(original.standing_recovery, original.path, original.body, original.epoch_id, original.client_request_id); check(recovery.user_id === env.dashboard.user_id); await getStandingSchema(); const kind = standingPath(original.path); if (kind === 'CONFIRM') { const c = await getStandingCandidate(recovery.candidate_request!, env); check(c.candidate.candidate_id === recovery.candidate_id && c.candidate_hash === recovery.reviewed_candidate_hash && c.candidate.scope_hash === recovery.reviewed_scope_hash); } else if (kind === 'CONTROL') { const v = await getStandingGrant(recovery.grant_id!, env); check(v.control.revision === original.body.expected_revision && await hash(v.control) === recovery.previous_control_hash && v.control.state !== 'REVOKED' && (original.body.command !== 'RESUME' || v.effective_state !== 'EXPIRED')); } }
export function standingAcknowledgment(v: unknown) { check(object(v) && v.simulation === true && v.native_bank_authority === false); return v; }
const candidateViewKey = (env: NextState) => `zhiyu-next-standing-candidate-view-v1:${env.environment_id}:${env.epoch_id}`;
export function forgetStandingCandidate(env: NextState) { localStorage.removeItem(candidateViewKey(env)); }
export function rememberStandingUpdate(update: StandingUpdate, env: NextState) { if (update.candidate) localStorage.setItem(candidateViewKey(env), JSON.stringify({ protocol: 'zhiyu-next-standing-candidate-view-v1', environment_id: env.environment_id, epoch_id: env.epoch_id, request: update.candidate.candidate.original_request })); else if (update.view && update.original_control?.revision === 1) forgetStandingCandidate(env); }
export async function readStandingCandidateView(env: NextState) { const raw = localStorage.getItem(candidateViewKey(env)); if (!raw) return null; const v: unknown = JSON.parse(raw); check(object(v) && exact(v, ['protocol', 'environment_id', 'epoch_id', 'request']) && v.protocol === 'zhiyu-next-standing-candidate-view-v1' && v.environment_id === env.environment_id && v.epoch_id === env.epoch_id); const body = parseStandingCandidateRequest(v.request); check(body.expected_epoch_id === env.epoch_id); return getStandingCandidate(body, env); }
/** Serial read of the fixed original inventory. Journal SETTLED alone is not a bank receipt. */
export async function readStandingActions(run: StandingRun, view: StandingView, env: NextState): Promise<Action[]> { const actions: Action[] = []; let total = 0; const receipts: string[] = []; const scope = standingNativeScope(view.grant.scope); check(run.original_action_ids.length <= scope.maximum_children); for (const [i, id] of run.original_action_ids.entries()) { const a = await readAction(id, run.original_effect_hashes[i]!); check(a.user_id === env.dashboard.user_id && await hash(a.effect) === a.effect_hash && a.effect.fee_cents === 0 && a.effect.loss_cents === 0 && a.effect.amount_cents <= scope.per_action_cap_cents); check(a.effect.action_type === (['SINGLE_GOAL', 'JOINT_GOALS'].includes(scope.family) ? 'ALLOCATE_GOAL' : scope.family === 'PERIODIC_PAYMENT' ? 'PAY_RECURRING' : 'PURCHASE_ASSET') && (['SINGLE_GOAL', 'JOINT_GOALS'].includes(scope.family) ? scope.goal_ids.includes(a.effect.goal_id!) : scope.family === 'PERIODIC_PAYMENT' ? a.effect.payee_id === scope.payee_id : scope.product_ids.includes(a.effect.product_id!)) && (a.effect.cash_uses ?? []).every((u) => scope.source_account_ids.includes(u.account_id)) && (a.effect.income_uses ?? []).every((u) => scope.source_account_ids.includes(u.account_id))); total += a.effect.amount_cents; check(integer(total) && total <= scope.per_event_cap_cents); if (a.receipt) { const r = a.receipt; check(object(r) && exact(r, ['simulation', 'receipt_id', 'action_id', 'bank_operation_id', 'status', 'executed_cents', 'fee_cents', 'loss_cents', 'posting_ids', 'occurred_at', 'reconciled_at']) && ['SUCCEEDED', 'RECONCILED'].includes(a.status) && a.bank_status === 'SETTLED' && r.status === 'SUCCEEDED' && r.executed_cents === a.effect.amount_cents && r.fee_cents === 0 && r.loss_cents === 0 && ids(r.posting_ids, 2, 100) && time(r.occurred_at) && (r.reconciled_at === null || time(r.reconciled_at))); receipts.push(r.receipt_id); } else check(!['SUCCEEDED', 'RECONCILED'].includes(a.status)); actions.push(a); } check(total === run.accepted_total_cents && run.original_receipt_ids.every((id) => receipts.includes(id)) && (run.state !== 'SETTLED' || sameIds(receipts, run.original_receipt_ids))); return actions; }
