import { webcrypto } from 'node:crypto';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { maturityActionFixture, maturityEpoch, maturityLocalSessionFixture, maturityLookupFixture, maturityPositionsFixture, maturityPrepareFixture, maturityPreviewFixture, maturityUser } from '../tests/full-maturity-execution-fixture';
import type { MaturityPrepare } from '../api/full-maturity-execution';
const props = () => ({ policyId: maturityPrepareFixture().policy_id, expectedVersionId: maturityPrepareFixture().expected_version_id, userId: maturityUser, epochId: maturityEpoch, showOriginalRecovery: false });
beforeEach(() => { vi.resetModules(); sessionStorage.clear(); vi.stubGlobal('crypto', webcrypto); }); afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
test('actual positions only identify candidate; explicit preview/prepare/GET/ASK/execute never auto advance', async () => {
  let stage: 'PREPARED' | 'CONFIRMED' | 'SETTLED' = 'PREPARED'; let body = maturityPrepareFixture();
  const fetcher = vi.fn(async (url: string, options?: RequestInit) => {
    if (url.endsWith('/session')) return new Response(JSON.stringify(maturityLocalSessionFixture())); if (url.endsWith('/positions')) return new Response(JSON.stringify(maturityPositionsFixture()));
    if (url.endsWith('/preview')) { body = JSON.parse(options!.body as string) as MaturityPrepare; const saved = JSON.parse(sessionStorage.getItem('bounded-funds-full-maturity-preview-v1:same-origin')!); expect(saved.body_json).toBe(options!.body); expect(saved.request_hash).toMatch(/^[0-9a-f]{64}$/); return new Response(JSON.stringify(maturityPreviewFixture(body))); }
    const store = await import('../features/full-maturity-execution-operation');
    if (options?.method === 'POST') { expect(store.getFullMaturityOperation().pending!.body_json).toBe(options.body); if (url.endsWith('/confirm')) stage = 'CONFIRMED'; if (url.endsWith('/execute')) stage = 'SETTLED'; return new Response(JSON.stringify(await maturityActionFixture(body, stage))); }
    const intent = store.getFullMaturityOperation().pending ?? await store.fullMaturityWorkspaceIntent(); return new Response(JSON.stringify(await maturityLookupFixture(intent, stage)));
  }); vi.stubGlobal('fetch', fetcher); const Panel = (await import('./FullMaturityExecutionPanel')).default; render(<Panel {...props()} />); expect(fetcher).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: '只读加载实际持仓与USER身份' })); await screen.findByRole('combobox'); fireEvent.change(screen.getByRole('combobox'), { target: { value: body.position_id } }); fireEvent.click(screen.getByRole('button', { name: '读取原合同到期预览' })); await screen.findByRole('region', { name: '服务器到期范围' }); fireEvent.click(screen.getByRole('button', { name: '明确准备这笔整额到期' })); await screen.findByText(/POST已返回/);
  fireEvent.click(screen.getByRole('button', { name: '独立GET原到期结果' })); await screen.findByText('RECORDED · PLANNED · 应用原回执未证明'); expect(screen.getByRole('button', { name: '明确确认这笔到期原命令' })).toBeDisabled(); fireEvent.click(screen.getByRole('checkbox')); fireEvent.click(screen.getByRole('button', { name: '明确确认这笔到期原命令' })); await waitFor(() => expect(stage).toBe('CONFIRMED')); fireEvent.click(screen.getByRole('button', { name: '独立GET原到期结果' })); await screen.findByText('RECORDED · AUTHORIZED · 应用原回执未证明'); fireEvent.click(screen.getByRole('checkbox')); fireEvent.click(screen.getByRole('button', { name: '明确执行这笔原到期动作' })); await waitFor(() => expect(stage).toBe('SETTLED')); fireEvent.click(screen.getByRole('button', { name: '独立GET原到期结果' })); await screen.findByText('RECORDED · SUCCEEDED · 银行与应用原回执已核'); expect(fetcher.mock.calls.filter(call => call[1]?.method === 'POST')).toHaveLength(4);
});
test('UNKNOWN/lost response same original GET remains accessible with blocked parent, no POST', async () => { const store = await import('../features/full-maturity-execution-operation'), body = maturityPrepareFixture(), intent = await store.maturityIntent('EXECUTE', maturityUser, body, await maturityActionFixture(body, 'CONFIRMED')); await store.beginFullMaturityOperation(intent); store.endFullMaturityAttempt(); const fetcher = vi.fn(async () => new Response(JSON.stringify(await maturityLookupFixture(intent, 'UNKNOWN')))); vi.stubGlobal('fetch', fetcher); const Panel = (await import('./FullMaturityExecutionPanel')).default; render(<Panel {...props()} mutationBlocked />); fireEvent.click(screen.getByRole('button', { name: '独立GET原到期结果' })); await screen.findByText('RECORDED · UNKNOWN · 应用原回执未证明'); expect(fetcher).toHaveBeenCalledOnce(); expect(store.getFullMaturityOperation().pending?.body_json).toBe(intent.body_json); });
test('independent original GET needs no policy list and 401 preserves identity for manual same USER login', async () => { const store = await import('../features/full-maturity-execution-operation'), intent = await store.maturityIntent('PREPARE', maturityUser, maturityPrepareFixture()); await store.beginFullMaturityOperation(intent); store.endFullMaturityAttempt(); const fetcher = vi.fn(async () => new Response(JSON.stringify({ error: { code: 'LOCAL_USER_REQUIRED', message: '需要同USER登录' } }), { status: 401 })); vi.stubGlobal('fetch', fetcher); const Panel = (await import('./FullMaturityExecutionPanel')).FullMaturityOriginalRecoveryPanel; render(<Panel />); fireEvent.click(screen.getByRole('button', { name: '只读核对原到期请求' })); await screen.findByRole('alert'); expect(fetcher).toHaveBeenCalledOnce(); expect(store.getFullMaturityOperation().pending?.body_json).toBe(intent.body_json); });
