import { useEffect, useRef, useState } from 'react';
import type { components } from '../../../../packages/contracts/schema';
import { getPositions } from '../api/goals';
import { readLocalActorSession } from '../api/local-actor';
import { errorMessage } from '../api/http';
import { recoveryCheck as check, recoveryRequestHash } from '../api/full-recovery-execution';
import { isFreshMaturityRead, lookupMaturityExecution, originalMaturityResponse, parseMaturityPrepare, postMaturityExecution, previewMaturityExecution } from '../api/full-maturity-execution';
import type { MaturityIntent, MaturityLookup, MaturityPreview } from '../api/full-maturity-execution';
import { releaseUUID } from '../api/goal-release-authorizations';
import { acceptFullMaturityRead, acceptFullMaturityWorkspaceRead, beginFullMaturityOperation, endFullMaturityAttempt, fullMaturityWorkspaceIntent, isFullMaturityWorkspaceUnresolved, maturityIntent, recoverFullMaturityOperation, useFullMaturityOperation } from '../features/full-maturity-execution-operation';
import { formatMoneyCents as money } from '../features/money';

function Original({ value }: { value: MaturityLookup }) { const action = value.action; return <section aria-label="到期原件"><p role="status">{value.status} · {action?.status ?? 'UNKNOWN'} · {action?.service_receipt_verified ? '银行与应用原回执已核' : '应用原回执未证明'}</p>{action && <><p>本金 {money(action.command.principal_cents)} · 原目标 {action.command.goal_id ?? 'GENERAL'} · 原仓位 {action.command.position_id} → {action.command.destination_account_id}</p><p>ASK_ONCE · commandHash {action.reviewed_command_hash} · 原截止 {action.command.expires_at} · 轮次 {action.epoch_state}</p></>}<details><summary>完整到期原响应</summary><pre>{originalMaturityResponse(value) ?? JSON.stringify(value, null, 2)}</pre></details><p>历史确认、原回执和条件本金均不是当前授权。银行SETTLED但应用未核仍保同一键。</p></section>; }

export function FullMaturityOriginalRecoveryPanel() {
  const op = useFullMaturityOperation(), [busy, setBusy] = useState(false), [error, setError] = useState(''), [value, setValue] = useState<MaturityLookup | null>(null);
  useEffect(() => { void recoverFullMaturityOperation(); }, []);
  async function read() { if (busy || op.busy || op.recovering) return; setBusy(true); setError(''); try { if (op.pending) { const result = await acceptFullMaturityRead(op.pending, await lookupMaturityExecution(op.pending)); setValue(result.lookup); } else if (op.workspace) { const intent = await fullMaturityWorkspaceIntent(); setValue(await acceptFullMaturityWorkspaceRead(intent, await lookupMaturityExecution(intent))); } } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  if (!op.pending && !op.workspace && !op.storage_error) return null;
  return <section className="card" aria-label="跨页原到期核对"><h3>原到期请求与固定动作</h3>{(error || op.storage_error) && <p role="alert">{error || op.storage_error}</p>}<p>只读原GET可独立使用；会话过期须在身份入口手动续同USER，不换键。</p><button type="button" disabled={busy || op.busy || op.recovering} onClick={() => void read()}>只读核对原到期请求</button>{value && <Original value={value} />}</section>;
}
export default function FullMaturityExecutionPanel({ policyId, userId, expectedVersionId, epochId, mutationBlocked = false, showOriginalRecovery = true }: { policyId: string; userId: string; expectedVersionId: string; epochId: string; mutationBlocked?: boolean; showOriginalRecovery?: boolean }) {
  const op = useFullMaturityOperation(), [positions, setPositions] = useState<components['schemas']['PositionView'][]>([]), [position, setPosition] = useState(''), [preview, setPreview] = useState<MaturityPreview | null>(null), [original, setOriginal] = useState<MaturityLookup | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [accepted, setAccepted] = useState(false), [pendingRead, setPendingRead] = useState(false);
  const scope = `${userId}:${epochId}:${policyId}:${expectedVersionId}`, latest = useRef({ scope, blocked: mutationBlocked }); latest.current = { scope, blocked: mutationBlocked }; const loaded = useRef<string | null>(null);
  useEffect(() => { void recoverFullMaturityOperation(); }, []);
  const displayed = loaded.current === scope, locked = busy || op.busy || op.recovering || mutationBlocked || !!op.pending || !!op.storage_error;
  const action = original?.action, sameScope = displayed && original && isFreshMaturityRead(original) && action?.user_id === userId && action.epoch_id === epochId && action.original_request.policy_id === policyId && action.original_request.expected_version_id === expectedVersionId && action.epoch_state === 'OPEN';
  const canConfirm = sameScope && action?.status === 'PLANNED' && !action.original_consent, canExecute = sameScope && action?.original_consent && ['AUTHORIZED', 'SUBMITTED', 'UNKNOWN'].includes(action.status) && !action.service_receipt_verified;
  async function load() { if (busy || op.busy) return; setBusy(true); setError(''); setPreview(null); setOriginal(null); setAccepted(false); const before = scope; try { const [actor, rows] = await Promise.all([readLocalActorSession(), getPositions()]); check(actor.principal.user_id === userId && actor.principal.role === 'USER' && rows.items.every(row => releaseUUID(row.id) && releaseUUID(row.account_id) && releaseUUID(row.product_id)) && new Set(rows.items.map(row => row.id)).size === rows.items.length); if (latest.current.scope === before) { loaded.current = before; setPositions(rows.items); setPosition(''); } } catch (cause) { if (latest.current.scope === before) setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function previewPlan() { if (locked || !displayed || !positions.some(row => row.id === position)) return; const before = scope; setBusy(true); setError(''); setPreview(null); setAccepted(false); try { const body = parseMaturityPrepare({ policy_id: policyId, expected_version_id: expectedVersionId, expected_epoch_id: epochId, position_id: position, idempotency_key: `maturity-${crypto.randomUUID()}` }); const body_json = JSON.stringify(body), request_hash = await recoveryRequestHash(body); check(!latest.current.blocked && latest.current.scope === before); sessionStorage.setItem(`bounded-funds-full-maturity-preview-v1:${import.meta.env.VITE_API_BASE_URL ?? 'same-origin'}`, JSON.stringify({ user_id: userId, path: '/full-maturity-actions/preview', body, body_json, request_hash })); const value = await previewMaturityExecution(body, userId); if (latest.current.scope === before) setPreview(value); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function send(intent: MaturityIntent, expectedScope?: string) { await beginFullMaturityOperation(intent, () => latest.current.blocked || expectedScope !== undefined && latest.current.scope !== expectedScope); setAccepted(false); setPendingRead(false); try { await postMaturityExecution(intent); setNotice('POST已返回，原请求仍未决；请独立GET核对，未自动确认或执行。'); } finally { endFullMaturityAttempt(); } }
  async function prepare() { if (locked || !displayed || preview?.proof.status !== 'VERIFIED_SCOPE' || op.workspace && isFullMaturityWorkspaceUnresolved(op.workspace)) return; setBusy(true); setError(''); try { const body = preview.original_request; check(body.policy_id === policyId && body.expected_version_id === expectedVersionId && body.expected_epoch_id === epochId && body.position_id === position); await send(await maturityIntent('PREPARE', userId, body), scope); setPreview(null); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function next(kind: 'CONFIRM' | 'EXECUTE') { if (locked || !accepted || !action || (kind === 'CONFIRM' ? !canConfirm : !canExecute)) return; const before = scope; setBusy(true); setError(''); try { await send(await maturityIntent(kind, userId, action.original_request, action), before); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function read() { if (busy || op.busy || op.recovering) return; setBusy(true); setError(''); setAccepted(false); setPendingRead(false); try { if (op.pending) { const result = await acceptFullMaturityRead(op.pending, await lookupMaturityExecution(op.pending)); setOriginal(result.lookup); setPendingRead(!result.complete); } else if (op.workspace) { const intent = await fullMaturityWorkspaceIntent(); setOriginal(await acceptFullMaturityWorkspaceRead(intent, await lookupMaturityExecution(intent))); } } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function resume() { if (!op.pending || !pendingRead || !accepted || busy || op.busy || mutationBlocked || op.storage_error) return; setBusy(true); setError(''); try { await send(op.pending); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  return <>{showOriginalRecovery && <FullMaturityOriginalRecoveryPanel />}<section className="card" aria-label="整仓到期USER执行"><h3>单笔整额到期 · USER逐次确认</h3><p>模拟合同本金，零费用/零损失；不支付收益、不支持部分或组合。持仓清单只提供原身份，新服务器预览唯一证明到期范围。</p>{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{op.storage_error && <p role="alert">{op.storage_error}</p>}
    <button type="button" disabled={busy || op.busy} onClick={() => void load()}>只读加载实际持仓与USER身份</button>
    {displayed && <><label>实际持仓<select value={position} disabled={locked} onChange={event => { setPosition(event.target.value); setPreview(null); setAccepted(false); }}><option value="">请选择原持仓，未证明到期</option>{positions.filter(row => ['HELD', 'MATURED'].includes(row.status) && row.maturity_at !== null).map(row => <option key={row.id} value={row.id}>{row.id} · 原本金{money(row.principal_cents)} · 原合同日{row.maturity_at}</option>)}</select></label><button type="button" disabled={locked || !position} onClick={() => void previewPlan()}>读取原合同到期预览</button></>}
    {displayed && preview && <section aria-label="服务器到期范围"><p>{preview.proof.status} · 完整持仓分母{preview.proof.candidate_denominator} · proofHash{preview.proof.proof_hash}</p>{preview.proof.command && <p>本金{money(preview.proof.command.principal_cents)} → {preview.proof.command.destination_account_id} · 保留目标{preview.proof.command.goal_id ?? 'GENERAL'} · commandHash{preview.proof.command_hash} · 未消除负检查点{preview.proof.remaining_negative_checkpoints ?? 'UNKNOWN'}</p>}{preview.proof.reasons.map((reason, i) => <p key={i}>{reason}</p>)}<details><summary>完整到期预览原件</summary><pre>{originalMaturityResponse(preview)}</pre></details><button type="button" disabled={locked || preview.proof.status !== 'VERIFIED_SCOPE' || !!op.workspace && isFullMaturityWorkspaceUnresolved(op.workspace)} onClick={() => void prepare()}>明确准备这笔整额到期</button></section>}
    {(op.pending || op.workspace) && <><p>保留原键{op.pending?.prepare_request.idempotency_key ?? op.workspace?.idempotency_key}；未知和NOT_FOUND不允许换键。</p><button type="button" disabled={busy || op.busy || op.recovering} onClick={() => void read()}>独立GET原到期结果</button></>}
    {original && <Original value={original} />}{(canConfirm || canExecute || pendingRead) && <label><input type="checkbox" checked={accepted} disabled={busy || op.busy || mutationBlocked || !!op.storage_error} onChange={event => setAccepted(event.target.checked)} />我明确复核完整原本金、目标、目的账户、轮次和命令哈希；同意本次操作或同身份恢复</label>}
    <button type="button" disabled={locked || !accepted || !canConfirm} onClick={() => void next('CONFIRM')}>明确确认这笔到期原命令</button><button type="button" disabled={locked || !accepted || !canExecute} onClick={() => void next('EXECUTE')}>明确执行这笔原到期动作</button>
    {pendingRead && <button type="button" disabled={!accepted || busy || op.busy || mutationBlocked || !!op.storage_error} onClick={() => void resume()}>手动恢复同body/key到期请求</button>}<p>签名会话失效时原GET/POST可能401；请求仍保留，先在身份入口手动续同USER。历史SEALED不产生新确认。</p>
  </section></>;
}
