import { useEffect, useRef, useState } from 'react';
import { errorMessage } from '../api/http';
import { readLocalActorSession } from '../api/local-actor';
import { getFullRecoveryPlan, getOriginalFullProductsResponse } from '../api/full-products';
import type { FullRecoveryPlan } from '../api/full-products';
import { getOriginalRecoveryResponse, isFreshRecoveryRead, lookupRecoveryExecution, parseRecoveryPrepare, postRecoveryExecution, previewRecoveryExecution, recoveryCheck, recoveryRequestHash } from '../api/full-recovery-execution';
import type { RecoveryIntent, RecoveryLookup, RecoveryPreview } from '../api/full-recovery-execution';
import { acceptFullRecoveryRead, acceptFullRecoveryWorkspaceRead, beginFullRecoveryOperation, endFullRecoveryAttempt, fullRecoveryWorkspaceIntent, isFullRecoveryWorkspaceUnresolved, prepareRecoveryIntent, recoverFullRecoveryOperation, useFullRecoveryOperation } from '../features/full-recovery-execution-operation';
import { formatMoneyCents } from '../features/money';
import { useWriteInFlight } from '../features/write-flight';

export type FullRecoveryExecutionProps = { policyId: string; userId: string; expectedVersionId: string; epochId: string; mutationBlocked?: boolean };
function Raw({ value, label }: { value: object; label: string }) { return <details><summary>{label}</summary><pre>{getOriginalRecoveryResponse(value) ?? JSON.stringify(value, null, 2)}</pre></details>; }
const money = (value: number | null) => value === null ? 'UNKNOWN · 尚未证明' : `¥${formatMoneyCents(value)}`;
export default function FullRecoveryExecutionPanel({ policyId, userId, expectedVersionId, epochId, mutationBlocked = false }: FullRecoveryExecutionProps) {
  const operation = useFullRecoveryOperation(), writing = useWriteInFlight();
  const [plan, setPlan] = useState<FullRecoveryPlan | null>(null), [position, setPosition] = useState(''), [preview, setPreview] = useState<RecoveryPreview | null>(null), [original, setOriginal] = useState<RecoveryLookup | null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [accepted, setAccepted] = useState(false), [resumeAccepted, setResumeAccepted] = useState(false), [pendingRead, setPendingRead] = useState(false);
  const scope = `${userId}:${epochId}:${policyId}:${expectedVersionId}`, current = useRef(scope); current.current = scope;
  const sourceScope = useRef<string | null>(null), displayed = sourceScope.current === scope;
  useEffect(() => { void recoverFullRecoveryOperation(); }, []);
  const locked = mutationBlocked || writing || busy || operation.busy || operation.recovering || !!operation.storage_error || !!operation.pending;
  const unresolved = !!operation.workspace && isFullRecoveryWorkspaceUnresolved(operation.workspace);
  const action = original?.action;
  const sameScope = displayed && !!original && isFreshRecoveryRead(original) && original.user_id === userId && original.original_request?.policy_id === policyId && original.original_request.expected_version_id === expectedVersionId && original.original_request.expected_epoch_id === epochId && original.epoch_state === 'OPEN';
  const canConfirm = sameScope && action?.status === 'PLANNED' && action.autonomy_level === 'ASK_ONCE' && original?.original_consent === null;
  const canExecute = sameScope && action && ['AUTHORIZED', 'SUBMITTED', 'UNKNOWN'].includes(action.status) && original?.original_consent !== null && action.autonomy_level === 'ASK_ONCE' && !action.receipt;
  async function load() {
    if (busy || operation.busy) return; const requested = scope; setBusy(true); setError(''); setPreview(null); setPlan(null); setOriginal(null); setAccepted(false);
    try { const [identity, value] = await Promise.all([readLocalActorSession(), getFullRecoveryPlan(policyId)]); recoveryCheck(identity.principal.user_id === userId && identity.principal.role === 'USER' && value.user_id === userId && value.policy_id === policyId && (!value.plan || value.plan.policy_version_id === expectedVersionId)); if (current.current === requested) { sourceScope.current = requested; setPlan(value); setPosition(value.plan?.lossless_steps[0]?.position_id ?? ''); } }
    catch (cause) { if (current.current === requested) setError(errorMessage(cause)); } finally { setBusy(false); }
  }
  async function previewPlan() {
    if (locked || !displayed || !position || !plan?.plan || !plan.plan.lossless_steps.some((row) => row.position_id === position)) return; const requested = scope; setBusy(true); setError(''); setPreview(null);
    try { const body = parseRecoveryPrepare({ policy_id: policyId, expected_version_id: expectedVersionId, expected_epoch_id: epochId, position_id: position, idempotency_key: `recovery-${crypto.randomUUID()}` }); sessionStorage.setItem(`bounded-funds-full-recovery-preview-v1:${import.meta.env.VITE_API_BASE_URL ?? 'same-origin'}`, JSON.stringify({ user_id: userId, request: body, body_json: JSON.stringify(body), request_hash: await recoveryRequestHash(body) })); const value = await previewRecoveryExecution(body, userId); if (current.current === requested) setPreview(value); }
    catch (cause) { if (current.current === requested) setError(errorMessage(cause)); } finally { setBusy(false); }
  }
  async function send(intent: RecoveryIntent) { await beginFullRecoveryOperation(intent, mutationBlocked); setPendingRead(false); setResumeAccepted(false); try { await postRecoveryExecution(intent); setNotice('原请求已返回，仍保留待核对门；请独立GET，不自动确认或执行。'); } finally { endFullRecoveryAttempt(); } }
  async function prepare() { if (locked || unresolved || !displayed || preview?.proof.status !== 'VERIFIED_SCOPE') return; setBusy(true); setError(''); try { await send(await prepareRecoveryIntent('PREPARE', userId, preview.original_request)); setPreview(null); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function next(kind: 'CONFIRM' | 'EXECUTE') { if (locked || !accepted || !original?.original_request || !action || (kind === 'CONFIRM' ? !canConfirm : !canExecute)) return; setBusy(true); setError(''); setAccepted(false); try { await send(await prepareRecoveryIntent(kind, userId, original.original_request, action)); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function recover() {
    const intent = operation.pending; if (!intent || busy || operation.busy) return; setBusy(true); setError(''); setPendingRead(false); setResumeAccepted(false); setAccepted(false);
    try { const result = await acceptFullRecoveryRead(intent, await lookupRecoveryExecution(intent)); sourceScope.current = `${intent.user_id}:${intent.prepare_request.expected_epoch_id}:${intent.prepare_request.policy_id}:${intent.prepare_request.expected_version_id}`; setOriginal(result.lookup); setPendingRead(!result.complete); setNotice(result.complete ? '独立原GET已匹配原body/双hash及本次结果；历史USER同意和回执不是当前银行权限。' : 'NOT_FOUND/UNKNOWN或USER逐次同意缺失，原固定动作与请求仍待核对，不能换键创建第二动作。'); }
    catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); }
  }
  async function resume() { if (!operation.pending || !pendingRead || !resumeAccepted || busy || operation.busy || mutationBlocked || writing || operation.storage_error) return; setBusy(true); setError(''); try { await send(operation.pending); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function readWorkspace() { if (!operation.workspace || operation.pending || busy || operation.busy) return; setBusy(true); setError(''); setAccepted(false); try { const intent = await fullRecoveryWorkspaceIntent(); const value = await acceptFullRecoveryWorkspaceRead(intent, await lookupRecoveryExecution(intent)); sourceScope.current = `${intent.user_id}:${intent.prepare_request.expected_epoch_id}:${intent.prepare_request.policy_id}:${intent.prepare_request.expected_version_id}`; setOriginal(value); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  return <section className="card" aria-label="完整安全恢复原动作"><h3>安全恢复 · 原USER逐次同意</h3><p>全部是模拟资金操作。只使用服务器当前策略、真实原仓位、原报价和期限；本页不输入金额、银行回执或时钟。当前新适配只支持零损失/零费用的授权整仓T0/T1；不承诺组合、部分或有损恢复。</p>
    {error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{operation.storage_error && <p role="alert">{operation.storage_error}</p>}
    {operation.pending && <section aria-label="恢复待核对原请求"><h4>原 {operation.pending.kind} 待核对</h4><p>原键 {operation.pending.prepare_request.idempotency_key} · 仓位 {operation.pending.prepare_request.position_id} · 轮次 {operation.pending.prepare_request.expected_epoch_id}</p><Raw value={operation.pending} label="POST前保存的完整恢复body/hash" /><button type="button" disabled={busy || operation.busy || operation.recovering} onClick={() => void recover()}>独立读取原恢复结果</button>{pendingRead && <><label><input type="checkbox" checked={resumeAccepted} disabled={mutationBlocked || busy || writing || !!operation.storage_error} onChange={(event) => setResumeAccepted(event.target.checked)} />我明确恢复同一原body与动作，不创建第二动作或更换键</label><button type="button" disabled={!resumeAccepted || mutationBlocked || busy || writing || !!operation.storage_error} onClick={() => void resume()}>手动恢复同一恢复原请求</button></>}<p>网络/解析/4xx不清门；NOT_FOUND不是最终未提交证明。自己的原GET可越过自身待核对门，刷新不自动POST。</p></section>}
    {operation.workspace && !operation.pending && <section aria-label="恢复原动作工作区"><p>固定Action {operation.workspace.action?.action_id ?? 'UNKNOWN'} · {unresolved ? '原动作未终局，禁止另一键或仓位替代。' : '保留原历史结果，不作为当前授权。'}</p><button type="button" disabled={busy || operation.busy || operation.recovering} onClick={() => void readWorkspace()}>只读刷新原恢复动作</button></section>}
    <button type="button" disabled={busy || operation.busy} onClick={() => void load()}>只读加载当前恢复规划与USER身份</button>
    {displayed && plan && <section aria-label="实际恢复候选"><p>服务器原规划 {plan.state} · {plan.plan?.status ?? 'UNKNOWN'} · 原规划执行标记 {plan.execution_support}。本页独立新执行入口仍需原生产和银行守卫。</p>{plan.source_issues.map((row, index) => <p key={index}>{row.code} · {row.source_ref} · {row.message}</p>)}{plan.plan && <><p>当前scope现金 {money(plan.plan.actual_scope_cash_cents)} · 原待恢复额 {money(plan.plan.required_recovery_cents)} · 条件准时净额 {money(plan.plan.conditional_on_time_recovery_cents)} · 原截止 {plan.plan.deadline_at ?? 'UNKNOWN'}</p><label>服务器实际选中的无损整仓<select value={position} disabled={locked} onChange={(event) => { setPosition(event.target.value); setPreview(null); }}><option value="">没有可证明候选/请选择</option>{plan.plan.lossless_steps.map((row) => <option key={row.position_id} value={row.position_id}>{row.position_id} · 原本金 {money(row.principal_cents)}</option>)}</select></label><ul>{plan.plan.candidates.map((row) => <li key={row.position_id}>{row.position_id} · {row.decision} · 本金 {money(row.principal_cents)} / 净额 {money(row.net_cents)} / 费用 {money(row.fee_cents)} / 损失 {money(row.independent_loss_cents)} · 准时 {row.on_time === null ? 'UNKNOWN' : row.on_time ? '条件准时' : '不能准时'}{row.reasons.map((reason, index) => <p key={index}>{reason}</p>)}</li>)}</ul><button type="button" disabled={locked || !position} onClick={() => void previewPlan()}>读取服务器原恢复执行预览</button></>}<details><summary>恢复规划原JSON</summary><pre>{getOriginalFullProductsResponse(plan) ?? JSON.stringify(plan, null, 2)}</pre></details><p>规划、身份和执行预览是分别采集的快照；prepare在服务器再次复核。预览身份不是准备动作，截止点不会为了确认被延长。</p></section>}
    {displayed && preview && <section aria-label="恢复执行范围预览"><h4>原范围 {preview.proof.status}</h4><p>原本金 {money(preview.proof.candidate.principal_cents)} · fee {money(preview.proof.candidate.fee_cents)} · loss {money(preview.proof.candidate.independent_loss_cents)} · net {money(preview.proof.candidate.net_cents)}</p><p>proofHash {preview.proof.proof_hash} · effectHash {preview.proof.effect_hash ?? 'UNKNOWN'} · 原截止 {preview.proof.deadline_at ?? 'UNKNOWN'}</p>{preview.proof.reasons.map((row, index) => <p key={index}>{row}</p>)}{preview.limitations.map((row, index) => <p key={index}>{row}</p>)}<Raw value={preview} label="恢复执行预览原JSON" /><button type="button" disabled={locked || unresolved || preview.proof.status !== 'VERIFIED_SCOPE'} onClick={() => void prepare()}>明确准备原整仓恢复动作</button></section>}
    {original && <section aria-label="固定原恢复动作"><h4>原键结果 {original.status}</h4>{action && <><p>Action {action.action_id} · 原状态 {action.status} · {action.autonomy_level} · 银行 {action.bank_status ?? '尚未观察/UNKNOWN'} · 轮次 {original.epoch_state}</p><p>原仓位 {action.effect.position_id} → 原目的账户 {action.effect.destination_account_id} · 原目标 {action.effect.goal_id ?? 'general_idle_funds'}</p><p>本金 {money(action.effect.amount_cents)} / 净额 {money(action.effect.net_cents ?? null)} / fee {money(action.effect.fee_cents ?? null)} / loss {money(action.effect.loss_cents ?? null)} · 原到账上界 {action.effect.latest_arrival_at ?? 'UNKNOWN'} · effectHash {action.effect_hash}</p><p>clientRequestHash {original.client_request_hash} · 原serverRequestHash {original.server_request_hash}</p><p>USER逐次同意 {original.original_consent ? `原件已核 · ${original.original_consent.original_confirmation_evidence_id} · ${original.original_consent.confirmed_at}` : '尚未观察/UNKNOWN；MVP状态不能替代FULL USER逐次同意'}</p><p>原回执 {action.receipt ? `${action.receipt.receipt_id} · ${action.receipt.status}` : '缺少应用回执，不宣称现金已恢复；银行SETTLED仍须沿原动作核对'}</p>{(canConfirm || canExecute) && <label><input type="checkbox" checked={accepted} disabled={locked} onChange={(event) => setAccepted(event.target.checked)} />我以当前本地USER明确复核原仓位、目的账户、零fee/loss、轮次和完整effectHash，并同意这一次操作</label>}<button type="button" disabled={locked || !accepted || !canConfirm} onClick={() => void next('CONFIRM')}>明确确认这一次原恢复动作</button><button type="button" disabled={locked || !accepted || !canExecute} onClick={() => void next('EXECUTE')}>明确执行或核对同一原恢复动作</button></>}<Raw value={original} label="原恢复请求/USER同意/回执完整JSON" /><p>原逐次同意/回执不是当前银行授权；后续执行每次由原服务器和独立银行重验。历史SEALED/不同当前版本不显示新的确认入口。</p></section>}
  </section>;
}

/** Root may mount this own-GET surface outside another family's mutation fieldset. */
export function FullRecoveryOriginalRecoveryPanel() {
  const operation = useFullRecoveryOperation(); const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  useEffect(() => { void recoverFullRecoveryOperation(); }, []);
  async function read() { if (busy || operation.busy || operation.recovering) return; setBusy(true); setError(''); try { if (operation.pending) { const intent = operation.pending, result = await acceptFullRecoveryRead(intent, await lookupRecoveryExecution(intent)); setNotice(result.complete ? '原结果完整匹配，固定工作区保留；不是当前资金授权。' : '原结果非终局，保留同body/key/Action。'); } else if (operation.workspace) { const intent = await fullRecoveryWorkspaceIntent(); await acceptFullRecoveryWorkspaceRead(intent, await lookupRecoveryExecution(intent)); setNotice('独立原GET已刷新工作区，原同意不等于当前授权。'); } } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  if (!operation.pending && !operation.workspace && !operation.storage_error) return null;
  return <section className="card" aria-label="跨页原恢复核对"><h3>原安全恢复请求/固定工作区</h3>{error && <p role="alert">{error}</p>}{operation.storage_error && <p role="alert">{operation.storage_error}</p>}{notice && <p role="status">{notice}</p>}<button type="button" disabled={busy || operation.busy || operation.recovering} onClick={() => void read()}>只读核对原安全恢复请求</button><Raw value={operation.pending ?? operation.workspace ?? { storage_error: operation.storage_error }} label="保留的原恢复body/hash/固定动作" /><p>本区域只有GET，无自动POST；登录过期先手动重新登录。NOT_FOUND和HTTP错误不解除原门。</p></section>;
}
