import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getFullAnnualPlanning, getOriginalFullAnnualResponse } from '../api/full-annual';
import { errorMessage } from '../api/http';
import { formatMoneyCents } from '../features/money';

const money = (value: number | null | undefined) => value == null ? '未知 · 尚未证明' : `¥${formatMoneyCents(value)}`;
export default function FullAnnualProtectionPanel() {
  const [day, setDay] = useState(0); const query = useQuery({ queryKey: ['full-annual-protection'], queryFn: getFullAnnualPlanning, retry: false, structuralSharing: false });
  const data = query.data; const projection = data?.projection; const chosen = data ? [data.initial_checkpoint, ...data.daily_checkpoints][day]! : null;
  return <section className="card readonly-section" aria-label="完整策略年度保护"><h3>完整策略年度保护</h3>
    <p>将已确认的一次支出和周期转账上限纳入365日条件规划。尚未绑定历史结清的登记金额保守视为未付；原90日执行参考仍须独立核验。</p>
    <button type="button" disabled={query.isFetching} onClick={() => void query.refetch()}>刷新完整保护规划</button>
    {query.isPending && <p role="status">正在核对完整策略原来源…</p>}{query.isError && <p role="alert">{errorMessage(query.error)}；未发布旧结果为当前成功。</p>}{query.isFetching && data && <p role="status">正在重新读取，下方仍是上次原报告。</p>}
    {!query.isError && data && projection && chosen && <>
      <p>{projection.status === 'UNKNOWN' ? '完整保护来源不足，全年金额未知' : projection.status === 'LIQUIDITY_RISK' ? '完整保护存在流动性缺口' : '当前登记范围内的完整保护已计算'}</p>
      <p className="caption">只读查询时点 {data.as_of} · 当前登记义务范围{projection.full_obligations_complete_within_registered_current_scope ? '完整' : '尚未完整证明'}；不包括完整历史未结清覆盖。</p><dl className="annual-amounts"><div><dt>完整规划安全闲置</dt><dd>{money(projection.full_annual_projection?.safe_idle_cents)}</dd></div><div><dt>完整规划最小余量</dt><dd>{money(projection.full_annual_projection?.minimum_margin_cents)}</dd></div><div><dt>完整规划缺口</dt><dd>{money(projection.full_annual_projection?.deficit_cents)}</dd></div></dl>
      <label className="field">查看完整保护日期<select value={day} onChange={(event) => setDay(Number(event.target.value))}>{[data.initial_checkpoint, ...data.daily_checkpoints].map((point) => <option key={point.day} value={point.day}>{point.date} · {point.status === 'PROVEN' ? '已计算' : '未知'}</option>)}</select></label>
      <p role="status">{chosen.date} · 最小日内余量 {money(chosen.minimum_intraday_margin_cents)}</p>
      <div className="annual-phases">{([['before_payment', '完整付款前'], ['after_payment', '完整付款后'], ['after_principal', '完整本金到账后']] as const).map(([field, label]) => <section className="annual-phase" key={field} aria-label={label}><h4>{label}</h4>{!chosen[field] && <p className="notice">原完整保护尚未证明，此阶段金额/原引用未知。</p>}<p>条件现金 {money(chosen[field]?.cash_cents)} · 余量 {money(chosen[field]?.margin_cents)}</p>{chosen[field] && <dl>{Object.entries(chosen[field]!.protected_cents_by_reason).map(([reason, cents]) => <div key={reason}><dt>{reason}</dt><dd>{money(cents)}</dd></div>)}</dl>}{chosen[field] && <p className="caption">原义务编号 {chosen[field]!.obligation_occurrence_ids.join('、') || '本阶段未列出'} · 原本金编号 {chosen[field]!.principal_position_ids.join('、') || '本阶段未列出'}</p>}</section>)}</div>
      <details><summary>实际登记义务与原版本（{projection.occurrences.length}项）</summary>{projection.occurrences.map((entry) => <article key={entry.occurrence_id}><p>{entry.kind} · 登记{entry.amount_basis === 'REGISTERED_EXACT' ? '固定金额' : '上限'} {money(entry.conservative_unpaid_cents)} · {entry.earliest_due_date} 至 {entry.latest_due_date}{entry.overdue ? ' · 已过最早应付日，仍未证明结清' : ''}</p><p>原版本 <code>{entry.policy_version_id}</code> · 原已付金额未知 · 未授权付款</p></article>)}</details>
      {projection.reasons.length > 0 && <ul className="issues">{projection.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>}
      <details><summary>来源账户局部检查（{projection.source_account_checks.length}项）</summary><p>仅当前现金扣除原目标归属、在途保留和已登记周期金额；未独立分配全部未来MVP账户支出，不能称完整账户可支付证明。</p>{projection.source_account_checks.map((check) => <article key={check.account_id}><p>原账户 <code>{check.account_id}</code> · {check.state}</p><dl className="annual-amounts"><div><dt>当前现金</dt><dd>{money(check.actual_cash_cents)}</dd></div><div><dt>原目标归属现金</dt><dd>{money(check.goal_owned_cash_cents)}</dd></div><div><dt>原在途保留</dt><dd>{money(check.reserved_cash_cents)}</dd></div><div><dt>登记周期金额</dt><dd>{money(check.registered_periodic_required_cents)}</dd></div><div><dt>当前账户剩余（可为负）</dt><dd>{money(check.remaining_current_cash_cents)}</dd></div></dl><p>future_account_debits_complete=false</p></article>)}</details>
      <details><summary>原FULL约束与条件问题</summary>{projection.full_annual_projection?.blocking_constraints.map((constraint, index) => <p key={index}>{constraint.code} · {constraint.date ?? '未指定日期'} · 原编号 {constraint.entity_id ?? '未提供'} · 需要 {money(constraint.required_cents)}，可用 {money(constraint.available_cents)}</p>)}</details>
      <details><summary>完整策略状态与来源</summary>{projection.policy_states.map((state) => <p key={state.policy_id}><code>{state.policy_id}</code> · {state.state} · {state.reasons.join('、')}</p>)}{data.full_policy_sources.map((source) => <article key={source.policy_id}><p>{source.template_name} · 原状态 {source.effective_status} · 原版本 <code>{source.version_id}</code>（{source.version_number}）</p><p>原配置hash <code>{source.content_hash}</code> · 规划确认{source.planning_confirmation_valid ? '原服务报告有效' : '尚未证明'} · 引用{source.references_current ? '原服务报告当前' : '尚未证明'}</p><details><summary>原登记配置/确认/引用结构</summary><pre className="readonly-raw">{JSON.stringify(source, null, 2)}</pre></details></article>)}{data.source_issues.map((issue, index) => <p key={index}>{issue.code} · {issue.message} · <code>{issue.source_ref}</code></p>)}</details>
      <p>节日金额：{projection.seasonal_status === 'ADOPTED_PROTECTED' ? `已明确采纳的今日保护额 ${money(projection.seasonal_adopted_adjustment_cents)}，保护结束只释放下界，不代表发生付款` : projection.seasonal_status === 'ADOPTED_FLOOR_RELEASED' ? '原采纳窗口已结束，完整原件证明通过；今日保护下界已释放为零，现金没有增加或发生付款' : projection.seasonal_status === 'ADOPTED_AMOUNT_UNKNOWN' ? '原采纳或当前来源未证明，金额未知' : projection.seasonal_status === 'NO_SEASONAL_POLICY' ? '未登记节日策略' : '仅建议，尚无采纳的附加金额'}。未来收入未计入现金边界；条件假设独立展示，不能证明未来入账。</p>
      <p>当前审计 {data.audit.status}（{data.audit.complete ? '原服务报告完整' : '原服务报告不完整'}）· {data.audit.scope}；不是独立银行验真或所有历史epoch验证。历史完整结清尚未实现，完整保护执行尚未实现。</p><p className="caption">原90日执行参考和365日原规划嵌入此报告；新增FULL曲线没有被原执行消费者采用。此区域与上方旧年度GET独立读取，不能称共同事务快照或当前自主资金。</p><details><summary>完整保护实际来源证据（{data.source_evidence_ids.length}项）</summary><ul>{data.source_evidence_ids.map((identity) => <li key={identity}><a href={`#evidence/EVIDENCE/${identity}`}>{identity}</a></li>)}</ul></details><p className="caption">输入摘要 <code>{data.input_digest}</code> · FULL输入hash <code>{projection.input_hash}</code>；仅展示原服务摘要，未改写历史哈希。</p><details><summary>具体未覆盖项</summary><ul>{data.limitations.map((item) => <li key={item}>{item}</li>)}</ul></details>
      <details><summary>完整保护原JSON响应</summary><pre className="readonly-raw">{getOriginalFullAnnualResponse(data) ?? '原响应未保留'}</pre></details>
    </>}
  </section>;
}
