import { webcrypto } from 'node:crypto';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { jointPlanFixture, jointResponseFixture } from '../tests/full-joint-goal-execution-fixture';
beforeEach(() => { vi.resetModules(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.stubGlobal('crypto', webcrypto); sessionStorage.clear(); });
afterEach(cleanup);
async function renderPanel(blocked = false) { const { default: Panel } = await import('./FullJointGoalExecutionPanel'); return render(<Panel mutationBlocked={blocked} showOriginalRecovery />); }
it('renders clear authority/whole reservation/atomicity boundary and no automatic network', async () => { const fetch = vi.fn(); vi.stubGlobal('fetch', fetch); await renderPanel(); expect(screen.getByRole('heading', { name: '联合目标 · 固定整组与逐子模拟执行' })).toBeInTheDocument(); expect(screen.getByText(/本页不输入金额、银行结果、权限或时钟/)).toBeInTheDocument(); expect(fetch).not.toHaveBeenCalled(); });
it('original GET remains usable through other-family block and displays ALL commands/1098 without enabling writes', async () => { const value = jointResponseFixture('CONFIRMED'), fetch = vi.fn<typeof globalThis.fetch>(async () => new Response(JSON.stringify(value), { status: 200 })); vi.stubGlobal('fetch', fetch); await renderPanel(true); fireEvent.change(screen.getByLabelText('读取既存原父计划ID'), { target: { value: value.original_plan.plan_id } }); fireEvent.click(screen.getByRole('button', { name: '只读读取原联合计划' })); await screen.findByRole('heading', { name: '原服务状态 CONFIRMED_UNRESERVED' }); expect(screen.getByText(/完整保护节点 1098/)).toBeInTheDocument(); expect(screen.getByRole('button', { name: '仅执行这个固定原子' })).toBeDisabled(); expect(fetch).toHaveBeenCalledTimes(1); expect(fetch.mock.calls[0]?.[1]?.method).toBe('GET'); });
it('UNKNOWN stops next child, keeps original keys and requires explicit recovery rather than auto execute', async () => { const r = jointResponseFixture('UNKNOWN'), fetch = vi.fn<typeof globalThis.fetch>(async () => new Response(JSON.stringify(r), { status: 200 })); vi.stubGlobal('fetch', fetch); await renderPanel(); fireEvent.change(screen.getByLabelText('读取既存原父计划ID'), { target: { value: r.original_plan.plan_id } }); fireEvent.click(screen.getByRole('button', { name: '只读读取原联合计划' })); await screen.findByRole('heading', { name: '原服务状态 UNRESOLVED' }); expect(screen.getByText(/前子 UNKNOWN \/ SUBMITTED/)).toBeInTheDocument(); expect(screen.getByRole('button', { name: '仅执行这个固定原子' })).toBeDisabled(); expect(fetch).toHaveBeenCalledTimes(1); });
it('reload of compact original locator requires manual original GET and never replays POST', async () => { const api = await import('../api/full-joint-goal-execution'), p = jointPlanFixture(); sessionStorage.setItem('bounded-funds-joint-goal-operation-v2:same-origin', JSON.stringify({ protocol: 'joint-goal-workspace-v2', pending: null, workspace_reference: api.jointReviewBinding(p) })); const fetch = vi.fn(); vi.stubGlobal('fetch', fetch); await renderPanel(); await screen.findByRole('region', { name: '恢复联合原定位' }); expect(fetch).not.toHaveBeenCalled(); expect(screen.getByText(/尚无本次服务器完整读取/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '填入原父计划读取ID' })); expect(screen.getByLabelText('读取既存原父计划ID')).toHaveValue(p.plan_id); });
it('historical parent never enables fresh confirm or child execution', async () => { const r = jointResponseFixture('HISTORY'); vi.stubGlobal('fetch', vi.fn<typeof globalThis.fetch>(async () => new Response(JSON.stringify(r), { status: 200 }))); await renderPanel(); fireEvent.change(screen.getByLabelText('读取既存原父计划ID'), { target: { value: r.original_plan.plan_id } }); fireEvent.click(screen.getByRole('button', { name: '只读读取原联合计划' })); await screen.findByRole('heading', { name: '原服务状态 RETAINED_HISTORY' }); await waitFor(() => expect(screen.getByRole('button', { name: '提交原联合整组明确确认' })).toBeDisabled()); expect(screen.getByRole('button', { name: '仅执行这个固定原子' })).toBeDisabled(); });
it('standalone thin original recovery exports only GET and no financial write controls', async () => { const { FullJointGoalOriginalRecoveryPanel } = await import('./FullJointGoalExecutionPanel'); const r = jointResponseFixture('UNKNOWN'), fetch = vi.fn<typeof globalThis.fetch>(async () => new Response(JSON.stringify(r), { status: 200 })); vi.stubGlobal('fetch', fetch); render(<FullJointGoalOriginalRecoveryPanel />); fireEvent.change(screen.getByLabelText('读取既存原父计划ID'), { target: { value: r.original_plan.plan_id } }); fireEvent.click(screen.getByRole('button', { name: '只读读取原联合计划' })); await screen.findByText(/只读原状态 UNRESOLVED/); expect(screen.queryByRole('button', { name: '仅执行这个固定原子' })).not.toBeInTheDocument(); expect(fetch).toHaveBeenCalledTimes(1); expect(fetch.mock.calls[0]?.[1]?.method).toBe('GET'); });
