import { webcrypto } from 'node:crypto';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, expect, test, vi } from 'vitest';
import { installHttpFixture } from '../tests/policy-fixture';
import { recoveryActionFixture, recoveryFixtureHash, recoveryLocalSessionFixture, recoveryLookupFixture, recoveryPlanningFixture, recoveryPrepareFixture, recoveryPreviewFixture, recoveryUser, recoveryEpoch } from '../tests/full-recovery-execution-fixture';
import type { RecoveryIntent, RecoveryPrepare } from '../api/full-recovery-execution';
let Panel: typeof import('./FullRecoveryExecutionPanel').default;
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubGlobal('crypto', webcrypto); Panel = (await import('./FullRecoveryExecutionPanel')).default; });
const body = recoveryPrepareFixture();
const props = { policyId: body.policy_id, expectedVersionId: body.expected_version_id, epochId: recoveryEpoch, userId: recoveryUser };
function open(blocked = false) { return render(<Panel {...props} mutationBlocked={blocked} />); }
function intentFor(prepare: RecoveryPrepare): RecoveryIntent { return { protocol: 'full-recovery-browser-v1', kind: 'PREPARE', user_id: recoveryUser, prepare_request: prepare, action: null, path: '/full-recovery-actions/prepare', body: prepare, body_json: JSON.stringify(prepare), request_hash: recoveryFixtureHash(prepare) }; }
function install(options: { unknown?: boolean; missingConsent?: boolean; executeUnknown?: boolean; responseLoss?: boolean } = {}) {
  let prepare = recoveryPrepareFixture(), stage: 'PREPARED' | 'CONFIRMED' | 'UNKNOWN' | 'SETTLED' = 'PREPARED';
  return installHttpFixture((method, path, value) => {
    if (path.endsWith('/local-actor/session')) return recoveryLocalSessionFixture();
    if (path.endsWith('/recovery-planning')) { const plan = recoveryPlanningFixture(); if (options.unknown) plan.source_issues = [{ code: 'TOOL_ONLY_SOURCE_UNKNOWN', source_ref: 'original-source-reference', message: '原来源尚未证明' }]; return plan; }
    if (path.endsWith('/preview')) { prepare = value as RecoveryPrepare; return recoveryPreviewFixture(prepare, options.unknown ? 'UNKNOWN' : 'VERIFIED_SCOPE'); }
    if (path.endsWith('/prepare')) { prepare = value as RecoveryPrepare; return recoveryActionFixture(); }
    if (method === 'POST' && path.endsWith('/confirm')) { stage = 'CONFIRMED'; return recoveryActionFixture(stage); }
    if (method === 'POST' && path.endsWith('/execute')) { stage = options.executeUnknown ? 'UNKNOWN' : 'SETTLED'; if (options.responseLoss) return new Response(JSON.stringify({ error: { code: 'TOOL_ONLY_LOSS', message: 'synthetic响应丢失' } }), { status: 500 }); return recoveryActionFixture(stage); }
    if (path.includes('/by-key/')) return recoveryLookupFixture(intentFor(prepare), options.missingConsent && stage === 'CONFIRMED' ? 'MISSING_CONSENT' : stage);
    throw new Error(`TOOL_ONLY_UNEXPECTED_${path}`);
  });
}
async function loadPreview() { fireEvent.click(screen.getByRole('button', { name: '只读加载当前恢复规划与USER身份' })); await screen.findByRole('region', { name: '实际恢复候选' }); fireEvent.click(screen.getByRole('button', { name: '读取服务器原恢复执行预览' })); await screen.findByRole('region', { name: '恢复执行范围预览' }); }
async function readPending() { const button = screen.getByRole('button', { name: '独立读取原恢复结果' }); await waitFor(() => expect(button).toBeEnabled()); fireEvent.click(button); await waitFor(() => expect(screen.queryByRole('region', { name: '恢复待核对原请求' })).not.toBeInTheDocument()); }
test('只用户点击才实际读取服务器候选和预览，无金额/clock输入，scopeproof不金融授权', async () => { const calls = install(); open(); expect(calls).toHaveLength(0); await loadPreview(); expect(screen.queryByRole('spinbutton')).not.toBeInTheDocument(); expect(screen.getByRole('heading', { name: '原范围 VERIFIED_SCOPE' })).toBeVisible(); expect(calls.map((row) => row.method)).toEqual(['GET', 'GET', 'POST']); expect(calls.at(-1)!.body).not.toHaveProperty('amount_cents'); expect(calls.at(-1)!.body).not.toHaveProperty('now'); expect(screen.getByText(/截止点不会为了确认被延长/)).toBeVisible(); });
test('prepare→原GET→USER明确confirm→原GET→固定execute→原GET回执，POST从不清门', async () => { const calls = install(); open(); await loadPreview(); fireEvent.click(screen.getByRole('button', { name: '明确准备原整仓恢复动作' })); await screen.findByRole('heading', { name: '原 PREPARE 待核对' }); await screen.findByText(/原请求已返回/); await readPending(); expect(screen.getByRole('button', { name: '明确确认这一次原恢复动作' })).toBeDisabled(); fireEvent.click(screen.getByRole('checkbox', { name: /我以当前本地USER/ })); fireEvent.click(screen.getByRole('button', { name: '明确确认这一次原恢复动作' })); await screen.findByRole('heading', { name: '原 CONFIRM 待核对' }); await readPending(); fireEvent.click(screen.getByRole('checkbox', { name: /我以当前本地USER/ })); fireEvent.click(screen.getByRole('button', { name: '明确执行或核对同一原恢复动作' })); await screen.findByRole('heading', { name: '原 EXECUTE 待核对' }); await readPending(); expect(screen.getByText(/原回执 .*SETTLED/)).toBeVisible(); const writes = calls.filter((row) => row.method === 'POST'); expect(writes).toHaveLength(4); const prepare = writes[1]!.body as RecoveryPrepare, confirmation = writes[2]!.body as Record<string, unknown>; expect(confirmation.accepted).toBe(true); expect(confirmation.expected_epoch_id).toBe(prepare.expected_epoch_id); expect(writes[3]!.body).toEqual({ expected_epoch_id: prepare.expected_epoch_id, reviewed_effect_hash: confirmation.reviewed_effect_hash }); });
test('AUTHORIZED无独立USER consent保确认未知，绝不拿状态授权执行', async () => { const calls = install({ missingConsent: true }); open(); await loadPreview(); fireEvent.click(screen.getByRole('button', { name: '明确准备原整仓恢复动作' })); await screen.findByRole('heading', { name: '原 PREPARE 待核对' }); await readPending(); fireEvent.click(screen.getByRole('checkbox', { name: /我以当前本地USER/ })); fireEvent.click(screen.getByRole('button', { name: '明确确认这一次原恢复动作' })); await screen.findByRole('heading', { name: '原 CONFIRM 待核对' }); const button = screen.getByRole('button', { name: '独立读取原恢复结果' }); await waitFor(() => expect(button).toBeEnabled()); fireEvent.click(button); await screen.findByText(/MVP状态不能替代FULL USER/); expect(screen.getByRole('heading', { name: '原 CONFIRM 待核对' })).toBeVisible(); expect(screen.getByRole('button', { name: '明确执行或核对同一原恢复动作' })).toBeDisabled(); expect(calls.filter((row) => row.path.endsWith('/execute'))).toHaveLength(0); });
test('execute响应丢失+银行SETTLED无应用receipt仍保原Action/键/body，不自动重试', async () => { const calls = install({ executeUnknown: true, responseLoss: true }); open(); await loadPreview(); fireEvent.click(screen.getByRole('button', { name: '明确准备原整仓恢复动作' })); await screen.findByRole('heading', { name: '原 PREPARE 待核对' }); await readPending(); fireEvent.click(screen.getByRole('checkbox', { name: /我以当前本地USER/ })); fireEvent.click(screen.getByRole('button', { name: '明确确认这一次原恢复动作' })); await screen.findByRole('heading', { name: '原 CONFIRM 待核对' }); await readPending(); fireEvent.click(screen.getByRole('checkbox', { name: /我以当前本地USER/ })); fireEvent.click(screen.getByRole('button', { name: '明确执行或核对同一原恢复动作' })); await screen.findByRole('heading', { name: '原 EXECUTE 待核对' }); await screen.findByRole('alert'); const button = screen.getByRole('button', { name: '独立读取原恢复结果' }); await waitFor(() => expect(button).toBeEnabled()); fireEvent.click(button); await screen.findByText(/缺少应用回执，不宣称现金已恢复/); expect(screen.getByRole('heading', { name: '原 EXECUTE 待核对' })).toBeVisible(); expect(calls.filter((row) => row.path.endsWith('/execute'))).toHaveLength(1); expect(await screen.findByRole('button', { name: '手动恢复同一恢复原请求' })).toBeDisabled(); });
test('他族mutationBlocked仍可自己GET原pending，禁止新preview/confirm/execute', async () => { const saved = intentFor(body); sessionStorage.setItem('bounded-funds-full-recovery-execution-operation-v1:http://http-unit-fixture.local', JSON.stringify(saved)); const calls = install(); open(true); const button = await screen.findByRole('button', { name: '独立读取原恢复结果' }); await waitFor(() => expect(button).toBeEnabled()); fireEvent.click(button); await screen.findByRole('region', { name: '固定原恢复动作' }); expect(screen.getByRole('button', { name: '明确确认这一次原恢复动作' })).toBeDisabled(); expect(calls).toHaveLength(1); expect(calls[0]!.method).toBe('GET'); });
test('刷新workspace不自动网络/POST，必须独立GET才可复核原动作', async () => { const saved = recoveryLookupFixture(intentFor(body)); sessionStorage.setItem('bounded-funds-full-recovery-execution-operation-v1:http://http-unit-fixture.local:workspace', JSON.stringify(saved)); const calls = install(); open(); await screen.findByRole('region', { name: '恢复原动作工作区' }); expect(calls).toHaveLength(0); expect(screen.queryByRole('region', { name: '固定原恢复动作' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '只读刷新原恢复动作' })); await screen.findByRole('region', { name: '固定原恢复动作' }); expect(calls).toHaveLength(1); expect(calls[0]!.method).toBe('GET'); });
test('当前版本prop变更不拿旧preview支持新prepare', async () => { const calls = install(); const view = open(); await loadPreview(); view.rerender(<Panel {...props} expectedVersionId="00000000-0000-0000-0000-000000000999" />); expect(screen.queryByRole('region', { name: '恢复执行范围预览' })).not.toBeInTheDocument(); expect(calls.filter((row) => row.path.endsWith('/prepare'))).toHaveLength(0); });
test('UNKNOWN proof无effect，真实缺项保留且不能准备', async () => { const calls = install({ unknown: true }); open(); await loadPreview(); expect(screen.getByRole('heading', { name: '原范围 UNKNOWN' })).toBeVisible(); expect(screen.getByText('TOOL_ONLY_SOURCE_UNKNOWN · original-source-reference · 原来源尚未证明')).toBeVisible(); expect(screen.getByRole('button', { name: '明确准备原整仓恢复动作' })).toBeDisabled(); expect(calls.filter((row) => row.path.endsWith('/prepare'))).toHaveLength(0); });
test('preview原body保存失败禁止POST，不替换来源/伪造成功', async () => { const calls = install(); open(); fireEvent.click(screen.getByRole('button', { name: '只读加载当前恢复规划与USER身份' })); await screen.findByRole('region', { name: '实际恢复候选' }); vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('TOOL_ONLY_STORAGE_DENIED'); }); fireEvent.click(screen.getByRole('button', { name: '读取服务器原恢复执行预览' })); await screen.findByRole('alert'); expect(calls.every((row) => row.method === 'GET')).toBe(true); expect(screen.queryByRole('region', { name: '恢复执行范围预览' })).not.toBeInTheDocument(); });
