import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { expect, test } from 'vitest';
import GoalReallocationPanel from './GoalReallocationPanel';
import { repairBinding, repairFixture, repairPolicyFixture } from '../tests/goal-reallocation-fixture';
import { installHttpFixture } from '../tests/policy-fixture';
function open(epoch: string | null = repairBinding.epochId) { render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } })}><GoalReallocationPanel goal={{ ...repairBinding.goal, name: '合成源目标' }} userId={repairBinding.userId} epochId={epoch} /></QueryClientProvider>); }
function handler(mode: Parameters<typeof repairFixture>[0] = 'UNKNOWN_USAGE') { const policy = repairPolicyFixture(mode === 'DISABLED'); return installHttpFixture((method) => method === 'GET' ? { simulation: true, bank_authority: false, dedicated_audit_event: false, items: [policy] } : repairFixture(mode)); }
test('初始只GET实际策略目录，选原规则后用户主动只读预览；无回拨写按钮', async () => { const calls = handler(); open(); const select = await screen.findByLabelText('选择原CrossGoalReallocationPolicy'); expect(calls).toHaveLength(1); expect(calls[0]!.method).toBe('GET'); fireEvent.change(select, { target: { value: repairPolicyFixture().policy_id } }); fireEvent.click(screen.getByRole('button', { name: '只读预览当前期修复下界' })); await screen.findByRole('heading', { name: '原当前期回拨预览 · UNKNOWN' }); expect(screen.getByText(/当前核心数学修复下界/)).toBeVisible(); expect(screen.getByText(/candidate_amount_cents=null/)).toBeVisible(); expect(screen.getByText(/累计已用 未知 · 未证明 \/ 累计剩余 未知 · 未证明/)).toBeVisible(); expect(screen.queryByRole('button', { name: /执行回拨|确认回拨|修复资金|创建回拨/ })).not.toBeInTheDocument(); expect(calls[1]!.path).toBe('/api/v1/goal-reallocation/preview'); expect(Object.keys(calls[1]!.body as object)).toHaveLength(5); });
test('默认关闭原规则显示0原caps与BLOCKED但不把数学下界当可执行额', async () => { handler('DISABLED'); open(); fireEvent.change(await screen.findByLabelText('选择原CrossGoalReallocationPolicy'), { target: { value: repairPolicyFixture().policy_id } }); expect(screen.getByText(/原规则启用：否，默认关闭/)).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: '只读预览当前期修复下界' })); await screen.findByRole('heading', { name: '原当前期回拨预览 · BLOCKED' }); expect(screen.getByText('CROSS_GOAL_REALLOCATION_DEFAULT_DISABLED')).toBeVisible(); expect(screen.getByText(/未提供.*candidate_amount_cents=null/)).toBeVisible(); });
test('UNKNOWN数学null不补0，模型缺失不捏造最低保障', async () => { handler('UNKNOWN_MATH'); open(); fireEvent.change(await screen.findByLabelText('选择原CrossGoalReallocationPolicy'), { target: { value: repairPolicyFixture().policy_id } }); fireEvent.click(screen.getByRole('button', { name: '只读预览当前期修复下界' })); await screen.findByRole('heading', { name: '当前核心修复数学 · UNKNOWN' }); expect(screen.getAllByText('未知 · 未证明', { selector: 'dd' })).toHaveLength(5); expect(screen.getByText(/本金释放 ¥0.00，未来收入纳入 ¥0.00/)).toBeVisible(); });
test('无规则/未知epoch明确缺依赖，不自动创建或确认', async () => { const calls = installHttpFixture(() => ({ simulation: true, bank_authority: false, dedicated_audit_event: false, items: [] })); open(null); await screen.findByLabelText('选择原CrossGoalReallocationPolicy'); expect(screen.getByText(/当前epoch未知/)).toBeVisible(); expect(screen.getByText(/没有已存在的显式回拨规则/)).toBeVisible(); expect(screen.getByRole('button', { name: '只读预览当前期修复下界' })).toBeDisabled(); expect(calls).toHaveLength(1); });
test('主动刷新清原预览不自动POST；版本409保原状态与失败，未算成功', async () => { let fail = false; const calls = installHttpFixture((method) => method === 'GET' ? { simulation: true, bank_authority: false, dedicated_audit_event: false, items: [repairPolicyFixture()] } : fail ? new Response(JSON.stringify({ error: { code: 'STALE_POLICY_VERSION', message: '原目标版本已变化', request_id: 'synthetic' } }), { status: 409 }) : repairFixture()); open(); fireEvent.change(await screen.findByLabelText('选择原CrossGoalReallocationPolicy'), { target: { value: repairPolicyFixture().policy_id } }); fireEvent.click(screen.getByRole('button', { name: '只读预览当前期修复下界' })); await screen.findByRole('heading', { name: '原当前期回拨预览 · UNKNOWN' }); fireEvent.click(screen.getByRole('button', { name: '只读刷新原回拨规则' })); expect(screen.queryByRole('heading', { name: '原当前期回拨预览 · UNKNOWN' })).not.toBeInTheDocument(); expect(await screen.findByLabelText('选择原CrossGoalReallocationPolicy')).toHaveValue(''); fail = true; fireEvent.change(screen.getByLabelText('选择原CrossGoalReallocationPolicy'), { target: { value: repairPolicyFixture().policy_id } }); fireEvent.click(screen.getByRole('button', { name: '只读预览当前期修复下界' })); expect(await screen.findByRole('alert')).toHaveTextContent('未生成候选或执行回拨'); expect(calls.filter((call) => call.method === 'POST')).toHaveLength(2); expect(within(screen.getByRole('region', { name: `目标现金紧急回拨预览 ${repairBinding.goal.id}` })).queryByRole('heading', { name: '原当前期回拨预览 · UNKNOWN' })).not.toBeInTheDocument(); });
