import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getFullPolicies } from '../api/full-policies';
import { getOriginalReallocationResponse, parseCrossGoalConfiguration, previewGoalReallocation, repairConditions } from '../api/goal-reallocation';
import type { ReallocationPreview } from '../api/goal-reallocation';
import type { Goal } from '../api/goals';
import { errorMessage } from '../api/http';
import { formatMoneyCents } from '../features/money';

type SourceGoal = Pick<Goal, 'id' | 'name' | 'policy_id' | 'policy_version_id'>;
const money = (n: number | null | undefined) => n === null || n === undefined ? '未知 · 未证明' : `¥${formatMoneyCents(n)}`;
const conditionNames = { HARD_OBLIGATION_SHORTFALL: '硬性义务短缺', LIVING_RESERVE_SHORTFALL: '生活费留存短缺', EMERGENCY_BUFFER_SHORTFALL: '应急缓冲短缺' };
function Preview({ result }: { result: ReallocationPreview }) {
  const d = result.decision, m = d.math, owned = result.goal_ownership, model = result.goal_model;
  return <section className="card readonly-section" aria-label="原当前期回拨预览"><h5>原当前期回拨预览 · {d.state}</h5><p>服务端时点 {result.as_of}；仅当前原三层核心保护，不是全年多期全局最优。</p><p className="notice">可执行候选：未提供（candidate_amount_cents=null）。实际回拨、独立目标确认授权和完整累计用量协议尚未实现；没有移动已归属资金。</p>
    <h6>当前核心修复数学 · {m.status}</h6><dl><dt>原银行现金</dt><dd>{money(m.cash_cents)}</dd><dt>已锁定目标现金</dt><dd>{money(m.locked_goal_cash_cents)}</dd><dt>在途现金占用</dt><dd>{money(m.reserved_cash_cents)}</dd><dt>未归属且未占用现金</dt><dd>{money(m.unowned_unreserved_cash_cents)}</dd><dt>当前核心数学修复下界</dt><dd>{money(m.minimum_repair_cents)}</dd><dt>源目标最低保障以上可释放现金的数学上界</dt><dd>{money(m.source_cash_releasable_above_minimum_cents)}</dd></dl><p>当前登记范围的唯一最低下界：{m.unique_minimum_for_registered_current_scope ? '服务报告已计算，只限此当前三层范围' : '未知，不能称唯一最低'}。本金释放 {money(m.principal_release_cents)}，未来收入纳入 {money(m.future_income_used_cents)}；本次不改持仓放置。</p>
    <ul>{repairConditions.map((condition) => <li key={condition}>{conditionNames[condition]} · 原保护 {money(m.required_by_condition?.[condition])} / 本层增量短缺 {money(m.shortfall_by_condition?.[condition])} · {d.triggered_conditions.includes(condition) ? '原数学触发' : m.status === 'UNKNOWN' ? '未知' : '原数学未触发'}</li>)}</ul><p>累计已用 {money(d.cumulative_used_cents)} / 累计剩余 {money(d.cumulative_remaining_cents)}；累计按同策略生命周期跨版本，不因新版本重置。缺原件不按0推断。</p>
    <h6>产权与资产放置分开</h6>{owned ? <><p>原目标已归属 {money(owned.allocated_cents)}；原归属证据 <code>{owned.ownership_evidence_id ?? '缺失'}</code> · {owned.current_ownership_proof_verified ? '服务报告原证据已核，仍无回拨授权' : '原归属证据未证明'}</p><p>归属现金 · 应用 {money(owned.cash.application_cents)} / 银行 {money(owned.cash.bank_cents)} · {owned.cash.state}；归属本金 · 应用 {money(owned.principal.application_cents)} / 银行 {money(owned.principal.bank_cents)} · {owned.principal.state}</p><p>原持仓引用 {owned.position_ids.join('、') || '本次无原持仓引用'}；回拨数学只讨论现金归属，不推定本金可提前回收。</p></> : <p>原目标归属未提供（null），现金/本金不能补0。</p>}
    {model?.status === 'VERIFIED' ? <p>原完整目标最低保障 {money(model.full_configuration?.minimum_guarantee_cents as number | undefined)} · 原模型证据 <code>{model.evidence_id}</code>；原base版本 <code>{model.base_policy_version_id}</code>。</p> : <p>完整目标模型 {model?.status ?? '未提供（null）'}；最低保障尚未证明，不补造模型。</p>}
    <h6>全部原阻断与未证明项</h6><ul>{d.reasons.map((reason) => <li key={reason}><code>{reason}</code></li>)}</ul>{result.source_issues.map((issue, i) => <p className="notice" key={i}>{issue.code} · {issue.entity_type} · {issue.entity_id ?? '无实体引用'}</p>)}
    <details><summary>当前原保护点、版本与输入摘要</summary><p>回拨规则版本 <code>{result.original_request.expected_policy_version_id}</code>；源目标版本 <code>{result.original_request.expected_goal_policy_version_id}</code>；原epoch <code>{result.epoch_id}</code>。</p><p>对账 <code>{result.reconciliation_input_hash}</code> · 完整保护 <code>{result.full_protection_input_hash}</code> · 原来源绑定 <code>{result.source_binding_hash}</code>。</p><pre className="readonly-raw">{JSON.stringify(result.original_current_protection_point, null, 2)}</pre></details><details><summary>完整原回拨预览HTTP响应</summary><p>此响应是只读计算与原来源报告，不是独立银行效果回执或当前资金授权。</p><pre className="readonly-raw">{getOriginalReallocationResponse(result)}</pre></details>{result.limitations.map((text, i) => <p className="caption" key={i}>{text}</p>)}
  </section>;
}
export default function GoalReallocationPanel({ goal, userId, epochId }: { goal: SourceGoal; userId: string; epochId: string | null }) {
  const query = useQuery({ queryKey: ['full-policies', 'goal-reallocation', userId, epochId], queryFn: getFullPolicies, retry: false, structuralSharing: false, refetchOnWindowFocus: false });
  const [selectedId, setSelectedId] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<ReallocationPreview | null>(null);
  const policies = query.data?.items.filter((p) => p.template_name === 'CrossGoalReallocationPolicy') ?? []; const selected = policies.find((p) => p.policy_id === selectedId);
  const matches = result && result.user_id === userId && result.epoch_id === epochId && result.original_request.source_goal_id === goal.id && result.original_request.expected_goal_policy_version_id === goal.policy_version_id && result.original_request.policy_id === selected?.policy_id && result.original_request.expected_policy_version_id === selected.current_version.version_id;
  let configuration: Record<string, unknown> | null = null, configurationError: string | null = null;
  if (selected) { try { configuration = parseCrossGoalConfiguration(selected.current_version.configuration); } catch (e) { configurationError = errorMessage(e); } }
  async function preview() { if (!selected || !epochId || busy || query.isFetching || query.isError || configurationError) return; setBusy(true); setError(null); setResult(null); try { setResult(await previewGoalReallocation({ goal, userId, epochId }, selected)); } catch (e) { setError(`${errorMessage(e)}；保留原状态，未生成候选或执行回拨。请刷新原目标/规则/epoch后重审。`); } finally { setBusy(false); } }
  return <section className="card readonly-section" aria-label={`目标现金紧急回拨预览 ${goal.id}`}><h4>目标现金紧急回拨 · 只读预览</h4><p>源目标 {goal.name} · <code>{goal.id}</code>。已归属资金默认不可跨目标移动；回拨规则的规划确认不等于资金授权，原目标执行桥仍禁止跨目标启用。</p><button type="button" disabled={busy || query.isFetching} onClick={() => { setResult(null); setError(null); setSelectedId(''); void query.refetch(); }}>只读刷新原回拨规则</button>{query.isPending && <p role="status">正在读取真实完整策略版本…</p>}{query.isError && <p role="alert">{errorMessage(query.error)}；未以旧规则当本次成功。</p>}{busy && <p role="status">服务端正在读取原对账、目标模型与保护，未移动资金…</p>}{error && <p role="alert">{error}</p>}{configurationError && <p role="alert">{configurationError}；不提交无效原配置。</p>}
    {!epochId && <p className="notice">当前epoch未知；缺当前原周期绑定，预览暂停。</p>}{!query.isError && query.data && <><label>选择原CrossGoalReallocationPolicy <select value={selectedId} disabled={busy || query.isFetching} onChange={(e) => { setSelectedId(e.target.value); setResult(null); setError(null); }}><option value="">先选择已存在的原规则</option>{policies.map((p) => <option key={p.policy_id} value={p.policy_id} disabled={p.epoch_id !== epochId || p.current_version.confirmation.user_id !== userId}>{p.name} · {p.effective_status} · 原v{p.current_version.version_number}{p.epoch_id !== epochId ? ' · 历史epoch' : ''}</option>)}</select></label>{policies.length === 0 && <p>没有已存在的显式回拨规则；默认关闭。可在策略中心准备并明确确认规划规则，本面板不自动创建或确认。</p>}{selected && configuration && <section aria-label="选定原回拨规则"><p>原规则启用：{configuration.enabled ? '是，仅规划规则' : '否，默认关闭'}；实际有效状态 {selected.effective_status}；当前引用 {selected.reference_validation}；规划确认 {selected.planning_confirmation_valid ? '原服务报告有效，仍无银行权限' : '当前无有效规划确认'}。</p><p>单次上限 {money(configuration.single_action_cap_cents as number)} / 同策略生命周期累计上限 {money(configuration.total_cap_cents as number)}；目的范围 PROTECTED_CASH。</p><p>原允许源目标 {(configuration.source_goal_ids as string[]).join('、') || '未声明'}；原紧急条件 {(configuration.emergency_conditions as string[]).join('、') || '未声明'}。</p><details><summary>选定原配置与确认JSON</summary><pre className="readonly-raw">{JSON.stringify(selected, null, 2)}</pre></details></section>}<button type="button" disabled={!selected || !epochId || !!configurationError || busy || query.isFetching || selected.epoch_id !== epochId || selected.current_version.confirmation.user_id !== userId} onClick={() => void preview()}>只读预览当前期修复下界</button></>}
    {matches && !query.isError && !query.isFetching && result && <Preview result={result} />}<p className="simulation-note">模拟只读预览，不是真实资金执行。candidate=null/累计用量UNKNOWN保留；没有实际回拨、修复、原确认或自动重试按钮。</p><a href="#policies">查看原策略与修改影响</a>
  </section>;
}
