import { webcrypto } from 'node:crypto';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { releaseBinding, releaseIntentFixture, releaseLookupFixture, releaseResponseFixture, releaseReviewFixture } from '../tests/goal-release-authorization-fixture';
import type { ReleaseResponse } from '../api/goal-release-authorizations';
let operation: typeof import('../features/goal-release-authorization-operation'), panel: typeof import('./GoalReleaseAuthorizationPanel'), queries: typeof import('@tanstack/react-query');
const endpoint = 'http://unit-goal-release-ui.local';
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubEnv('VITE_API_BASE_URL', endpoint); vi.stubGlobal('crypto', webcrypto); operation = await import('../features/goal-release-authorization-operation'); panel = await import('./GoalReleaseAuthorizationPanel'); queries = await import('@tanstack/react-query'); });
afterEach(() => { sessionStorage.clear(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); });
type Options = { lost?: boolean; reject?: boolean; notFound?: boolean; badLookup?: boolean; scopeState?: ReleaseResponse['current_scope_status']; empty?: boolean };
async function transport(options: Options = {}) {
  const r = await releaseReviewFixture(), calls: { path: string; method: string; body: unknown; raw: string | undefined }[] = [];
  vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const path = new URL(String(input)).pathname, method = init?.method ?? 'GET', raw = init?.body === undefined ? undefined : String(init.body); const body: unknown = raw === undefined ? undefined : JSON.parse(raw); calls.push({ path, method, body, raw }); let data: unknown;
    if (path === '/api/v1/full-policies') data = { simulation: true, bank_authority: false, dedicated_audit_event: false, items: options.empty ? [] : [r.policy] };
    else if (path === '/api/v1/goals') data = { simulation: true, items: r.sources.map((s) => s.goal) };
    else if (path.endsWith('/full-model')) data = r.sources.find((s) => path.includes(s.goal.id))!.model;
    else if (path.endsWith('/preview')) data = r.preview;
    else if (path.endsWith('/confirm')) { const original = operation.getGoalReleaseAuthorizationOperation().pending!; expect(sessionStorage.getItem(`bounded-funds-goal-release-authorization-operation-v1:${endpoint}`)).toBe(JSON.stringify(original)); expect(raw).toBe(original.body_json); if (options.lost) throw new Error('SYNTHETIC_LOST_REPLY'); if (options.reject) return new Response(JSON.stringify({ error: { code: 'STALE_RELEASE_POLICY', message: 'SYNTHETIC409', request_id: 'UNIT_ONLY' } }), { status: 409 }); data = await releaseResponseFixture(original, options.scopeState); }
    else if (path.includes('/by-key/')) { const original = operation.getGoalReleaseAuthorizationOperation().pending!, result = await releaseLookupFixture(original, !options.notFound, options.scopeState); if (options.badLookup) result.original!.original_authorization.original_request.reviewed_scope_hash = '0'.repeat(64); data = result; }
    else data = r.policy;
    return new Response(JSON.stringify(data));
  })); return { r, calls };
}
function open(blocked = false, epoch: string | null = releaseBinding.epochId) { const Component = panel.default, client = new queries.QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } }); return render(<queries.QueryClientProvider client={client}><Component goal={{ ...releaseBinding.goal, name: '合成第一来源目标' }} userId={releaseBinding.userId} epochId={epoch} mutationBlocked={blocked} /></queries.QueryClientProvider>); }
async function reviewScope() { const fixture = await releaseReviewFixture(); fireEvent.change(await screen.findByLabelText('选择已存在的当前回拨规则'), { target: { value: fixture.policy.policy_id } }); fireEvent.click(screen.getByRole('button', { name: '只读准备完整专用授权范围' })); return screen.findByRole('region', { name: '专用授权明确复核' }); }
const acceptance = '我已逐个复核全部源目标、原版本与最低保障、受保护现金目的、紧急条件、有效期和单次/累计上限，明确确认此专用范围';
test('初始只GET，明确按钮准备实际来源全部两Goal+原最低保障；checkbox之前无confirm/execute', async () => { const { calls } = await transport(); open(); await screen.findByLabelText('选择已存在的当前回拨规则'); expect(calls).toHaveLength(1); expect(calls[0]!.method).toBe('GET'); const review = await reviewScope(); expect(within(review).getByRole('heading', { name: '全部源目标 · 2 个' })).toBeVisible(); expect(within(review).getByText(/最低保障 ¥230.03/)).toBeVisible(); expect(within(review).getByText(/¥300.07/)).toBeVisible(); expect(within(review).getByText(/¥700.01/)).toBeVisible(); expect(screen.getByRole('button', { name: '明确确认专用回拨授权范围' })).toBeDisabled(); expect(calls.filter((c) => c.method === 'POST')).toHaveLength(1); expect(calls.every((c) => !c.path.endsWith('/confirm'))).toBe(true); expect(screen.queryByRole('button', { name: /执行回拨|修复资金/ })).not.toBeInTheDocument(); });
test('显式接受后发送exact5字段并先持久原scope/body/key；HTTP200仍pending，原GET匹配才解门', async () => { const { calls } = await transport(); open(); await reviewScope(); fireEvent.click(screen.getByLabelText(acceptance)); fireEvent.click(screen.getByRole('button', { name: '明确确认专用回拨授权范围' })); await screen.findByText(/收到原服务确认记录/); const intent = operation.getGoalReleaseAuthorizationOperation().pending!; const confirm = calls.find((c) => c.path.endsWith('/confirm'))!; expect(confirm.raw).toBe(intent.body_json); expect(Object.keys(confirm.body as object).sort()).toEqual(['accepted', 'expected_epoch_id', 'expected_policy_version_id', 'idempotency_key', 'reviewed_scope_hash']); expect(intent.reviewed_scope.source_goals).toHaveLength(2); expect(screen.getByRole('button', { name: '明确确认专用回拨授权范围' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: '只读核对原专用授权' })); await screen.findByText(/已解除本族待核对门/); expect(operation.getGoalReleaseAuthorizationOperation().pending).toBeNull(); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(1); expect(screen.getAllByText(/执行 NOT_IMPLEMENTED/).length).toBeGreaterThan(0); });
test('响应丢失及NOT_FOUND保持原键，不提供重新POST；错误原请求查询不能解除', async () => { const options: Options = { lost: true, notFound: true }, { calls } = await transport(options); open(); await reviewScope(); fireEvent.click(screen.getByLabelText(acceptance)); fireEvent.click(screen.getByRole('button', { name: '明确确认专用回拨授权范围' })); await screen.findByRole('alert'); const intent = operation.getGoalReleaseAuthorizationOperation().pending; fireEvent.click(screen.getByRole('button', { name: '只读核对原专用授权' })); await screen.findByText(/不是最终未提交证明/); expect(operation.getGoalReleaseAuthorizationOperation().pending).toEqual(intent); options.notFound = false; options.badLookup = true; fireEvent.click(screen.getByRole('button', { name: '只读核对原专用授权' })); await screen.findByText(/未解除原专用授权请求/); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(1); expect(operation.getGoalReleaseAuthorizationOperation().pending).toEqual(intent); });
test('HTTP409仍原pending，用户只读核对STALE原记录后不当当前资金授权', async () => { const { calls } = await transport({ reject: true, scopeState: 'STALE' }); open(); await reviewScope(); fireEvent.click(screen.getByLabelText(acceptance)); fireEvent.click(screen.getByRole('button', { name: '明确确认专用回拨授权范围' })); await screen.findByText(/SYNTHETIC409/); expect(operation.getGoalReleaseAuthorizationOperation().pending).not.toBeNull(); fireEvent.click(screen.getByRole('button', { name: '只读核对原专用授权' })); await screen.findByRole('heading', { name: '专用授权原记录 · STALE' }); expect(screen.getByText(/原记录只是历史确认/)).toBeVisible(); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(1); });
test('刷新与来源prop版本变化撤掉旧复核；他族blocked允许只读来源但确认禁用', async () => { const { calls } = await transport(); const view = open(); await reviewScope(); fireEvent.click(screen.getByLabelText(acceptance)); fireEvent.click(screen.getByRole('button', { name: '只读刷新专用授权来源' })); expect(screen.queryByRole('region', { name: '专用授权明确复核' })).not.toBeInTheDocument(); await reviewScope(); const Component = panel.default, client = new queries.QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } }); view.rerender(<queries.QueryClientProvider client={client}><Component goal={{ ...releaseBinding.goal, name: '原目标', policy_version_id: '76000000-0000-4000-8000-000000000010' }} userId={releaseBinding.userId} epochId={releaseBinding.epochId} mutationBlocked /></queries.QueryClientProvider>); expect(screen.queryByRole('region', { name: '专用授权明确复核' })).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: '只读刷新专用授权来源' })).toBeEnabled(); expect(calls.every((c) => !c.path.endsWith('/confirm'))).toBe(true); });
test('历史epoch/他族blocked仍自身GET可核；刷新恢复无自动POST', async () => { const intent = await releaseIntentFixture(); sessionStorage.setItem(`bounded-funds-goal-release-authorization-operation-v1:${endpoint}`, JSON.stringify(intent)); const { calls } = await transport({ scopeState: 'ARCHIVED' }); open(true, '76000000-0000-4000-8000-000000000011'); await screen.findByRole('region', { name: '待核对专用授权原请求' }); expect(screen.getByRole('button', { name: '只读核对原专用授权' })).toBeEnabled(); fireEvent.click(screen.getByRole('button', { name: '只读核对原专用授权' })); await screen.findByRole('heading', { name: '专用授权原记录 · ARCHIVED' }); expect(operation.getGoalReleaseAuthorizationOperation().pending).toBeNull(); expect(calls.every((c) => c.method === 'GET')).toBe(true); expect(calls.find((c) => c.path.includes('/by-key/'))!.path).toContain(intent.body.expected_epoch_id); });
test('无规则/未知epoch是实际缺依赖；不能用引导ticks或本地body冒专用确认', async () => { const { calls } = await transport({ empty: true }); open(false, null); await screen.findByLabelText('选择已存在的当前回拨规则'); expect(screen.getByText(/当前epoch未知/)).toBeVisible(); expect(screen.getByText(/尚无显式回拨规则/)).toBeVisible(); expect(screen.getByRole('button', { name: '只读准备完整专用授权范围' })).toBeDisabled(); expect(calls).toHaveLength(1); });
