import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import GoalAdjustmentsPanel from './GoalAdjustmentsPanel';
import { adjustmentGoals, adjustmentOwner, adjustmentPreview, adjustmentRead, adjustmentSelection } from '../tests/goal-adjustment-fixture';

afterEach(() => vi.unstubAllGlobals());
async function open(onReviewCandidate = vi.fn(), blocked = false) { const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(adjustmentRead()), { status: 200 })).mockResolvedValueOnce(new Response(JSON.stringify(adjustmentPreview()), { status: 200 })); vi.stubGlobal('fetch', fetch); render(<GoalAdjustmentsPanel ownerUserId={adjustmentOwner} goals={adjustmentGoals()} onReviewCandidate={onReviewCandidate} blocked={blocked} />); expect(fetch).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: '只读读取当前调整依据' })); await screen.findByRole('combobox', { name: '调整目标' }); fireEvent.change(screen.getByRole('combobox', { name: '调整目标' }), { target: { value: adjustmentRead().goals[0]!.goal_id } }); return fetch; }
async function deadline() { const selected = adjustmentSelection().adjustments[0]!; if (selected.field !== 'deadline') throw new Error('Synthetic fixture must register a deadline'); fireEvent.change(screen.getByRole('combobox', { name: '调整字段' }), { target: { value: 'deadline' } }); fireEvent.change(screen.getByLabelText('明确范围下界'), { target: { value: selected.lower_date } }); fireEvent.change(screen.getByLabelText('明确范围上界'), { target: { value: selected.upper_date } }); fireEvent.click(screen.getByRole('button', { name: '仅预览所选范围' })); }
it('requires manual read/selection/preview/adoption and never confirms', async () => { const adopt = vi.fn(); const fetch = await open(adopt); await deadline(); await screen.findByRole('heading', { name: 'PROPOSAL' }); expect(fetch).toHaveBeenCalledTimes(2); expect(JSON.parse(fetch.mock.calls[1]![1]!.body)).toEqual(adjustmentSelection()); expect(adopt).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: '采用候选进入原模型复核' })); expect(adopt).toHaveBeenCalledWith(adjustmentRead().goals[0]!.goal_id, adjustmentPreview().version_previews[0]!.actual_existing_preview); expect(fetch).toHaveBeenCalledTimes(2); expect(screen.getByText(/月最低贡献是当前期偏好/)).toBeInTheDocument(); });
it('edits remove old candidate and block stale adoption', async () => { await open(); await deadline(); await screen.findByRole('heading', { name: 'PROPOSAL' }); fireEvent.change(screen.getByLabelText('明确范围上界'), { target: { value: '2026-10-09' } }); expect(screen.queryByRole('button', { name: '采用候选进入原模型复核' })).not.toBeInTheDocument(); });
it('global block prevents preview/adoption but permits GET', async () => { const fetch = await open(vi.fn(), true); fireEvent.change(screen.getByLabelText('明确范围下界'), { target: { value: '0' } }); fireEvent.change(screen.getByLabelText('明确范围上界'), { target: { value: '0' } }); expect(screen.getByRole('button', { name: '仅预览所选范围' })).toBeDisabled(); expect(fetch).toHaveBeenCalledTimes(1); });
it('missing actual owner or goals produces no request', () => { const fetch = vi.fn(); vi.stubGlobal('fetch', fetch); render(<GoalAdjustmentsPanel ownerUserId={undefined} goals={undefined} />); expect(screen.getByRole('button', { name: '只读读取当前调整依据' })).toBeDisabled(); expect(fetch).not.toHaveBeenCalled(); });
it('HTTP unknown errors do not produce a fake proposal or confirmation', async () => { const fetch = await open(); fetch.mockReset(); fetch.mockResolvedValueOnce(new Response(JSON.stringify({ error: { code: 'STALE_ADJUSTMENT_INPUT', message: '真实版本已变化' } }), { status: 409 })); fireEvent.change(screen.getByLabelText('明确范围下界'), { target: { value: '0' } }); fireEvent.change(screen.getByLabelText('明确范围上界'), { target: { value: '0' } }); fireEvent.click(screen.getByRole('button', { name: '仅预览所选范围' })); await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('真实版本已变化')); expect(screen.queryByRole('button', { name: '采用候选进入原模型复核' })).not.toBeInTheDocument(); });
