import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { seasonalFixture, seasonalIntentFixture, seasonalLookupFixture, seasonalProofFixture, seasonalReceiptFixture, unknownSeasonalPreview } from '../tests/seasonal-adoption-fixture';
let Panel: typeof import('./SeasonalReserveAdoptionPanel')['default'], Recovery: typeof import('./SeasonalReserveAdoptionPanel')['SeasonalAdoptionOriginalRecoveryPanel'], op: typeof import('../features/seasonal-adoption-operation');
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubGlobal('crypto', webcrypto); vi.stubEnv('VITE_API_BASE_URL', 'http://seasonal-panel.local'); const module = await import('./SeasonalReserveAdoptionPanel'); Panel = module.default; Recovery = module.SeasonalAdoptionOriginalRecoveryPanel; op = await import('../features/seasonal-adoption-operation'); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); sessionStorage.clear(); });
async function transport({ unknown = false, lose = false, found = true, agent = false } = {}) {
  const f = await seasonalFixture(), calls: { path: string; method: string; body: unknown }[] = [];
  vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, options?: RequestInit) => { const path = new URL(String(input)).pathname, method = options?.method ?? 'GET', body = options?.body ? JSON.parse(String(options.body)) : null; calls.push({ path, method, body });
    if (path.endsWith('/local-actor/session')) { const identity = structuredClone(f.identity); if (agent) identity.principal.role = 'AGENT'; return new Response(JSON.stringify(identity)); }
    if (path.endsWith('/preview')) return new Response(JSON.stringify(unknown ? unknownSeasonalPreview() : f.preview));
    if (path.endsWith('/confirm')) { if (lose) throw new Error('SYNTHETIC_RESPONSE_LOSS'); const original = op.getSeasonalAdoptionOperation().pending; if (!original) throw new Error('SYNTHETIC_MISSING_PERSISTED_ORIGINAL'); return new Response(JSON.stringify(await seasonalReceiptFixture(original))); }
    if (path.includes('/by-key/')) { const original = op.getSeasonalAdoptionOperation().pending; if (!original) throw new Error('SYNTHETIC_MISSING_PERSISTED_ORIGINAL'); return new Response(JSON.stringify(await seasonalLookupFixture(original, found))); }
    return new Response(JSON.stringify(seasonalProofFixture()));
  })); return { f, calls };
}
function open(f: Awaited<ReturnType<typeof seasonalFixture>>, blocked = false) { return render(<Panel fullPolicy={f.full} userId={f.scope.user_id} epochId={f.scope.epoch_id} mutationBlocked={blocked} />); }
async function preview(f: Awaited<ReturnType<typeof seasonalFixture>>) { await waitFor(() => expect(op.getSeasonalAdoptionOperation().recovering).toBe(false)); fireEvent.change(screen.getByLabelText('用户指定登记节日窗口 ID'), { target: { value: f.scope.window_id } }); fireEvent.click(screen.getByText('只读预览原节日建议采纳')); await screen.findByRole('region', { name: '季节采纳完整复核' }); }
async function accept() { fireEvent.click(screen.getByText('只读检查采纳USER会话')); await screen.findByText(/已读取本地签名 USER/); fireEvent.change(screen.getByLabelText('采纳理由'), { target: { value: '合成明确固定来源复核' } }); fireEvent.click(screen.getByLabelText('我已复核原周期、完整来源及服务器固定金额，明确采纳')); }
test('默认无自动POST，原建议金额只读、来源完整、未登录USER不能确认', async () => { const { f, calls } = await transport(); open(f); expect(calls).toEqual([]); await preview(f); expect(screen.getByText('明确确认原季节储备采纳')).toBeDisabled(); expect(screen.getByText('¥18.00')).toBeVisible(); expect(screen.getByText(/两个|原历史所需调整/)).toBeVisible(); expect(screen.queryByLabelText('采纳金额')).toBeNull(); expect(calls.filter((c) => c.method === 'POST').map((c) => c.path.split('/').at(-1))).toEqual(['preview']); });
test('签名USER手动复核后精确CONFIRM，POST200保原门，独立GET才能解除', async () => { const { f, calls } = await transport(); open(f); await preview(f); await accept(); fireEvent.click(screen.getByText('明确确认原季节储备采纳')); await screen.findByText(/收到采纳响应/); const intent = op.getSeasonalAdoptionOperation().pending; expect(intent).not.toBeNull(); expect(calls.find((c) => c.path.endsWith('/confirm'))!.body).toEqual(intent!.body); expect(JSON.stringify(intent!.body)).not.toMatch(/amount_cents|role|actor|time/); fireEvent.click(screen.getByText('只读核对原季节采纳请求')); await waitFor(() => expect(op.getSeasonalAdoptionOperation().pending).toBeNull()); await screen.findByRole('region', { name: '原季节采纳回执' }); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(1); });
test('丢响应/NOT_FOUND保原身份，外部门及策略列表缺失也可薄GET恢复', async () => { const { f, calls } = await transport({ lose: true, found: false }); const view = open(f); await preview(f); await accept(); fireEvent.click(screen.getByText('明确确认原季节储备采纳')); await screen.findByRole('alert'); const original = op.getSeasonalAdoptionOperation().pending; expect(original).not.toBeNull(); view.unmount(); render(<Recovery />); await screen.findByText('只读核对原季节采纳请求'); fireEvent.click(screen.getByText('只读核对原季节采纳请求')); await screen.findByText(/原键未终局/); expect(op.getSeasonalAdoptionOperation().pending).toEqual(original); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(1); expect(calls.filter((c) => c.path.endsWith('/local-actor/session'))).toHaveLength(1); });
test('当前版本改变不能采纳旧候选，刷新当前READ_ONLY清复核不继承确认', async () => { const { f, calls } = await transport(); const view = open(f); await preview(f); await accept(); const next = { ...f.full, current_version: { ...f.full.current_version, version_id: '00000000-0000-0000-0000-000000000099' } }; view.rerender(<Panel fullPolicy={next} userId={f.scope.user_id} epochId={f.scope.epoch_id} />); expect(screen.getByText('明确确认原季节储备采纳')).toBeDisabled(); fireEvent.click(screen.getByText('只读刷新当前季节采纳')); await screen.findByRole('region', { name: '当前季节采纳状态' }); expect(screen.queryByRole('region', { name: '季节采纳完整复核' })).toBeNull(); expect(screen.getByText(/当前状态 ADVICE_ONLY/)).toBeVisible(); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(0); });
test('同version策略已暂停或引用UNKNOWN也不能继续旧复核，原只读GET仍可达', async () => { const { f, calls } = await transport(); const view = open(f); await preview(f); await accept(); view.rerender(<Panel fullPolicy={{ ...f.full, effective_status: 'SUSPENDED', planning_confirmation_valid: false, reference_validation: 'CHANGED_OR_UNAVAILABLE' }} userId={f.scope.user_id} epochId={f.scope.epoch_id} />); expect(screen.getByText('明确确认原季节储备采纳')).toBeDisabled(); expect(screen.getByText('只读预览原节日建议采纳')).toBeDisabled(); expect(screen.getByText('只读刷新当前季节采纳')).toBeEnabled(); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(0); });
test('UNKNOWN来源保持null不能确认、AGENT会话不能假称USER', async () => { const { f, calls } = await transport({ unknown: true, agent: true }); open(f); await waitFor(() => expect(op.getSeasonalAdoptionOperation().recovering).toBe(false)); fireEvent.change(screen.getByLabelText('用户指定登记节日窗口 ID'), { target: { value: f.scope.window_id } }); fireEvent.click(screen.getByText('只读预览原节日建议采纳')); await screen.findByText(/ACTUAL_COMPLETE_HISTORY_NOT_PROVEN/); expect(screen.queryByText('明确确认原季节储备采纳')).toBeNull(); fireEvent.click(screen.getByText('只读检查采纳USER会话')); await screen.findByRole('alert'); expect(calls.filter((c) => c.path.endsWith('/confirm'))).toHaveLength(0); });
test('其他族门禁POST和预览，自身持久原键GET仍可用，不依赖当前USER', async () => { const { f, calls } = await transport(); const intent = await seasonalIntentFixture(); await op.beginSeasonalAdoptionOperation(intent); op.endSeasonalAdoptionAttempt(); open(f, true); expect(screen.getByText('只读预览原节日建议采纳')).toBeDisabled(); fireEvent.click(screen.getByText('只读核对原季节采纳请求')); await waitFor(() => expect(op.getSeasonalAdoptionOperation().pending).toBeNull()); expect(calls.every((c) => c.method === 'GET')).toBe(true); });
