"""Create sixteen MVP persistence tables

Revision ID: 0001_mvp_tables
Revises:
"""

import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_mvp_tables"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_products",
        sa.Column("product_code", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("risk_level", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "principal_fluctuation", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("minimum_purchase_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("lock_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("redemption_delay_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("annual_yield_bps", sa.Integer(), server_default="0", nullable=False),
        sa.Column("early_withdrawal_loss_bps", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "maturity_rule",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "early_withdrawal_rule",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "auto_purchase_allowed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "auto_redeem_allowed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asset_class IN ('CASH', 'CASH_MGMT_T0', 'CASH_MGMT_T1', 'FIXED_DEPOSIT', "
            "'FIXED_DEPOSIT_7D', 'FIXED_DEPOSIT_30D', 'FIXED_DEPOSIT_90D', 'LOW_RISK_TERM')",
            name=op.f("ck_asset_products_asset_class"),
        ),
        sa.CheckConstraint(
            "annual_yield_bps BETWEEN 0 AND 10000", name=op.f("ck_asset_products_yield_range")
        ),
        sa.CheckConstraint(
            "early_withdrawal_loss_bps BETWEEN 0 AND 10000",
            name=op.f("ck_asset_products_loss_range"),
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_until >= effective_from",
            name=op.f("ck_asset_products_effective_window"),
        ),
        sa.CheckConstraint(
            "lock_days >= 0 AND redemption_delay_days >= 0",
            name=op.f("ck_asset_products_durations"),
        ),
        sa.CheckConstraint(
            "minimum_purchase_cents >= 0", name=op.f("ck_asset_products_nonnegative_minimum")
        ),
        sa.CheckConstraint("risk_level BETWEEN 0 AND 5", name=op.f("ck_asset_products_risk_level")),
        sa.CheckConstraint("version_number > 0", name=op.f("ck_asset_products_positive_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_products")),
        sa.UniqueConstraint(
            "product_code", "version_number", name="uq_asset_products_code_version"
        ),
    )
    op.create_table(
        "users",
        sa.Column("external_ref", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Shanghai", nullable=False),
        sa.Column("is_simulated", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("is_simulated", name=op.f("ck_users_simulation_only")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_ref", name=op.f("uq_users_external_ref")),
    )
    op.create_table(
        "accounts",
        sa.Column("external_ref", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("bank_code", sa.String(length=16), server_default="ICBC", nullable=False),
        sa.Column("account_type", sa.String(length=24), server_default="CASH", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="CNY", nullable=False),
        sa.Column("balance_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_type IN ('CASH', 'GOAL', 'CREDIT_CARD', 'CASH_MANAGEMENT', 'FIXED_DEPOSIT')",
            name=op.f("ck_accounts_account_type"),
        ),
        sa.CheckConstraint(
            "bank_code = 'ICBC' AND currency = 'CNY'", name=op.f("ck_accounts_icbc_cny_only")
        ),
        sa.CheckConstraint("balance_cents >= 0", name=op.f("ck_accounts_nonnegative_balance")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_accounts_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_accounts_id")),
        sa.UniqueConstraint("user_id", "external_ref", name="uq_accounts_user_external_ref"),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "decision_runs",
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("trigger_type", sa.String(length=48), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "policy_version_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=24), server_default="PENDING", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "snapshot_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_decision_runs_snapshot_hash")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'BLOCKED')",
            name=op.f("ck_decision_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_decision_runs_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_runs")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_decision_runs_id")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_decision_runs_user_idempotency"),
    )
    op.create_index(
        "ix_decision_runs_user_as_of", "decision_runs", ["user_id", "as_of"], unique=False
    )
    op.create_index(op.f("ix_decision_runs_user_id"), "decision_runs", ["user_id"], unique=False)
    op.create_table(
        "evidence_items",
        sa.Column("evidence_level", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=48), nullable=False),
        sa.Column("source_ref", sa.String(length=160), nullable=False),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="VALID", nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_evidence_items_content_hash")
        ),
        sa.CheckConstraint(
            "evidence_level IN ('BANK_CONFIRMED', 'BANK_OBSERVED', 'USER_DECLARED', "
            "'MODEL_INFERRED', 'USER_CONFIRMED_POLICY')",
            name=op.f("ck_evidence_items_evidence_level"),
        ),
        sa.CheckConstraint(
            "status IN ('VALID', 'CONFLICTED', 'UNKNOWN', 'SUPERSEDED')",
            name=op.f("ck_evidence_items_status"),
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_evidence_items_not_self_superseding"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_evidence_items_valid_window"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id", "user_id"],
            ["evidence_items.id", "evidence_items.user_id"],
            name=op.f("fk_evidence_items_supersedes_id_evidence_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_evidence_items_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_evidence_items_id")),
    )
    op.create_index(op.f("ix_evidence_items_user_id"), "evidence_items", ["user_id"], unique=False)
    op.create_index(
        "ix_evidence_items_user_source",
        "evidence_items",
        ["user_id", "source_type", "source_ref"],
        unique=False,
    )
    op.create_table(
        "policies",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("policy_type", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="PROPOSED", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DISCOVERED', 'PROPOSED', 'CONFIRMED', 'ACTIVE', 'MODIFIED', "
            "'SUSPENDED', 'EXPIRED', 'REVOKED')",
            name=op.f("ck_policies_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_policies_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_policies_id")),
    )
    op.create_index(op.f("ix_policies_user_id"), "policies", ["user_id"], unique=False)
    op.create_table(
        "credit_card_bills",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("source_ref", sa.String(length=160), nullable=False),
        sa.Column("statement_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column("minimum_due_cents", sa.BigInteger(), nullable=False),
        sa.Column("paid_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=24), server_default="UNPAID", nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE')",
            name=op.f("ck_credit_card_bills_status"),
        ),
        sa.CheckConstraint(
            "0 <= minimum_due_cents AND minimum_due_cents <= total_cents",
            name=op.f("ck_credit_card_bills_amounts"),
        ),
        sa.CheckConstraint(
            "0 <= paid_cents AND paid_cents <= total_cents",
            name=op.f("ck_credit_card_bills_paid_amount"),
        ),
        sa.CheckConstraint(
            "due_date >= statement_date", name=op.f("ck_credit_card_bills_due_date")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name=op.f("fk_credit_card_bills_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "user_id"],
            ["evidence_items.id", "evidence_items.user_id"],
            name=op.f("fk_credit_card_bills_evidence_id_evidence_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_credit_card_bills_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_card_bills")),
        sa.UniqueConstraint("account_id", "source_ref", name="uq_credit_card_bills_account_source"),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_credit_card_bills_id")),
    )
    op.create_index(
        op.f("ix_credit_card_bills_user_id"), "credit_card_bills", ["user_id"], unique=False
    )
    op.create_table(
        "policy_proposals",
        sa.Column("source_type", sa.String(length=48), nullable=False),
        sa.Column("source_text", sa.Text(), server_default="", nullable=False),
        sa.Column("compiler_version", sa.String(length=64), nullable=False),
        sa.Column(
            "proposed_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "evidence_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=24), server_default="PROPOSED", nullable=False),
        sa.Column("confirmed_policy_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence_ids) = 'array'", name=op.f("ck_policy_proposals_evidence_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(proposed_configuration) = 'object'",
            name=op.f("ck_policy_proposals_configuration_object"),
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED', 'CONFIRMED', 'REJECTED', 'EXPIRED')",
            name=op.f("ck_policy_proposals_status"),
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_policy_id", "user_id"],
            ["policies.id", "policies.user_id"],
            name=op.f("fk_policy_proposals_confirmed_policy_id_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_policy_proposals_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_proposals")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_policy_proposals_id")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_policy_proposals_user_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_policy_proposals_user_id"), "policy_proposals", ["user_id"], unique=False
    )
    op.create_table(
        "policy_versions",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "confirmation",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_reason", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "evidence_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "impact_analysis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_policy_versions_content_hash")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(configuration) = 'object'",
            name=op.f("ck_policy_versions_configuration_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence_ids) = 'array'", name=op.f("ck_policy_versions_evidence_array")
        ),
        sa.CheckConstraint(
            "previous_hash IS NULL OR previous_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_policy_versions_previous_hash"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from",
            name=op.f("ck_policy_versions_valid_window"),
        ),
        sa.CheckConstraint("version_number > 0", name=op.f("ck_policy_versions_positive_version")),
        sa.ForeignKeyConstraint(
            ["policy_id", "user_id"],
            ["policies.id", "policies.user_id"],
            name=op.f("fk_policy_versions_policy_id_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_policy_versions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint("id", "policy_id", "user_id", name="uq_policy_versions_id_policy_user"),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_policy_versions_id")),
        sa.UniqueConstraint(
            "policy_id", "version_number", name="uq_policy_versions_policy_version"
        ),
    )
    op.create_index(
        op.f("ix_policy_versions_user_id"), "policy_versions", ["user_id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("source_ref", sa.String(length=160), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_cents", sa.BigInteger(), nullable=True),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("counterparty_ref", sa.String(length=160), nullable=True),
        sa.Column("is_one_off", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "category_confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('CREDIT', 'DEBIT')", name=op.f("ck_transactions_direction")
        ),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_transactions_positive_amount")),
        sa.CheckConstraint(
            "balance_after_cents >= 0", name=op.f("ck_transactions_nonnegative_balance_after")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "user_id"],
            ["evidence_items.id", "evidence_items.user_id"],
            name=op.f("fk_transactions_evidence_id_evidence_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transactions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("account_id", "source_ref", name="uq_transactions_account_source"),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_transactions_id")),
    )
    op.create_index(
        "ix_transactions_account_occurred",
        "transactions",
        ["account_id", "occurred_at"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_table(
        "decision_constraints",
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column("constraint_key", sa.String(length=120), nullable=False),
        sa.Column("is_hard", sa.Boolean(), nullable=False),
        sa.Column("satisfied", sa.Boolean(), nullable=True),
        sa.Column("required_cents", sa.BigInteger(), nullable=True),
        sa.Column("available_cents", sa.BigInteger(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("calculation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "required_cents >= 0", name=op.f("ck_decision_constraints_nonnegative_required")
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_id", "user_id"],
            ["decision_runs.id", "decision_runs.user_id"],
            name=op.f("fk_decision_constraints_decision_run_id_decision_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id", "user_id"],
            ["policy_versions.id", "policy_versions.user_id"],
            name=op.f("fk_decision_constraints_policy_version_id_policy_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_decision_constraints_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_constraints")),
        sa.UniqueConstraint(
            "decision_run_id", "constraint_key", name="uq_decision_constraints_run_key"
        ),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_decision_constraints_id")),
    )
    op.create_index(
        op.f("ix_decision_constraints_user_id"), "decision_constraints", ["user_id"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("target_cents", sa.BigInteger(), nullable=False),
        sa.Column("allocated_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("deadline", sa.Date(), nullable=False),
        sa.Column("monthly_min_cents", sa.BigInteger(), nullable=False),
        sa.Column("monthly_target_cents", sa.BigInteger(), nullable=False),
        sa.Column("monthly_max_cents", sa.BigInteger(), nullable=False),
        sa.Column("importance", sa.Integer(), server_default="50", nullable=False),
        sa.Column("minimum_protection_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("reducible", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deferrable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "cross_goal_reallocation_allowed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("asset_policy_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "0 <= monthly_min_cents AND monthly_min_cents <= monthly_target_cents "
            "AND monthly_target_cents <= monthly_max_cents",
            name=op.f("ck_goals_monthly_range"),
        ),
        sa.CheckConstraint("importance BETWEEN 0 AND 100", name=op.f("ck_goals_importance")),
        sa.CheckConstraint(
            "minimum_protection_cents >= 0", name=op.f("ck_goals_minimum_protection")
        ),
        sa.CheckConstraint(
            "target_cents > 0 AND allocated_cents >= 0", name=op.f("ck_goals_target_amounts")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name=op.f("fk_goals_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["asset_policy_id", "user_id"],
            ["policies.id", "policies.user_id"],
            name=op.f("fk_goals_asset_policy_id_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id", "user_id"],
            ["policies.id", "policies.user_id"],
            name=op.f("fk_goals_policy_id_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id", "policy_id", "user_id"],
            ["policy_versions.id", "policy_versions.policy_id", "policy_versions.user_id"],
            name=op.f("fk_goals_policy_version_id_policy_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_goals_id")),
        sa.UniqueConstraint("policy_id", name="uq_goals_policy"),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "asset_positions",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column("principal_cents", sa.BigInteger(), nullable=False),
        sa.Column("accrued_yield_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maturity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="HELD", nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('HELD', 'REDEEMING', 'REDEEMED', 'MATURED', 'UNKNOWN')",
            name=op.f("ck_asset_positions_status"),
        ),
        sa.CheckConstraint(
            "available_at IS NULL OR available_at >= purchased_at",
            name=op.f("ck_asset_positions_availability"),
        ),
        sa.CheckConstraint(
            "maturity_at IS NULL OR maturity_at >= purchased_at",
            name=op.f("ck_asset_positions_maturity"),
        ),
        sa.CheckConstraint(
            "principal_cents >= 0 AND accrued_yield_cents >= 0",
            name=op.f("ck_asset_positions_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name=op.f("fk_asset_positions_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "user_id"],
            ["goals.id", "goals.user_id"],
            name=op.f("fk_asset_positions_goal_id_goals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id", "user_id"],
            ["policy_versions.id", "policy_versions.user_id"],
            name=op.f("fk_asset_positions_policy_version_id_policy_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["asset_products.id"],
            name=op.f("fk_asset_positions_product_id_asset_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_asset_positions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_positions")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_asset_positions_id")),
    )
    op.create_index(
        op.f("ix_asset_positions_user_id"), "asset_positions", ["user_id"], unique=False
    )
    op.create_table(
        "action_plans",
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column("source_account_id", sa.Uuid(), nullable=False),
        sa.Column("destination_account_id", sa.Uuid(), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column("action_type", sa.String(length=48), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("autonomy_level", sa.String(length=24), server_default="BLOCKED", nullable=False),
        sa.Column("status", sa.String(length=24), server_default="PLANNED", nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "autonomy_level IN ('AUTO_EXECUTE', 'ASK_ONCE', 'ADVISE_ONLY', 'BLOCKED')",
            name=op.f("ck_action_plans_autonomy_level"),
        ),
        sa.CheckConstraint(
            "request_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_action_plans_request_hash")
        ),
        sa.CheckConstraint(
            "status IN ('PLANNED', 'AUTHORIZED', 'SUBMITTED', 'SUCCEEDED', 'FAILED', 'UNKNOWN', "
            "'INVALIDATED', 'CANCELLED', 'RECONCILED')",
            name=op.f("ck_action_plans_status"),
        ),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_action_plans_positive_amount")),
        sa.CheckConstraint(
            "destination_account_id IS NULL OR destination_account_id <> source_account_id",
            name=op.f("ck_action_plans_distinct_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_id", "user_id"],
            ["decision_runs.id", "decision_runs.user_id"],
            name=op.f("fk_action_plans_decision_run_id_decision_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["destination_account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name=op.f("fk_action_plans_destination_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "user_id"],
            ["goals.id", "goals.user_id"],
            name=op.f("fk_action_plans_goal_id_goals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id", "user_id"],
            ["policy_versions.id", "policy_versions.user_id"],
            name=op.f("fk_action_plans_policy_version_id_policy_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["position_id", "user_id"],
            ["asset_positions.id", "asset_positions.user_id"],
            name=op.f("fk_action_plans_position_id_asset_positions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["asset_products.id"],
            name=op.f("fk_action_plans_product_id_asset_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name=op.f("fk_action_plans_source_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_action_plans_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_plans")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_action_plans_id")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_action_plans_user_idempotency"),
    )
    op.create_index(op.f("ix_action_plans_user_id"), "action_plans", ["user_id"], unique=False)
    op.create_index(
        "ix_action_plans_user_status", "action_plans", ["user_id", "status"], unique=False
    )
    op.create_table(
        "action_receipts",
        sa.Column("action_plan_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("receipt_ref", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("executed_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("fee_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("loss_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('SUCCEEDED', 'FAILED', 'UNKNOWN')", name=op.f("ck_action_receipts_status")
        ),
        sa.CheckConstraint("attempt_number > 0", name=op.f("ck_action_receipts_positive_attempt")),
        sa.CheckConstraint(
            "executed_cents >= 0 AND fee_cents >= 0 AND loss_cents >= 0",
            name=op.f("ck_action_receipts_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["action_plan_id", "user_id"],
            ["action_plans.id", "action_plans.user_id"],
            name=op.f("fk_action_receipts_action_plan_id_action_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_action_receipts_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_receipts")),
        sa.UniqueConstraint(
            "action_plan_id", "attempt_number", name="uq_action_receipts_action_attempt"
        ),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_action_receipts_id")),
        sa.UniqueConstraint("user_id", "receipt_ref", name="uq_action_receipts_user_ref"),
    )
    op.create_index(
        op.f("ix_action_receipts_user_id"), "action_receipts", ["user_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_type", sa.String(length=48), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("decision_run_id", sa.Uuid(), nullable=True),
        sa.Column("action_plan_id", sa.Uuid(), nullable=True),
        sa.Column("action_receipt_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("payload_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_audit_events_event_hash")
        ),
        sa.CheckConstraint(
            "previous_hash IS NULL OR previous_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_audit_events_previous_hash"),
        ),
        sa.CheckConstraint(
            "sequence_number > 0 AND payload_version > 0",
            name=op.f("ck_audit_events_positive_sequence_version"),
        ),
        sa.ForeignKeyConstraint(
            ["action_plan_id", "user_id"],
            ["action_plans.id", "action_plans.user_id"],
            name=op.f("fk_audit_events_action_plan_id_action_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["action_receipt_id", "user_id"],
            ["action_receipts.id", "action_receipts.user_id"],
            name=op.f("fk_audit_events_action_receipt_id_action_receipts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["causation_id", "user_id"],
            ["audit_events.id", "audit_events.user_id"],
            name=op.f("fk_audit_events_causation_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_id", "user_id"],
            ["decision_runs.id", "decision_runs.user_id"],
            name=op.f("fk_audit_events_decision_run_id_decision_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_audit_events_id")),
        sa.UniqueConstraint("user_id", "event_hash", name="uq_audit_events_user_hash"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_audit_events_user_idempotency"),
        sa.UniqueConstraint("user_id", "sequence_number", name="uq_audit_events_user_sequence"),
    )
    op.create_index(op.f("ix_audit_events_user_id"), "audit_events", ["user_id"], unique=False)
    op.create_index(
        "ix_audit_events_user_occurred", "audit_events", ["user_id", "occurred_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Frozen safety boundary: this revision may only drop disposable test schemas.
    if op.get_context().as_sql:
        raise ValueError("Offline downgrade is disabled; use a generated bf_test_ database")
    database = op.get_bind().engine.url.database
    if database is None or re.fullmatch(r"bf_test_[0-9a-f]{32}", database) is None:
        raise ValueError("Downgrade requires a generated bf_test_<32 hex> database")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_user_occurred", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_user_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_action_receipts_user_id"), table_name="action_receipts")
    op.drop_table("action_receipts")
    op.drop_index("ix_action_plans_user_status", table_name="action_plans")
    op.drop_index(op.f("ix_action_plans_user_id"), table_name="action_plans")
    op.drop_table("action_plans")
    op.drop_index(op.f("ix_asset_positions_user_id"), table_name="asset_positions")
    op.drop_table("asset_positions")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_decision_constraints_user_id"), table_name="decision_constraints")
    op.drop_table("decision_constraints")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index("ix_transactions_account_occurred", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_policy_versions_user_id"), table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_policy_proposals_user_id"), table_name="policy_proposals")
    op.drop_table("policy_proposals")
    op.drop_index(op.f("ix_credit_card_bills_user_id"), table_name="credit_card_bills")
    op.drop_table("credit_card_bills")
    op.drop_index(op.f("ix_policies_user_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index("ix_evidence_items_user_source", table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_user_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_decision_runs_user_id"), table_name="decision_runs")
    op.drop_index("ix_decision_runs_user_as_of", table_name="decision_runs")
    op.drop_table("decision_runs")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("asset_products")
    # ### end Alembic commands ###
