/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Summary */
        get: operations["account_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policy Proposals */
        get: operations["list_policy_proposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-proposals/{proposal_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Policy Proposal */
        post: operations["confirm_policy_proposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policy Versions */
        get: operations["list_policy_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Policy */
        patch: operations["change_policy"];
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend */
        post: operations["suspend_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountSummary */
        AccountSummary: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Timezone */
            timezone: string;
            /** Oldest Account Observed At */
            oldest_account_observed_at: string | null;
            /** Latest Account Observed At */
            latest_account_observed_at: string | null;
            /** Accounts */
            accounts: components["schemas"]["AccountView"][];
            /** Credit Card Bills */
            credit_card_bills: components["schemas"]["BillView"][];
            /** Cash Balance Cents */
            cash_balance_cents: number;
            /** Position Principal Cents */
            position_principal_cents: number;
            /** Unknown Position Principal Cents */
            unknown_position_principal_cents: number;
            /** Credit Card Unpaid Cents */
            credit_card_unpaid_cents: number;
        };
        /** AccountView */
        AccountView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External Ref */
            external_ref: string;
            /** Name */
            name: string;
            /** Account Type */
            account_type: string;
            /** Bank Code */
            bank_code: string;
            /**
             * Currency
             * @constant
             */
            currency: "CNY";
            /** Balance Cents */
            balance_cents: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** BillView */
        BillView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Source Ref */
            source_ref: string;
            /** Evidence Id */
            evidence_id: string | null;
            /**
             * Statement Date
             * Format: date
             */
            statement_date: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Total Cents */
            total_cents: number;
            /** Minimum Due Cents */
            minimum_due_cents: number;
            /** Paid Cents */
            paid_cents: number;
            /** Status */
            status: string;
        };
        /** ConfirmationRequest */
        ConfirmationRequest: {
            /** Accepted */
            accepted: boolean;
            /** Reviewed Hash */
            reviewed_hash: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default bounded-funds-api
             * @constant
             */
            service: "bounded-funds-api";
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
        };
        /** LifecycleResult */
        LifecycleResult: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /**
             * Current Version Id
             * Format: uuid
             * @description 首次提交该命令后形成的版本；幂等重放返回历史回执，实时版本须 GET 查询
             */
            current_version_id: string;
            /** Previous Version Id */
            previous_version_id?: string | null;
            /**
             * Status
             * @description 首次提交命令时的持久状态；幂等重放不代表当前实时状态
             */
            status: string;
            /**
             * Effective Status
             * @description 首次提交命令时计算的有效状态；当前授权必须重新 GET 并校验
             */
            effective_status: string;
            /** Invalidated Action Ids */
            invalidated_action_ids: string[];
            /** Inflight Action Ids */
            inflight_action_ids: string[];
            /**
             * Requires Recompute
             * @default true
             */
            requires_recompute: boolean;
        };
        /** PolicyChangeRequest */
        PolicyChangeRequest: {
            /** Accepted */
            accepted: boolean;
            /** Reviewed Hash */
            reviewed_hash: string;
            /**
             * Expected Version Id
             * Format: uuid
             */
            expected_version_id: string;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** PolicyList */
        PolicyList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["PolicyView"][];
        };
        /** PolicyVersionList */
        PolicyVersionList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["PolicyVersionView"][];
        };
        /** PolicyVersionView */
        PolicyVersionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /** Version Number */
            version_number: number;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
            /** Confirmation */
            confirmation: {
                [key: string]: unknown;
            };
            /** Confirmed At */
            confirmed_at: string | null;
            /** Valid From */
            valid_from: string | null;
            /** Valid Until */
            valid_until: string | null;
            /** Change Reason */
            change_reason: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Content Hash */
            content_hash: string;
            /** Previous Hash */
            previous_hash: string | null;
            /** Impact Analysis */
            impact_analysis: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PolicyView */
        PolicyView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Policy Type */
            policy_type: string;
            /** Status */
            status: string;
            /** Effective Status */
            effective_status: string;
            /**
             * Version Authorized
             * @description 当前确认版本、生命周期和证据是否有效；不代表已满足资金或具体动作约束。
             */
            version_authorized: boolean;
            current_version: components["schemas"]["PolicyVersionView"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PositionList */
        PositionList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["PositionView"][];
        };
        /** PositionView */
        PositionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Goal Id */
            goal_id: string | null;
            /** Policy Version Id */
            policy_version_id: string | null;
            /** Principal Cents */
            principal_cents: number;
            /** Accrued Yield Cents */
            accrued_yield_cents: number;
            /**
             * Purchased At
             * Format: date-time
             */
            purchased_at: string;
            /** Maturity At */
            maturity_at: string | null;
            /** Available At */
            available_at: string | null;
            /** Status */
            status: string;
        };
        /** ProductList */
        ProductList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["ProductView"][];
        };
        /** ProductView */
        ProductView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Product Code */
            product_code: string;
            /** Version Number */
            version_number: number;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Risk Level */
            risk_level: number;
            /** Principal Fluctuation */
            principal_fluctuation: boolean;
            /** Minimum Purchase Cents */
            minimum_purchase_cents: number;
            /** Lock Days */
            lock_days: number;
            /** Redemption Delay Days */
            redemption_delay_days: number;
            /** Annual Yield Bps */
            annual_yield_bps: number;
            /** Early Withdrawal Loss Bps */
            early_withdrawal_loss_bps: number;
            /** Maturity Rule */
            maturity_rule: {
                [key: string]: unknown;
            };
            /** Early Withdrawal Rule */
            early_withdrawal_rule: {
                [key: string]: unknown;
            };
            /** Auto Purchase Allowed */
            auto_purchase_allowed: boolean;
            /** Auto Redeem Allowed */
            auto_redeem_allowed: boolean;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective Until */
            effective_until: string | null;
        };
        /** ProposalList */
        ProposalList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["ProposalView"][];
        };
        /** ProposalView */
        ProposalView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Source Type */
            source_type: string;
            /** Source Text */
            source_text: string;
            /** Compiler Version */
            compiler_version: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Configuration Hash */
            configuration_hash: string;
            /** Validation Ready */
            validation_ready: boolean;
            /** Confirmed Policy Id */
            confirmed_policy_id: string | null;
        };
        /** StateChangeRequest */
        StateChangeRequest: {
            /**
             * Expected Version Id
             * Format: uuid
             */
            expected_version_id: string;
        };
        /** TransactionPage */
        TransactionPage: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["TransactionView"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** TransactionView */
        TransactionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Source Ref */
            source_ref: string;
            /** Evidence Id */
            evidence_id: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "CREDIT" | "DEBIT";
            /** Amount Cents */
            amount_cents: number;
            /** Balance After Cents */
            balance_after_cents: number | null;
            /** Category */
            category: string;
            /** Counterparty Ref */
            counterparty_ref: string | null;
            /** Is One Off */
            is_one_off: boolean;
            /** Category Confirmed */
            category_confirmed: boolean;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_transactions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                account_id?: string | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_products: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_positions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_policy_proposals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    confirm_policy_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_policies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_policy_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersionList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    change_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    suspend_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    revoke_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
