/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Summary */
        get: operations["account_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policy Proposals */
        get: operations["list_policy_proposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-proposals/{proposal_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Policy Proposal */
        post: operations["confirm_policy_proposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover */
        post: operations["discover_policies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile Text */
        post: operations["compile_policy_candidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-compilations/{compilation_id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Text Compilation */
        post: operations["revise_policy_compilation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policy Versions */
        get: operations["list_policy_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Policy */
        patch: operations["change_policy"];
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend */
        post: operations["suspend_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/living-reserve/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate */
        get: operations["estimate_living_reserve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boundary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Boundary */
        get: operations["read_boundary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Goals */
        get: operations["list_goals"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/allocation-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Allocation */
        get: operations["preview_goal_allocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/asset-policies/{policy_id}/allocation-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Asset Allocation */
        get: operations["preview_asset_allocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recovery/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Recovery Preview */
        get: operations["preview_recovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recovery/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Recovery Run */
        post: operations["run_recovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recovery/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Recovery Run */
        get: operations["get_recovery_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountSummary */
        AccountSummary: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Timezone */
            timezone: string;
            /** Oldest Account Observed At */
            oldest_account_observed_at: string | null;
            /** Latest Account Observed At */
            latest_account_observed_at: string | null;
            /** Accounts */
            accounts: components["schemas"]["AccountView"][];
            /** Credit Card Bills */
            credit_card_bills: components["schemas"]["BillView"][];
            /** Cash Balance Cents */
            cash_balance_cents: number;
            /** Position Principal Cents */
            position_principal_cents: number;
            /** Unknown Position Principal Cents */
            unknown_position_principal_cents: number;
            /** Credit Card Unpaid Cents */
            credit_card_unpaid_cents: number;
        };
        /** AccountView */
        AccountView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External Ref */
            external_ref: string;
            /** Name */
            name: string;
            /** Account Type */
            account_type: string;
            /** Bank Code */
            bank_code: string;
            /**
             * Currency
             * @constant
             */
            currency: "CNY";
            /** Balance Cents */
            balance_cents: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** AssetAllocationResponse */
        AssetAllocationResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            allocation: components["schemas"]["AssetAllocationResult"];
            /** Source Evidence Ids */
            source_evidence_ids: string[];
            /** Input Digest */
            input_digest: string;
            /** Source Issues */
            source_issues: components["schemas"]["BoundarySourceIssue"][];
        };
        /** AssetAllocationResult */
        AssetAllocationResult: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /**
             * Policy Version Id
             * Format: uuid
             */
            policy_version_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "general_idle_funds" | "goal";
            /** Goal Id */
            goal_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "READY" | "INSUFFICIENT_EVIDENCE" | "LIQUIDITY_RISK" | "INACTIVE_POLICY";
            /**
             * Financial Only
             * @default true
             * @constant
             */
            financial_only: true;
            /**
             * Preview Only
             * @default true
             * @constant
             */
            preview_only: true;
            /** Selected Asset Class */
            selected_asset_class?: string | null;
            /** Selected Product Id */
            selected_product_id?: string | null;
            /** Suggested Cents */
            suggested_cents?: number | null;
            /** Retained Cash Cents */
            retained_cash_cents?: number | null;
            /** Comparison Days */
            comparison_days?: number | null;
            /** Scope Cash Cents */
            scope_cash_cents?: number | null;
            /** Remaining Managed Cents */
            remaining_managed_cents?: number | null;
            /** Net Simulated Yield Cents */
            net_simulated_yield_cents?: number | null;
            /** Source Cash Uses */
            source_cash_uses?: components["schemas"]["AssetCashUse"][];
            /** Candidates */
            candidates?: components["schemas"]["AssetCandidate"][];
            baseline_boundary: components["schemas"]["BoundaryResult"];
            reservation_adjusted_boundary?: components["schemas"]["BoundaryResult"] | null;
            candidate_boundary?: components["schemas"]["BoundaryResult"] | null;
            /** Selection Hash */
            selection_hash: string;
            /** Reasons */
            reasons?: string[];
        };
        /** AssetCandidate */
        AssetCandidate: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Code */
            product_code: string;
            /** Version Number */
            version_number: number;
            /** Asset Class */
            asset_class: string;
            /**
             * Status
             * @enum {string}
             */
            status: "FEASIBLE" | "REJECTED";
            /** Financial Cap Cents */
            financial_cap_cents?: number | null;
            /** Max Allocatable Cents */
            max_allocatable_cents?: number | null;
            /** Net Simulated Yield Cents */
            net_simulated_yield_cents?: number | null;
            exit_plan?: components["schemas"]["PlannedExit"] | null;
            /** Candidate Boundary Hash */
            candidate_boundary_hash?: string | null;
            /** Reasons */
            reasons?: string[];
        };
        /** AssetCashUse */
        AssetCashUse: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Amount Cents */
            amount_cents: number;
        };
        /** BillView */
        BillView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Source Ref */
            source_ref: string;
            /** Evidence Id */
            evidence_id: string | null;
            /**
             * Statement Date
             * Format: date
             */
            statement_date: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Total Cents */
            total_cents: number;
            /** Minimum Due Cents */
            minimum_due_cents: number;
            /** Paid Cents */
            paid_cents: number;
            /** Status */
            status: string;
        };
        /** BlockingConstraint */
        BlockingConstraint: {
            /** Code */
            code: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Date */
            date?: string | null;
            /** Required Cents */
            required_cents?: number | null;
            /** Available Cents */
            available_cents?: number | null;
        };
        /** BoundaryPoint */
        BoundaryPoint: {
            /** Day */
            day: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Phase
             * @enum {string}
             */
            phase: "BEFORE_PAYMENT" | "AFTER_PAYMENT" | "AFTER_PRINCIPAL";
            /** Cash Cents */
            cash_cents: number;
            /** Protected Cents By Reason */
            protected_cents_by_reason: {
                [key: string]: number;
            };
            /** Margin Cents */
            margin_cents: number;
            /** Obligation Occurrence Ids */
            obligation_occurrence_ids: string[];
            /** Principal Position Ids */
            principal_position_ids: string[];
        };
        /** BoundaryResponse */
        BoundaryResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            boundary: components["schemas"]["BoundaryResult"];
            /** Source Evidence Ids */
            source_evidence_ids: string[];
            /** Input Digest */
            input_digest: string;
            /** Source Issues */
            source_issues: components["schemas"]["BoundarySourceIssue"][];
        };
        /** BoundaryResult */
        BoundaryResult: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "READY" | "LIQUIDITY_RISK" | "INSUFFICIENT_EVIDENCE";
            /**
             * Financial Only
             * @default true
             * @constant
             */
            financial_only: true;
            /** Safe Idle Cents */
            safe_idle_cents: number | null;
            /** Minimum Margin Cents */
            minimum_margin_cents: number | null;
            /** Deficit Cents */
            deficit_cents: number | null;
            /** Protected Cents By Reason */
            protected_cents_by_reason: {
                [key: string]: number;
            };
            /** Max Allocatable By Product */
            max_allocatable_by_product: {
                [key: string]: number | null;
            };
            /** Blocking Constraints */
            blocking_constraints: components["schemas"]["BlockingConstraint"][];
            /** Calculation Trace */
            calculation_trace: components["schemas"]["BoundaryPoint"][];
            /** Boundary Hash */
            boundary_hash: string;
            /** Calculation Notes */
            calculation_notes?: string[];
        };
        /** BoundarySourceIssue */
        BoundarySourceIssue: {
            /** Code */
            code: string;
            /** Source Ref */
            source_ref: string;
            /** Message */
            message: string;
        };
        /** CompilationIssue */
        CompilationIssue: {
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Source Fragment */
            source_fragment: string;
        };
        /** CompilationRequest */
        CompilationRequest: {
            /** Text */
            text: string;
            /**
             * Engine
             * @default rules
             * @enum {string}
             */
            engine: "rules" | "llm";
        };
        /** CompilationResponse */
        CompilationResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Compilation Id
             * Format: uuid
             */
            compilation_id: string;
            compilation: components["schemas"]["CompilationResult"];
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            } | null;
            /** Configuration Hash */
            configuration_hash: string | null;
            /** Proposal Id */
            proposal_id: string | null;
            /** Proposal Status */
            proposal_status: string | null;
        };
        /** CompilationResult */
        CompilationResult: {
            /** Compiler Version */
            compiler_version: string;
            /**
             * Reference Date
             * Format: date
             */
            reference_date: string;
            /** Timezone */
            timezone: string;
            /** Draft */
            draft: {
                [key: string]: unknown;
            };
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            } | null;
            /** Issues */
            issues?: components["schemas"]["CompilationIssue"][];
            /** Assumptions */
            assumptions?: string[];
        };
        /** CompilationRevisionRequest */
        CompilationRevisionRequest: {
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
        };
        /** ConfirmationRequest */
        ConfirmationRequest: {
            /** Accepted */
            accepted: boolean;
            /** Reviewed Hash */
            reviewed_hash: string;
        };
        /** CoverageGap */
        CoverageGap: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Missing Dates */
            missing_dates: string[];
        };
        /** CreateGoalRequest */
        CreateGoalRequest: {
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /**
             * Expected Version Id
             * Format: uuid
             */
            expected_version_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
        };
        /** DailyReserveAmount */
        DailyReserveAmount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Covered */
            covered: boolean;
            /** Amount Cents */
            amount_cents: number | null;
        };
        /**
         * DiscoveryRequest
         * @description Discovery uses the trusted server snapshot; clients cannot inject facts or time.
         */
        DiscoveryRequest: Record<string, never>;
        /** DiscoveryResult */
        DiscoveryResult: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Rule Version
             * @default mvp-104-v1
             */
            rule_version: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Created Proposal Ids */
            created_proposal_ids: string[];
            /** Reused Proposal Ids */
            reused_proposal_ids: string[];
            /** Skipped */
            skipped: components["schemas"]["DiscoverySkip"][];
        };
        /** DiscoverySkip */
        DiscoverySkip: {
            /** Reason Code */
            reason_code: string;
            /** Source Ref */
            source_ref: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** ExcludedReserveTransaction */
        ExcludedReserveTransaction: {
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Amount Cents */
            amount_cents: number;
            /** Reasons */
            reasons: string[];
        };
        /** GoalAllocationResponse */
        GoalAllocationResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            allocation: components["schemas"]["GoalAllocationResult"];
            /** Source Evidence Ids */
            source_evidence_ids: string[];
            /** Input Digest */
            input_digest: string;
            /** Source Issues */
            source_issues: components["schemas"]["BoundarySourceIssue"][];
        };
        /** GoalAllocationResult */
        GoalAllocationResult: {
            /**
             * Algorithm Version
             * @default single-goal-allocation-v1
             */
            algorithm_version: string;
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /**
             * Policy Version Id
             * Format: uuid
             */
            policy_version_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "READY" | "MINIMUM_SHORTFALL" | "LIQUIDITY_RISK" | "INSUFFICIENT_EVIDENCE" | "INACTIVE_POLICY";
            /**
             * Financial Only
             * @default true
             * @constant
             */
            financial_only: true;
            /**
             * Preview Only
             * @default true
             * @constant
             */
            preview_only: true;
            /** Suggested Cents */
            suggested_cents?: number | null;
            /** Max Safe Cents */
            max_safe_cents?: number | null;
            /** Remaining Min Cents */
            remaining_min_cents?: number | null;
            /** Remaining Target Cents */
            remaining_target_cents?: number | null;
            /** Remaining Max Cents */
            remaining_max_cents?: number | null;
            /** Eligible New Funds Cents */
            eligible_new_funds_cents?: number | null;
            /** Minimum Shortfall Cents */
            minimum_shortfall_cents?: number | null;
            /** Lot Allocations */
            lot_allocations?: components["schemas"]["LotAllocation"][];
            baseline_boundary: components["schemas"]["BoundaryResult"];
            candidate_boundary?: components["schemas"]["BoundaryResult"] | null;
            /** Allocation Hash */
            allocation_hash: string;
            /** Reasons */
            reasons?: string[];
        };
        /** GoalList */
        GoalList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["GoalView"][];
        };
        /** GoalResponse */
        GoalResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            goal: components["schemas"]["GoalView"];
        };
        /** GoalView */
        GoalView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /**
             * Policy Version Id
             * Format: uuid
             */
            policy_version_id: string;
            /** Account Id */
            account_id: string | null;
            /** Name */
            name: string;
            /** Target Cents */
            target_cents: number;
            /** Allocated Cents */
            allocated_cents: number;
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /** Monthly Min Cents */
            monthly_min_cents: number;
            /** Monthly Target Cents */
            monthly_target_cents: number;
            /** Monthly Max Cents */
            monthly_max_cents: number;
            /** Importance */
            importance: number;
            /** Minimum Protection Cents */
            minimum_protection_cents: number;
            /** Reducible */
            reducible: boolean;
            /** Deferrable */
            deferrable: boolean;
            /** Cross Goal Reallocation Allowed */
            cross_goal_reallocation_allowed: boolean;
            /** Asset Policy Id */
            asset_policy_id: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default bounded-funds-api
             * @constant
             */
            service: "bounded-funds-api";
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
        };
        /** LifecycleResult */
        LifecycleResult: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /**
             * Current Version Id
             * Format: uuid
             * @description 首次提交该命令后形成的版本；幂等重放返回历史回执，实时版本须 GET 查询
             */
            current_version_id: string;
            /** Previous Version Id */
            previous_version_id?: string | null;
            /**
             * Status
             * @description 首次提交命令时的持久状态；幂等重放不代表当前实时状态
             */
            status: string;
            /**
             * Effective Status
             * @description 首次提交命令时计算的有效状态；当前授权必须重新 GET 并校验
             */
            effective_status: string;
            /** Invalidated Action Ids */
            invalidated_action_ids: string[];
            /** Inflight Action Ids */
            inflight_action_ids: string[];
            /**
             * Requires Recompute
             * @default true
             */
            requires_recompute: boolean;
        };
        /** LivingReserveEstimate */
        LivingReserveEstimate: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "READY" | "INSUFFICIENT_HISTORY";
            /**
             * Reference Date
             * Format: date
             */
            reference_date: string;
            /** Timezone */
            timezone: string;
            /**
             * History Start
             * Format: date
             */
            history_start: string;
            /**
             * History End
             * Format: date
             */
            history_end: string;
            /** Lookback Days */
            lookback_days: number;
            /** Horizon Days */
            horizon_days: number;
            /** Quantile */
            quantile: number;
            /** Quantile Fraction */
            quantile_fraction: string;
            /** Rank */
            rank: number | null;
            /** Window Count */
            window_count: number;
            /** Base Reserve Cents */
            base_reserve_cents: number | null;
            /** Extra Buffer Cents */
            extra_buffer_cents: number;
            /** Recommended Reserve Cents */
            recommended_reserve_cents: number | null;
            /** Selected Categories */
            selected_categories: string[];
            /** Account Ids */
            account_ids: string[];
            /** Normalized Configuration */
            normalized_configuration: {
                [key: string]: unknown;
            };
            /** Daily Amounts */
            daily_amounts: components["schemas"]["DailyReserveAmount"][];
            /** Windows */
            windows: components["schemas"]["ReserveWindow"][];
            /** Included Transaction Ids */
            included_transaction_ids: string[];
            /** Excluded Transactions */
            excluded_transactions: components["schemas"]["ExcludedReserveTransaction"][];
            /** Coverage Gaps */
            coverage_gaps: components["schemas"]["CoverageGap"][];
            /** Issues */
            issues: string[];
        };
        /** LotAllocation */
        LotAllocation: {
            /**
             * Origin Transaction Id
             * Format: uuid
             */
            origin_transaction_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Amount Cents */
            amount_cents: number;
            /** Remaining Available Cents */
            remaining_available_cents: number;
        };
        /** PlannedExit */
        PlannedExit: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "FIXED_MATURITY" | "PLANNED_REDEMPTION";
            /** Request At */
            request_at?: string | null;
            /**
             * Principal Available At
             * Format: date-time
             */
            principal_available_at: string;
            /** Earning Days */
            earning_days: number;
            /** Liquidity Days */
            liquidity_days: number;
            /** Terms Digest */
            terms_digest: string;
        };
        /** PolicyChangeRequest */
        PolicyChangeRequest: {
            /** Accepted */
            accepted: boolean;
            /** Reviewed Hash */
            reviewed_hash: string;
            /**
             * Expected Version Id
             * Format: uuid
             */
            expected_version_id: string;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** PolicyList */
        PolicyList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["PolicyView"][];
        };
        /** PolicyVersionList */
        PolicyVersionList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["PolicyVersionView"][];
        };
        /** PolicyVersionView */
        PolicyVersionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /** Version Number */
            version_number: number;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
            /** Confirmation */
            confirmation: {
                [key: string]: unknown;
            };
            /** Confirmed At */
            confirmed_at: string | null;
            /** Valid From */
            valid_from: string | null;
            /** Valid Until */
            valid_until: string | null;
            /** Change Reason */
            change_reason: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Content Hash */
            content_hash: string;
            /** Previous Hash */
            previous_hash: string | null;
            /** Impact Analysis */
            impact_analysis: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PolicyView */
        PolicyView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Policy Type */
            policy_type: string;
            /** Status */
            status: string;
            /** Effective Status */
            effective_status: string;
            /**
             * Version Authorized
             * @description 当前确认版本、生命周期和证据是否有效；不代表已满足资金或具体动作约束。
             */
            version_authorized: boolean;
            current_version: components["schemas"]["PolicyVersionView"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PositionList */
        PositionList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["PositionView"][];
        };
        /** PositionView */
        PositionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Goal Id */
            goal_id: string | null;
            /** Policy Version Id */
            policy_version_id: string | null;
            /** Principal Cents */
            principal_cents: number;
            /** Accrued Yield Cents */
            accrued_yield_cents: number;
            /**
             * Purchased At
             * Format: date-time
             */
            purchased_at: string;
            /** Maturity At */
            maturity_at: string | null;
            /** Available At */
            available_at: string | null;
            /** Status */
            status: string;
        };
        /** ProductList */
        ProductList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["ProductView"][];
        };
        /** ProductView */
        ProductView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Product Code */
            product_code: string;
            /** Version Number */
            version_number: number;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Risk Level */
            risk_level: number;
            /** Principal Fluctuation */
            principal_fluctuation: boolean;
            /** Minimum Purchase Cents */
            minimum_purchase_cents: number;
            /** Lock Days */
            lock_days: number;
            /** Redemption Delay Days */
            redemption_delay_days: number;
            /** Annual Yield Bps */
            annual_yield_bps: number;
            /** Early Withdrawal Loss Bps */
            early_withdrawal_loss_bps: number;
            /** Maturity Rule */
            maturity_rule: {
                [key: string]: unknown;
            };
            /** Early Withdrawal Rule */
            early_withdrawal_rule: {
                [key: string]: unknown;
            };
            /** Auto Purchase Allowed */
            auto_purchase_allowed: boolean;
            /** Auto Redeem Allowed */
            auto_redeem_allowed: boolean;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective Until */
            effective_until: string | null;
        };
        /** ProposalList */
        ProposalList: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["ProposalView"][];
        };
        /** ProposalView */
        ProposalView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Source Type */
            source_type: string;
            /** Source Text */
            source_text: string;
            /** Compiler Version */
            compiler_version: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Configuration Hash */
            configuration_hash: string;
            /** Validation Ready */
            validation_ready: boolean;
            /** Confirmed Policy Id */
            confirmed_policy_id: string | null;
        };
        /** RecoveryAction */
        RecoveryAction: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /**
             * Source Account Id
             * Format: uuid
             */
            source_account_id: string;
            /**
             * Destination Account Id
             * Format: uuid
             */
            destination_account_id: string;
            /** Goal Id */
            goal_id?: string | null;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Version Number */
            product_version_number: number;
            /** Terms Digest */
            terms_digest: string;
            /**
             * Original Policy Version Id
             * Format: uuid
             */
            original_policy_version_id: string;
            /**
             * Current Policy Id
             * Format: uuid
             */
            current_policy_id: string;
            /**
             * Current Policy Version Id
             * Format: uuid
             */
            current_policy_version_id: string;
            /** Current Authorization Hash */
            current_authorization_hash: string;
            quote: components["schemas"]["RecoveryQuote"];
            /**
             * Autonomy Level
             * @enum {string}
             */
            autonomy_level: "AUTO_EXECUTE" | "ASK_ONCE";
            /** Baseline Boundary Hash */
            baseline_boundary_hash: string;
            /** Plan Inputs Hash */
            plan_inputs_hash: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Request Hash */
            request_hash: string;
        };
        /** RecoveryActionStatus */
        RecoveryActionStatus: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /** Status */
            status: string;
            /** Bank Request Id */
            bank_request_id?: string | null;
            /** Bank Status */
            bank_status?: string | null;
            /** Receipt Id */
            receipt_id?: string | null;
        };
        /** RecoveryCandidate */
        RecoveryCandidate: {
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "AUTO_EXECUTE" | "ASK_ONCE" | "ADVISE_ONLY" | "BLOCKED";
            /** Reasons */
            reasons?: string[];
            action?: components["schemas"]["RecoveryAction"] | null;
            projected_boundary?: components["schemas"]["BoundaryResult"] | null;
        };
        /** RecoveryNotification */
        RecoveryNotification: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Action Id */
            action_id?: string | null;
        };
        /** RecoveryPlan */
        RecoveryPlan: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * Preview Only
             * @default true
             * @constant
             */
            preview_only: true;
            /**
             * Status
             * @enum {string}
             */
            status: "NO_RECOVERY_NEEDED" | "AUTO_RECOVERY_AVAILABLE" | "PARTIAL_RECOVERY_AVAILABLE" | "ASK_ONCE" | "ADVISE_ONLY" | "NO_SAFE_RECOVERY" | "INSUFFICIENT_EVIDENCE";
            actual_boundary: components["schemas"]["BoundaryResult"];
            projected_boundary?: components["schemas"]["BoundaryResult"] | null;
            /** Steps */
            steps?: components["schemas"]["RecoveryAction"][];
            /** Candidates */
            candidates?: components["schemas"]["RecoveryCandidate"][];
            /** Uncovered Checkpoints */
            uncovered_checkpoints?: components["schemas"]["BoundaryPoint"][];
            first_sustained_safe_point?: components["schemas"]["BoundaryPoint"] | null;
            /** Plan Hash */
            plan_hash: string;
            /** Reasons */
            reasons?: string[];
        };
        /** RecoveryPreviewResponse */
        RecoveryPreviewResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            plan: components["schemas"]["RecoveryPlan"];
            /** Source Evidence Ids */
            source_evidence_ids: string[];
            /** Input Digest */
            input_digest: string;
            /** Source Issues */
            source_issues: components["schemas"]["BoundarySourceIssue"][];
        };
        /** RecoveryQuote */
        RecoveryQuote: {
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Version Number */
            product_version_number: number;
            /** Terms Digest */
            terms_digest: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "REDEEM" | "EARLY_WITHDRAW" | "MATURE";
            /** Principal Cents */
            principal_cents: number;
            /** Fee Cents */
            fee_cents: number;
            /** Loss Cents */
            loss_cents: number;
            /** Net Cents */
            net_cents: number;
            /**
             * Request At
             * Format: date-time
             */
            request_at: string;
            /**
             * Principal Available At
             * Format: date-time
             */
            principal_available_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RecoveryRunRequest */
        RecoveryRunRequest: {
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** RecoveryRunResponse */
        RecoveryRunResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Status */
            status: string;
            plan: components["schemas"]["RecoveryPlan"];
            actual_boundary: components["schemas"]["BoundaryResult"];
            /** Actions */
            actions: components["schemas"]["RecoveryActionStatus"][];
            /** Notifications */
            notifications: components["schemas"]["RecoveryNotification"][];
        };
        /** ReserveEstimationResponse */
        ReserveEstimationResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            estimation: components["schemas"]["LivingReserveEstimate"];
            /** Source Evidence Ids */
            source_evidence_ids: string[];
            /** Input Digest */
            input_digest: string;
            /** Source Issues */
            source_issues: components["schemas"]["ReserveSourceIssue"][];
            /** Candidate Configuration */
            candidate_configuration: {
                [key: string]: unknown;
            } | null;
            /** Candidate Configuration Hash */
            candidate_configuration_hash: string | null;
        };
        /** ReserveSourceIssue */
        ReserveSourceIssue: {
            /** Code */
            code: string;
            /** Source Ref */
            source_ref: string;
            /** Message */
            message: string;
        };
        /** ReserveWindow */
        ReserveWindow: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Amount Cents */
            amount_cents: number;
        };
        /** StateChangeRequest */
        StateChangeRequest: {
            /**
             * Expected Version Id
             * Format: uuid
             */
            expected_version_id: string;
        };
        /** TransactionPage */
        TransactionPage: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Items */
            items: components["schemas"]["TransactionView"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** TransactionView */
        TransactionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Source Ref */
            source_ref: string;
            /** Evidence Id */
            evidence_id: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "CREDIT" | "DEBIT";
            /** Amount Cents */
            amount_cents: number;
            /** Balance After Cents */
            balance_after_cents: number | null;
            /** Category */
            category: string;
            /** Counterparty Ref */
            counterparty_ref: string | null;
            /** Is One Off */
            is_one_off: boolean;
            /** Category Confirmed */
            category_confirmed: boolean;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_transactions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                account_id?: string | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_products: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_positions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_policy_proposals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    confirm_policy_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_policies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    discover_policies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DiscoveryRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    compile_policy_candidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompilationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompilationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    revise_policy_compilation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compilation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompilationRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompilationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_policy_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersionList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    change_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    suspend_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    revoke_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    estimate_living_reserve: {
        parameters: {
            query?: {
                horizon_days?: number;
                lookback_days?: number;
                quantile?: number;
                extra_buffer_cents?: number;
                essential_categories?: string[];
                exclude_one_off?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveEstimationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    read_boundary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundaryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_goals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_goal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    preview_goal_allocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalAllocationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    preview_asset_allocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetAllocationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    preview_recovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryPreviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    run_recovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_recovery_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
