import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getFullPolicies } from '../api/full-policies';
import { getFullAssetPlan, getFullRecoveryPlan, getOriginalFullProductsResponse, getProductCatalog, getProductPositions, groupPrincipalDates, parseAssetOptions, productBoundaryPoints } from '../api/full-products';
import type { AssetOptions, FullAssetPlan, FullRecoveryPlan, ProductBoundary } from '../api/full-products';
import { errorMessage } from '../api/http';
import { formatMoneyCents } from '../features/money';
import { object, parseMoneyInput } from '../features/policy-form';
import FullAssetExecutionPanel from '../components/FullAssetExecutionPanel';

const money = (value: number | null | undefined) => value == null ? '未知 · 未证明' : `¥${formatMoneyCents(value)}`;
function BoundaryCard({ title, value }: { title: string; value: ProductBoundary | null | undefined }) { return <article aria-label={title}><h4>{title}</h4>{value ? <><p>{value.status} · {productBoundaryPoints(value)}个原阶段点（365未来日期 + 初始日，各3阶段；不是1098天）</p><dl className="annual-amounts"><div><dt>安全闲置</dt><dd>{money(value.safe_idle_cents)}</dd></div><div><dt>最小余量</dt><dd>{money(value.minimum_margin_cents)}</dd></div><div><dt>缺口</dt><dd>{money(value.deficit_cents)}</dd></div></dl><details><summary>原曲线JSON</summary><pre className="readonly-raw">{JSON.stringify(value, null, 2)}</pre></details></> : <p className="notice">条件曲线尚未知，没有填成零或实际到账。</p>}</article>; }
function AssetResult({ data }: { data: FullAssetPlan }) {
  const plan = data.allocation;
  return <section aria-label="资产规划结果"><h3>{data.state === 'UNKNOWN' ? 'UNKNOWN · 资产来源未证明' : `条件规划：${plan!.status}`}</h3><p>比较期 {data.planning_constraints.comparison_days}天，最多 {data.planning_constraints.max_components}个今日批次；保护仍为原365日曲线。90日是默认收益比较期，不是扩大授权。</p><p>实际未提供类别：{data.unavailable_asset_classes.join('、') || '响应未列出缺类；不等于全部类别已实测'}</p>
    {plan && <><p>原声明版本 <code>{plan.policy_version_id}</code> · {plan.scope} / 目标 <code>{plan.goal_id ?? '一般闲置资金'}</code></p><dl className="annual-amounts"><div><dt>今日条件申购</dt><dd>{money(plan.total_purchase_cents)}</dd></div><div><dt>保留原scope现金</dt><dd>{money(plan.retained_scope_cash_cents)}</dd></div><div><dt>条件模拟净收益</dt><dd>{money(plan.net_simulated_yield_cents)}</dd></div><div><dt>当前今日批次数</dt><dd>{plan.purchase_count ?? '未知'}</dd></div></dl><p>用款日期 {plan.funds_use_date ?? '未证明'} · 梯度 {plan.ladder_status} · 搜索节点 {plan.search_nodes}</p>
      <BoundaryCard title="申购前原365日保护" value={plan.baseline_boundary} /><BoundaryCard title="申购后条件365日保护" value={plan.projected_boundary} />
      <h4>逐产品期限相容性与拒绝理由</h4>{plan.candidates.length === 0 && <p>没有已证明候选；不是可用类别全已通过。</p>}{plan.candidates.map((candidate) => <article className="card" key={candidate.product_id}><h5>{candidate.product_code} · 原版本 {candidate.version_number} · {candidate.status}</h5><p>目录类别 {candidate.catalog_asset_class} → 规划类别 {candidate.planning_asset_class ?? 'UNKNOWN · 未识别完整条款'}</p><p>财务上限 {money(candidate.financial_cap_cents)} · 今日单批上限 {money(candidate.maximum_batch_cents)}</p><p>本金可用时刻 {candidate.exit_plan?.principal_available_at ?? '未知'} · {candidate.exit_plan?.kind ?? '无已证明退出计划'}</p>{candidate.reasons.map((reason) => <p className="notice" key={reason}>{reason}</p>)}<p className="caption">原 terms_digest <code>{candidate.terms_digest}</code> · bank_auto_eligible=false</p></article>)}
      <h4>今日条件批次到期分桶</h4>{plan.batches.length === 0 ? <p>没有合法今日批次；不能补画七/九十天梯度。</p> : groupPrincipalDates(plan.batches, (batch) => batch.principal_available_at).map((bucket) => <article key={bucket.timestamp!}><h5>原本金可用时刻 {bucket.timestamp}</h5>{bucket.rows.map((batch) => <p key={batch.product_id}>{batch.product_code} v{batch.version_number} · {money(batch.amount_cents)} · 条件净收益 {money(batch.net_simulated_yield_cents)} · 购买假设时刻 {batch.purchase_at} · 原资金账户 {batch.cash_uses.map((use) => `${use.account_id}: ${money(use.amount_cents)}`).join('；')}</p>)}</article>)}{plan.reasons.map((reason) => <p className="notice" key={reason}>{reason}</p>)}
    </>}{data.source_issues.map((issue, i) => <p className="notice" key={i}>{issue.code} · {issue.message} · 原来源 <code>{issue.source_ref}</code></p>)}{data.limitations.map((limitation) => <p className="caption" key={limitation}>{limitation}</p>)}<details><summary>资产规划原响应</summary><pre className="readonly-raw">{getOriginalFullProductsResponse(data)}</pre></details></section>;
}
function RecoveryResult({ data }: { data: FullRecoveryPlan }) {
  const plan = data.plan;
  return <section aria-label="原报价提前支取影响"><h3>{data.state === 'UNKNOWN' ? 'UNKNOWN · 原报价或归属未证明' : `只读恢复规划：${plan!.status}`}</h3>{plan && <><p>原Recovery版本 <code>{plan.policy_version_id}</code> · 当前引用资产版本 <code>{plan.linked_asset_policy_version_id}</code> · 截止时刻 {plan.deadline_at ?? '未知'}</p><p>原scope现金 {money(plan.actual_scope_cash_cents)}；需恢复 {money(plan.required_recovery_cents)}；无损条件按时回款 {money(plan.conditional_on_time_recovery_cents)}</p><BoundaryCard title="当前实际财务边界" value={plan.actual_boundary} /><BoundaryCard title="无损条件回款边界" value={plan.lossless_conditional_boundary} />
    <p>持续安全首阶段 {plan.first_sustained_safe_point ? `${plan.first_sustained_safe_point.date} / ${plan.first_sustained_safe_point.phase} / 余量 ${money(plan.first_sustained_safe_point.margin_cents)}` : '未知 · 没有已证明持续安全点'}；尚未覆盖 {plan.uncovered_checkpoints.length}个原阶段。</p>{plan.uncovered_checkpoints.length > 0 && <details><summary>逐阶段尚未覆盖缺口</summary><ul>{plan.uncovered_checkpoints.map((point) => <li key={`${point.day}:${point.phase}`}>{point.date} / {point.phase} / 原余量 {money(point.margin_cents)}</li>)}</ul></details>}<h4>原持仓 / 报价 / 损失</h4>{plan.candidates.length === 0 && <p>响应未列出已证明持仓候选。</p>}{plan.candidates.map((candidate) => <article className="card" key={candidate.position_id}><h5>原持仓 <code>{candidate.position_id}</code> · {candidate.decision}</h5><p>归属目标 {candidate.goal_id ?? '一般现金scope'} · 原回款账户 <code>{candidate.destination_account_id}</code></p><dl className="annual-amounts"><div><dt>原本金</dt><dd>{money(candidate.principal_cents)}</dd></div><div><dt>独立整数损失</dt><dd>{money(candidate.independent_loss_cents)}</dd></div><div><dt>原费用</dt><dd>{money(candidate.fee_cents)}</dd></div><div><dt>条件净额</dt><dd>{money(candidate.net_cents)}</dd></div></dl><p>报价来源 {candidate.quote_source} · 原quote <code>{candidate.original_quote?.quote_id ?? '未提供'}</code> · 有效至 {candidate.original_quote?.expires_at ?? '未知'} · 最早条件回款 {candidate.earliest_conditional_cash_at ?? '未知'} · 是否及时 {candidate.on_time === null ? '未知' : candidate.on_time ? '服务端条件计划按时' : '不能按时'}</p><p>完整规划限额 {candidate.within_full_planning_limits ? '符合' : '未符合'}；可入无损条件步骤 {candidate.lossless_eligible ? '服务端报告可以' : '不可以'}。bank_authority=false。</p>{candidate.reasons.map((reason) => <p className="notice" key={reason}>{reason}</p>)}{candidate.conditional_impact_boundary && <BoundaryCard title="单笔早退条件影响，尚未执行" value={candidate.conditional_impact_boundary} />}</article>)}{plan.reasons.map((reason) => <p className="notice" key={reason}>{reason}</p>)}</>}{data.source_issues.map((issue, i) => <p className="notice" key={i}>{issue.code} · {issue.message} · <code>{issue.source_ref}</code></p>)}{data.limitations.map((limitation) => <p className="caption" key={limitation}>{limitation}</p>)}<details><summary>提前支取规划原响应</summary><pre className="readonly-raw">{getOriginalFullProductsResponse(data)}</pre></details></section>;
}
export default function FullProductsPage({ mutationBlocked = false }: { mutationBlocked?: boolean }) {
  const catalogue = useQuery({ queryKey: ['full-product-catalogue'], queryFn: getProductCatalog, retry: false }); const positions = useQuery({ queryKey: ['full-product-positions'], queryFn: getProductPositions, retry: false }); const policies = useQuery({ queryKey: ['full-policies'], queryFn: getFullPolicies, retry: false });
  const [versionFilter, setVersionFilter] = useState('ALL'); const [selectedVersion, setSelectedVersion] = useState(''); const [assetPolicy, setAssetPolicy] = useState(''); const [recoveryPolicy, setRecoveryPolicy] = useState(''); const [comparison, setComparison] = useState('90'); const [complexity, setComplexity] = useState('3'); const [turnover, setTurnover] = useState(''); const [useDate, setUseDate] = useState(''); const [mode, setMode] = useState<'PORTFOLIO' | 'FIXED_LADDER'>('PORTFOLIO'); const [deadline, setDeadline] = useState(''); const [assetRequest, setAssetRequest] = useState<{ policy_id: string; options: AssetOptions } | null>(null); const [recoveryRequest, setRecoveryRequest] = useState<{ policy_id: string; deadline: string | null } | null>(null); const [inputError, setInputError] = useState('');
  const asset = useQuery({ queryKey: ['full-product-asset-plan', assetRequest], queryFn: () => getFullAssetPlan(assetRequest!.policy_id, assetRequest!.options), enabled: !!assetRequest, retry: false, refetchOnWindowFocus: false }); const recovery = useQuery({ queryKey: ['full-product-recovery-plan', recoveryRequest], queryFn: () => getFullRecoveryPlan(recoveryRequest!.policy_id, recoveryRequest!.deadline), enabled: !!recoveryRequest, retry: false, refetchOnWindowFocus: false });
  const versions = catalogue.data?.versions.filter((row) => versionFilter === 'ALL' || versionFilter === 'MATCHED' && row.current_source_matched || versionFilter === 'DRIFTED' && !row.current_source_matched) ?? []; const selected = catalogue.data?.versions.find((row) => row.id === selectedVersion); const original = selected?.original_product;
  function readAssets() { try { if (!assetPolicy || !/^\d+$/.test(comparison) || !/^\d+$/.test(complexity)) throw new Error('请选择实际完整资产声明和严格整数规划窗口'); const options = parseAssetOptions({ comparison_days: Number(comparison), max_components: Number(complexity), max_turnover_cents: turnover.trim() ? parseMoneyInput(turnover) : null, funds_use_date: useDate || null, mode }); setInputError(''); const next = { policy_id: assetPolicy, options }; if (JSON.stringify(next) === JSON.stringify(assetRequest)) void asset.refetch(); else setAssetRequest(next); } catch (error) { setInputError(errorMessage(error)); } }
  function readRecovery() { try { if (!recoveryPolicy || deadline && (!/(?:Z|[+-]\d\d:\d\d)$/.test(deadline) || !Number.isFinite(Date.parse(deadline)))) throw new Error('请选择实际完整Recovery声明；更早截止使用带时区ISO时刻'); setInputError(''); const next = { policy_id: recoveryPolicy, deadline: deadline || null }; if (JSON.stringify(next) === JSON.stringify(recoveryRequest)) void recovery.refetch(); else setRecoveryRequest(next); } catch (error) { setInputError(errorMessage(error)); } }
  return <div><section className="page-intro"><div><p className="eyebrow">原版本 · 日期 · 条件现金</p><h2>产品与期限</h2></div><button type="button" disabled={catalogue.isFetching || positions.isFetching || policies.isFetching} onClick={() => { void catalogue.refetch(); void positions.refetch(); void policies.refetch(); }}>刷新只读产品来源</button></section><p className="simulation-note">均为模拟产品。只读规划不是真实资金执行，不自动投配、赎回、续期或授予银行权限；未来收入计入0，未来借记与FULL新保护未证明时不得推断安全。</p>
    <section className="card readonly-section" aria-label="不可变产品目录"><h3>不可变产品原件</h3>{catalogue.isPending && <p role="status">正在读取实际登记目录…</p>}{catalogue.isError && <p role="alert">{errorMessage(catalogue.error)}</p>}{!catalogue.isError && catalogue.data && <><p>目录 {catalogue.data.state} · 服务端登记范围{catalogue.data.complete_within_registered_capacity ? '在容量内完整' : '未完整'} · 未登记 {catalogue.data.unregistered_product_ids.length}项</p>{catalogue.data.issues.map((issue) => <p className="notice" key={issue}>{issue}</p>)}<label className="field">版本来源筛选<select value={versionFilter} onChange={(event) => setVersionFilter(event.target.value)}><option value="ALL">全部登记历史原件</option><option value="MATCHED">当前来源整行匹配</option><option value="DRIFTED">当前来源已漂移</option></select></label><label className="field">产品原版本<select value={selectedVersion} onChange={(event) => setSelectedVersion(event.target.value)}><option value="">选择实际原版本</option>{versions.map((row) => <option value={row.id} key={row.id}>{row.product_code} v{row.version_number} · {row.current_source_matched ? '当前源匹配' : '历史保留 / 当前源漂移'}</option>)}</select></label>{selected && object(original) && <article><h4>{String(original.name ?? selected.product_code)} v{selected.version_number}</h4><p>原catalogue <code>{selected.id}</code> · 原product <code>{selected.product_id}</code> · observed_at {selected.observed_at}</p><p>生效窗口 {selected.effective_from} → {selected.effective_until ?? '无已登记截止'}；来源匹配不等于当前允许购买。</p><dl className="annual-amounts"><div><dt>类别 / 风险 / 本金波动</dt><dd>{String(original.asset_class)} / {String(original.risk_level)} / {original.principal_fluctuation ? '有' : '无'}</dd></div><div><dt>原起投</dt><dd>{money(original.minimum_purchase_cents as number)}</dd></div><div><dt>原锁定 / 赎回延迟</dt><dd>{String(original.lock_days)}天 / {String(original.redemption_delay_days)}天</dd></div><div><dt>原模拟年收益基点</dt><dd>{String(original.annual_yield_bps)} bps；不是实际收益</dd></div></dl><p>期限 {object(original.maturity_rule) && Number.isSafeInteger(original.maturity_rule.term_days) ? `${original.maturity_rule.term_days}天（原条款字段）` : '未知 / 未提供term_days，不能从名称推断'}；原rollover={object(original.maturity_rule) && typeof original.maturity_rule.rollover === 'boolean' ? String(original.maturity_rule.rollover) : 'UNKNOWN'}，auto_rollover={object(original.maturity_rule) && typeof original.maturity_rule.auto_rollover === 'boolean' ? String(original.maturity_rule.auto_rollover) : 'UNKNOWN'}。</p><p>到期后重新读取当时真实策略/资金/产品再判断；续期执行接口未实现。本页不自动滚存。</p><p className="caption">服务端 immutable_original_verified=true；旧决策绑定此目录=false，不声称旧run已使用本版本重放。原product hash <code>{selected.product_hash}</code>；terms digest <code>{selected.terms_digest}</code>。</p><details><summary>完整保留原产品JSON</summary><pre className="readonly-raw">{JSON.stringify(original, null, 2)}</pre></details></article>}<details><summary>整个目录原响应</summary><pre className="readonly-raw">{getOriginalFullProductsResponse(catalogue.data)}</pre></details></>}</section>
    <section className="card readonly-section" aria-label="原持仓可用日分桶"><h3>原持仓可用日分桶</h3><p>只按原available_at字段分组，maturity_at单独显示。HELD / MATURED等原状态和日期不等于银行实际回款证明；本金不加入今天现金。</p>{positions.isError && <p role="alert">{errorMessage(positions.error)}</p>}{!positions.isError && positions.data && <>{positions.data.items.length === 0 && <p>当前返回持仓0项，未补造产品或本金。</p>}{groupPrincipalDates(positions.data.items, (row) => row.available_at).map((bucket) => <article key={bucket.timestamp ?? 'UNKNOWN'}><h4>{bucket.timestamp ?? 'UNKNOWN · 原本金可用日期缺失'}</h4>{bucket.rows.map((position) => <p key={position.id}>原持仓 <code>{position.id}</code> · {position.status} · 本金 {money(position.principal_cents)} · 原成熟时刻 {position.maturity_at ?? '未知'} · 目标 <code>{position.goal_id ?? '未关联目标'}</code> · 购买授权版本 <code>{position.policy_version_id ?? '未提供'}</code></p>)}</article>)}<details><summary>原持仓响应</summary><pre className="readonly-raw">{getOriginalFullProductsResponse(positions.data)}</pre></details></>}</section>
    <section className="card readonly-section" aria-label="期限与组合只读规划"><h3>期限相容性与今日组合</h3>{policies.isError && <p role="alert">{errorMessage(policies.error)}</p>}<p>需要既有完整AssetAuthorizationPolicy规划确认；这里只收紧比较期限、用款日期、组合复杂度和换手，不能创建授权。<a href="#policies">查看实际策略</a></p><label className="field">实际完整资产声明<select value={assetPolicy} onChange={(event) => setAssetPolicy(event.target.value)}><option value="">选择原声明</option>{policies.data?.items.filter((row) => row.template_name === 'AssetAuthorizationPolicy').map((row) => <option value={row.policy_id} key={row.policy_id}>{row.name ?? row.policy_id} · {row.effective_status}</option>)}</select></label><label className="field">规划模式<select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="PORTFOLIO">今日多资产组合</option><option value="FIXED_LADDER">原目标定存梯度</option></select></label><label className="field">收益比较天数（1–365）<input inputMode="numeric" value={comparison} onChange={(event) => setComparison(event.target.value)} /></label><label className="field">最大今日批次数（1–4）<input inputMode="numeric" value={complexity} onChange={(event) => setComplexity(event.target.value)} /></label><label className="field">更严格换手上限（元，可留空）<input inputMode="decimal" value={turnover} onChange={(event) => setTurnover(event.target.value)} /></label><label className="field">更早用款日期（日初保守到账，可留空）<input type="date" value={useDate} onChange={(event) => setUseDate(event.target.value)} /></label><button type="button" disabled={!assetPolicy || asset.isFetching} onClick={readAssets}>读取原策略条件组合</button>{asset.isFetching && <p role="status">只读重算当前原资金与目录…</p>}{asset.isError && <p role="alert">{errorMessage(asset.error)}</p>}{!asset.isError && asset.data && <AssetResult data={asset.data} />}</section>
    <section className="card readonly-section" aria-label="提前支取只读规划"><h3>提前支取损失与回款期限</h3><p>读取既有报价，不发行新报价。损失金额/时限未知保留null；有损候选不能填入无损现金方案，ASK_ONCE只表示仍须独立选择/确认，执行未接。</p><label className="field">实际完整恢复声明<select value={recoveryPolicy} onChange={(event) => setRecoveryPolicy(event.target.value)}><option value="">选择原Recovery声明</option>{policies.data?.items.filter((row) => row.template_name === 'RecoveryPolicy').map((row) => <option value={row.policy_id} key={row.policy_id}>{row.name ?? row.policy_id} · {row.effective_status}</option>)}</select></label><label className="field">更早回款截止（带时区ISO，可留空）<input placeholder="2026-10-07T09:00:00+08:00" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label><button type="button" disabled={!recoveryPolicy || recovery.isFetching} onClick={readRecovery}>读取原报价条件影响</button>{recovery.isFetching && <p role="status">正在只读核对原购买、报价与365日保护…</p>}{recovery.isError && <p role="alert">{errorMessage(recovery.error)}</p>}{!recovery.isError && recovery.data && <RecoveryResult data={recovery.data} />}</section>{inputError && <p role="alert">{inputError}</p>}
    <FullAssetExecutionPanel mutationBlocked={mutationBlocked} />
  </div>;
}
