import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { compilationRef, declarationRef, estimateOnboardingReserve, findOnboardingCompilation, getOnboardingContext, getOnboardingProposals, getOnboardingTransactions, getOriginalOnboardingResponse, onboardingAssetConfiguration, onboardingObligationConfiguration, readOnboardingCompilation, readOnboardingDeclaration, reserveParameters, serverCalendarDate, submitOnboardingIntent } from '../api/onboarding';
import type { DeclarationRecord, Discovery, OnboardingContext, Reserve } from '../api/onboarding';
import { getGoals } from '../api/goals';
import { getPolicies } from '../api/policies';
import type { Compilation } from '../api/policies';
import { errorMessage } from '../api/http';
import { beginOnboardingCommand, beginOnboardingDeclarationReplay, endOnboardingAttempt, getOnboardingDraft, isDeclarationKind, prepareOnboardingDeclaration, prepareOnboardingIntent, recoverOnboardingDraft, retainOnboardingCandidate, retainOnboardingDeclaration, retainOnboardingDiscovery, sameOnboardingBinding, setOnboardingStep, updateOnboardingInput, useOnboardingDraft } from '../features/onboarding-draft';
import type { CandidateRef, DeclarationKind, DeclarationRef, OnboardingInputs, OnboardingIntent } from '../features/onboarding-draft';
import { formatMoneyCents } from '../features/money';
import { useDemoOperation } from '../features/demo-operation';
import { useFullPolicyOperation } from '../features/full-policy-operation';
import { useWriteInFlight } from '../features/write-flight';
import { ConfigurationReview } from '../components/PolicyConfigForm';

const steps = ['读取真实模拟账户规律', '发现义务候选', '复核持续时间与优先级', '准备生活准备金', '设置应急缓冲', '准备未来目标', '复核资产与安全恢复授权', '查看自主资金与Agent权力边界'];
const money = (value: number | null) => value === null ? 'UNKNOWN · 尚未证明' : `¥${formatMoneyCents(value)}`;
function Raw({ value, title }: { value: object; title: string }) { return <details><summary>{title}</summary><pre className="readonly-raw">{getOriginalOnboardingResponse(value) ?? '未保存原响应文本；不将派生展示称原字节'}</pre></details>; }
function Candidate({ reference: ref, context, kind }: { reference: CandidateRef; context: OnboardingContext; kind: 'emergency' | 'goal' }) {
  const current = context.binding !== null && sameOnboardingBinding(ref.binding, context.binding);
  const original = useQuery({ queryKey: ['onboarding-original-compilation', ref.compilation_id, ref.binding.user_id, ref.binding.epoch_id, ref.binding.reference_date], queryFn: () => readOnboardingCompilation(ref), retry: false, structuralSharing: false });
  const expectedType = kind === 'emergency' ? 'emergency_buffer' : 'goal_saving'; const result = original.data;
  return <section aria-label={kind === 'emergency' ? '原应急候选复核' : '原目标候选复核'}><h3>原候选 · 尚需独立明确确认</h3><p>原编译编号 <code>{ref.compilation_id}</code>；原日期 {ref.binding.reference_date} · {ref.binding.timezone}。</p><p>用户原文：{ref.input_text}</p>{!current && <p className="notice">BLOCKED · 当前用户/周期/日期与原候选锚不一致；仅看原材料，不能当作当前授权。</p>}
    {original.isPending && <p role="status">正在读取原编译…</p>}{original.isError && <p role="alert">{errorMessage(original.error)}；原候选未读得，不回落本地草稿作为成功。</p>}
    {result && !original.isError && <><p>原服务候选状态 {result.proposal_status ?? '未形成完整提案'}；配置hash <code>{result.configuration_hash ?? 'UNKNOWN · 配置未完整'}</code>。</p><ConfigurationReview configuration={result.configuration ?? result.compilation.draft} />
      {result.compilation.issues!.map((issue, index) => <p role="status" key={index}>{issue.code} · {issue.field} · {issue.message} · 原片段 {issue.source_fragment}</p>)}<ul>{result.compilation.assumptions!.map((item) => <li key={item}>待复核假设：{item}</li>)}</ul>
      {result.configuration?.type !== expectedType && <p className="notice">BLOCKED · 本步需要{expectedType}；当前候选类型不符或必要字段尚缺。请在原编译入口明确修订，不能自动补齐。</p>}
      {current && <p><a href="#policies">到策略中心读取并修订原编译、复核完整配置后明确确认</a>{kind === 'goal' && <>；确认后再<a href="#goals">到目标中心关联实际目标账户</a></>}。</p>}
      <Raw value={result} title="查看原编译完整响应与问题" />
    </>}
    <p className="caption">编译、PROPOSED和本地草稿没有执行权限；已确认原候选也须重新读取当前策略与版本条件。FULL目标额外属性的双hash确认交互尚未在此引导接入。</p>
  </section>;
}
function DeclaredCandidate({ reference, kind }: { reference: DeclarationRef; kind: DeclarationKind }) {
  const intent: OnboardingIntent = { kind, body_json: reference.body_json, binding: reference.binding }; const result = useQuery({ queryKey: ['onboarding-original-declaration', reference.proposal_id, reference.request_hash], queryFn: () => readOnboardingDeclaration(intent), retry: false, structuralSharing: false }); const record = result.data?.record;
  const matching = record?.proposal_id === reference.proposal_id && record.evidence_id === reference.evidence_id && record.configuration_hash === reference.configuration_hash && record.request_hash === reference.request_hash;
  return <section aria-label="已登记的原结构化候选"><h3>原结构化候选 · 独立确认前不授权</h3><p>原提案 <code>{reference.proposal_id}</code>；原证据 <code>{reference.evidence_id}</code>。</p>{result.isPending && <p role="status">正在只读核对原声明…</p>}{result.isError && <p role="alert">{errorMessage(result.error)}；原候选未核对，不能据本地记录授权。</p>}{result.data && !result.isError && (result.data.status !== 'RECORDED' || !matching ? <p role="alert">UNKNOWN · 本次原键未读得完整匹配候选，不自动再声明或确认。</p> : <><ConfigurationReview configuration={record!.configuration} /><p>当前原提案状态 {record!.current_proposal_status} · 配置hash <code>{record!.configuration_hash}</code> · 原请求hash <code>{record!.request_hash}</code>。</p><p>grants_authority=false；回执不是当前权限。<a href="#policies">到策略中心读取该原提案、复核完整配置并独立明确确认</a>。修改这里的新草稿不会改写该原候选。</p><Raw value={result.data} title="原键查询完整响应与原声明body" /></>)}</section>;
}
export default function OnboardingPage({ mutationBlocked = false }: { mutationBlocked?: boolean }) {
  const client = useQueryClient(); const state = useOnboardingDraft(); const demo = useDemoOperation(); const full = useFullPolicyOperation(); const writing = useWriteInFlight(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [note, setNote] = useState(''); const [offset, setOffset] = useState(0); const [reserve, setReserve] = useState<Reserve | null>(null); const [discovery, setDiscovery] = useState<Discovery | null>(null);
  useEffect(() => { recoverOnboardingDraft(); }, []);
  const step = state.draft.step; const inputs = state.draft.inputs; const context = useQuery({ queryKey: ['onboarding-context'], queryFn: getOnboardingContext, retry: false, structuralSharing: false });
  const transactions = useQuery({ queryKey: ['onboarding-transactions', offset], queryFn: () => getOnboardingTransactions(offset), enabled: step === 1, retry: false, structuralSharing: false });
  const proposals = useQuery({ queryKey: ['onboarding-proposals'], queryFn: getOnboardingProposals, enabled: [2, 3, 5, 6].includes(step), retry: false, structuralSharing: false });
  const policies = useQuery({ queryKey: ['onboarding-current-policies'], queryFn: getPolicies, enabled: step === 7, retry: false });
  const goals = useQuery({ queryKey: ['onboarding-current-goals'], queryFn: getGoals, enabled: step === 6 || step === 7, retry: false });
  const blocked = mutationBlocked || busy || state.busy || state.draft.pending !== null || state.storage_error !== null || demo.busy || demo.pending !== null || demo.storage_error !== null || full.busy || full.pending !== null || full.storage_error !== null || writing;
  function update<K extends keyof OnboardingInputs>(key: K, value: OnboardingInputs[K]) { setError(''); try { updateOnboardingInput(key, value); if (['horizon_days', 'lookback_days', 'quantile', 'extra_buffer_yuan', 'categories', 'exclude_one_off'].includes(key)) setReserve(null); } catch (e) { setError(errorMessage(e)); } }
  function navigate(next: number) { setError(''); try { setOnboardingStep(next); } catch (e) { setError(errorMessage(e)); } }
  async function freshContext() { const current = await getOnboardingContext(); client.setQueryData(['onboarding-context'], current); if (!current.binding) throw new Error('BLOCKED · 未读得当前开放模拟周期；未开始候选请求'); return current; }
  async function submit(kind: 'DISCOVERY' | 'EMERGENCY' | 'GOAL') {
    if (blocked) return; setBusy(true); setError(''); setNote('');
    try { const actual = await freshContext(); const intent = prepareOnboardingIntent(kind, actual.binding!, kind === 'EMERGENCY' ? inputs.emergency_text : inputs.goal_text); beginOnboardingCommand(intent);
      try { const response = await submitOnboardingIntent(intent);
        if (kind === 'DISCOVERY') { const result = response as Discovery; const list = await getOnboardingProposals(); const returned = [...result.created_proposal_ids, ...result.reused_proposal_ids]; if (!returned.every((id) => list.items.some((item) => item.id === id && item.source_type === 'DETERMINISTIC_POLICY_DISCOVERY'))) throw new Error('发现回执中的原提案未读得，保留原请求'); retainOnboardingDiscovery(intent, returned); setDiscovery(result); client.setQueryData(['onboarding-proposals'], list); setNote('已读得这次发现回执中的原候选；没有确认或授予执行权限。'); }
        else { const result = response as Compilation; const original = await readOnboardingCompilation({ compilation_id: result.compilation_id, binding: intent.binding }); if (original.configuration_hash !== result.configuration_hash || original.proposal_id !== result.proposal_id) throw new Error('原编译与本次回执不一致，保留原请求'); retainOnboardingCandidate(intent, compilationRef(intent, original)); setNote('已保存原编译身份；退出后需重新读取并在既有入口明确确认，没有自动生效。'); await client.invalidateQueries({ queryKey: ['onboarding-proposals'] }); }
      } finally { endOnboardingAttempt(); }
    } catch (e) { setError(`${errorMessage(e)}${getOnboardingDraft().draft.pending ? '；请只读核对原请求，不换原文重提。' : ''}`); } finally { setBusy(false); }
  }
  async function admitDeclaration(intent: OnboardingIntent) { const response = await submitOnboardingIntent(intent) as DeclarationRecord; const lookup = await readOnboardingDeclaration(intent); if (lookup.status !== 'RECORDED' || !lookup.record || lookup.record.proposal_id !== response.proposal_id || lookup.record.evidence_id !== response.evidence_id || lookup.record.configuration_hash !== response.configuration_hash || lookup.record.request_hash !== response.request_hash) throw new Error('原键未读得完整匹配候选，保留原请求'); retainOnboardingDeclaration(intent, declarationRef(intent, lookup.record)); await client.invalidateQueries({ queryKey: ['onboarding-proposals'] }); setNote('已原键核对这份USER_DECLARED新候选；原来源提案不变，没有自动确认。'); }
  async function submitDeclaration(kind: DeclarationKind, configuration: Record<string, unknown>, sourceProposalId: string | null = null) { if (blocked) return; setBusy(true); setError(''); setNote(''); try { const actual = await freshContext(); if (kind === 'LIVING' && (!reserve || reserve.estimation.status !== 'READY' || serverCalendarDate(reserve.as_of, actual.binding!.timezone) !== actual.binding!.reference_date)) throw new Error('生活估算不完整或跨日期，请先只读重新估算'); const intent = prepareOnboardingDeclaration(kind, actual.binding!, configuration, sourceProposalId); beginOnboardingCommand(intent); try { await admitDeclaration(intent); } finally { endOnboardingAttempt(); } } catch (e) { setError(`${errorMessage(e)}；未确认或授予权限，已保存原请求时继续原键核对。`); } finally { setBusy(false); } }
  async function replayDeclaration() { const intent = state.draft.pending; if (!intent || !isDeclarationKind(intent.kind) || busy || state.busy || mutationBlocked) return; setBusy(true); setError(''); setNote(''); try { const actual = await freshContext(); if (actual.binding!.user_id !== intent.binding.user_id || actual.binding!.epoch_id !== intent.binding.epoch_id) throw new Error('原声明用户/周期已变化，不能向新周期重放'); beginOnboardingDeclarationReplay(intent); try { await admitDeclaration(intent); } finally { endOnboardingAttempt(); } } catch (e) { setError(`${errorMessage(e)}；原body/key保持，不能新键重提。`); } finally { setBusy(false); } }
  async function recover() {
    const original = state.draft.pending; if (!original || state.busy || busy) return; setBusy(true); setError(''); setNote('');
    try { const actual = await freshContext(); if (isDeclarationKind(original.kind)) { if (actual.binding!.user_id !== original.binding.user_id || actual.binding!.epoch_id !== original.binding.epoch_id) throw new Error('BLOCKED · 原声明用户/周期已变化'); const lookup = await readOnboardingDeclaration(original); if (lookup.status !== 'RECORDED' || !lookup.record) { setNote('NOT_FOUND · 不是最终未提交证明；原body/key保留，新写入仍禁止。可以保留记录核对，或用户明确同原键/body重放候选。'); return; } retainOnboardingDeclaration(original, declarationRef(original, lookup.record)); setNote('原键已核对完整原候选身份；只恢复填写，仍需独立明确确认。'); return; } if (!sameOnboardingBinding(original.binding, actual.binding!)) throw new Error('BLOCKED · 原用户/周期/日期已变化，不能把新日期编译当原请求恢复');
      const list = await getOnboardingProposals(); client.setQueryData(['onboarding-proposals'], list);
      if (original.kind === 'DISCOVERY') { setNote('已只读列出当前候选；发现接口缺按原请求查询的持久回执，不能证明这些候选就是该未知响应。BLOCKED · 原发现请求仍保留，没有自动重复发现。'); return; }
      const ref = await findOnboardingCompilation(original, actual.binding!, list.items); retainOnboardingCandidate(original, ref); setNote('已通过唯一原提案/原编译读取恢复候选身份；候选仍未生权限。');
    } catch (e) { setError(`${errorMessage(e)}；原body和日期锚继续保留，没有自动POST。`); } finally { setBusy(false); }
  }
  async function estimate() { if (blocked) return; setBusy(true); setError(''); setReserve(null); try { const params = reserveParameters(inputs); const actual = await freshContext(); setReserve(await estimateOnboardingReserve(actual.binding!, params)); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  const data = context.data; const selected = proposals.data?.items.find((item) => item.id === inputs.obligation_id); let obligationConfig: Record<string, unknown> | null = null; let assetConfig: Record<string, unknown> | null = null; let configurationIssue = '';
  try { if (step === 3 && selected) obligationConfig = onboardingObligationConfiguration(selected, inputs); if (step === 7) assetConfig = onboardingAssetConfiguration(inputs); } catch (e) { configurationIssue = errorMessage(e); }
  return <div className="onboarding-page"><header><h1>首次引导 · 明确事实与授权</h1><p>按8步复核账户、义务、保护和目标。本地草稿只恢复填写位置；浏览到第8步不表示8步已完成，更不会自动确认策略或执行资金。</p><a href="#overview">只读查看资金总览</a></header>
    <nav className="onboarding-steps" aria-label="首次引导8个原步骤"><ol>{steps.map((title, index) => <li key={title}><button type="button" aria-current={step === index + 1 ? 'step' : undefined} disabled={state.storage_error !== null} onClick={() => navigate(index + 1)}>{index + 1}. {title}</button></li>)}</ol></nav>
    <p role="status">当前浏览步骤 {step}/8 · 功能与验收仍部分覆盖，不以勾选完成计权限。</p>{state.storage_error && <p role="alert">{state.storage_error}</p>}{error && <p role="alert">{error}</p>}{note && <p role="status">{note}</p>}
    {state.draft.pending && <section className="onboarding-pending" aria-label="待核对引导原请求"><h2>待核对原候选请求 · {state.draft.pending.kind}</h2><p>新候选写入和输入编辑暂停。此请求不涉及资金执行；它的结果未知仍须沿原身份核对。</p><pre className="readonly-raw">{JSON.stringify(state.draft.pending, null, 2)}</pre><button type="button" disabled={busy || state.busy} onClick={() => void recover()}>只读核对原引导候选</button>{isDeclarationKind(state.draft.pending.kind) && <button type="button" disabled={mutationBlocked || busy || state.busy || !!state.storage_error || demo.busy || !!demo.pending || !!demo.storage_error || full.busy || !!full.pending || !!full.storage_error || writing} onClick={() => void replayDeclaration()}>手动重放原结构化候选（同原键/body）</button>}<p>不自动重编译；原接口缺client key/持久发现回执时保留具体阻断。</p></section>}
    {context.isPending && <p role="status">正在读取真实模拟账户、当前周期和资金边界…</p>}{context.isError && <p role="alert">{errorMessage(context.error)}；未把本地草稿当已读账户。</p>}<button type="button" disabled={context.isFetching || busy} onClick={() => void context.refetch()}>只读刷新当前账户与边界</button>
    {data && !context.isError && <p className="caption">原用户 <code>{data.accounts.user_id}</code>；原周期 <code>{data.demo.epoch_id ?? 'UNKNOWN · 当前无周期'}</code>；服务日期 {data.binding?.reference_date ?? '未绑定'} · {data.accounts.timezone}。账户/边界/周期分别读取，不是一份事务快照。</p>}
    <section className="onboarding-current-step" aria-label={`引导第${step}步 ${steps[step - 1]}`}><h2>{step}. {steps[step - 1]}</h2>
      {step === 1 && <>{data && !context.isError && <><p>原账户现金 {money(data.accounts.cash_balance_cents)}；原资产本金 {money(data.accounts.position_principal_cents)}；未知持仓本金 {money(data.accounts.unknown_position_principal_cents)}。这些是事实金额，不能直接当可自主金额。</p><ul>{data.accounts.accounts.map((account) => <li key={account.id}>{account.name} · {account.account_type} · {money(account.balance_cents)} · 原观察 {account.observed_at}</li>)}</ul><Raw value={data.accounts} title="账户与信用卡账单完整原响应" /></>}
        {transactions.isPending && <p role="status">正在读取该页原交易…</p>}{transactions.isError && <p role="alert">{errorMessage(transactions.error)}</p>}{transactions.data && !transactions.isError && <><p>本页原交易 {transactions.data.items.length} 条 / 总数 {transactions.data.total}，offset={transactions.data.offset}；只读分页不代表已完整覆盖历史。</p><ul className="onboarding-transactions">{transactions.data.items.map((item) => <li key={item.id}><p>{item.occurred_at} · {item.direction} · {money(item.amount_cents)} · {item.category}{!item.category_confirmed && '（分类未确认）'}{item.is_one_off && '（一次性）'}</p><code>{item.source_ref}</code> · 证据 {item.evidence_id ?? 'UNKNOWN · 无证据引用'}</li>)}</ul><div className="onboarding-actions"><button type="button" disabled={transactions.isFetching || offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}>上一页原交易</button><button type="button" disabled={transactions.isFetching || offset + transactions.data.items.length >= transactions.data.total || offset >= 1_000_000} onClick={() => setOffset(offset + 50)}>下一页原交易</button></div><Raw value={transactions.data} title="本页原交易完整响应" /></>}</>}
      {step === 2 && <><p>从真实模拟历史提出可能的房租与信用卡账期还款候选；缺少规律、证据或其他贷款类型时不会猜测。发现只产生候选，不确认。</p><button type="button" disabled={blocked || !data?.binding || context.isError} onClick={() => void submit('DISCOVERY')}>用户主动从历史发现候选</button>
        {proposals.isError && <p role="alert">{errorMessage(proposals.error)}</p>}{proposals.data && <><p>服务当前提案 {proposals.data.items.length} 项；不把其他来源提案叫本次发现。</p><ul>{proposals.data.items.filter((item) => item.source_type === 'DETERMINISTIC_POLICY_DISCOVERY').map((item) => <li key={item.id}>{String(item.configuration.name ?? item.configuration.type)} · {item.status} · 原配置hash <code>{item.configuration_hash}</code><p>{item.source_text}</p><a href="#policies">到策略中心读取原发现候选</a></li>)}</ul></>}
        {discovery && <><p>这次实际回执：新候选{discovery.created_proposal_ids.length}、复用{discovery.reused_proposal_ids.length}；跳过{discovery.skipped.length}。不代表后续都可确认。</p><ul>{discovery.skipped.map((item, index) => <li key={index}>{item.reason_code} · {item.source_ref}</li>)}</ul><Raw value={discovery} title="原发现回执与跳过原因" /></>}</>}
      {step === 3 && <><p>选择原义务候选，填写拟调整的持续时间与重要程度。用户主动提交时创建一份USER_DECLARED新候选；原发现提案及原hash不会被改写。</p><label className="field">原义务候选<select value={inputs.obligation_id} disabled={blocked} onChange={(event) => update('obligation_id', event.target.value)}><option value="">请选择实际候选</option>{proposals.data?.items.filter((item) => item.configuration.type === 'recurring_obligation').map((item) => <option key={item.id} value={item.id}>{String(item.configuration.name ?? item.id)} · {item.status}</option>)}</select></label>{selected && <><p>原proposal <code>{selected.id}</code> · 原hash <code>{selected.configuration_hash}</code></p><ConfigurationReview configuration={selected.configuration} /></>}
        <label className="field">拟开始日期<input type="date" value={inputs.valid_from} disabled={blocked} onChange={(event) => update('valid_from', event.target.value)} /></label><label className="field">拟结束日期（含当天）<input type="date" value={inputs.valid_until} disabled={blocked} onChange={(event) => update('valid_until', event.target.value)} /></label><label className="field">拟重要程度（0–100）<input inputMode="numeric" value={inputs.importance} disabled={blocked} onChange={(event) => update('importance', event.target.value)} /></label>
        {configurationIssue && <p role="status">待补齐候选：{configurationIssue}</p>}{obligationConfig && <><h3>拟提交新候选完整配置 · 先复核</h3><ConfigurationReview configuration={obligationConfig} /></>}<button type="button" disabled={blocked || !data?.binding || context.isError || !obligationConfig} onClick={() => obligationConfig && void submitDeclaration('OBLIGATION', obligationConfig, selected!.id)}>用户主动提交完整义务候选（不确认）</button><p>仅改上面的期限与重要程度；原金额、收款对象、提前天数、auto_execute和其他优先级字段全部保留并展示。新候选无权限，仍到<a href="#policies">既有策略入口</a>逐项复核、独立明确确认。</p>{state.draft.declarations.obligation && <DeclaredCandidate reference={state.draft.declarations.obligation} kind="OBLIGATION" />}</>}
      {step === 4 && <><p>以实际日常消费历史与覆盖证据估算生活准备金，不评价用户消费。参数初值来自原接口默认，仅供复核，未确认保护策略。</p><div className="onboarding-form-grid">{([['horizon_days', '保护天数（1–366）'], ['lookback_days', '历史回看天数（1–366）'], ['quantile', '分位数（大于0且不超过1）'], ['extra_buffer_yuan', '额外缓冲（元）']] as const).map(([key, title]) => <label className="field" key={key}>{title}<input inputMode="decimal" value={inputs[key]} disabled={blocked} onChange={(event) => update(key, event.target.value)} /></label>)}</div><details><summary>分类与一次性排除条件</summary><label className="field">原必要消费分类代码（逗号分隔）<input value={inputs.categories} disabled={blocked} onChange={(event) => update('categories', event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={inputs.exclude_one_off} disabled={blocked} onChange={(event) => update('exclude_one_off', event.target.checked)} />排除原已标注的一次性消费</label></details><button type="button" disabled={blocked || !data?.binding || context.isError} onClick={() => void estimate()}>只读估算生活准备金</button>
        {reserve && <section aria-label="真实生活准备金估算结果"><h3>{reserve.estimation.status}</h3><p>原范围 {reserve.estimation.history_start} → {reserve.estimation.history_end}；实际日分母{reserve.estimation.daily_amounts.length}，有效窗口{reserve.estimation.window_count}，原rank {reserve.estimation.rank ?? 'UNKNOWN'}。</p><p>基础准备金 {money(reserve.estimation.base_reserve_cents)}；建议准备金 {money(reserve.estimation.recommended_reserve_cents)}。原input_digest <code>{reserve.input_digest}</code>。</p><ul>{reserve.source_issues.map((item, index) => <li key={index}>{item.code} · {item.source_ref} · {item.message}</li>)}{reserve.estimation.coverage_gaps.map((gap) => <li key={gap.account_id}>账户 {gap.account_id} 缺 {gap.missing_dates.length} 天覆盖；缺日期：{gap.missing_dates.join('、')}</li>)}</ul>{reserve.candidate_configuration ? <><ConfigurationReview configuration={reserve.candidate_configuration} /><p>原候选hash <code>{reserve.candidate_configuration_hash}</code>；CANDIDATE_READY_UNCONFIRMED。</p><button type="button" disabled={blocked || !data?.binding || context.isError} onClick={() => void submitDeclaration('LIVING', reserve.candidate_configuration!)}>用户主动提交生活保护候选（不确认）</button></> : <p>UNKNOWN · 尚未形成可确认候选，未把建议值补零。</p>}<p>估算参数、排除项和覆盖证据只供复核。声明仅产生USER_DECLARED新提案，不把估计结果冒充银行事实；保护策略仍需独立明确确认。</p><Raw value={reserve} title="完整估算原响应与全日/窗口/排除分母" /></section>}{state.draft.declarations.living && <DeclaredCandidate reference={state.draft.declarations.living} kind="LIVING" />}</>}
      {(step === 5 || step === 6) && <><p>{step === 5 ? '说明需要保留的应急金额和有效期；规则编译只准备候选。' : '说明未来目标金额、具体日期和月度最低/建议/最高储备额；不将未来收入加入今天自主资金。'}</p><label className="field">{step === 5 ? '应急策略原文' : '未来目标策略原文'}<textarea rows={4} maxLength={2000} disabled={blocked} value={step === 5 ? inputs.emergency_text : inputs.goal_text} onChange={(event) => update(step === 5 ? 'emergency_text' : 'goal_text', event.target.value)} placeholder={step === 5 ? '保留明确金额的应急金，可注明有效期；缺金额不猜测' : '明确一个买车/旅行目标、金额、截止日和月度三项储备额；缺项继续复核'} /></label><button type="button" disabled={blocked || !data?.binding || context.isError || !(step === 5 ? inputs.emergency_text : inputs.goal_text).trim()} onClick={() => void submit(step === 5 ? 'EMERGENCY' : 'GOAL')}>用户主动编译{step === 5 ? '应急' : '目标'}候选</button>
        {data && state.draft.candidates[step === 5 ? 'emergency' : 'goal'] && <Candidate key={state.draft.candidates[step === 5 ? 'emergency' : 'goal']!.compilation_id} reference={state.draft.candidates[step === 5 ? 'emergency' : 'goal']!} context={data} kind={step === 5 ? 'emergency' : 'goal'} />}
        {step === 6 && <><p><a href="#goals">读取原目标中心并关联实际账户</a>。候选确认和目标账户登记分开，不能只读编译成功就称目标已创建。</p>{goals.isError && <p role="alert">{errorMessage(goals.error)}</p>}{goals.data && <p>服务当前原目标 {goals.data.items.length} 个；这不是本步新目标已创建的证明。</p>}<p className="notice">BLOCKED · 本向导尚未接完整目标额外属性双hash确认与原键结果查询；保留原编译和既存确认/账户登记入口。</p></>}</>}
      {step === 7 && <><p>复核实际MVP资产授权中的金额上限、到账/锁定容忍度和安全恢复条件。下面是本地拟声明字段，没有confirm或银行权限；不使用独立FULL bank_authority=false回执代替原MVP金融授权。</p>
        <label className="field">拟资产策略名称<input maxLength={120} disabled={blocked} value={inputs.asset_name} onChange={(event) => update('asset_name', event.target.value)} /></label><div className="onboarding-form-grid"><label className="field">拟资产有效开始日期<input type="date" disabled={blocked} value={inputs.asset_valid_from} onChange={(event) => update('asset_valid_from', event.target.value)} /></label><label className="field">拟资产有效结束日期（含当天）<input type="date" disabled={blocked} value={inputs.asset_valid_until} onChange={(event) => update('asset_valid_until', event.target.value)} /></label></div>
        <label className="field">拟资产作用域<select disabled={blocked} value={inputs.asset_scope} onChange={(event) => update('asset_scope', event.target.value)}><option value="general_idle_funds">一般安全闲置资金</option><option value="goal">指定实际目标</option></select></label>{inputs.asset_scope === 'goal' && <label className="field">拟关联实际目标<select value={inputs.asset_goal_id} disabled={blocked} onChange={(event) => update('asset_goal_id', event.target.value)}><option value="">请选择当前原目标</option>{goals.data?.items.map((goal) => <option key={goal.id} value={goal.id}>{goal.name} · {goal.id}</option>)}</select></label>}
        <fieldset disabled={blocked}><legend>拟允许的资产类别</legend>{['CASH', 'CASH_MGMT_T0', 'CASH_MGMT_T1', 'FIXED_DEPOSIT'].map((name) => { const selected = inputs.asset_classes.split(',').filter(Boolean); return <label className="checkbox-field" key={name}><input type="checkbox" checked={selected.includes(name)} onChange={(event) => update('asset_classes', (event.target.checked ? [...selected, name] : selected.filter((value) => value !== name)).join(','))} />{name}</label>; })}</fieldset>
        <div className="onboarding-form-grid">{([['total_cap_yuan', '拟自主总本金上限（元）'], ['single_cap_yuan', '拟单次金额上限（元）'], ['redemption_days', '拟最长赎回到账天数'], ['lock_days', '拟最长锁定天数'], ['principal_risk', '拟最高本金风险等级（0–5）']] as const).map(([key, title]) => <label className="field" key={key}>{title}<input value={inputs[key]} inputMode="decimal" disabled={blocked} onChange={(event) => update(key, event.target.value)} /></label>)}</div>
        <label className="checkbox-field"><input type="checkbox" disabled={blocked} checked={inputs.auto_recovery} onChange={(event) => update('auto_recovery', event.target.checked)} />拟允许无损自动安全恢复（仍须正式确认原策略）</label><label className="checkbox-field"><input type="checkbox" disabled={blocked} checked={inputs.penalty_withdrawal} onChange={(event) => update('penalty_withdrawal', event.target.checked)} />拟允许有损提前退出（草稿不是本次损失确认）</label>
        {configurationIssue && <p role="status">待补齐候选：{configurationIssue}</p>}{assetConfig && <><h3>拟资产候选完整配置 · 先复核</h3><ConfigurationReview configuration={assetConfig} /></>}<button type="button" disabled={blocked || !data?.binding || context.isError || !assetConfig || (assetConfig.scope === 'goal' && !goals.data?.items.some((goal) => goal.id === assetConfig.goal_id))} onClick={() => assetConfig && void submitDeclaration('ASSET', assetConfig)}>用户主动提交资产候选（不确认、不执行）</button><p>这份声明只产生USER_DECLARED提案；安全恢复/有损退出的授权效力仍由独立明确确认和执行时原服务验证决定。Scenario实验接口不会被浏览器调用。<a href="#demo">既有演示模板入口</a>与这份自定义候选独立。</p>{state.draft.declarations.asset && <DeclaredCandidate reference={state.draft.declarations.asset} kind="ASSET" />}
        {policies.isError && <p role="alert">{errorMessage(policies.error)}</p>}{policies.data && <><h3>当前服务读得的原资产策略</h3>{policies.data.items.filter((policy) => policy.policy_type === 'asset_authorization').map((policy) => <section key={policy.id}><p>{policy.name} · {policy.effective_status} · 原版本核验{policy.version_authorized ? '服务报告通过' : '未通过'}</p>{policy.current_version ? <ConfigurationReview configuration={policy.current_version.configuration} /> : <p>UNKNOWN · 缺当前版本</p>}<p>这些原配置条件不是向导新授予的权限，具体执行仍由原服务即时重验。</p></section>)}</>}
      </>}
      {step === 8 && <>{data && !context.isError && <><p>原边界 {data.dashboard.boundary.state} · {data.dashboard.boundary.status}，时点 {data.dashboard.as_of}。</p><dl className="onboarding-boundary"><div><dt>当前安全闲置额（财务边界）</dt><dd>{money(data.dashboard.boundary.safe_idle_cents)}</dd></div><div><dt>当前可自主执行金额</dt><dd>UNKNOWN · 尚未合并当前资产授权与执行条件</dd></div><div><dt>当前受保护资金</dt><dd>{money(data.dashboard.boundary.current_protected_cents)}</dd></div><div><dt>最小余量</dt><dd>{money(data.dashboard.boundary.minimum_margin_cents)}</dd></div><div><dt>当前资金缺口</dt><dd>{money(data.dashboard.boundary.deficit_cents)}</dd></div></dl><ul>{data.dashboard.boundary.blocking_constraints.map((item, index) => <li key={index}>{item.code} · {item.date ?? '未提供日期'} · {item.entity_id ?? '未提供来源编号'} · 原需要 {item.required_cents == null ? 'UNKNOWN' : money(item.required_cents)}</li>)}</ul></>}
        <p>财务边界内安全闲置额不是自动执行额度；还须结合实际资产作用域、总额/单次上限与具体执行门重验。Agent仅在已确认原策略、可信当前事实和具体产品/执行条件内工作。候选与草稿不授权；未来收入不能扩大今天的自主资金。UNKNOWN保持未知；有损退出仍须原明确确认，普通消费只记事实。</p><p>执行与年度规划边界另见<a href="#annual">年度规划</a>；从<a href="#policies">策略中心</a>复核当前状态，从<a href="#evidence">证据入口</a>检查来源。这里没有“一键完成/授权全部”。</p><p className="notice">原8步完整首次浏览器流程、退出恢复、可用性及尚缺后台确认/声明链继续PENDING。当前仅已接步骤可运行，不以导航到末步关闭FULL-701。</p></>}
    </section>
    <footer className="onboarding-actions"><button type="button" disabled={step === 1 || state.storage_error !== null} onClick={() => navigate(step - 1)}>上一步（仅浏览）</button><button type="button" disabled={step === 8 || state.storage_error !== null} onClick={() => navigate(step + 1)}>下一步（不确认、不授权）</button></footer>
  </div>;
}
