import { webcrypto } from 'node:crypto';
import { fireEvent, render, screen, within, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { dashboardFixture } from '../tests/dashboard-fixture';
import { stateFixture } from '../tests/demo-fixture';
import { questionBase, questionIntentFixture, questionLookupFixture, questionResponseFixture, questionSession, questionVariables } from '../tests/question-fixture';
let operation: typeof import('../features/one-question-operation'); let page: typeof import('./OneQuestionPage'); let queries: typeof import('@tanstack/react-query');
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubEnv('VITE_API_BASE_URL', 'http://unit-question-page.local'); vi.stubGlobal('crypto', webcrypto); operation = await import('../features/one-question-operation'); page = await import('./OneQuestionPage'); queries = await import('@tanstack/react-query'); });
afterEach(() => { sessionStorage.clear(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); });
function transport(options: { lost?: boolean; notFound?: boolean; stale?: boolean; closed?: boolean; bad?: boolean } = {}) {
  const calls: { method: string; path: string; body: unknown; raw: string | undefined }[] = [];
  let latest: ReturnType<typeof questionResponseFixture> | null = null;
  vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const path = new URL(String(input)).pathname; const method = init?.method ?? 'GET'; const body = init?.body ? JSON.parse(String(init.body)) : undefined; calls.push({ method, path, body, raw: init?.body === undefined ? undefined : String(init.body) }); let data: unknown;
    if (path.endsWith('/accounts/summary')) data = dashboardFixture().account_facts.facts;
    else if (path.endsWith('/dashboard')) data = dashboardFixture(); else if (path.endsWith('/demo/state')) data = stateFixture();
    else if (path.includes('/by-key/') || path.includes('/by-start-key/')) data = questionLookupFixture(operation.getOneQuestionOperation().pending!, !options.notFound);
    else if (method === 'POST') { const pending = operation.getOneQuestionOperation().pending!; expect(sessionStorage.getItem(sessionStorage.key(0)!)).toBe(JSON.stringify(pending)); if (options.lost) throw new Error('TOOL_ONLY_LOST_RESPONSE'); const lookup = questionLookupFixture(pending); const value = questionResponseFixture(); value.original_receipt = lookup.original_receipt!; value.current_revision = lookup.current_revision!; value.effective_state = value.current_revision.state; value.pending_question = value.current_revision.pending_question; if (pending.kind === 'CLOSE') { value.current_source_fingerprint = null; value.fresh_evaluation_at = null; } latest = structuredClone(value); data = value; }
    else { const value = latest ? structuredClone(latest) : questionResponseFixture(); if (options.stale) { value.effective_state = 'STALE_RECOMPUTATION_REQUIRED'; value.pending_question = null; value.current_source_fingerprint = 'b'.repeat(64); } if (options.closed) { Object.assign(value.current_revision, { state: 'CLOSED', command_kind: 'CLOSE', revision: 2, previous_run_id: value.original_receipt.run_id, pending_question: null }); value.effective_state = 'CLOSED'; value.pending_question = null; value.current_source_fingerprint = null; value.fresh_evaluation_at = null; } if (options.bad) (value as unknown as Record<string, unknown>).execution_eligible = true; data = value; }
    return new Response(JSON.stringify(data));
  })); return calls;
}
function open(blocked = false) { const Component = page.default; const client = new queries.QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } }); render(<queries.QueryClientProvider client={client}><Component mutationBlocked={blocked} /></queries.QueryClientProvider>); }
async function loadSession() { fireEvent.change(screen.getByLabelText('原会话UUID'), { target: { value: questionSession } }); fireEvent.click(screen.getByRole('button', { name: '读取原会话' })); return screen.findByRole('region', { name: '当前问答' }); }
test('只读恢复显示一个实际pending/完整2世界，精确钱额，不自动POST/确认/资金', async () => { const calls = transport(); open(); const region = await loadSession(); expect(within(region).getByRole('group', { name: '本轮只回答：amount' })).toBeVisible(); expect(within(region).getByRole('button', { name: 'small · ¥100.01' })).toBeVisible(); expect(within(region).getByText('2 / 2 / 2 / 0')).toBeVisible(); expect(screen.getByText(/不是真实资金执行/)).toBeVisible(); expect(calls.every((call) => call.method === 'GET')).toBe(true); });
test('用户主动START精确原动作/完整变量与实际epoch，POST前持久原请求；回执仍不自动清门', async () => { const calls = transport(); open(); const start = screen.getByRole('button', { name: '保存原请求并开始问答' }); await waitFor(() => expect(start).toBeEnabled()); fireEvent.change(screen.getByLabelText('原准备行动UUID'), { target: { value: questionBase } }); fireEvent.change(screen.getByLabelText('完整有限变量JSON'), { target: { value: JSON.stringify(questionVariables) } }); fireEvent.click(start); await screen.findByText(/已收到原回执/); const pending = operation.getOneQuestionOperation().pending!; expect(pending.kind).toBe('START'); expect(calls.filter((call) => call.method === 'POST')).toEqual([{ method: 'POST', path: '/api/v1/finite-planning/sessions', body: pending.body, raw: pending.body_json }]); expect(start).toBeDisabled(); });
test('ANSWER响应丢失留exactbody/key，刷新无重发，NOT_FOUND非终局，同原body手动再提交', async () => { const calls = transport({ lost: true, notFound: true }); open(); await loadSession(); fireEvent.click(screen.getByRole('button', { name: 'small · ¥100.01' })); await screen.findByText(/原结果可能不明/); const pending = operation.getOneQuestionOperation().pending!; expect(pending.kind).toBe('ANSWER'); expect(pending.body).toMatchObject({ choice_key: 'small', expected_revision: 1 }); fireEvent.click(screen.getByRole('button', { name: '原键只读核对' })); await screen.findByText(/原键暂未找到/); expect(operation.getOneQuestionOperation().pending).toEqual(pending); fireEvent.click(screen.getByRole('button', { name: '手动重放同一原请求' })); await waitFor(() => expect(calls.filter((call) => call.method === 'POST')).toHaveLength(2)); expect(calls.filter((call) => call.method === 'POST').map((call) => call.raw)).toEqual([pending.body_json, pending.body_json]); });
test('他族blocked仍自身GET可达；精确START原键匹配解除自身门，未自动POST', async () => { const intent = await questionIntentFixture(); sessionStorage.setItem('bounded-funds-one-question-operation-v1:http://unit-question-page.local', JSON.stringify(intent)); const calls = transport(); open(true); await screen.findByRole('region', { name: '原问答恢复' }); expect(screen.getByRole('button', { name: '手动重放同一原请求' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: '原键只读核对' })); await screen.findByText(/已解除本请求门/); expect(operation.getOneQuestionOperation().pending).toBeNull(); expect(calls.every((call) => call.method === 'GET')).toBe(true); });
test('来源STALE不展示旧回答，显式refresh只送epoch/revision/key且保未知门', async () => { const calls = transport({ stale: true, lost: true }); open(); await loadSession(); expect(screen.queryByRole('button', { name: 'small · ¥100.01' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '主动重算当前来源' })); await screen.findByText(/原结果可能不明/); expect(calls.find((call) => call.method === 'POST')).toMatchObject({ path: `/api/v1/finite-planning/sessions/${questionSession}/refresh`, body: { expected_revision: 1 } }); expect(Object.keys(calls.find((call) => call.method === 'POST')!.body as object).sort()).toEqual(['expected_epoch_id', 'expected_revision', 'idempotency_key']); });
test('明确关闭checkbox后原POST，closed不能回答/刷新；原历史evaluation仍可读', async () => { const calls = transport(); open(); await loadSession(); const close = screen.getByRole('button', { name: '确认关闭问答' }); expect(close).toBeDisabled(); fireEvent.click(screen.getByLabelText(/明确关闭此问答/)); fireEvent.click(close); await screen.findByRole('heading', { name: '已明确关闭，历史规划仅作参考' }); expect(screen.getByRole('button', { name: '主动重算当前来源' })).toBeDisabled(); expect(calls.filter((call) => call.method === 'POST')).toEqual([expect.objectContaining({ path: `/api/v1/finite-planning/sessions/${questionSession}/close` })]); expect(operation.getOneQuestionOperation().pending!.kind).toBe('CLOSE'); });
test('篡改响应不能显示可回答问题；错误保留而非假success', async () => { transport({ bad: true }); open(); await loadSession().catch(() => undefined); expect(await screen.findByRole('alert')).toHaveTextContent('一次一问'); expect(screen.queryByRole('region', { name: '当前问答' })).not.toBeInTheDocument(); });
