import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { errorMessage } from '../api/http';
import { getOnboardingContext } from '../api/onboarding';
import { getQuestionSession, getOriginalQuestionResponse, lookupQuestionCommand, parseQuestionVariables, postQuestionCommand, questionUUID } from '../api/question-workflow';
import type { QuestionBody, QuestionIntent, QuestionKind, QuestionLookup, QuestionRevision } from '../api/question-workflow';
import { beginOneQuestionOperation, clearOneQuestionAfterLookup, endOneQuestionAttempt, prepareOneQuestionIntent, recoverOneQuestionOperation, useOneQuestionOperation } from '../features/one-question-operation';
import { formatMoneyCents } from '../features/money';

const labels = { PENDING_ANSWER: '只回答当前一个问题', READY_FOR_REVIEW: '规划已稳定，仍需独立行动复核', ALL_WORLDS_BLOCKED: '所有剩余世界均被阻止', UNKNOWN: '原事实或完整世界尚未知', STALE_RECOMPUTATION_REQUIRED: '当前来源已变化，请主动重算', ARCHIVED: '原周期已归档，不能继续提交', CLOSED: '已明确关闭，历史规划仅作参考' };
const initialVariables = JSON.stringify([{ variable_id: 'transfer_amount', field: 'TRANSFER_AMOUNT', choices: [{ key: 'small', value: { kind: 'money', amount_cents: 10000 } }, { key: 'large', value: { kind: 'money', amount_cents: 20000 } }], completeness: 'COMPLETE', source: 'USER_REQUEST', evidence_id: null, impact_scope: 'ORIGINAL_MVP_PLANNING_REQUEST' }], null, 2);
function Revision({ value }: { value: QuestionRevision }) {
  return <><dl className="annual-amounts"><div><dt>原会话 / revision</dt><dd><code>{value.session_id}</code> / {value.revision}</dd></div><div><dt>原动作</dt><dd><code>{value.base_action_id}</code></dd></div><div><dt>剩余声明世界 / 已计算 / 已知 / 未知</dt><dd>{value.evaluation.expected_world_count} / {value.evaluation.evaluated_world_count} / {value.evaluation.known_world_count} / {value.evaluation.unknown_or_unsupported_world_count}</dd></div><div><dt>完整声明域内是否已证明</dt><dd>{value.evaluation.complete_within_declared_domain ? '服务端报告完整' : '未证明；保留原分母'}</dd></div></dl>
    <p>{value.evaluation.explanation}</p><p>一步 minimax 只比较本轮剩余经济签名；不是整个问题树的最少问题证明。</p><p>已登记偏好：{Object.entries(value.answers).map(([field, answer]) => `${field}=${answer}`).join('；') || '无'}</p>
    {value.command_kind === 'REBASE' && <p className="notice">真实来源变化，旧答案已失效；本次原答案没有应用。</p>}
    <details><summary>逐世界原后果（{value.evaluation.worlds.length}项）</summary>{value.evaluation.worlds.map((world) => <article key={world.world_key}><p>{Object.entries(world.assignments).map(([name, choice]) => `${name}=${choice}`).join('；')} · {String(world.outcome.status)}</p><pre className="readonly-raw">{JSON.stringify(world.outcome, null, 2)}</pre></article>)}</details>
    {value.evaluation.reasons.map((reason) => <p className="notice" key={reason}>{reason}</p>)}<p className="caption">原run <code>{value.run_id}</code> · 查询/登记时点 {value.as_of} · 原command hash <code>{value.command_hash}</code></p></>;
}
export default function OneQuestionPage({ mutationBlocked = false }: { mutationBlocked?: boolean }) {
  const client = useQueryClient(); const operation = useOneQuestionOperation(); const [sessionInput, setSessionInput] = useState(''); const [sessionId, setSessionId] = useState(''); const [baseAction, setBaseAction] = useState(''); const [variablesText, setVariablesText] = useState(initialVariables); const [message, setMessage] = useState(''); const [lookup, setLookup] = useState<QuestionLookup | null>(null); const [lookupBusy, setLookupBusy] = useState(false); const [closeAccepted, setCloseAccepted] = useState(false);
  useEffect(() => { const saved = recoverOneQuestionOperation(); const id = saved.session?.session_id ?? saved.pending?.session_id; if (id) { setSessionId(id); setSessionInput(id); } }, []);
  const context = useQuery({ queryKey: ['one-question-context'], queryFn: getOnboardingContext, retry: false });
  const read = useQuery({ queryKey: ['one-question-session', sessionId], queryFn: () => getQuestionSession(sessionId), enabled: questionUUID(sessionId), retry: false, refetchOnWindowFocus: false });
  const current = !read.isError ? read.data : null; const revision = current?.current_revision; const pending = operation.pending;
  const blocked = mutationBlocked || operation.busy || !!operation.storage_error; const newBlocked = blocked || !!pending;
  async function submit(intent: QuestionIntent) {
    let began = false; setMessage(''); try { await beginOneQuestionOperation(intent, mutationBlocked); began = true; const response = await postQuestionCommand(intent); client.setQueryData(['one-question-session', response.current_revision.session_id], response); setSessionId(response.current_revision.session_id); setSessionInput(response.current_revision.session_id); setMessage('已收到原回执；仍保留原请求，请另用原键只读核对后解除提交门。'); }
    catch (error) { setMessage(`${errorMessage(error)}。原结果可能不明，不生成新键或自动重试。`); }
    finally { if (began) endOneQuestionAttempt(); }
  }
  async function start() {
    try { const binding = context.data?.binding; if (!binding) throw new Error('当前实际用户/OPEN周期未取得，不能开始'); const variables = parseQuestionVariables(JSON.parse(variablesText)); if (!questionUUID(baseAction)) throw new Error('请输入现有尚未提交银行的原准备行动UUID'); const body = { base_action_id: baseAction, variables, expected_epoch_id: binding.epoch_id, idempotency_key: `question-start-${crypto.randomUUID()}` }; const intent = await prepareOneQuestionIntent({ kind: 'START', user_id: binding.user_id, session_id: null, base_action_id: baseAction, variables, previous_run_id: null, body }); await submit(intent); } catch (error) { setMessage(errorMessage(error)); }
  }
  async function next(kind: Exclude<QuestionKind, 'START'>, choice?: string) {
    try { if (!revision) throw new Error('未读取当前原会话'); const body: QuestionBody = { expected_epoch_id: revision.epoch_id, expected_revision: revision.revision, idempotency_key: `question-${kind.toLowerCase()}-${crypto.randomUUID()}`, ...(kind === 'ANSWER' ? { question_id: current!.pending_question!.question_id, choice_key: choice! } : {}) }; const intent = await prepareOneQuestionIntent({ kind, user_id: revision.user_id, session_id: revision.session_id, base_action_id: revision.base_action_id, variables: revision.variables, previous_run_id: revision.run_id, body }); await submit(intent); } catch (error) { setMessage(errorMessage(error)); }
  }
  async function recover() {
    if (!pending) return; setLookupBusy(true); setMessage(''); try { const original = await lookupQuestionCommand(pending); setLookup(original); if (original.status === 'RECORDED') { await clearOneQuestionAfterLookup(pending, original); setSessionId(original.session_id!); setSessionInput(original.session_id!); if (sessionId === original.session_id) await read.refetch(); setMessage('完整原命令、body、hash和回执匹配；已解除本请求门。历史回执不是当前资金授权。'); } else setMessage('原键暂未找到，不是终局；继续保留原body/key，只能手动核对或同原请求重放。'); } catch (error) { setMessage(errorMessage(error)); } finally { setLookupBusy(false); }
  }
  return <div><section className="page-intro"><div><p className="eyebrow">有限偏好 · 当前一个问题</p><h2>一次一问</h2></div></section><p className="simulation-note">所有内容均为模拟规划，不是真实资金执行。回答仅筛选声明世界，不确认行动、不继承旧确认、不提交银行。</p>
    {operation.storage_error && <p role="alert">{operation.storage_error}</p>}{mutationBlocked && <p className="notice">其他原请求尚待核对，本页新写入暂不可用；自身只读恢复仍可访问。</p>}{message && <p role="status">{message}</p>}
    {pending && <section className="card" aria-label="原问答恢复"><h3>原请求待核对</h3><p>{pending.kind} · 原键 <code>{pending.body.idempotency_key}</code> · 原hash <code>{pending.request_hash}</code></p><details><summary>保留的完整原请求</summary><pre className="readonly-raw">{pending.body_json}</pre></details><button type="button" disabled={operation.busy || lookupBusy} onClick={() => void recover()}>原键只读核对</button><button type="button" disabled={blocked || lookupBusy} onClick={() => void submit(pending)}>手动重放同一原请求</button>{lookup && <><p>{lookup.status === 'RECORDED' ? '已读回匹配原件' : 'NOT_FOUND_NOT_FINAL · 原结果仍不明'}</p><details><summary>原键读取JSON</summary><pre className="readonly-raw">{getOriginalQuestionResponse(lookup)}</pre></details></>}</section>}
    <section className="card readonly-section" aria-label="读取原问答"><h3>恢复原会话</h3><label className="field">原会话UUID<input value={sessionInput} onChange={(event) => setSessionInput(event.target.value.trim())} /></label><button type="button" disabled={!questionUUID(sessionInput) || read.isFetching} onClick={() => { if (sessionId === sessionInput) void read.refetch(); else setSessionId(sessionInput); }}>读取原会话</button>{read.isFetching && <p role="status">正在读取原持久会话…</p>}{read.isError && <p role="alert">{errorMessage(read.error)}。未把旧问题视为可回答。</p>}</section>
    {current && revision && <section className="card" aria-label="当前问答"><h3>{labels[current.effective_state]}</h3><Revision value={revision} />{current.effective_state === 'PENDING_ANSWER' && current.pending_question && <fieldset disabled={newBlocked}><legend>本轮只回答：{current.pending_question.variable_id}</legend><p>最坏剩余经济签名 {current.pending_question.worst_residual_signature_count} · 影响动作 {current.pending_question.affected_action_types.join('、') || '未列出'}</p>{current.pending_question.choices.map((choice) => <button key={choice.key} type="button" onClick={() => void next('ANSWER', choice.key)}>{choice.key} · {choice.value.kind === 'money' ? `¥${formatMoneyCents(choice.value.amount_cents)}` : choice.value.kind === 'account' ? choice.value.account_id : JSON.stringify(choice.value.intent)}</button>)}</fieldset>}
      <button type="button" disabled={newBlocked || ['CLOSED', 'ARCHIVED'].includes(current.effective_state) || revision.revision >= 16} onClick={() => void next('REFRESH')}>主动重算当前来源</button><label className="field"><span><input type="checkbox" checked={closeAccepted} onChange={(event) => setCloseAccepted(event.target.checked)} /> 明确关闭此问答；不撤销或执行原资金行动</span></label><button type="button" disabled={newBlocked || !closeAccepted || ['CLOSED', 'ARCHIVED'].includes(current.effective_state)} onClick={() => void next('CLOSE')}>确认关闭问答</button>
      <details><summary>原回执与当前状态JSON</summary><pre className="readonly-raw">{getOriginalQuestionResponse(current)}</pre></details></section>}
    <section className="card" aria-label="开始有限问答"><h3>从原准备行动开始</h3><p>仅支持原五种动作的小规模偏好：1–3变量，每变量2–8个选项，完整世界最多128个。金额使用整数分。示例是可修改输入，不是实际事实或授权。</p>{context.isError && <p role="alert">{errorMessage(context.error)}</p>}<p>实际用户 <code>{context.data?.binding?.user_id ?? '未知'}</code> · 当前周期 <code>{context.data?.binding?.epoch_id ?? '未知'}</code></p><fieldset disabled={newBlocked || !context.data?.binding}><legend>明确声明候选域</legend><label className="field">原准备行动UUID<input value={baseAction} onChange={(event) => setBaseAction(event.target.value.trim())} /></label><label className="field">完整有限变量JSON<textarea rows={12} value={variablesText} onChange={(event) => setVariablesText(event.target.value)} /></label><button type="button" onClick={() => void start()}>保存原请求并开始问答</button></fieldset></section>
  </div>;
}
