import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getFullReconciliation, getOriginalReconciliationResponse } from '../api/full-reconciliation';
import type { Reconciliation, ReconciliationAmount, ReconciliationIssue } from '../api/full-reconciliation';
import { errorMessage } from '../api/http';
import { formatMoneyCents } from '../features/money';

const money = (value: number | null) => value === null ? '未知 · 未证明' : `¥${formatMoneyCents(value)}`;
const stateLabels: Record<string, string> = { MATCHED: '当前范围匹配', MANUAL_REVIEW_REQUIRED: '需要人工核对', UNKNOWN: '未证明', SERVICE_RECEIPT_VERIFIED: '原服务回执已核', BANK_SETTLED_APPLICATION_UNRESOLVED: '银行已结算，应用结果未解决', PENDING_BANK: '银行结果待核', PREPARED_NO_BANK_OBSERVED: '原行动已准备，尚无银行原件', NO_EFFECT_OBSERVED_NOT_FINAL: '当前未见效果，非终局', BANK_REJECTION_VERIFIED: '原银行拒绝已核', DIFFERENCE: '存在差额', MISSING: '独立原数缺失' };
const label = (state: string) => `${stateLabels[state] ?? state} · ${state}`;
function Issues({ rows, name }: { rows: ReconciliationIssue[]; name: string }) { return <section aria-label={name}><h4>{name} · {rows.length}项</h4>{rows.length ? <ul>{rows.map((issue, index) => <li key={index}><strong>{issue.kind} / {issue.code}</strong> · {issue.message} · 原来源 <code>{issue.source_ref}</code></li>)}</ul> : <p>本响应此清单未列出问题；仍以完整报告范围为准。</p>}</section>; }
function Amount({ value, name }: { value: ReconciliationAmount; name: string }) { return <article className="card" aria-label={name}><h4>{name}</h4><p>{label(value.state)} · 原实体 <code>{value.entity_id}</code></p><dl className="annual-amounts"><div><dt>应用账面</dt><dd>{money(value.application_cents)}</dd></div><div><dt>独立模拟银行账面</dt><dd>{money(value.bank_cents)}</dd></div><div><dt>差额（应用 − 银行）</dt><dd>{money(value.difference_cents)}</dd></div></dl><p>原银行head {value.bank_head ? `${value.bank_head.ledger_key} / sequence ${value.bank_head.sequence_number} / ${value.bank_head.occurred_at}` : '缺失，不补零'} {value.bank_head && <code>{value.bank_head.posting_id}</code>}</p></article>; }
function Action({ row }: { row: Reconciliation['actions'][number] }) { return <article className="card" aria-label={`原行动 ${row.action_id}`}><h4>{row.action_type} · {label(row.state)}</h4><p>原动作 <code>{row.action_id}</code> · 状态 {row.original_action_status}；原只读路径 <code>{row.read_original_action_path}</code></p>
  <dl className="delivery-fields"><div><dt>原幂等键</dt><dd><code>{row.original_idempotency_key}</code></dd></div><div><dt>原请求哈希</dt><dd><code>{row.original_request_hash}</code></dd></div><div><dt>原经济后果哈希</dt><dd><code>{row.effect_hash ?? '未知 · 未提供'}</code></dd></div><div><dt>预期金额 / 费用 / 损失</dt><dd>{money(row.expected_amount_cents)} / {money(row.expected_fee_cents)} / {money(row.expected_loss_cents)}</dd></div><div><dt>实际核得金额 / 费用 / 损失</dt><dd>{money(row.actual_executed_cents)} / {money(row.actual_fee_cents)} / {money(row.actual_loss_cents)}</dd></div><div><dt>完整结算腿</dt><dd>{row.complete_settlement_legs_verified ? '服务本次报告已核' : '服务本次未报告已核'}</dd></div><div><dt>原服务回执</dt><dd>{row.service_receipt_verified ? '服务本次报告已核，不是当前授权' : '未核 / 未解决'}</dd></div></dl>
  {row.state === 'BANK_SETTLED_APPLICATION_UNRESOLVED' && <p className="notice">银行可能已改变资金，原应用仍待核；不能假定现金未变、生成新键或重扣。</p>}{['PENDING_BANK', 'NO_EFFECT_OBSERVED_NOT_FINAL', 'UNKNOWN'].includes(row.state) && <p className="notice">保留原UNKNOWN和同一键；当前没看到终态不表示失败，本页不盲重试。</p>}
  <h5>原操作与回执引用</h5>{row.bank_operation_ids.length ? <ul>{row.bank_operation_ids.map((id, index) => <li key={id}>银行原操作 <code>{id}</code> · {row.bank_statuses[index]} · 原请求hash <code>{row.bank_request_hashes[index]}</code></li>)}</ul> : <p>本行动无已捕获银行操作引用，不能推定已拒绝。</p>}{row.receipt_ids.length ? <ul>{row.receipt_ids.map((id, index) => <li key={id}>原应用回执 <code>{id}</code> · {row.receipt_statuses[index]} · <a href={`#evidence/RECEIPT/${id}`}>读取回执来源关系</a></li>)}</ul> : <p>原应用回执缺失，未补造成功回执。</p>}<p>原银行腿 <code>{row.posting_ids.join('、') || '未提供'}</code>；仅核原键 query_original_key_only=true，retry_or_repair_performed=false。</p><Issues rows={row.issues} name={`行动具体问题 ${row.action_id}`} /></article>; }
function Report({ data }: { data: Reconciliation }) { const [postingPage, setPostingPage] = useState(0); const lastPostingPage = Math.max(0, Math.ceil(data.bank_postings.length / 20) - 1); const visiblePostingPage = Math.min(postingPage, lastPostingPage); const visiblePostings = data.bank_postings.slice(visiblePostingPage * 20, visiblePostingPage * 20 + 20); return <div><section className="card readonly-section" aria-label="本次对账状态"><h3>{label(data.state)}</h3><p>本次业务时点 {data.as_of} · 原owner <code>{data.user_id}</code></p><p>独立模拟银行账本 {data.bank_ledger_verified ? '服务报告已核' : '未证明'}；当前应用投影 {data.current_application_projection_matched ? '服务报告匹配' : '未匹配 / 未证明'}；待投影差异 {data.pending_application_projection_explained ? '服务报告可由原待投影解释，仍待核对' : '未报告已解释'}。</p><p>即使 MATCHED 或 SERVICE_RECEIPT_VERIFIED，本响应仍 economic_verified=false、receipt_is_current_authority=false，不提供当前资金权限或正式外部经济效果证明。</p>{data.manual_review_required && <p className="notice">人工核对是当前报告状态；没有创建人工任务、修账或再次执行。请保留原键、原状态和具体问题。</p>}<p className="caption">信用卡负债未在本现金比较中；持仓只核本金，不以未到账收益或市场估值作现金。</p></section>
  <section className="card readonly-section" aria-label="完整原行分母"><h3>完整原行分母</h3><ul>{data.inventory.map((row) => <li key={row.table}><code>{row.table}</code> · 捕获 {row.captured_count} / 实际 {row.actual_count} · {row.complete ? '本表捕获完整' : '本表未覆盖完整原分母'}</li>)}</ul><p>完整捕获不等于所有效果都已验证；未覆盖原数不从清单删除。</p></section>
  <section className="card readonly-section" aria-label="现金账核对"><h3>现金账 · 账户原余额</h3>{data.account_cash.length ? data.account_cash.map((row) => <Amount key={row.entity_id} value={row} name={`账户 ${row.entity_id}`} />) : <p>本次捕获范围无非信用卡现金比较行，不能补造余额。</p>}</section>
  <section className="card readonly-section" aria-label="持仓账核对"><h3>持仓账 · 原本金</h3>{data.position_principals.length ? data.position_principals.map((row) => <Amount key={row.entity_id} value={row} name={`持仓 ${row.entity_id}`} />) : <p>本次捕获范围无持仓比较行，不能推出未来收益。</p>}</section>
  <section className="card readonly-section" aria-label="目标归属账核对"><h3>目标归属账 · 产权与放置分开</h3>{data.goal_ownership.length ? data.goal_ownership.map((goal) => <article className="card" aria-label={`目标归属 ${goal.goal_id}`} key={goal.goal_id}><h4>目标 <code>{goal.goal_id}</code> · 原已归属 {money(goal.allocated_cents)}</h4><p>原放置账户 <code>{goal.account_id ?? '未关联账户'}</code>；当前产权原证据 {goal.current_ownership_proof_verified ? '服务报告已核' : '尚未证明'}</p><p>原产权证据 <code>{goal.ownership_evidence_id ?? '缺失'}</code> · hash <code>{goal.ownership_evidence_hash ?? '缺失'}</code>{goal.ownership_evidence_id && <> · <a href={`#evidence/EVIDENCE/${goal.ownership_evidence_id}`}>读取原产权证据关系</a></>}</p><p>原目标持仓 <code>{goal.position_ids.join('、') || '本次未列出'}</code></p><Amount value={goal.cash} name={`目标现金 ${goal.goal_id}`} /><Amount value={goal.principal} name={`目标本金 ${goal.goal_id}`} /></article>) : <p>本次捕获范围没有目标归属行，不替代目标确认。</p>}</section>
  <section className="card readonly-section" aria-label="行动预期与实际"><h3>行动预期与实际 · {data.actions.length}条原行动</h3>{data.actions.map((row) => <Action key={row.action_id} row={row} />)}{data.actions.length === 0 && <p>本次捕获无原行动；没有触发新行动。</p>}</section>
  <section className="card readonly-section" aria-label="原银行结算腿"><h3>原银行结算腿 · {data.bank_postings.length}条</h3><p>完整捕获 {data.bank_postings.length}条原腿，每页展示20条；原完整数组和核验分母保持，不把SETTLED字符串代替完整结算腿核验。</p><details><summary>逐腿原值与引用</summary><nav aria-label="原银行腿只读分页"><button type="button" disabled={visiblePostingPage === 0} onClick={() => setPostingPage(visiblePostingPage - 1)}>上一页原银行腿</button><span>第 {visiblePostingPage + 1} / {lastPostingPage + 1}页</span><button type="button" disabled={visiblePostingPage === lastPostingPage} onClick={() => setPostingPage(visiblePostingPage + 1)}>下一页原银行腿</button></nav>{visiblePostings.map((row) => <article key={row.posting_id}><h4><code>{row.posting_id}</code> · sequence {row.sequence_number}</h4><p>{row.ledger_dimension} / {row.ledger_key} / {row.leg_ref ?? '无leg_ref'} · {row.occurred_at}</p><p>原操作 <code>{row.operation_id ?? '无操作引用 / 原opening'}</code> · 原恢复请求 <code>{row.redemption_id ?? '未关联'}</code></p><p>之前 {money(row.balance_before_cents)} / 原变动 {money(row.delta_cents)} / 之后 {money(row.balance_after_cents)}；是否验真以本次完整账本状态为准。</p></article>)}</details></section>
  <section className="card readonly-section" aria-label="原审计核验"><h3>原生产审计核验</h3><p>{data.audit.status} · 链 {data.audit.chain_status} · 引用 {data.audit.reference_status} · checkpoint {data.audit.checkpoint_status}</p><p>原epoch <code>{data.audit.epoch_id ?? '未提供'}</code> · 实际 {data.audit.actual_count} / 预期 {data.audit.expected_count} · 已核至 {data.audit.verified_through_sequence}；诊断{data.audit.errors_truncated ? '有截断，未完整' : '未报告截断'}。</p><details><summary>审计完整诊断与原tail</summary><pre className="readonly-raw">{JSON.stringify(data.audit, null, 2)}</pre></details></section>
  <section className="card readonly-section" aria-label="问题与未覆盖范围"><Issues rows={data.uncovered} name="具体未证明项" /><Issues rows={data.issues} name="全部原问题" />{data.limitations.map((limit, index) => <p className="caption" key={index}>{limit}</p>)}</section><details className="card"><summary>本次对账完整原JSON响应</summary><p className="caption">保留HTTP响应文本供核对；没有独立重算审计、输入哈希或银行效果。原 input_hash <code>{data.input_hash}</code>。</p><pre className="readonly-raw">{getOriginalReconciliationResponse(data)}</pre></details></div>; }
export default function ReconciliationPage() {
  const query = useQuery({ queryKey: ['full-current-reconciliation'], queryFn: getFullReconciliation, retry: false, structuralSharing: false, refetchOnWindowFocus: false });
  return <div><section className="page-intro"><div><p className="eyebrow">独立原件 · 三账口径 · 同一原键</p><h2>对账中心</h2></div><button type="button" disabled={query.isFetching} onClick={() => void query.refetch()}>只读刷新当前对账</button></section><p className="simulation-note">模拟账本只读报告，不是真实资金执行。现金、持仓本金、目标归属分别核对；未授权修账、重试或替换原键。</p>{query.isPending && <p role="status">正在读取当前同快照对账…</p>}{query.isFetching && query.data && <p role="status">当前正在重新读取；下方是上次原报告，不能称本次已完成。</p>}{query.isError && <p role="alert">{errorMessage(query.error)}；未把上次报告当成当前成功。</p>}{!query.isError && query.data && <Report data={query.data} />}</div>;
}
