import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { compareScenario, getOriginalScenarioResponse, getScenarioContext } from '../api/scenario-simulation';
import type { ScenarioComparison, ScenarioContext, ScenarioRequest } from '../api/scenario-simulation';
import { errorMessage } from '../api/http';
import { formatMoneyCents } from '../features/money';

const money = (n: number | null) => n === null ? '未知 · 未证明' : `¥${formatMoneyCents(n)}`;
const status = (s: string) => s === 'READY' ? '边界可计算 · READY' : s === 'LIQUIDITY_RISK' ? '存在流动性风险 · LIQUIDITY_RISK' : '来源未证明 · INSUFFICIENT_EVIDENCE';
type Draft = { horizon: 90 | 365; cash: string; delta: string; reserve: string; amount: string; product: string; term: string; settlement: string };
const empty = (): Draft => ({ horizon: 90, cash: '', delta: '0', reserve: '', amount: '0', product: '', term: '0', settlement: '0' });
function inputInteger(text: string): number { if (!/^-?\d+$/.test(text) || !Number.isSafeInteger(Number(text))) throw new Error('参数须填写可精确表示的整数分或整数天'); return Number(text); }
function requestBody(base: ScenarioContext, draft: Draft): ScenarioRequest {
  const reserve = base.emergency_choices.find((p) => p.policy_id === draft.reserve);
  const product = base.product_choices.find((p) => p.product_id === draft.product);
  if (draft.reserve && !reserve || draft.product && !product) throw new Error('所选原实体已不在当前快照，请刷新后重审');
  return { expected_epoch_id: base.epoch_id, expected_source_hash: base.source_hash, expected_engine_hash: base.engine_hash, horizon_days: draft.horizon,
    cash_change: draft.cash ? { account_id: draft.cash, delta_cents: inputInteger(draft.delta) } : null,
    emergency_change: reserve ? { policy_id: reserve.policy_id, expected_version_id: reserve.version_id, amount_cents: inputInteger(draft.amount) } : null,
    product_change: product ? { product_id: product.product_id, expected_version_number: product.version_number, term_days: inputInteger(draft.term), settlement_delay_days: inputInteger(draft.settlement) } : null };
}
function Results({ result }: { result: ScenarioComparison }) {
  const [day, setDay] = useState(0); const actualDay = Math.min(day, result.horizon_days);
  const products = [...new Set([...Object.keys(result.baseline.max_allocatable_by_product), ...Object.keys(result.hypothetical.max_allocatable_by_product)])];
  return <section className="card readonly-section" aria-label="服务端反事实比较"><h3>服务端反事实比较</h3><p>本次服务端时点 {result.as_of} · {result.horizon_days}天未来窗口；不是未来现金已结算。</p><div className="policy-map-summary"><article aria-label="同次原基线"><h4>同次原基线</h4><p>{status(result.baseline.status)}</p><p>安全闲置 {money(result.baseline.safe_idle_cents)} · 最低余量 {money(result.baseline.minimum_margin_cents)}</p></article><article aria-label="假设结果"><h4>假设结果 · 非到账事实</h4><p>{status(result.hypothetical.status)}</p><p>安全闲置 {money(result.hypothetical.safe_idle_cents)} · 最低余量 {money(result.hypothetical.minimum_margin_cents)}</p></article></div><p>假设相对原基线的安全闲置变化 {money(result.delta_safe_idle_cents)}；数值变化不授予资金权限。</p>{result.delta_safe_idle_cents === 0 && <p className="caption">本次安全闲置没有变化；参数可能仅改变产品占用上限，或当前约束使结果相同，不能宣称产生收益。</p>}
    <h4>假设新配置的产品占用上限</h4>{products.length ? <ul>{products.map((id) => <li key={id}><code>{id}</code> · 原 {money(result.baseline.max_allocatable_by_product[id] ?? null)} / 假设 {money(result.hypothetical.max_allocatable_by_product[id] ?? null)}；不是实际可执行购买额。</li>)}</ul> : <p>当前原输入没有产品；未生成产品或报价。</p>}
    <h4>逐日三阶段 · 原本金返还日未改</h4><label>查看第几天 <input type="number" min="0" max={result.horizon_days} step="1" value={actualDay} onChange={(e) => { const n = Number(e.target.value); if (Number.isInteger(n) && n >= 0 && n <= result.horizon_days) setDay(n); }} /></label>{(['baseline', 'hypothetical'] as const).map((kind) => <article key={kind} aria-label={`${kind === 'baseline' ? '基线' : '假设'}第${actualDay}天三阶段`}><h5>{kind === 'baseline' ? '原基线' : '假设'}</h5>{result[kind].calculation_trace.filter((p) => p.day === actualDay).map((p) => <p key={p.phase}>{p.date} · {p.phase} · 现金 {money(p.cash_cents)} / 余量 {money(p.margin_cents)} · 原本金返还持仓 {p.principal_position_ids.join('、') || '本阶段无已核原返还'}</p>)}{result[kind].calculation_trace.length === 0 && <p>原来源未证明，三阶段金额未知；没有补零曲线。</p>}</article>)}
    <details><summary>全部真实阻断与假设参数原文</summary><pre className="readonly-raw">{JSON.stringify({ baseline: result.baseline.blocking_constraints, hypothetical: result.hypothetical.blocking_constraints, changed_parameters: result.changed_parameters }, null, 2)}</pre></details><details><summary>本次完整原HTTP响应</summary><p>保留原JSON与原request/hash，客户端未独立核银行或原审计链。</p><pre className="readonly-raw">{getOriginalScenarioResponse(result)}</pre></details>
  </section>;
}
export default function ScenarioSimulationPage() {
  const query = useQuery({ queryKey: ['scenario-simulation-context'], queryFn: getScenarioContext, retry: false, structuralSharing: false, refetchOnWindowFocus: false });
  const [draft, setDraft] = useState<Draft>(empty); const [result, setResult] = useState<ScenarioComparison | null>(null); const [lastRequest, setLastRequest] = useState<ScenarioRequest | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const update = (patch: Partial<Draft>) => { setDraft((old) => ({ ...old, ...patch })); setResult(null); setError(null); };
  const calculate = async (replay = false) => { if (!query.data || busy || query.isFetching || query.isError) return; setBusy(true); setError(null); setResult(null); try { const body = replay ? lastRequest : requestBody(query.data, draft); if (!body) throw new Error('没有同原参数可重放'); setLastRequest(structuredClone(body)); setResult(await compareScenario(query.data, body)); } catch (e) { setError(`${errorMessage(e)}；未改正式事实或生成成功结果。`); } finally { setBusy(false); } };
  const refresh = async () => { setResult(null); setError(null); setDraft(empty()); await query.refetch(); };
  const base = query.data; const replayCurrent = !!base && !!lastRequest && lastRequest.expected_epoch_id === base.epoch_id && lastRequest.expected_source_hash === base.source_hash && lastRequest.expected_engine_hash === base.engine_hash;
  return <div><section className="page-intro"><div><p className="eyebrow">原件绑定 · 假设参数 · 确定性边界</p><h2>场景模拟器</h2></div><button type="button" disabled={busy || query.isFetching} onClick={() => void refresh()}>只读刷新原快照</button></section><p className="simulation-note">这是假设比较，不是真实资金执行。服务端复算结果；没有到账、策略确认、产品改版、报价或银行授权。现有演示控台与正式模拟历史独立保留。</p>{query.isPending && <p role="status">正在读取当前原件及服务端边界…</p>}{query.isError && <p role="alert">{errorMessage(query.error)}；没有用旧快照冒充本次读取。</p>}{busy && <p role="status">服务端正在只读复算，同一请求内读取当前原件…</p>}{error && <p role="alert">{error}</p>}
    {base && !query.isError && <><section className="card readonly-section" aria-label="当前原件绑定"><h3>当前原件与明确范围</h3><p>原epoch <code>{base.epoch_id}</code> · 时点 {base.as_of} · 原审计报告 {base.audit.status} / {base.audit.complete ? '当前范围完整' : '不完整，金额未知'}</p><p>原事实 fingerprint <code>{base.source_hash}</code>；引擎源摘要 <code>{base.engine_hash}</code>（{Object.keys(base.engine_files).length}项源文件，服务端报告；非客户端银行验真）。</p><p>90天原安全闲置 {money(base.baseline_90.safe_idle_cents)} / 365天 {money(base.baseline_365.safe_idle_cents)}；未接未来收入和完整FULL保护。</p>{base.source_issues.map((issue, n) => <p className="notice" key={n}>{issue.code} · {issue.source_ref} · {issue.message}</p>)}</section>
    <form className="card" aria-label="有界假设参数" onSubmit={(e) => { e.preventDefault(); void calculate(); }}><fieldset disabled={busy || query.isFetching}><legend>只选择假设参数；所有金额按整数分</legend><label>只读比较窗口 <select value={draft.horizon} onChange={(e) => update({ horizon: Number(e.target.value) as 90 | 365 })}><option value="90">90天原边界</option><option value="365">365天原边界</option></select></label>
      <fieldset><legend>事实参数 · 普通现金余额</legend><label>原普通现金账户 <select value={draft.cash} onChange={(e) => update({ cash: e.target.value })}><option value="">不改变现金事实</option>{base.cash_choices.map((a) => <option value={a.account_id} key={a.account_id}>{a.account_id} · 原 {money(a.balance_cents)}</option>)}</select></label>{base.cash_choices.length === 0 && <p>BLOCKED：没有有原银行证据且未关联目标归属的普通CASH账户；不改目标或信用卡余额。</p>}<label>假设现金增减（整数分，±10000000） <input inputMode="numeric" value={draft.delta} disabled={!draft.cash} onChange={(e) => update({ delta: e.target.value })} /></label><p className="caption">正数是假设余额，绝不是工资到账或BANK_CONFIRMED；假设余额不得负。</p></fieldset>
      <fieldset><legend>策略参数 · 原应急缓冲</legend><label>原应急策略版本 <select value={draft.reserve} onChange={(e) => { const p = base.emergency_choices.find((p) => p.policy_id === e.target.value); update({ reserve: e.target.value, amount: String(p?.amount_cents ?? 0) }); }}><option value="">不改变策略</option>{base.emergency_choices.map((p) => <option key={p.policy_id} value={p.policy_id}>{p.policy_id} · 版本{p.version_id} · 原 {money(p.amount_cents)}</option>)}</select></label>{base.emergency_choices.length === 0 && <p>BLOCKED：没有当前原边界载入且有原确认证据的应急缓冲版本；不补造确认。</p>}<label>假设应急金额（整数分，0—10000000） <input inputMode="numeric" value={draft.amount} disabled={!draft.reserve} onChange={(e) => update({ amount: e.target.value })} /></label><p className="caption">仅假设改金额，不创建或确认策略，不修改原生命周期。</p></fieldset>
      <fieldset><legend>产品参数 · 假设新配置占用期</legend><label>原固定本金返还产品 <select value={draft.product} onChange={(e) => { const p = base.product_choices.find((p) => p.product_id === e.target.value); update({ product: e.target.value, term: String(p?.term_days ?? 0), settlement: String(p?.settlement_delay_days ?? 0) }); }}><option value="">不改变产品参数</option>{base.product_choices.map((p) => <option key={p.product_id} value={p.product_id}>{p.product_id} · 原v{p.version_number} · {p.term_days}+{p.settlement_delay_days}天</option>)}</select></label>{base.product_choices.length === 0 && <p>BLOCKED：没有当前原固定本金返还条款产品；不能假造本金保证或期限。</p>}<label>假设期限天数（0—365） <input inputMode="numeric" value={draft.term} disabled={!draft.product} onChange={(e) => update({ term: e.target.value })} /></label><label>假设结算延迟天数（0—365） <input inputMode="numeric" value={draft.settlement} disabled={!draft.product} onChange={(e) => update({ settlement: e.target.value })} /></label><p className="caption">两项合计≤365天；原锁定/风险/最低购买额不改，原持仓本金返还日也不改。仅复算假设新资金占用上限；当前约束相同时上限可能不变。</p></fieldset>
      <div className="button-row"><button type="submit">服务端只读比较</button><button type="button" onClick={() => { setDraft(empty()); setResult(null); setError(null); }}>重置本页参数</button><button type="button" disabled={!replayCurrent} onClick={() => void calculate(true)}>同原参数显式重放</button></div><p className="caption">重置只清本页，不reset正式数据。重放会重新读取当前原件；epoch、事实或引擎变化时须刷新重审，不自动重试。</p>
    </fieldset></form>{result && <Results key={result.scenario_hash} result={result} />}{base.limitations.map((text, index) => <p className="caption" key={index}>{text}</p>)}<details className="card"><summary>当前快照完整原HTTP响应</summary><pre className="readonly-raw">{getOriginalScenarioResponse(base)}</pre></details></>}
  </div>;
}
