import { webcrypto } from 'node:crypto';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { beforeEach, expect, test, vi } from 'vitest';
import ScenarioRiskReviewPage from './ScenarioRiskReviewPage';
import type { RiskRequest } from '../api/scenario-risk-review';
import { riskAssetPolicy, riskBill, riskBillBody, riskComparisonFixture, riskContextFixture, riskFullPolicy, riskGoal, riskProduct, riskProductBody } from '../tests/scenario-risk-review-fixture';
import { installHttpFixture } from '../tests/policy-fixture';
beforeEach(() => vi.stubGlobal('crypto', webcrypto));
function open(blocked = false) { render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } })}><ScenarioRiskReviewPage mutationBlocked={blocked} /></QueryClientProvider>); }
test('初始只读GET，四种原分项实际分母、无执行/确认/reset', async () => { const calls = installHttpFixture(() => riskContextFixture()); open(); await screen.findByRole('heading', { name: '当前原件与实际分母' }); expect(screen.getByText(/原账单 1.*原目标 1/)).toBeVisible(); expect(screen.getByText(/未来收入对今日现金与执行贡献始终0/)).toBeVisible(); expect(screen.getByRole('button', { name: '服务端分项只读比较' })).toBeDisabled(); expect(calls).toEqual([{ method: 'GET', path: '/api/v1/scenario-risk-review/context', body: undefined }]); });
test('账单原剩余与假设分开，主动POST整数原body；编辑隐结果、清页不reset', async () => { const value = await riskComparisonFixture(); const calls = installHttpFixture((method) => method === 'GET' ? riskContextFixture() : value); open(); await screen.findByRole('heading', { name: '当前原件与实际分母' }); fireEvent.change(screen.getByLabelText('当前实际原对象'), { target: { value: riskBill } }); expect(screen.getByLabelText(/假设剩余应付/)).toHaveValue('400'); fireEvent.change(screen.getByLabelText(/假设剩余应付/), { target: { value: '300' } }); fireEvent.click(screen.getByRole('button', { name: '服务端分项只读比较' })); await screen.findByRole('heading', { name: /分项服务端结果/ }); expect(screen.getByText(/安全闲置差额 ¥1.00/)).toBeVisible(); expect(screen.getByText(/假设剩余0绝不表示已付款/)).toBeVisible(); expect(calls[1]!.body).toEqual(riskBillBody()); fireEvent.change(screen.getByLabelText(/假设剩余应付/), { target: { value: '0' } }); expect(screen.queryByRole('heading', { name: /分项服务端结果/ })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '仅清本页假设' })); expect(screen.getByLabelText('当前实际原对象')).toHaveValue(''); expect(calls).toHaveLength(2); });
test('原产品优化器与未消费字段可读，无报价/银行动作', async () => { const body = riskProductBody(); const value = await riskComparisonFixture(body); const calls = installHttpFixture((method) => method === 'GET' ? riskContextFixture() : value); open(); await screen.findByRole('heading', { name: '当前原件与实际分母' }); fireEvent.change(screen.getByLabelText('假设分项'), { target: { value: 'PRODUCT' } }); fireEvent.change(screen.getByLabelText('当前实际原对象'), { target: { value: riskProduct } }); fireEvent.change(screen.getByLabelText('当前原资产规划策略'), { target: { value: riskAssetPolicy } }); fireEvent.change(screen.getByLabelText(/假设提前损失/), { target: { value: '3333' } }); fireEvent.click(screen.getByRole('button', { name: '服务端分项只读比较' })); await screen.findByRole('heading', { name: /分项服务端结果/ }); const section = screen.getByRole('article', { name: '产品原优化器敏感性' }); expect(within(section).getByText(/实际费用 未知 · 未证明.*实际损失 未知 · 未证明/)).toBeVisible(); expect(within(section).getByText(/early_loss 未被优化器消费/)).toBeVisible(); expect(calls).toHaveLength(2); expect(calls[1]!.body).toEqual(body); });
test('完整策略UNKNOWN/null显示实际缺口，不自动确认策略', async () => { const context = riskContextFixture(); const source = context.full_policies[0]!; const body: RiskRequest = { ...riskBillBody(), hypothesis: { kind: 'FULL_POLICY', policy_id: source.policy_id, expected_version_id: source.version_id, configuration: source.configuration } }; const result = await riskComparisonFixture(body, context); const calls = installHttpFixture((method) => method === 'GET' ? context : result); open(); await screen.findByRole('heading', { name: '当前原件与实际分母' }); fireEvent.change(screen.getByLabelText('假设分项'), { target: { value: 'FULL_POLICY' } }); fireEvent.change(screen.getByLabelText('当前实际原对象'), { target: { value: riskFullPolicy } }); fireEvent.click(screen.getByRole('button', { name: '服务端分项只读比较' })); await screen.findByRole('heading', { name: /分项服务端结果/ }); expect(within(screen.getByRole('article', { name: '完整策略金融差量' })).getByText(/UNKNOWN · 原365天安全闲置/)).toBeVisible(); expect(screen.getByText(/未来目标分配 UNKNOWN/)).toBeVisible(); expect(calls).toHaveLength(2); });
test('目标输入必须有序、整数；未合法输入不发POST', async () => { const calls = installHttpFixture(() => riskContextFixture()); open(); await screen.findByRole('heading', { name: '当前原件与实际分母' }); fireEvent.change(screen.getByLabelText('假设分项'), { target: { value: 'GOAL' } }); fireEvent.change(screen.getByLabelText('当前实际原对象'), { target: { value: riskGoal } }); fireEvent.change(screen.getByLabelText(/假设月度最低/), { target: { value: '1000' } }); fireEvent.click(screen.getByRole('button', { name: '服务端分项只读比较' })); expect(await screen.findByRole('alert')).toHaveTextContent('正式事实未改'); expect(calls).toHaveLength(1); });
test('中断无自动重试，只可用户显式同body；源刷新后旧请求不可重绑', async () => { const value = await riskComparisonFixture(); let writes = 0; let reads = 0; const calls = installHttpFixture((method) => { if (method === 'GET') { const context = riskContextFixture(); if (++reads > 1) context.source_hash = 'f'.repeat(64); return context; } return ++writes === 1 ? new Response(JSON.stringify({ error: { code: 'STALE_SCENARIO_RISK_SOURCE', message: '原件已变', request_id: 'SYNTHETIC' } }), { status: 409 }) : value; }); open(); await screen.findByRole('heading', { name: '当前原件与实际分母' }); fireEvent.change(screen.getByLabelText('当前实际原对象'), { target: { value: riskBill } }); fireEvent.change(screen.getByLabelText(/假设剩余应付/), { target: { value: '300' } }); fireEvent.click(screen.getByRole('button', { name: '服务端分项只读比较' })); await screen.findByRole('alert'); expect(calls).toHaveLength(2); expect(screen.queryByRole('heading', { name: /分项服务端结果/ })).not.toBeInTheDocument(); fireEvent.change(screen.getByLabelText(/假设剩余应付/), { target: { value: '301' } }); fireEvent.click(screen.getByRole('button', { name: '同原请求显式重放' })); await screen.findByRole('heading', { name: /分项服务端结果/ }); expect(calls[2]!.body).toEqual(calls[1]!.body); fireEvent.click(screen.getByRole('button', { name: '只读刷新原对象' })); await screen.findByText('f'.repeat(64), { selector: 'code' }); expect(screen.getByRole('button', { name: '同原请求显式重放' })).toBeDisabled(); expect(writes).toBe(2); });
test('跨族门只阻POST，自己的原GET仍可刷新', async () => { const calls = installHttpFixture(() => riskContextFixture()); open(true); await screen.findByRole('heading', { name: '当前原件与实际分母' }); expect(screen.getByRole('button', { name: '服务端分项只读比较' })).toBeDisabled(); expect(screen.getByRole('button', { name: '只读刷新原对象' })).toBeEnabled(); fireEvent.click(screen.getByRole('button', { name: '只读刷新原对象' })); await vi.waitFor(() => expect(calls).toHaveLength(2)); expect(calls.every((call) => call.method === 'GET')).toBe(true); });
