import { webcrypto } from 'node:crypto';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { beforeEach, expect, test, vi } from 'vitest';
import ScenarioSimulationPage from './ScenarioSimulationPage';
import type { ScenarioRequest } from '../api/scenario-simulation';
import { scenarioComparisonFixture, scenarioContextFixture, simAccount, simPolicy, simProduct } from '../tests/scenario-simulation-fixture';
import { installHttpFixture } from '../tests/policy-fixture';
beforeEach(() => vi.stubGlobal('crypto', webcrypto));
function open() { render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } })}><ScenarioSimulationPage /></QueryClientProvider>); }
test('初始只读GET显示原范围，未主动发compare/事件/reset/金融写', async () => { const calls = installHttpFixture(() => scenarioContextFixture()); open(); await screen.findByRole('heading', { name: '当前原件与明确范围' }); expect(screen.getByText(/90天原安全闲置 ¥500.02/)).toBeVisible(); expect(screen.getByText(/不是工资到账或BANK_CONFIRMED/)).toBeVisible(); expect(calls).toEqual([{ method: 'GET', path: '/api/v1/scenario-simulation/context', body: undefined }]); expect(screen.getByRole('button', { name: '同原参数显式重放' })).toBeDisabled(); });
test('三参数主动POST原body，由server响应展示；编辑后隐旧结果，本页reset无服务写', async () => { const calls = installHttpFixture((method, _path, body) => method === 'GET' ? scenarioContextFixture() : scenarioComparisonFixture(body as ScenarioRequest)); open(); await screen.findByRole('heading', { name: '当前原件与明确范围' }); fireEvent.change(screen.getByLabelText('原普通现金账户'), { target: { value: simAccount } }); fireEvent.change(screen.getByLabelText(/假设现金增减/), { target: { value: '10001' } }); fireEvent.change(screen.getByLabelText('原应急策略版本'), { target: { value: simPolicy } }); fireEvent.change(screen.getByLabelText(/假设应急金额/), { target: { value: '30001' } }); fireEvent.change(screen.getByLabelText('原固定本金返还产品'), { target: { value: simProduct } }); fireEvent.change(screen.getByLabelText(/假设期限天数/), { target: { value: '3' } }); fireEvent.click(screen.getByRole('button', { name: '服务端只读比较' })); await screen.findByRole('heading', { name: '服务端反事实比较' }); expect(within(screen.getByRole('article', { name: '假设结果' })).getByText(/安全闲置 ¥500.02/)).toBeVisible(); expect(calls[1]!.body).toMatchObject({ cash_change: { account_id: simAccount, delta_cents: 10001 }, emergency_change: { policy_id: simPolicy, amount_cents: 30001 }, product_change: { product_id: simProduct, term_days: 3, settlement_delay_days: 1 }, horizon_days: 90 }); fireEvent.change(screen.getByLabelText(/假设现金增减/), { target: { value: '20001' } }); expect(screen.queryByRole('heading', { name: '服务端反事实比较' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '重置本页参数' })); expect(screen.getByLabelText('原普通现金账户')).toHaveValue(''); expect(calls).toHaveLength(2); });
test('响应中断只手动同原参数重放，无自动重试或client成功结果', async () => { let writes = 0; const calls = installHttpFixture((method, _path, body) => method === 'GET' ? scenarioContextFixture() : ++writes === 1 ? new Response(JSON.stringify({ error: { code: 'FAILED', message: '原只读计算失败', request_id: 'synthetic' } }), { status: 409 }) : scenarioComparisonFixture(body as ScenarioRequest)); open(); await screen.findByRole('heading', { name: '当前原件与明确范围' }); fireEvent.change(screen.getByLabelText('原普通现金账户'), { target: { value: simAccount } }); fireEvent.change(screen.getByLabelText(/假设现金增减/), { target: { value: '10001' } }); fireEvent.click(screen.getByRole('button', { name: '服务端只读比较' })); expect(await screen.findByRole('alert')).toHaveTextContent('未改正式事实或生成成功结果'); expect(calls).toHaveLength(2); expect(screen.queryByRole('heading', { name: '服务端反事实比较' })).not.toBeInTheDocument(); fireEvent.change(screen.getByLabelText(/假设现金增减/), { target: { value: '20001' } }); fireEvent.click(screen.getByRole('button', { name: '同原参数显式重放' })); await screen.findByRole('heading', { name: '服务端反事实比较' }); expect(calls[2]!.body).toEqual(calls[1]!.body); expect(writes).toBe(2); });
test('未知原证据保null；365查看366日期三阶段，未补零或到账', async () => { const calls = installHttpFixture((method, _path, body) => method === 'GET' ? scenarioContextFixture(true) : scenarioComparisonFixture(body as ScenarioRequest, true)); open(); await screen.findByRole('heading', { name: '当前原件与明确范围' }); expect(screen.getByText(/90天原安全闲置 未知 · 未证明/)).toBeVisible(); fireEvent.change(screen.getByLabelText('只读比较窗口'), { target: { value: '365' } }); fireEvent.click(screen.getByRole('button', { name: '服务端只读比较' })); await screen.findByRole('heading', { name: '服务端反事实比较' }); expect(within(screen.getByRole('article', { name: '假设结果' })).getByText(/来源未证明/)).toBeVisible(); expect(screen.getAllByText('原来源未证明，三阶段金额未知；没有补零曲线。')).toHaveLength(2); expect((calls[1]!.body as ScenarioRequest).horizon_days).toBe(365); });
test('缺原实体分支明确BLOCKED；参数越界拒绝POST，刷新变epoch不重绑旧重放', async () => { let reads = 0; const calls = installHttpFixture(() => { const base = scenarioContextFixture(); if (++reads > 1) { base.epoch_id = simAccount; base.audit.epoch_id = simAccount; } return base; }); open(); await screen.findByRole('heading', { name: '当前原件与明确范围' }); fireEvent.change(screen.getByLabelText('原普通现金账户'), { target: { value: simAccount } }); fireEvent.change(screen.getByLabelText(/假设现金增减/), { target: { value: '10000001' } }); fireEvent.click(screen.getByRole('button', { name: '服务端只读比较' })); await screen.findByRole('alert'); expect(calls).toHaveLength(1); fireEvent.click(screen.getByRole('button', { name: '只读刷新原快照' })); await screen.findByText(simAccount, { selector: 'code' }); expect(screen.getByRole('button', { name: '同原参数显式重放' })).toBeDisabled(); expect(calls).toHaveLength(2); });
test('三种原实体都缺失时可读明确BLOCKED，不能自动创建声明或产品', async () => { const base = scenarioContextFixture(); base.cash_choices = []; base.emergency_choices = []; base.product_choices = []; const calls = installHttpFixture(() => base); open(); await screen.findByRole('heading', { name: '当前原件与明确范围' }); expect(screen.getAllByText(/BLOCKED：/)).toHaveLength(3); expect(calls).toHaveLength(1); });
