import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { compareRisk, getOriginalRiskResponse, getRiskContext, parseRiskRequest } from '../api/scenario-risk-review';
import type { RiskComparison, RiskContext, RiskCurve, RiskFamily, RiskRequest } from '../api/scenario-risk-review';
import { errorMessage } from '../api/http';
import { formatMoneyCents } from '../features/money';
import { object } from '../features/policy-form';

const money = (value: number | null | undefined) => value == null ? '未知 · 未证明' : `¥${formatMoneyCents(value)}`;
type Draft = { family: RiskFamily; id: string; asset: string; values: Record<string, string>; configuration: string };
const empty = (): Draft => ({ family: 'BILL', id: '', asset: '', values: {}, configuration: '' });
const names: Record<RiskFamily, string> = { BILL: '账单剩余与到期', GOAL: '目标月度与期限', FULL_POLICY: '完整策略候选', PRODUCT: '产品风险与流动性' };
function number(text: string | undefined): number { if (!text || !/^-?\d+$/.test(text) || !Number.isSafeInteger(Number(text))) throw new Error('假设必须是精确整数分、天或bps'); return Number(text); }
function select(base: RiskContext, draft: Draft, id: string): Draft {
  if (draft.family === 'BILL') { const row = base.bills.find((row) => row.bill_id === id); return { ...draft, id, values: row ? { remaining_due_cents: String(Math.max(0, row.total_cents - row.paid_cents)), due_offset_days: '0' } : {} }; }
  if (draft.family === 'GOAL') { const row = base.goals.find((row) => row.goal_id === id); const contribution = row?.source_version.configuration.monthly_contribution; return { ...draft, id, values: object(contribution) ? { monthly_min_cents: String(contribution.min_cents), monthly_target_cents: String(contribution.target_cents), monthly_max_cents: String(contribution.max_cents), deadline_offset_days: '0' } : {} }; }
  if (draft.family === 'FULL_POLICY') { const row = base.full_policies.find((row) => row.policy_id === id); return { ...draft, id, configuration: row ? JSON.stringify(row.configuration, null, 2) : '' }; }
  const row = base.products.find((row) => row.product_id === id); return { ...draft, id, values: row ? Object.fromEntries(['risk_level', 'lock_days', 'redemption_delay_days', 'minimum_purchase_cents', 'early_withdrawal_loss_bps'].map((key) => [key, String(row[key as keyof typeof row])])) : {} };
}
function body(base: RiskContext, draft: Draft): RiskRequest {
  let hypothesis: RiskRequest['hypothesis']; const v = draft.values;
  if (draft.family === 'BILL') hypothesis = { kind: 'BILL', bill_id: draft.id, remaining_due_cents: number(v.remaining_due_cents), due_offset_days: number(v.due_offset_days) };
  else if (draft.family === 'GOAL') { const source = base.goals.find((row) => row.goal_id === draft.id); if (!source) throw new Error('缺当前目标版本，请刷新后选择'); hypothesis = { kind: 'GOAL', goal_id: draft.id, expected_version_id: source.source_version.version_id, monthly_min_cents: number(v.monthly_min_cents), monthly_target_cents: number(v.monthly_target_cents), monthly_max_cents: number(v.monthly_max_cents), deadline_offset_days: number(v.deadline_offset_days) }; }
  else if (draft.family === 'FULL_POLICY') { const source = base.full_policies.find((row) => row.policy_id === draft.id); if (!source) throw new Error('缺当前完整策略版本'); hypothesis = { kind: 'FULL_POLICY', policy_id: draft.id, expected_version_id: source.version_id, configuration: JSON.parse(draft.configuration) as Record<string, unknown> }; }
  else { const source = base.products.find((row) => row.product_id === draft.id); const asset = base.full_policies.find((row) => row.policy_id === draft.asset && row.template_name === 'AssetAuthorizationPolicy'); if (!source || !asset) throw new Error('缺原不可变产品或已登记资产规划版本'); hypothesis = { kind: 'PRODUCT', product_id: draft.id, expected_version_number: source.version_number, asset_policy_id: asset.policy_id, expected_policy_version_id: asset.version_id, risk_level: number(v.risk_level), lock_days: number(v.lock_days), redemption_delay_days: number(v.redemption_delay_days), minimum_purchase_cents: number(v.minimum_purchase_cents), early_withdrawal_loss_bps: number(v.early_withdrawal_loss_bps) }; }
  return parseRiskRequest({ expected_epoch_id: base.epoch_id, expected_source_hash: base.source_hash, expected_engine_hash: base.engine_hash, hypothesis });
}
function Curve({ value, title, day }: { value: RiskCurve | null; title: string; day: number }) {
  return <article aria-label={title}><h4>{title}</h4>{value === null ? <p>UNKNOWN · 无已证明曲线，没有补零。</p> : <><p>{value.status} · 安全闲置 {money(value.safe_idle_cents)} · 最低余量 {money(value.minimum_margin_cents)}</p>{value.calculation_trace.filter((point) => point.day === day).map((point) => <p key={point.phase}>{point.date} · {point.phase} · 条件现金 {money(point.cash_cents)} / 余量 {money(point.margin_cents)}</p>)}<p className="caption">1098个原阶段点；不是未来逐账户借记证明，也不是资金授权。</p></>}</article>;
}
function Results({ result }: { result: RiskComparison }) {
  const [day, setDay] = useState(0); const p = result.product_preview; const full = result.full_policy_preview?.financial_impact;
  return <section className="card readonly-section" aria-label="分项服务端结果"><h3>分项服务端结果 · {names[result.family]}</h3><p>{result.status} · 服务端时点 {result.as_of}；当前银行事实、策略和持仓没有写入。</p><p>安全闲置差额 {money(result.delta_safe_idle_cents)}；这是条件比较，不能购买或回拨。</p>{result.reasons.map((reason) => <p className="notice" key={reason}>{reason}</p>)}
    {(result.family === 'BILL' || result.family === 'GOAL') && <><label>查看假设第几天（0—365） <input type="number" min="0" max="365" step="1" value={day} onChange={(event) => { const value = Number(event.target.value); if (Number.isInteger(value) && value >= 0 && value <= 365) setDay(value); }} /></label><div className="policy-map-summary"><Curve value={result.baseline_full} title="同次完整保护原基线" day={day} /><Curve value={result.hypothetical_full} title="保留完整保护的假设曲线" day={day} /></div></>}
    {full && <article aria-label="完整策略金融差量"><h4>原完整策略金融消费者</h4><p>{full.status} · 原365天安全闲置 {money(full.before?.safe_idle_cents)} / 候选 {money(full.after?.safe_idle_cents)} · 最低余量差 {money(full.delta_minimum_margin_cents)}</p><p>今天与逾期原义务保留；仅原消费者支持的未来义务变化可以计算。</p><p>当前目标与本金差0只表示没有写原产权；未来目标分配 UNKNOWN。</p>{(full.reasons ?? []).map((reason) => <p key={reason}>{reason}</p>)}</article>}
    {p && <article aria-label="产品原优化器敏感性"><h4>原产品优化器 · 无银行授权</h4><p>原 {p.before.status} / 假设 {p.after.status} · 原总配置 {money(p.before.total_purchase_cents)} / 假设 {money(p.after.total_purchase_cents)}</p><p>所选产品条件本金：原 {money(p.original_selected_principal_cents)} / 假设 {money(p.hypothetical_selected_principal_cents)}</p><p>提前损失假设上界：原 {money(p.original_early_loss_upper_bound_cents)} / 假设 {money(p.hypothetical_early_loss_upper_bound_cents)}；本金×声明bps向上取整。</p><p>实际费用 {money(p.actual_fee_cents)} · 实际损失 {money(p.actual_loss_cents)}。不是当前赎回报价。</p><p className="notice">early_loss 未被优化器消费；完整 FULL 保护未被产品优化器消费。原持仓不变，不承诺收益或实际可买。</p>{(['before', 'after'] as const).map((kind) => <div key={kind}><h5>{kind === 'before' ? '原参数' : '假设参数'}适配与批次</h5>{p[kind].candidates?.map((candidate) => <p key={candidate.product_id}>{candidate.product_code} · {candidate.status} · 上限 {money(candidate.maximum_batch_cents)} · {candidate.reasons.join(' / ') || '原消费者无拒绝原因'}</p>)}{p[kind].batches?.map((batch) => <p key={batch.product_id}>{batch.product_code} · 条件配置 {money(batch.amount_cents)} · 假设可用 {batch.principal_available_at} · 模拟公式收益 {money(batch.net_simulated_yield_cents)}（不是实测收益）</p>)}</div>)}</article>}
    <details><summary>原对象与假设对象分别复核</summary><h4>原对象 · 历史未改</h4><pre className="readonly-raw">{JSON.stringify(result.original_selected, null, 2)}</pre><h4>假设对象 · HYPOTHETICAL</h4><pre className="readonly-raw">{JSON.stringify(result.hypothetical_selected, null, 2)}</pre></details><details><summary>本次完整原 HTTP 响应与请求摘要</summary><p>客户端核有限合同与金额一致性；未独立验银行经济结果。新比较摘要 {result.comparison_hash}。</p><pre className="readonly-raw">{getOriginalRiskResponse(result)}</pre></details>{result.limitations.map((text, index) => <p className="caption" key={index}>{text}</p>)}
  </section>;
}
export default function ScenarioRiskReviewPage({ mutationBlocked = false }: { mutationBlocked?: boolean }) {
  const query = useQuery({ queryKey: ['scenario-risk-review'], queryFn: getRiskContext, retry: false, structuralSharing: false, refetchOnWindowFocus: false });
  const [draft, setDraft] = useState<Draft>(empty); const [result, setResult] = useState<RiskComparison | null>(null); const [lastBody, setLastBody] = useState<RiskRequest | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const update = (value: Partial<Draft>) => { setDraft((old) => ({ ...old, ...value })); setResult(null); setError(null); };
  const calculate = async (replay = false) => { if (!query.data || query.isError || query.isFetching || busy || mutationBlocked) return; setBusy(true); setResult(null); setError(null); try { const request = replay ? lastBody : body(query.data, draft); if (!request) throw new Error('没有可重放的原参数'); setLastBody(structuredClone(request)); setResult(await compareRisk(query.data, request)); } catch (error) { setError(`${errorMessage(error)}；没有生成客户端结果，正式事实未改。`); } finally { setBusy(false); } };
  const refresh = async () => { setResult(null); setError(null); setDraft(empty()); await query.refetch(); };
  const base = query.data; const replay = !!base && !!lastBody && lastBody.expected_epoch_id === base.epoch_id && lastBody.expected_source_hash === base.source_hash && lastBody.expected_engine_hash === base.engine_hash;
  const controls: [string, string][] = draft.family === 'BILL' ? [['remaining_due_cents', '假设剩余应付（分，0—10000000）'], ['due_offset_days', '相对原到期日偏移（天，±365）']] : draft.family === 'GOAL' ? [['monthly_min_cents', '假设月度最低（分）'], ['monthly_target_cents', '假设月度目标（分）'], ['monthly_max_cents', '假设月度最高（分）'], ['deadline_offset_days', '相对原目标期限偏移（天，±365）']] : draft.family === 'PRODUCT' ? [['risk_level', '假设产品风险（0—5）'], ['lock_days', '假设锁期（天，0—365）'], ['redemption_delay_days', '假设赎回延迟（天，0—365）'], ['minimum_purchase_cents', '假设最低购买额（分，0—10000000）'], ['early_withdrawal_loss_bps', '假设提前损失（bps，0—10000）']] : [];
  const choices = base ? draft.family === 'BILL' ? base.bills.map((row) => ({ id: row.bill_id, label: `${row.bill_id} · 原剩余 ${money(Math.max(0, row.total_cents - row.paid_cents))} · ${row.due_date}` })) : draft.family === 'GOAL' ? base.goals.map((row) => ({ id: row.goal_id, label: `${row.goal_id} · 原版本 ${row.source_version.version_id}` })) : draft.family === 'FULL_POLICY' ? base.full_policies.map((row) => ({ id: row.policy_id, label: `${row.template_name} · ${row.policy_id} · ${row.effective_status}` })) : base.products.map((row) => ({ id: row.product_id, label: `${row.product_code} · 原v${row.version_number} · ${row.asset_class}` })) : [];
  return <div><section className="page-intro"><div><p className="eyebrow">事实与假设分开 · 原服务端计算</p><h2>分项反事实评估</h2></div><button type="button" disabled={busy || query.isFetching} onClick={() => void refresh()}>只读刷新原对象</button></section><p className="simulation-note">这是零写入假设比较，不是真实资金执行。未来收入对今日现金与执行贡献始终0；不产生确认、BANK 回执或授权。</p>{query.isPending && <p role="status">正在读取当前原对象…</p>}{query.isError && <p role="alert">{errorMessage(query.error)}；当前来源未证明，没有使用旧结果。</p>}{error && <p role="alert">{error}</p>}{busy && <p role="status">服务端只读复算中…</p>}
    {base && !query.isError && <><section className="card readonly-section" aria-label="分项原件范围"><h3>当前原件与实际分母</h3><p>原epoch <code>{base.epoch_id}</code> · {base.as_of} · 目录 {base.catalogue_status}</p><p>原完整保护安全闲置 {money(base.baseline_full?.safe_idle_cents)}；执行 NOT_IMPLEMENTED，原银行经济结果未独立核验。</p><p>原账单 {base.inventory_counts.bills} / 原目标 {base.inventory_counts.goals}（可选 {base.inventory_counts.goal_choices}）/ 原完整策略 {base.inventory_counts.full_policies} / 目录产品 {base.inventory_counts.catalogue_products}。</p><p>原事实新协议摘要 <code>{base.source_hash}</code> · 引擎摘要 <code>{base.engine_hash}</code>。不是旧factDigest或资金权力。</p>{base.source_issues.map((issue, index) => <p className="notice" key={index}>{issue.code} · {issue.source_ref} · {issue.message}</p>)}</section>
    <form className="card" aria-label="单分项假设" onSubmit={(event) => { event.preventDefault(); void calculate(); }}><fieldset disabled={busy || query.isFetching || mutationBlocked}><legend>一次只比较一个分项</legend><label>假设分项 <select value={draft.family} onChange={(event) => update({ ...empty(), family: event.target.value as RiskFamily })}>{(Object.keys(names) as RiskFamily[]).map((family) => <option value={family} key={family}>{names[family]}</option>)}</select></label><label>当前实际原对象 <select value={draft.id} onChange={(event) => update(select(base, draft, event.target.value))}><option value="">请选择原对象</option>{choices.map((row) => <option value={row.id} key={row.id}>{row.label}</option>)}</select></label>{!choices.length && <p className="notice">BLOCKED：本分项没有当前可选原对象；不会创建虚拟原事实或权限。</p>}
      {controls.map(([field, label]) => <label key={field}>{label} <input inputMode="numeric" disabled={!draft.id} value={draft.values[field] ?? ''} onChange={(event) => update({ values: { ...draft.values, [field]: event.target.value } })} /></label>)}
      {draft.family === 'BILL' && <p className="caption">原银行剩余、已付款与原逾期保留；假设剩余0绝不表示已付款。候选日期不得早于原statement。</p>}
      {draft.family === 'GOAL' && <p className="caption">原当前归属、FullModel和本金日期保留；仅月度有序金额和期限假设参与此计算，不是完整目标联合最优。</p>}
      {draft.family === 'FULL_POLICY' && <><label>完整 JSON 假设候选 <textarea rows={14} value={draft.configuration} disabled={!draft.id} onChange={(event) => update({ configuration: event.target.value })} /></label><p className="caption">使用原Schema与原金融消费者校验；不支持的模板或金额保 UNKNOWN。没有确认或修改原版本。</p></>}
      {draft.family === 'PRODUCT' && <><label>当前原资产规划策略 <select value={draft.asset} onChange={(event) => update({ asset: event.target.value })}><option value="">请选择原规划版本</option>{base.full_policies.filter((row) => row.template_name === 'AssetAuthorizationPolicy').map((row) => <option value={row.policy_id} key={row.policy_id}>{row.policy_id} · {row.effective_status} · {row.version_id}</option>)}</select></label><p className="caption">原目录版本、产品条款与持仓不改。风险/锁期/赎回/最低额由原优化器消费；early_loss只另算假设上界，无实际报价，原模拟收益不是效果实测。</p></>}
      <div className="button-row"><button type="submit" disabled={!draft.id}>服务端分项只读比较</button><button type="button" onClick={() => { update(empty()); }}>仅清本页假设</button><button type="button" disabled={!replay} onClick={() => void calculate(true)}>同原请求显式重放</button></div><p className="caption">无自动POST或重试。原epoch/source/engine变化时必须只读刷新后重审；清本页不reset正式历史。</p></fieldset>{mutationBlocked && <p className="notice">其它资金请求未决，暂不发只读POST；本页GET刷新仍可使用。</p>}</form>{result && <Results key={result.comparison_hash} result={result} />}
    <details className="card"><summary>实际原对象与完整原 HTTP 响应</summary><p>原FullModel缺失与未支持属性不补造；可在原对象中查看具体issue。</p><pre className="readonly-raw">{getOriginalRiskResponse(base)}</pre></details>{base.limitations.map((text, index) => <p className="caption" key={index}>{text}</p>)}</>}
  </div>;
}
