import type { components } from '../../../../packages/contracts/schema';
import { request } from './http';
import { object } from '../features/policy-form';
import { assertMoneyFields } from '../features/money';
import { spendingHash } from './spending-evidence';

// Actual Main/OpenAPI aliases generated by Root; runtime parser requires all
// model_dump fields, including defaults which OpenAPI marks optional.
export type CalendarParameters = Required<components['schemas']['CalendarPeriodicParameters']>;
export type CalendarCadence = components['schemas']['CalendarSchedule']['cadence'];
export type CalendarSource = components['schemas']['SuggestionSource'];
export type CalendarOriginalFact = Required<components['schemas']['PeriodicFact']>;
export type CalendarPattern = Required<Omit<components['schemas']['CalendarPeriodicPattern'], 'schedule' | 'samples'>> & {
  schedule: Required<components['schemas']['CalendarSchedule']>;
  samples: (components['schemas']['CalendarSample'] & { original: CalendarOriginalFact })[];
};
export type CalendarPeriodicReport = Required<Omit<components['schemas']['CalendarPeriodicSuggestions'], 'parameters' | 'patterns'>> & {
  parameters: CalendarParameters; patterns: CalendarPattern[];
};
export type CalendarCandidateReview = { user_id: string; epoch_id: string; as_of: string; source_digest: string; pattern: CalendarPattern };
const originalResponses = new WeakMap<object, string>();
export const getCalendarOriginalResponse = (value: object): string | null => originalResponses.get(value) ?? null;
const uuid = (v: unknown): v is string => typeof v === 'string' && /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/.test(v);
const hash = (v: unknown): v is string => typeof v === 'string' && /^[0-9a-f]{64}$/.test(v);
const date = (v: unknown): v is string => typeof v === 'string' && /^\d{4}-\d\d-\d\d$/.test(v) && Number.isFinite(Date.parse(v)) && new Date(v).toISOString().slice(0, 10) === v;
const time = (v: unknown): v is string => typeof v === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(v) && Number.isFinite(Date.parse(v));
const integer = (v: unknown, minimum = 0): v is number => Number.isSafeInteger(v) && (v as number) >= minimum;
const strings = (v: unknown): v is string[] => Array.isArray(v) && v.every((x) => typeof x === 'string');
const ids = (v: unknown): v is string[] => strings(v) && v.every(uuid) && new Set(v).size === v.length;
const rational = (v: unknown): v is string => typeof v === 'string' && v.length <= 128 && /^(?:0|[1-9]\d*)(?:\/[1-9]\d*)?$/.test(v);
function check(v: unknown): asserts v { if (!v) throw new Error('周期候选原来源、日历或非授权合同不完整；未建立义务。'); }
function exact(v: Record<string, unknown>, keys: string[]) { return Object.keys(v).sort().join('|') === keys.sort().join('|'); }
export function parseCalendarParameters(v: unknown): CalendarParameters {
  check(object(v) && exact(v, ['lookback_days', 'minimum_cycles', 'maximum_day_spread', 'maximum_cv_bps']) && integer(v.lookback_days, 1) && v.lookback_days <= 365 && integer(v.minimum_cycles, 3) && v.minimum_cycles <= 12 && integer(v.maximum_day_spread) && v.maximum_day_spread <= 2 && integer(v.maximum_cv_bps) && v.maximum_cv_bps <= 1000);
  return v as CalendarParameters;
}
function source(v: unknown, asOf: string): asserts v is CalendarSource {
  check(object(v) && ['transactions', 'credit_card_bills', 'evidence_items'].includes(v.fact_type as string) && uuid(v.fact_id) && (v.account_id === null || uuid(v.account_id)) && typeof v.source_ref === 'string' && uuid(v.evidence_id) && hash(v.evidence_hash) && typeof v.evidence_source_type === 'string' && typeof v.evidence_source_ref === 'string' && time(v.evidence_observed_at) && Date.parse(v.evidence_observed_at) <= Date.parse(asOf) && object(v.fact));
  assertMoneyFields(v);
}
function fact(v: unknown, pattern: Record<string, unknown>, asOf: string): asserts v is CalendarOriginalFact {
  check(object(v) && v.kind === pattern.kind && v.account_id === pattern.account_id && v.payee_ref === pattern.payee_ref && date(v.occurred_on) && integer(v.amount_cents) && Array.isArray(v.supporting_sources));
  source(v.source, asOf); check(v.source.account_id === v.account_id); v.supporting_sources.forEach((s) => source(s, asOf));
  if (v.kind === 'CREDIT_CARD_BILL') check(v.source.fact_type === 'credit_card_bills' && v.source.evidence_source_type === 'SIMULATED_CREDIT_CARD_BILL' && v.source.fact.total_cents === v.amount_cents && v.source.fact.due_date === v.occurred_on);
  else {
    check(v.source.fact_type === 'transactions' && v.source.evidence_source_type === 'SIMULATED_BANK_TRANSACTION' && v.source.fact.transaction_id === v.source.fact_id && v.source.fact.account_id === v.account_id && v.source.fact.direction === 'DEBIT' && v.source.fact.amount_cents === v.amount_cents && v.source.fact.counterparty_ref === v.payee_ref && time(v.source.fact.occurred_at));
    if (v.kind === 'RENT') check(v.supporting_sources.length === 1 && v.supporting_sources[0]!.evidence_source_type === 'SIMULATED_USER_CATEGORY_CONFIRMATION');
  }
}
async function pattern(v: unknown, report: Record<string, unknown>, params: CalendarParameters): Promise<void> {
  check(object(v) && hash(v.pattern_id) && ['FIXED_TRANSFER', 'RENT', 'CREDIT_CARD_BILL'].includes(v.kind as string) && uuid(v.account_id) && typeof v.payee_ref === 'string' && v.payee_ref.length > 0 && v.payee_ref === v.payee_ref.trim() && ['READY_DISCOVERY', 'INSUFFICIENT_HISTORY', 'UNSTABLE', 'UNKNOWN'].includes(v.status as string) && strings(v.reason_codes));
  check(v.advice_only === true && v.requires_confirmation === true && v.auto_execute === false && v.bank_authority === false && v.future_obligation_guaranteed === false && v.source_scope === (v.kind === 'CREDIT_CARD_BILL' ? 'OBSERVED_BILLS_ONLY' : 'COVERED_TRANSACTIONS'));
  const schedule = v.schedule; check(object(schedule) && ['MONTHLY_DATE', 'MONTH_END', 'WEEKLY'].includes(schedule.cadence as string) && integer(schedule.day_spread) && strings(schedule.observed_cycle_keys) && schedule.next_occurrence_is_hypothesis === true && (schedule.next_occurrence === null || date(schedule.next_occurrence)));
  if (schedule.cadence === 'WEEKLY') check(schedule.due_day === null && schedule.days_before_month_end === null && integer(schedule.weekday) && schedule.weekday <= 6 && schedule.observed_cycle_keys.every(date));
  else {
    check(schedule.weekday === null && schedule.observed_cycle_keys.every((key) => /^\d{4}-(?:0[1-9]|1[0-2])$/.test(key)));
    if (schedule.cadence === 'MONTHLY_DATE') check(integer(schedule.due_day, 1) && schedule.due_day <= 31 && schedule.days_before_month_end === null);
    else check(schedule.due_day === null && integer(schedule.days_before_month_end) && schedule.days_before_month_end <= 30);
  }
  check(integer(v.sample_count, 1) && integer(v.cycle_count, 1) && v.cycle_count <= v.sample_count && Array.isArray(v.samples) && v.samples.length === v.sample_count && schedule.observed_cycle_keys.length === v.sample_count && new Set(schedule.observed_cycle_keys).size === v.cycle_count && integer(v.amount_min_cents) && integer(v.amount_max_cents) && v.amount_min_cents <= v.amount_max_cents && rational(v.mean_fraction_cents) && rational(v.variance_fraction_cents_squared) && (v.cv_squared_fraction === null || rational(v.cv_squared_fraction)));
  const factIds = new Set<string>();
  for (const sample of v.samples) {
    check(object(sample) && date(sample.occurred_on) && sample.occurred_on >= String(report.history_start) && sample.occurred_on <= String(report.history_end) && integer(sample.amount_cents));
    fact(sample.original, v, String(report.as_of));
    check(sample.occurred_on === sample.original.occurred_on && sample.amount_cents === sample.original.amount_cents && sample.amount_cents >= v.amount_min_cents && sample.amount_cents <= v.amount_max_cents);
    // Invalid duplicate samples are retained as UNSTABLE, never promoted to a candidate.
    factIds.add(sample.original.source.fact_id);
    const allSources = [sample.original.source, ...sample.original.supporting_sources];
    check(Array.isArray(report.source_evidence_ids) && allSources.every((s) => (report.source_evidence_ids as unknown[]).includes(s.evidence_id)));
  }
  const ready = v.status === 'READY_DISCOVERY';
  if (ready) check(object(report.history_proof) && report.history_proof.verified === true && v.cycle_count >= params.minimum_cycles && factIds.size === v.sample_count && v.cycle_count === v.sample_count && schedule.day_spread <= params.maximum_day_spread);
  else check(schedule.next_occurrence === null);
  check(['AVAILABLE_FOR_USER_REVIEW', 'NOT_READY', 'DSL_UNSUPPORTED'].includes(v.candidate_support as string));
  if (v.candidate_support === 'AVAILABLE_FOR_USER_REVIEW') {
    check(ready && v.reason_codes.length === 0 && object(v.candidate_configuration) && hash(v.candidate_configuration_hash));
    const config = v.candidate_configuration;
    check(v.template_name === (v.kind === 'FIXED_TRANSFER' ? 'PeriodicTransferPolicy' : 'RecurringObligationPolicy') && config.type === (v.kind === 'FIXED_TRANSFER' ? 'periodic_transfer' : 'recurring_obligation') && config.payee_id === v.payee_ref && config.auto_execute === false && config.due_day === (schedule.cadence === 'MONTH_END' ? 31 : schedule.due_day));
    check(schedule.cadence !== 'WEEKLY' && (schedule.cadence !== 'MONTH_END' || schedule.days_before_month_end === 0 && schedule.day_spread === 0));
    if (v.kind === 'FIXED_TRANSFER') check(config.source_account_id === v.account_id && config.single_action_cap_cents === v.amount_max_cents);
    check(object(config.amount_rule));
    if (v.kind === 'CREDIT_CARD_BILL') check(config.amount_rule.kind === 'bill_balance' && config.amount_rule.account_id === v.account_id);
    else check(config.amount_rule.kind === 'range' && config.amount_rule.min_cents === v.amount_min_cents && config.amount_rule.max_cents === v.amount_max_cents);
    check(await spendingHash(config) === v.candidate_configuration_hash);
  } else {
    check(v.candidate_configuration === null && v.candidate_configuration_hash === null && v.template_name === null);
    if (v.candidate_support === 'DSL_UNSUPPORTED') check(ready && v.reason_codes.includes('CURRENT_POLICY_DSL_CANNOT_EXPRESS_THIS_SCHEDULE') && (schedule.cadence === 'WEEKLY' || schedule.cadence === 'MONTH_END' && (schedule.days_before_month_end !== 0 || schedule.day_spread !== 0)));
    else check(!ready);
  }
}
export async function parseCalendarPeriodicReport(v: unknown, expectedParameters?: CalendarParameters, userId?: string, raw?: string): Promise<CalendarPeriodicReport> {
  check(object(v) && v.protocol === 'full-calendar-periodic-discovery-v2' && v.simulation === true && uuid(v.user_id) && (userId === undefined || v.user_id === userId) && uuid(v.epoch_id) && time(v.as_of));
  for (const key of ['writes_performed', 'grants_authority', 'bank_authority', 'hard_protection_changed', 'future_obligation_created', 'audit_chain_verified']) check(v[key] === false);
  check(date(v.history_start) && date(v.history_end) && v.history_start <= v.history_end && v.source_scope === 'TRANSACTION_COVERAGE_WITH_OBSERVED_BILLS_ONLY' && hash(v.source_digest) && ids(v.source_evidence_ids) && Array.isArray(v.source_issues) && integer(v.excluded_transaction_count) && strings(v.limitations) && Array.isArray(v.patterns));
  const params = parseCalendarParameters(v.parameters);
  if (expectedParameters) check(Object.keys(expectedParameters).every((key) => params[key as keyof CalendarParameters] === expectedParameters[key as keyof CalendarParameters]));
  const proof = v.history_proof;
  check(object(proof) && typeof proof.verified === 'boolean' && ids(proof.account_ids) && ids(proof.evidence_ids) && strings(proof.reason_codes) && (proof.period_start === null || date(proof.period_start)) && (proof.period_end === null || date(proof.period_end)));
  if (proof.verified) check(date(proof.period_start) && date(proof.period_end) && proof.period_start <= v.history_start && proof.period_end >= v.history_end && proof.reason_codes.length === 0 && v.source_issues.length === 0);
  v.source_issues.forEach((issue) => check(object(issue) && typeof issue.code === 'string' && typeof issue.message === 'string' && typeof issue.source_ref === 'string'));
  // The registered mean is a rational *string*, not integer money. Exempt exactly
  // this DTO path; raw sources/configuration and every other money field stay strict.
  assertMoneyFields({ ...v, patterns: v.patterns.map((row) => object(row) ? { ...row, mean_fraction_cents: null } : row) });
  for (const row of v.patterns) await pattern(row, v, params);
  check(new Set(v.patterns.map((row) => object(row) ? row.pattern_id : null)).size === v.patterns.length);
  if (!proof.verified) check(v.patterns.every((row) => object(row) && row.status === 'UNKNOWN' && row.candidate_configuration === null));
  const parsed = v as CalendarPeriodicReport;
  if (raw !== undefined) originalResponses.set(parsed, raw);
  return parsed;
}
export async function readCalendarPeriodicSuggestions(parameters: CalendarParameters, userId?: string): Promise<CalendarPeriodicReport> {
  const p = parseCalendarParameters(parameters);
  const query = new URLSearchParams(Object.entries(p).map(([key, value]) => [key, String(value)]));
  return request(`/policy-suggestions/calendar-periodic?${query}`, 'GET', undefined, (value, raw) => parseCalendarPeriodicReport(value, p, userId, raw));
}
