import type { components } from '../../../../packages/contracts/schema';
import { object } from '../features/policy-form';
import { assertMoneyFields } from '../features/money';
import { recoveryCheck as check, recoveryCanonicalJson as canonical, recoveryRequestHash as hash, parseRecoveryPrepare } from './full-recovery-execution';
import { releaseDigest as digest, releaseUUID as uuid, releaseUUID5 } from './goal-release-authorizations';
import { parseLocalActorSession } from './local-actor';
import { request } from './http';

export type MaturityPrepare = components['schemas']['FullMaturityRequest'];
export type MaturityProof = components['schemas']['FullMaturityProof'];
export type MaturityPreview = components['schemas']['FullMaturityPreview'];
export type MaturityAction = components['schemas']['FullMaturityAction'];
export type MaturityLookup = Required<components['schemas']['FullMaturityLookup']>;
export type MaturityIntent = { protocol: 'full-maturity-browser-v1'; kind: 'PREPARE' | 'CONFIRM' | 'EXECUTE'; user_id: string; prepare_request: MaturityPrepare; action: MaturityAction | null; path: string; body: MaturityPrepare | components['schemas']['FullMaturityConfirmation'] | components['schemas']['FullMaturityExecuteRequest']; body_json: string; request_hash: string };
const base = '/full-maturity-actions', algorithm = 'full-maturity-user-execution-v1';
const rawOriginals = new WeakMap<object, string>(), freshReads = new WeakSet<object>();
export const originalMaturityResponse = (value: object) => rawOriginals.get(value) ?? null;
export const isFreshMaturityRead = (value: object) => freshReads.has(value);
const exact = (value: Record<string, unknown>, fields: string[]) => Object.keys(value).sort().join('|') === [...fields].sort().join('|');
const same = (left: unknown, right: unknown) => canonical(left) === canonical(right);
const time = (value: unknown): value is string => typeof value === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(value) && Number.isFinite(Date.parse(value));
const sameTime = (a: unknown, b: unknown) => time(a) && time(b) && Date.parse(a) === Date.parse(b);
const money = (value: unknown): value is number => Number.isSafeInteger(value) && Number(value) >= 0;
const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every(v => typeof v === 'string');
const ids = (value: unknown): value is string[] => strings(value) && value.every(uuid) && new Set(value).size === value.length;
const save = <T extends object>(value: T, raw?: string): T => { if (raw !== undefined) { check(same(JSON.parse(raw), value)); rawOriginals.set(value, raw); } return value; };
export const parseMaturityPrepare = (value: unknown): MaturityPrepare => parseRecoveryPrepare(value);
export const maturityBankKey = async (key: string) => `maturity:user:${await hash({ key })}`;
export async function maturityActionId(body: MaturityPrepare): Promise<string> { return releaseUUID5(body.expected_epoch_id, await maturityBankKey(body.idempotency_key)); }

function parseCommand(value: unknown, body: MaturityPrepare, user: string): asserts value is components['schemas']['MaturityContractCommand'] {
  check(object(value) && exact(value, ['user_id', 'position_id', 'position_account_id', 'product_id', 'goal_id', 'original_policy_version_id', 'destination_account_id', 'principal_cents', 'requested_at', 'available_at', 'expires_at', 'kind']) && value.user_id === user && value.position_id === body.position_id && ['position_account_id', 'product_id', 'original_policy_version_id', 'destination_account_id'].every(k => uuid(value[k])) && (value.goal_id === null || uuid(value.goal_id)) && money(value.principal_cents) && value.principal_cents > 0 && value.kind === 'MATURE' && ['requested_at', 'available_at', 'expires_at'].every(k => time(value[k])) && value.available_at === value.requested_at && Date.parse(String(value.expires_at)) - Date.parse(String(value.requested_at)) === 900_000);
}
const commandHash = (command: unknown, body: MaturityPrepare) => hash({ protocol: algorithm, request: body, bank_request: command });
export async function parseMaturityProof(value: unknown, body: MaturityPrepare, user: string): Promise<MaturityProof> {
  check(object(value) && exact(value, ['protocol', 'simulation', 'grants_authority', 'receipt_is_current_authority', 'bank_receipt_proven', 'projected_cash_is_current_cash', 'user_id', 'epoch_id', 'position_id', 'as_of', 'status', 'reasons', 'command', 'candidate_denominator', 'input_hash', 'command_hash', 'conditional_protection_hash', 'remaining_negative_checkpoints', 'proof_hash']) && value.protocol === algorithm && value.simulation === true && ['grants_authority', 'receipt_is_current_authority', 'bank_receipt_proven', 'projected_cash_is_current_cash'].every(k => value[k] === false) && value.user_id === user && value.epoch_id === body.expected_epoch_id && value.position_id === body.position_id && time(value.as_of) && ['VERIFIED_SCOPE', 'BLOCKED', 'UNKNOWN'].includes(String(value.status)) && strings(value.reasons) && Number.isSafeInteger(value.candidate_denominator) && Number(value.candidate_denominator) >= 0 && digest(value.input_hash) && digest(value.proof_hash) && (value.conditional_protection_hash === null || digest(value.conditional_protection_hash)) && (value.remaining_negative_checkpoints === null || Number.isSafeInteger(value.remaining_negative_checkpoints) && Number(value.remaining_negative_checkpoints) >= 0 && Number(value.remaining_negative_checkpoints) <= 1098));
  if (value.command !== null) { parseCommand(value.command, body, user); check(value.command_hash === await commandHash(value.command, body) && Date.parse(value.command.requested_at) <= Date.parse(value.as_of)); } else check(value.command_hash === null);
  if (value.status === 'VERIFIED_SCOPE') check(value.reasons.length === 0 && value.command !== null && Number(value.candidate_denominator) > 0 && digest(value.conditional_protection_hash) && value.remaining_negative_checkpoints !== null && Date.parse(value.as_of) < Date.parse((value.command as components['schemas']['MaturityContractCommand']).expires_at)); else check(value.reasons.length > 0);
  const { proof_hash, ...unsigned } = value; check(proof_hash === await hash(unsigned)); assertMoneyFields(value); return value as MaturityProof;
}
export async function parseMaturityPreview(value: unknown, body: MaturityPrepare, user: string, raw?: string): Promise<MaturityPreview> {
  parseMaturityPrepare(body); check(uuid(user) && object(value) && exact(value, ['simulation', 'bank_authority', 'grants_authority', 'read_only', 'user_id', 'original_request', 'proof', 'limitations']) && value.simulation === true && value.bank_authority === false && value.grants_authority === false && value.read_only === true && value.user_id === user && same(value.original_request, body) && strings(value.limitations)); await parseMaturityProof(value.proof, body, user); return save(value as MaturityPreview, raw);
}
async function parseEvent(value: unknown, action: MaturityAction): Promise<void> {
  check(object(value) && exact(value, ['action_id', 'position_id', 'original_product_id', 'original_policy_version_id', 'goal_id', 'destination_account_id', 'original_action_status', 'bank_operation_id', 'original_bank_status', 'original_receipt_id', 'principal_cents', 'settled_at', 'proof_status', 'service_receipt_verified', 'receipt_is_current_authority', 'economic_verified', 'absence_is_final', 'originals_hash', 'originals', 'issues']) && value.action_id === action.action_id && value.position_id === action.command.position_id && value.original_product_id === action.command.product_id && value.original_policy_version_id === action.command.original_policy_version_id && value.goal_id === action.command.goal_id && value.destination_account_id === action.command.destination_account_id && value.original_action_status === action.status && value.principal_cents === action.command.principal_cents && ['VERIFIED', 'NOT_RECEIVED', 'UNKNOWN'].includes(String(value.proof_status)) && value.service_receipt_verified === action.service_receipt_verified && ['receipt_is_current_authority', 'economic_verified', 'absence_is_final'].every(k => value[k] === false) && (value.bank_operation_id === null || uuid(value.bank_operation_id)) && (value.original_receipt_id === null || uuid(value.original_receipt_id)) && (value.original_bank_status === null || ['ACCEPTED', 'PENDING', 'SETTLED', 'UNKNOWN', 'REJECTED'].includes(String(value.original_bank_status))) && (value.settled_at === null || time(value.settled_at)) && strings(value.issues) && object(value.originals) && exact(value.originals, ['action', 'bank_requests', 'receipts', 'bank_operations', 'position']) && value.originals_hash === await hash(value.originals));
  const originals = value.originals, row = originals.action;
  check(object(row) && row.id === action.action_id && row.user_id === action.user_id && row.action_type === 'ASSET_MATURITY' && row.status === action.status && row.idempotency_key === action.bank_key && row.request_hash === action.server_request_hash && same(row.request, action.original_action_request) && row.position_id === action.command.position_id && row.product_id === action.command.product_id && row.policy_version_id === action.command.original_policy_version_id && row.goal_id === action.command.goal_id && row.amount_cents === action.command.principal_cents && row.source_account_id === action.command.position_account_id && row.destination_account_id === action.command.destination_account_id);
  check(Array.isArray(originals.bank_requests) && originals.bank_requests.length <= 1 && Array.isArray(originals.bank_operations) && originals.bank_operations.length <= 1 && Array.isArray(originals.receipts) && originals.receipts.length <= 1);
  const bank = originals.bank_requests[0], operation = originals.bank_operations[0], receipt = originals.receipts[0];
  for (const b of [bank, operation]) if (b !== undefined) check(object(b) && uuid(b.id) && b.user_id === action.user_id && b.action_plan_id === action.action_id && b.idempotency_key === action.bank_key && same(b.request, action.command) && b.request_hash === await hash(action.command) && sameTime(b.requested_at, action.command.requested_at) && sameTime(b.available_at, action.command.available_at));
  if (bank !== undefined) check(object(bank) && bank.position_id === action.command.position_id && bank.destination_account_id === action.command.destination_account_id && bank.product_id === action.command.product_id && bank.goal_id === action.command.goal_id && bank.principal_cents === action.command.principal_cents);
  if (bank !== undefined && operation !== undefined) check(object(bank) && object(operation) && bank.id === operation.id && operation.legacy_redemption_id === bank.id && operation.status === bank.status);
  check(value.bank_operation_id === (object(operation) ? operation.id : object(bank) ? bank.id : null) && value.original_bank_status === (object(operation) ? operation.status : object(bank) ? bank.status : null) && value.original_receipt_id === (object(receipt) ? receipt.id : null) && value.settled_at === (object(bank) ? bank.settled_at : null));
  if (receipt !== undefined) check(object(receipt) && uuid(receipt.id) && receipt.user_id === action.user_id && receipt.action_plan_id === action.action_id && receipt.executed_cents === action.command.principal_cents && receipt.fee_cents === 0 && receipt.loss_cents === 0 && receipt.status === 'SUCCEEDED' && object(receipt.response) && receipt.response.bank_request_id === value.bank_operation_id && ids(receipt.response.posting_ids) && receipt.response.posting_ids.length === 2 && time(receipt.occurred_at));
  check((value.proof_status === 'VERIFIED') === action.service_receipt_verified);
  if (action.service_receipt_verified) check(['SUCCEEDED', 'RECONCILED'].includes(action.status) && value.original_bank_status === 'SETTLED' && bank !== undefined && operation !== undefined && receipt !== undefined && time(value.settled_at) && object(originals.position) && originals.position.id === action.command.position_id && originals.position.user_id === action.user_id && originals.position.status === 'REDEEMED');
  if (['SUCCEEDED', 'RECONCILED'].includes(action.status)) check(action.service_receipt_verified);
  assertMoneyFields(value);
}
export async function parseMaturityAction(value: unknown, body: MaturityPrepare, user: string, expected?: MaturityAction | null, raw?: string): Promise<MaturityAction> {
  check(object(value) && exact(value, ['simulation', 'bank_authority', 'receipt_is_current_authority', 'user_id', 'action_id', 'epoch_id', 'original_request', 'original_action_request', 'client_request_hash', 'server_request_hash', 'reviewed_command_hash', 'bank_key', 'autonomy_level', 'status', 'command', 'original_consent', 'original_event', 'economic_verified', 'service_receipt_verified', 'epoch_state', 'historical']) && value.simulation === true && value.bank_authority === false && value.receipt_is_current_authority === false && value.economic_verified === false && value.user_id === user && value.epoch_id === body.expected_epoch_id && value.action_id === await maturityActionId(body) && same(parseMaturityPrepare(value.original_request), body) && value.client_request_hash === await hash(body) && object(value.original_action_request) && value.server_request_hash === await hash(value.original_action_request) && value.bank_key === await maturityBankKey(body.idempotency_key) && value.autonomy_level === 'ASK_ONCE' && ['PLANNED', 'AUTHORIZED', 'SUBMITTED', 'UNKNOWN', 'SUCCEEDED', 'RECONCILED', 'FAILED', 'INVALIDATED', 'CANCELLED'].includes(String(value.status)) && typeof value.service_receipt_verified === 'boolean' && ['OPEN', 'SEALED', 'MISSING'].includes(String(value.epoch_state)) && value.historical === (value.epoch_state !== 'OPEN'));
  parseCommand(value.command, body, user); check(value.reviewed_command_hash === await commandHash(value.command, body));
  const original = value.original_action_request, marker = original.full_maturity_execution;
  check(exact(original, ['bank_request', 'contract_terms_digest', 'contract_evidence_ids', 'full_maturity_execution']) && same(original.bank_request, value.command) && digest(original.contract_terms_digest) && ids(original.contract_evidence_ids) && original.contract_evidence_ids.length > 0 && object(marker) && exact(marker, ['protocol', 'user_id', 'epoch_id', 'action_id', 'request', 'client_request_hash', 'command_hash', 'original_proof_hash']) && marker.protocol === algorithm && marker.user_id === user && marker.epoch_id === body.expected_epoch_id && marker.action_id === value.action_id && same(marker.request, body) && marker.client_request_hash === value.client_request_hash && marker.command_hash === value.reviewed_command_hash && digest(marker.original_proof_hash));
  if (expected) check(value.action_id === expected.action_id && value.server_request_hash === expected.server_request_hash && value.reviewed_command_hash === expected.reviewed_command_hash && same(value.command, expected.command));
  if (value.original_consent !== null) {
    const c = value.original_consent; check(object(c) && exact(c, ['protocol', 'simulation', 'grants_authority', 'user_id', 'epoch_id', 'action_id', 'reviewed_command_hash', 'original_confirmation', 'principal_at_confirmation', 'confirmed_at']) && c.protocol === algorithm && c.simulation === true && c.grants_authority === false && c.user_id === user && c.epoch_id === body.expected_epoch_id && c.action_id === value.action_id && c.reviewed_command_hash === value.reviewed_command_hash && same(c.original_confirmation, { expected_epoch_id: body.expected_epoch_id, reviewed_command_hash: value.reviewed_command_hash, accepted: true }) && time(c.confirmed_at) && Date.parse(c.confirmed_at) >= Date.parse(value.command.requested_at) && Date.parse(c.confirmed_at) < Date.parse(value.command.expires_at));
    const actor = parseLocalActorSession({ simulation: true, bank_authority: false, confirms_financial_action: false, principal: c.principal_at_confirmation }).principal;
    check(actor.user_id === user && actor.role === 'USER' && Date.parse(actor.issued_at) <= Date.parse(c.confirmed_at) && Date.parse(c.confirmed_at) < Date.parse(actor.expires_at));
  }
  if (['AUTHORIZED', 'SUBMITTED', 'SUCCEEDED', 'RECONCILED'].includes(String(value.status))) check(value.original_consent !== null);
  await parseEvent(value.original_event, value as MaturityAction); assertMoneyFields(value); return save(value as MaturityAction, raw);
}
export async function parseMaturityIntent(value: unknown): Promise<MaturityIntent> {
  check(object(value) && exact(value, ['protocol', 'kind', 'user_id', 'prepare_request', 'action', 'path', 'body', 'body_json', 'request_hash']) && value.protocol === 'full-maturity-browser-v1' && uuid(value.user_id) && ['PREPARE', 'CONFIRM', 'EXECUTE'].includes(String(value.kind)) && object(value.body) && value.body_json === JSON.stringify(value.body) && value.request_hash === await hash(value.body)); const prepare = parseMaturityPrepare(value.prepare_request);
  if (value.kind === 'PREPARE') check(value.action === null && value.path === `${base}/prepare` && same(value.body, prepare));
  else { const action = await parseMaturityAction(value.action, prepare, value.user_id); check(value.path === `${base}/actions/${action.action_id}/${value.kind === 'CONFIRM' ? 'confirm' : 'execute'}` && value.body.expected_epoch_id === prepare.expected_epoch_id && value.body.reviewed_command_hash === action.reviewed_command_hash && exact(value.body, value.kind === 'CONFIRM' ? ['expected_epoch_id', 'reviewed_command_hash', 'accepted'] : ['expected_epoch_id', 'reviewed_command_hash']) && (value.kind !== 'CONFIRM' || value.body.accepted === true)); }
  return value as MaturityIntent;
}
export async function parseMaturityLookup(value: unknown, intent: MaturityIntent, raw?: string): Promise<MaturityLookup> {
  await parseMaturityIntent(intent); check(object(value) && exact(value, ['simulation', 'grants_authority', 'not_found_is_final', 'user_id', 'idempotency_key', 'status', 'action']) && value.simulation === true && value.grants_authority === false && value.not_found_is_final === false && value.user_id === intent.user_id && value.idempotency_key === intent.prepare_request.idempotency_key && ['RECORDED', 'NOT_FOUND_NOT_FINAL'].includes(String(value.status)));
  if (value.status === 'RECORDED') await parseMaturityAction(value.action, intent.prepare_request, intent.user_id, intent.action); else check(value.action === null); return save(value as MaturityLookup, raw);
}
export async function previewMaturityExecution(body: MaturityPrepare, user: string): Promise<MaturityPreview> { parseMaturityPrepare(body); return request(`${base}/preview`, 'POST', body, (v, raw) => parseMaturityPreview(v, body, user, raw)); }
export async function postMaturityExecution(intent: MaturityIntent): Promise<MaturityAction> { await parseMaturityIntent(intent); return request(intent.path, 'POST', intent.body, (v, raw) => parseMaturityAction(v, intent.prepare_request, intent.user_id, intent.action, raw)); }
export async function lookupMaturityExecution(intent: MaturityIntent): Promise<MaturityLookup> { await parseMaturityIntent(intent); const value = await request(`${base}/by-key/${encodeURIComponent(intent.prepare_request.idempotency_key)}`, 'GET', undefined, (v, raw) => parseMaturityLookup(v, intent, raw)); freshReads.add(value); return value; }
