import type { components } from '../../../../packages/contracts/schema';
import { request } from './http';
import { object } from '../features/policy-form';
import { assertMoneyFields } from '../features/money';
import { annualDayNumber, validateAnnualBoundary } from './planning';

export type ProductCatalog = components['schemas']['CatalogReadResponse'];
export type CatalogVersion = components['schemas']['CatalogVersionView'];
type AssetAllocation = Required<components['schemas']['FullAssetPlanningResult']> & { candidates: Required<components['schemas']['FullAssetCandidate']>[] };
export type FullAssetPlan = Omit<components['schemas']['FullAssetAllocationResponse'], 'allocation'> & { allocation: AssetAllocation | null };
export type AssetOptions = Required<components['schemas']['FullAssetPlanOptions']>;
export type FullRecoveryPlan = components['schemas']['FullRecoveryPlanningResponse'];
export type Positions = components['schemas']['PositionList'];
type Boundary = components['schemas']['BoundaryResult'];
const uuid = (value: unknown): value is string => typeof value === 'string' && /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i.test(value);
const digest = (value: unknown): value is string => typeof value === 'string' && /^[0-9a-f]{64}$/.test(value);
const timestamp = (value: unknown): value is string => typeof value === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(value) && Number.isFinite(Date.parse(value));
const integer = (value: unknown, min = 0, max = Number.MAX_SAFE_INTEGER) => Number.isSafeInteger(value) && (value as number) >= min && (value as number) <= max;
const nullable = (value: unknown, predicate: (value: unknown) => boolean) => value === null || predicate(value);
const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every((row) => typeof row === 'string');
const ids = (value: unknown): value is string[] => Array.isArray(value) && value.every(uuid) && new Set(value).size === value.length;
function check(value: unknown): asserts value { if (!value) throw new Error('产品原版本、规划期限、精确金额或无银行授权边界未通过校验'); }
const originals = new WeakMap<object, string>();
export const getOriginalFullProductsResponse = (value: object) => originals.get(value) ?? null;
function save<T extends object>(value: T, raw?: string): T { if (raw !== undefined) originals.set(value, raw); return value; }
function sameJson(a: unknown, b: unknown): boolean { if (a === b) return true; if (Array.isArray(a) && Array.isArray(b)) return a.length === b.length && a.every((row, i) => sameJson(row, b[i])); return object(a) && object(b) && Object.keys(a).length === Object.keys(b).length && Object.keys(a).every((key) => Object.hasOwn(b, key) && sameJson(a[key], b[key])); }
function product(value: unknown, registered = false): void {
  check(object(value) && uuid(registered ? value.id : value.product_id) && typeof value.product_code === 'string' && value.product_code.length > 0 && integer(value.version_number, 1) && typeof value.asset_class === 'string' && integer(value.risk_level, 0, 5) && typeof value.principal_fluctuation === 'boolean');
  check(['minimum_purchase_cents', 'lock_days', 'redemption_delay_days', 'annual_yield_bps', 'early_withdrawal_loss_bps'].every((key) => integer(value[key])) && ['auto_purchase_allowed', 'auto_redeem_allowed'].every((key) => typeof value[key] === 'boolean') && timestamp(value.created_at) && timestamp(value.effective_from) && nullable(value.effective_until, timestamp) && object(value.maturity_rule));
  check(value.effective_until === null || Date.parse(value.effective_until as string) >= Date.parse(value.effective_from)); assertMoneyFields(value);
}
export function parseCatalogVersion(value: unknown): CatalogVersion {
  check(object(value) && uuid(value.id) && uuid(value.product_id) && digest(value.product_hash) && digest(value.terms_digest) && timestamp(value.observed_at) && timestamp(value.effective_from) && nullable(value.effective_until, timestamp) && value.immutable_original_verified === true && typeof value.current_source_matched === 'boolean' && value.bank_authority === false && value.legacy_decisions_bound_to_this_catalogue === false);
  product(value.original_product, true); const original = value.original_product as Record<string, unknown>; check(original.id === value.product_id && original.product_code === value.product_code && original.version_number === value.version_number && original.effective_from === value.effective_from && original.effective_until === value.effective_until); return value as CatalogVersion;
}
export function parseProductCatalog(value: unknown, raw?: string): ProductCatalog {
  check(object(value) && value.simulation === true && value.grants_authority === false && ['REGISTERED', 'UNKNOWN'].includes(value.state as string) && Array.isArray(value.versions) && value.versions.length <= 1000 && ids(value.unregistered_product_ids) && strings(value.issues) && typeof value.complete_within_registered_capacity === 'boolean');
  const versions = value.versions.map(parseCatalogVersion); check(new Set(versions.map((row) => row.id)).size === versions.length && new Set(versions.map((row) => `${row.product_code}:${row.version_number}`)).size === versions.length);
  if (value.state === 'REGISTERED') check(value.complete_within_registered_capacity === true && versions.length > 0 && versions.every((row) => row.current_source_matched) && value.unregistered_product_ids.length === 0 && value.issues.length === 0); else check(value.issues.length > 0);
  return save(value as ProductCatalog, raw);
}
export function parsePositions(value: unknown, raw?: string): Positions {
  check(object(value) && value.simulation === true && Array.isArray(value.items)); check(value.items.every((row) => object(row) && ['id', 'account_id', 'product_id'].every((key) => uuid(row[key])) && nullable(row.goal_id, uuid) && nullable(row.policy_version_id, uuid) && integer(row.principal_cents) && integer(row.accrued_yield_cents) && timestamp(row.purchased_at) && nullable(row.maturity_at, timestamp) && nullable(row.available_at, timestamp) && typeof row.status === 'string'));
  check(new Set(value.items.map((row) => row.id)).size === value.items.length); assertMoneyFields(value); return save(value as Positions, raw);
}
export function parseAssetOptions(value: unknown): AssetOptions {
  check(object(value) && Object.keys(value).sort().join('|') === ['comparison_days', 'max_components', 'max_turnover_cents', 'funds_use_date', 'mode'].sort().join('|') && integer(value.comparison_days, 1, 365) && integer(value.max_components, 1, 4) && nullable(value.max_turnover_cents, (row) => integer(row)) && ['PORTFOLIO', 'FIXED_LADDER'].includes(value.mode as string)); if (value.funds_use_date !== null) annualDayNumber(value.funds_use_date); return value as AssetOptions;
}
/** 365 future dates plus day0, each BEFORE/AFTER_PAYMENT/AFTER_PRINCIPAL: 1098 points. */
export function productBoundaryPoints(value: unknown): number {
  check(object(value) && Array.isArray(value.calculation_trace)); const first = value.calculation_trace.find((row) => object(row) && row.day === 0); check(first || value.status === 'INSUFFICIENT_EVIDENCE'); return validateAnnualBoundary(value, first ? annualDayNumber(first.date) : 0, 365).size;
}
function verifiedCatalog(value: unknown): void {
  check(object(value) && ['VERIFIED', 'UNKNOWN'].includes(value.status as string) && Array.isArray(value.products) && Array.isArray(value.bindings) && strings(value.issues));
  if (value.status === 'UNKNOWN') { check(value.products.length === 0 && value.bindings.length === 0); return; }
  check(value.products.length === value.bindings.length && value.issues.length === 0); const products = value.products; const bindings = value.bindings;
  products.forEach((row) => { product(row); check(digest(row.terms_digest)); const matches = bindings.filter((binding) => object(binding) && binding.product_id === row.product_id); check(matches.length === 1 && uuid(matches[0].catalogue_version_id) && digest(matches[0].product_record_hash) && matches[0].terms_digest === row.terms_digest); });
  check(new Set(products.map((row) => row.product_id)).size === products.length && new Set(bindings.map((row) => row.catalogue_version_id)).size === bindings.length);
}
function envelope(value: unknown, id: string, schema: string): asserts value is Record<string, unknown> {
  check(uuid(id) && object(value) && value.schema_version === schema && value.simulation === true && value.planning_only === true && value.bank_authority === false && value.execution_support === 'NOT_IMPLEMENTED' && value.protection_scope === 'ORIGINAL_VERIFIED_365_DAY_CURVE' && uuid(value.user_id) && value.policy_id === id && timestamp(value.as_of) && ['COMPUTED', 'UNKNOWN'].includes(value.state as string) && digest(value.input_hash) && ids(value.source_evidence_ids) && strings(value.limitations) && Array.isArray(value.source_issues) && value.source_issues.every((row) => object(row) && ['code', 'source_ref', 'message'].every((key) => typeof row[key] === 'string'))); assertMoneyFields(value);
}
function exit(value: unknown, terms: string): void { check(object(value) && ['FIXED_MATURITY', 'PLANNED_REDEMPTION'].includes(value.kind as string) && nullable(value.request_at, timestamp) && timestamp(value.principal_available_at) && integer(value.earning_days, 0, 3660) && integer(value.liquidity_days, 0, 3660) && value.terms_digest === terms); }
export function parseFullAssetPlan(value: unknown, policyId: string, options: AssetOptions, raw?: string): FullAssetPlan {
  parseAssetOptions(options); envelope(value, policyId, 'verified-full-asset-planning-v1'); check(sameJson(value.planning_constraints, options) && strings(value.unavailable_asset_classes)); verifiedCatalog(value.catalogue);
  if (value.state === 'UNKNOWN') check(value.allocation === null);
  else {
    const a = value.allocation; check(object(a) && a.algorithm_version === 'finite-integer-original-product-portfolio-v1' && a.policy_id === policyId && uuid(a.policy_version_id) && ['general_idle_funds', 'goal'].includes(a.scope as string) && (a.scope === 'goal' ? uuid(a.goal_id) : a.goal_id === null) && a.planning_only === true && a.bank_authority === false && a.execution_support === 'NOT_IMPLEMENTED' && a.future_income_included_cents === 0 && ['OPTIMAL', 'NO_PURCHASE', 'UNKNOWN', 'INACTIVE_POLICY', 'INSUFFICIENT_EVIDENCE', 'LIQUIDITY_RISK'].includes(a.status as string) && digest(a.input_hash) && strings(a.reasons) && nullable(a.funds_use_date, (row) => { try { annualDayNumber(row); return true; } catch { return false; } }));
    productBoundaryPoints(a.baseline_boundary); if (a.projected_boundary !== null) productBoundaryPoints(a.projected_boundary); check(Array.isArray(a.candidates) && Array.isArray(a.batches) && a.batches.length <= options.max_components && ['total_purchase_cents', 'retained_scope_cash_cents', 'net_simulated_yield_cents'].every((key) => nullable(a[key], (row) => integer(row))) && nullable(a.purchase_count, (row) => integer(row, 0, 4)) && integer(a.search_nodes, 0, 200000));
    const catalogue = value.catalogue as components['schemas']['VerifiedCatalogProducts']; const match = (id: unknown, code: unknown, version: unknown, terms: unknown) => catalogue.products.some((row) => row.product_id === id && row.product_code === code && row.version_number === version && row.terms_digest === terms);
    for (const c of a.candidates) { check(object(c) && match(c.product_id, c.product_code, c.version_number, c.terms_digest) && typeof c.catalog_asset_class === 'string' && nullable(c.planning_asset_class, (row) => typeof row === 'string') && ['FEASIBLE', 'REJECTED', 'RETAIN_CASH'].includes(c.status as string) && c.bank_auto_eligible === false && nullable(c.financial_cap_cents, (row) => integer(row)) && nullable(c.maximum_batch_cents, (row) => integer(row)) && strings(c.reasons)); if (c.exit_plan !== null) exit(c.exit_plan, c.terms_digest as string); }
    for (const b of a.batches) { check(object(b) && match(b.product_id, b.product_code, b.version_number, b.terms_digest) && b.bank_authority === false && integer(b.amount_cents, 1) && integer(b.net_simulated_yield_cents) && timestamp(b.purchase_at) && Date.parse(b.purchase_at) === Date.parse(value.as_of as string) && timestamp(b.principal_available_at) && Date.parse(b.principal_available_at) >= Date.parse(b.purchase_at) && Array.isArray(b.cash_uses) && b.cash_uses.every((row) => object(row) && uuid(row.account_id) && integer(row.amount_cents, 1))); exit(b.exit_plan, b.terms_digest as string); check((b.exit_plan as Record<string, unknown>).principal_available_at === b.principal_available_at && b.cash_uses.reduce((sum: bigint, row: { amount_cents: number }) => sum + BigInt(row.amount_cents), 0n) === BigInt(b.amount_cents as number)); }
    check(new Set(a.candidates.map((c) => c.product_id)).size === a.candidates.length && new Set(a.batches.map((b) => b.product_id)).size === a.batches.length && ['NOT_REQUESTED', 'MATCHED_MULTI_MATURITY', 'SINGLE_MATURITY_AVAILABLE', 'NO_VALID_FIXED_BATCHES'].includes(a.ladder_status as string));
    if (['OPTIMAL', 'NO_PURCHASE'].includes(a.status as string)) { check(a.purchase_count === a.batches.length && a.total_purchase_cents === a.batches.reduce((sum: number, b: { amount_cents: number }) => sum + b.amount_cents, 0) && a.net_simulated_yield_cents === a.batches.reduce((sum: number, b: { net_simulated_yield_cents: number }) => sum + b.net_simulated_yield_cents, 0)); const dates = new Set(a.batches.map((b) => b.principal_available_at)); if (options.mode === 'FIXED_LADDER') check(a.ladder_status === (dates.size > 1 ? 'MATCHED_MULTI_MATURITY' : dates.size ? 'SINGLE_MATURITY_AVAILABLE' : 'NO_VALID_FIXED_BATCHES') || a.batches.length === 0 && a.ladder_status === 'NOT_REQUESTED'); else check(a.ladder_status === 'NOT_REQUESTED'); }
    else check(a.batches.length === 0 && a.total_purchase_cents === null && a.net_simulated_yield_cents === null && a.purchase_count === null);
  }
  return save(value as FullAssetPlan, raw);
}
export function parseFullRecoveryPlan(value: unknown, policyId: string, raw?: string): FullRecoveryPlan {
  envelope(value, policyId, 'verified-full-recovery-planning-v1'); parseProductCatalog(value.catalogue); check(Array.isArray(value.catalogue_bindings) && value.catalogue_bindings.every((row) => object(row) && uuid(row.product_id) && uuid(row.catalogue_version_id) && digest(row.product_record_hash) && digest(row.terms_digest)));
  if (value.state === 'UNKNOWN') check(value.plan === null);
  else {
    const p = value.plan; check(object(p) && p.algorithm_version === 'full-whole-position-recovery-v1' && p.policy_id === policyId && p.user_id === value.user_id && ['policy_version_id', 'linked_asset_policy_id', 'linked_asset_policy_version_id'].every((key) => uuid(p[key])) && digest(p.linked_asset_configuration_hash) && p.as_of === value.as_of && p.planning_only === true && p.bank_authority === false && p.execution_support === 'NOT_IMPLEMENTED' && ['NO_RECOVERY_NEEDED', 'NOT_TRIGGERED', 'CONDITIONAL_RECOVERY_PLAN', 'LIQUIDITY_RISK', 'UNKNOWN', 'INACTIVE_POLICY'].includes(p.status as string) && ['general_idle_funds', 'goal'].includes(p.scope as string) && (p.scope === 'goal' ? uuid(p.goal_id) : p.goal_id === null) && nullable(p.deadline_at, timestamp) && ['actual_scope_cash_cents', 'required_recovery_cents', 'conditional_on_time_recovery_cents'].every((key) => nullable(p[key], (row) => integer(row))) && strings(p.reasons) && strings(p.observed_triggers) && digest(p.input_hash)); productBoundaryPoints(p.actual_boundary); if (p.lossless_conditional_boundary !== null) productBoundaryPoints(p.lossless_conditional_boundary);
    check(Array.isArray(p.candidates) && Array.isArray(p.lossless_steps) && Array.isArray(p.uncovered_checkpoints) && p.observed_triggers.every((trigger: string) => ['BOUNDARY_SHRINK', 'AUTHORIZATION_REVOKED', 'POLICY_EXPIRED', 'LIQUIDITY_SHORTFALL'].includes(trigger))); const candidates = p.candidates;
    const checkpointCurve = (p.lossless_conditional_boundary ?? p.actual_boundary) as Boundary;
    const negativePoints = checkpointCurve.calculation_trace.filter((point) => point.margin_cents < 0);
    check(sameJson(p.uncovered_checkpoints, negativePoints));
    if (p.status === 'UNKNOWN') check(p.first_sustained_safe_point === null);
    else { const lastBad = checkpointCurve.calculation_trace.reduce((last, point, index) => point.margin_cents < 0 ? index : last, -1); check(sameJson(p.first_sustained_safe_point, checkpointCurve.calculation_trace[lastBad + 1] ?? null)); }
    for (const c of candidates) {
      check(object(c) && ['position_id', 'destination_account_id', 'product_id', 'catalogue_version_id'].every((key) => uuid(c[key])) && nullable(c.goal_id, uuid) && nullable(c.original_policy_version_id, uuid) && digest(c.terms_digest) && digest(c.product_record_hash) && integer(c.product_version_number, 1) && integer(c.principal_cents) && ['BANK_CONFIRMED', 'DERIVED_ORIGINAL_TERMS', 'MISSING'].includes(c.quote_source as string) && ['independent_loss_cents', 'fee_cents', 'net_cents'].every((key) => nullable(c[key], (row) => integer(row))) && nullable(c.earliest_conditional_cash_at, timestamp) && nullable(c.liquidity_rank, (row) => integer(row)) && nullable(c.on_time, (row) => typeof row === 'boolean') && typeof c.within_full_planning_limits === 'boolean' && typeof c.lossless_eligible === 'boolean' && ['ASK_ONCE', 'BLOCKED', 'UNKNOWN', 'EXCLUDED_SCOPE'].includes(c.decision as string) && c.bank_authority === false && strings(c.reasons));
      const bindings = value.catalogue_bindings.filter((row) => row.product_id === c.product_id && row.catalogue_version_id === c.catalogue_version_id && row.product_record_hash === c.product_record_hash && row.terms_digest === c.terms_digest); check(bindings.length === 1);
      if (c.net_cents !== null) check(c.independent_loss_cents !== null && c.fee_cents !== null && BigInt(c.principal_cents as number) === BigInt(c.net_cents as number) + BigInt(c.independent_loss_cents as number) + BigInt(c.fee_cents as number));
      if (c.lossless_eligible) check(c.goal_id === p.goal_id && c.independent_loss_cents === 0 && c.fee_cents === 0 && c.within_full_planning_limits === true); if (c.conditional_impact_boundary !== null && c.conditional_impact_boundary !== undefined) productBoundaryPoints(c.conditional_impact_boundary);
      if (c.original_quote !== null) { const q = c.original_quote; check(object(q) && uuid(q.quote_id) && q.user_id === value.user_id && q.position_id === c.position_id && q.product_id === c.product_id && q.product_version_number === c.product_version_number && q.terms_digest === c.terms_digest && q.principal_cents === c.principal_cents && ['REDEEM', 'EARLY_WITHDRAW', 'MATURE'].includes(q.kind as string) && ['request_at', 'principal_available_at', 'expires_at'].every((key) => timestamp(q[key])) && ids(q.evidence_ids) && ['principal_cents', 'fee_cents', 'loss_cents', 'net_cents'].every((key) => integer(q[key])) && BigInt(q.principal_cents as number) === BigInt(q.net_cents as number) + BigInt(q.fee_cents as number) + BigInt(q.loss_cents as number) && Date.parse(q.expires_at as string) > Date.parse(q.request_at as string) && Date.parse(q.principal_available_at as string) >= Date.parse(q.request_at as string)); if (c.net_cents !== null) check(q.net_cents === c.net_cents && q.fee_cents === c.fee_cents && q.loss_cents === c.independent_loss_cents); }
    }
    check(new Set(candidates.map((c) => c.position_id)).size === candidates.length && p.lossless_steps.every((step) => object(step) && step.lossless_eligible === true && candidates.some((candidate) => sameJson(candidate, step)))); if (p.status === 'UNKNOWN') check(p.lossless_conditional_boundary === null && p.actual_scope_cash_cents === null && p.required_recovery_cents === null && p.conditional_on_time_recovery_cents === null);
  }
  return save(value as FullRecoveryPlan, raw);
}
export const getProductCatalog = () => request<ProductCatalog>('/catalog/products', 'GET', undefined, parseProductCatalog);
export const getProductPositions = () => request<Positions>('/positions', 'GET', undefined, parsePositions);
export function getFullAssetPlan(policyId: string, options: AssetOptions): Promise<FullAssetPlan> { check(uuid(policyId)); parseAssetOptions(options); const query = new URLSearchParams({ planning_comparison_days: String(options.comparison_days), planning_max_components: String(options.max_components), planning_mode: options.mode }); if (options.max_turnover_cents !== null) query.set('planning_max_turnover_cents', String(options.max_turnover_cents)); if (options.funds_use_date !== null) query.set('planning_funds_use_date', options.funds_use_date); return request(`/full-policies/${policyId}/asset-allocation?${query}`, 'GET', undefined, (value, raw) => parseFullAssetPlan(value, policyId, options, raw)); }
export function getFullRecoveryPlan(policyId: string, deadline: string | null = null): Promise<FullRecoveryPlan> { check(uuid(policyId) && nullable(deadline, timestamp)); const query = deadline === null ? '' : `?${new URLSearchParams({ planning_deadline_at: deadline })}`; return request(`/full-policies/${policyId}/recovery-planning${query}`, 'GET', undefined, (value, raw) => parseFullRecoveryPlan(value, policyId, raw)); }
export function groupPrincipalDates<T>(rows: T[], date: (row: T) => string | null): { timestamp: string | null; rows: T[] }[] { const groups = new Map<string | null, T[]>(); rows.forEach((row) => { const key = date(row); check(nullable(key, timestamp)); groups.set(key, [...(groups.get(key) ?? []), row]); }); return [...groups.entries()].sort(([a], [b]) => a === null ? b === null ? 0 : 1 : b === null ? -1 : Date.parse(a) - Date.parse(b)).map(([timestamp, rows]) => ({ timestamp, rows })); }
export type ProductBoundary = Boundary;
