import { webcrypto } from 'node:crypto';
import { beforeEach, expect, it, vi } from 'vitest';
import { getJointExecution, isFreshJointExecutionRead, jointReviewBinding, parseJointBinding, parseJointConfirm, parseJointExecute, parseJointLookup, parseJointPlan, parseJointPrepare, parseJointPreview, parseJointResponse, postJointExecution } from './full-joint-goal-execution';
import { prepareJointIntent } from '../features/full-joint-goal-operation';
import { jointActorFixture, jointConfirmFixture, jointFixtureHash, jointFixtureId, jointLookupFixture, jointPlanFixture, jointPreviewFixture, jointResponseFixture } from '../tests/full-joint-goal-execution-fixture';
beforeEach(() => { vi.stubGlobal('crypto', webcrypto); vi.unstubAllGlobals(); vi.stubGlobal('crypto', webcrypto); });
it('TOOL_ONLY consumes complete native-shaped two-goal plan/1098 protection without financial assertions', async () => { const value = jointPreviewFixture(); const parsed = await parseJointPreview(value, value.request, value.user_id); expect(parsed.plan?.allocation_input.hard_protection_points).toHaveLength(1098); expect(parsed.plan?.children).toHaveLength(2); expect(await parseJointResponse(jointResponseFixture('CONFIRMED'))).toHaveProperty('bank_authority', false); });
it.each(['amount_cents', 'now', 'role', 'result'])('rejects client-injected %s in original prepare', (field) => { expect(() => parseJointPrepare({ ...jointPlanFixture().inputs.request, [field]: 1 })).toThrow(); });
it('requires explicit strict acceptance and bounded fixed child', () => { expect(() => parseJointConfirm({ ...jointConfirmFixture(), accepted: 'true' })).toThrow(); const p = jointPlanFixture(); const b = { accepted: true, reviewed_plan_hash: p.plan_hash, expected_epoch_id: p.epoch_id, expected_child_number: 1, expected_action_id: p.children[0]!.action_id }; expect(() => parseJointExecute({ ...b, expected_child_number: 9 })).toThrow(); expect(() => parseJointExecute({ ...b, amount_cents: 1 })).toThrow(); });
it.each(['owner', 'child_order', 'amount', 'bank_key', 'effect_hash', 'point_count', 'date', 'model_hash'])('rejects mismatched complete plan %s', async (change) => { const p = jointPlanFixture(); if (change === 'owner') p.user_id = jointFixtureId(999); if (change === 'child_order') p.children.reverse(); if (change === 'amount') p.children[0]!.command.effect.amount_cents += 1; if (change === 'bank_key') p.children[0]!.bank_idempotency_key += ':replacement'; if (change === 'effect_hash') p.children[0]!.command.effect_hash = '0'.repeat(64); if (change === 'point_count') p.allocation_input.hard_protection_points.pop(); if (change === 'date') { p.allocation_input.hard_protection_points[0]!.date = '2027-01-01'; p.allocation.input_hash = jointFixtureHash(p.allocation_input); } if (change === 'model_hash') p.children[0]!.original_model_evidence_hash = '0'.repeat(64); await expect(parseJointPlan(p)).rejects.toThrow(); });
it('retains finite arbitrary original metadata instead of pretending to reproduce Python float tokens', async () => { const p = jointPlanFixture(); const inventory = p.inputs.joint.original_actual_input.base.original_inventory as Record<string, unknown>; inventory.retained_tool_only_float = [{ confidence: 0.83 }]; await expect(parseJointPlan(p)).resolves.toHaveProperty('plan_hash', p.plan_hash); });
it('compact locator preserves all fixed original commands and cannot silently truncate', async () => { const p = jointPlanFixture(), binding = jointReviewBinding(p); expect(JSON.stringify(binding).length).toBeLessThan(20000); expect(await parseJointBinding(binding)).toHaveProperty('grants_authority', false); binding.children.pop(); await expect(parseJointBinding(binding)).rejects.toThrow(); });
it.each(['true_authority', 'fake_receipt', 'missing_child', 'actor_role', 'confirmed_body'])('rejects unsafe response %s', async (change) => { const r = jointResponseFixture('CONFIRMED'); if (change === 'true_authority') Object.assign(r, { current_authority_assessed: true }); if (change === 'fake_receipt') r.state = 'ORIGINAL_SERVICE_RECEIPTS_VERIFIED'; if (change === 'missing_child') r.children.pop(); if (change === 'actor_role') Object.assign(r.original_consent!.original_evidence.content as object, { actor_role: 'AGENT' }); if (change === 'confirmed_body') r.original_consent!.original_request.idempotency_key = 'replacement'; await expect(parseJointResponse(r)).rejects.toThrow(); });
it('UNKNOWN and retained history remain explicit and non-authorizing', async () => { expect((await parseJointResponse(jointResponseFixture('UNKNOWN'))).state).toBe('UNRESOLVED'); expect((await parseJointResponse(jointResponseFixture('HISTORY'))).state).toBe('RETAINED_HISTORY'); });
it('key lookup matches exact original body/hash/kind and NOT_FOUND remains non-final', async () => { const p = jointPlanFixture(), intent = await prepareJointIntent('PREPARE', p.user_id, p.inputs.request), lookup = jointLookupFixture(intent); expect((await parseJointLookup(lookup, intent)).status).toBe('RECORDED'); lookup.original_request_hash = '0'.repeat(64); await expect(parseJointLookup(lookup, intent)).rejects.toThrow(); const missing = { ...lookup, status: 'NOT_FOUND_NOT_FINAL', command_kind: null, original_request: null, original_request_hash: null, original: null }; expect((await parseJointLookup(missing, intent)).not_found_is_final).toBe(false); });
it('only actual independent GET creates current-invocation read provenance', async () => { const r = jointResponseFixture(); expect(isFreshJointExecutionRead(await parseJointResponse(r))).toBe(false); vi.stubGlobal('fetch', vi.fn<typeof globalThis.fetch>(async () => new Response(JSON.stringify(r), { status: 200 }))); const parsed = await getJointExecution(r.original_plan.plan_id, r.user_id); expect(isFreshJointExecutionRead(parsed)).toBe(true); });
it('each POST independently requests actual signed USER; nonUSER/wrong-owner/401 never sends financial body', async () => { const p = jointPlanFixture(), intent = await prepareJointIntent('PREPARE', p.user_id, p.inputs.request); for (const variant of ['AGENT', 'WRONG_OWNER', '401']) { const actor = jointActorFixture(); if (variant === 'AGENT') actor.principal.role = 'AGENT'; if (variant === 'WRONG_OWNER') actor.principal.user_id = jointFixtureId(987); const fetch = vi.fn<typeof globalThis.fetch>(async () => new Response(JSON.stringify(variant === '401' ? { error: { code: 'UNAUTHORIZED', message: 'actual test 401' } } : actor), { status: variant === '401' ? 401 : 200 })); vi.stubGlobal('fetch', fetch); await expect(postJointExecution(intent)).rejects.toThrow(); expect(fetch).toHaveBeenCalledTimes(1); expect(fetch.mock.calls[0]?.[0]).toContain('/local-actor/session'); } });

it('parent confirmed label without the original consent remains rejected', async () => { const r = jointResponseFixture(); r.state = 'CONFIRMED_UNRESERVED'; await expect(parseJointResponse(r)).rejects.toThrow(); });
