import type { components } from '../../../../packages/contracts/schema';
import { request } from './http';
import { object } from '../features/policy-form';
import { assertMoneyFields } from '../features/money';
import { spendingCanonicalJson as canonical, spendingHash as hash, spendingUUID as uuid, spendingDigest as digest } from './spending-evidence';

export type RecoveryPrepare = components['schemas']['FullRecoveryPrepareRequest'];
export type RecoveryProof = Required<components['schemas']['FullRecoveryExecutionProof']>;
export type RecoveryPreview = Required<components['schemas']['FullRecoveryExecutionPreview']>;
export type RecoveryLookup = Required<components['schemas']['FullRecoveryExecutionLookup']>;
export type RecoveryConsent = Required<components['schemas']['FullRecoveryUserConsent']>;
export type RecoveryAction = components['schemas']['ActionResponse'];
export type RecoveryIntent = { protocol: 'full-recovery-browser-v1'; kind: 'PREPARE' | 'CONFIRM' | 'EXECUTE'; user_id: string; prepare_request: RecoveryPrepare; action: RecoveryAction | null; path: string; body: RecoveryPrepare | components['schemas']['FullRecoveryConfirmation'] | components['schemas']['FullRecoveryExecuteRequest']; body_json: string; request_hash: string };
export const recoveryCanonicalJson = canonical;
export const recoveryRequestHash = hash;
const originals = new WeakMap<object, string>(), reads = new WeakSet<object>();
export const getOriginalRecoveryResponse = (value: object) => originals.get(value) ?? null;
export const isFreshRecoveryRead = (value: object) => reads.has(value);
export function recoveryCheck(value: unknown): asserts value { if (!value) throw new Error('恢复原请求、仓位、USER逐次同意或固定经济后果不一致；原件和待核对门保留。'); }
const exact = (value: Record<string, unknown>, fields: string[]) => Object.keys(value).sort().join('|') === [...fields].sort().join('|');
const time = (value: unknown): value is string => typeof value === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(value) && Number.isFinite(Date.parse(value));
const cents = (value: unknown): value is number => Number.isSafeInteger(value) && Number(value) >= 0;
const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every((row) => typeof row === 'string');
const ids = (value: unknown): value is string[] => Array.isArray(value) && value.every(uuid) && new Set(value).size === value.length;
const save = <T extends object>(value: T, raw?: string): T => { if (raw !== undefined) originals.set(value, raw); return value; };

export function parseRecoveryPrepare(value: unknown): RecoveryPrepare {
  recoveryCheck(object(value) && exact(value, ['policy_id', 'expected_version_id', 'expected_epoch_id', 'position_id', 'idempotency_key']) && ['policy_id', 'expected_version_id', 'expected_epoch_id', 'position_id'].every((key) => uuid(value[key])) && typeof value.idempotency_key === 'string' && value.idempotency_key.trim().length > 0 && value.idempotency_key.length <= 120);
  return value as RecoveryPrepare;
}
/** Internal response consistency; actual audit/source/permission and finances are server verified. */
export async function parseRecoveryProof(value: unknown, body: RecoveryPrepare, user: string): Promise<RecoveryProof> {
  recoveryCheck(object(value) && exact(value, ['protocol', 'simulation', 'bank_authority', 'grants_authority', 'preserves_original_permission_checks', 'user_id', 'epoch_id', 'policy_id', 'full_policy_version_id', 'position_id', 'as_of', 'status', 'candidate', 'deadline_at', 'input_hash', 'effect_hash', 'reasons', 'proof_hash']) && value.protocol === 'full-recovery-execution-v1' && value.simulation === true && value.bank_authority === false && value.grants_authority === false && value.preserves_original_permission_checks === true && value.user_id === user && value.epoch_id === body.expected_epoch_id && value.policy_id === body.policy_id && value.full_policy_version_id === body.expected_version_id && value.position_id === body.position_id && time(value.as_of) && ['VERIFIED_SCOPE', 'BLOCKED', 'UNKNOWN'].includes(value.status as string) && strings(value.reasons) && digest(value.input_hash) && digest(value.proof_hash) && (value.effect_hash === null || digest(value.effect_hash)) && (value.deadline_at === null || time(value.deadline_at)));
  const c = value.candidate; recoveryCheck(object(c) && c.position_id === body.position_id && (c.goal_id === null || uuid(c.goal_id)) && uuid(c.destination_account_id) && uuid(c.product_id) && uuid(c.catalogue_version_id) && digest(c.terms_digest) && digest(c.product_record_hash) && Number.isSafeInteger(c.product_version_number) && Number(c.product_version_number) > 0 && (c.original_policy_version_id === null || uuid(c.original_policy_version_id)) && cents(c.principal_cents) && c.principal_cents > 0 && ['BANK_CONFIRMED', 'DERIVED_ORIGINAL_TERMS', 'MISSING'].includes(c.quote_source as string) && ['ASK_ONCE', 'BLOCKED', 'UNKNOWN', 'EXCLUDED_SCOPE'].includes(c.decision as string) && strings(c.reasons) && c.bank_authority === false && typeof c.lossless_eligible === 'boolean' && typeof c.within_full_planning_limits === 'boolean' && (c.on_time === null || typeof c.on_time === 'boolean') && (c.liquidity_rank === null || Number.isSafeInteger(c.liquidity_rank)) && (c.earliest_conditional_cash_at === null || time(c.earliest_conditional_cash_at)));
  for (const field of ['independent_loss_cents', 'fee_cents', 'net_cents']) recoveryCheck(c[field] === null || cents(c[field]));
  if (c.original_quote !== null) {
    const q = c.original_quote; recoveryCheck(object(q) && uuid(q.quote_id) && q.user_id === user && q.position_id === body.position_id && q.product_id === c.product_id && q.product_version_number === c.product_version_number && q.terms_digest === c.terms_digest && ['REDEEM', 'EARLY_WITHDRAW', 'MATURE'].includes(q.kind as string) && ['principal_cents', 'fee_cents', 'loss_cents', 'net_cents'].every((key) => cents(q[key])) && q.principal_cents === c.principal_cents && BigInt(q.principal_cents as number) === BigInt(q.net_cents as number) + BigInt(q.fee_cents as number) + BigInt(q.loss_cents as number) && ['request_at', 'principal_available_at', 'expires_at'].every((key) => time(q[key])) && Date.parse(q.expires_at as string) > Date.parse(q.request_at as string) && Date.parse(q.principal_available_at as string) >= Date.parse(q.request_at as string) && ids(q.evidence_ids));
  }
  if (value.status === 'VERIFIED_SCOPE') recoveryCheck(value.reasons.length === 0 && time(value.deadline_at) && Date.parse(value.deadline_at) >= Date.parse(value.as_of) && c.decision === 'ASK_ONCE' && c.lossless_eligible === true && c.within_full_planning_limits === true && c.on_time === true && uuid(c.original_policy_version_id) && c.independent_loss_cents === 0 && c.fee_cents === 0 && c.net_cents === c.principal_cents && object(c.original_quote) && c.original_quote.kind === 'REDEEM' && c.original_quote.fee_cents === 0 && c.original_quote.loss_cents === 0 && c.original_quote.net_cents === c.principal_cents && c.quote_source !== 'MISSING');
  else recoveryCheck(value.reasons.length > 0);
  const { proof_hash: declared, ...compact } = value; recoveryCheck(declared === await hash(compact)); assertMoneyFields(value); return value as RecoveryProof;
}
export async function parseRecoveryAction(value: unknown, body: RecoveryPrepare, user: string, expected?: RecoveryAction | null, raw?: string): Promise<RecoveryAction> {
  recoveryCheck(object(value) && value.simulation === true && value.user_id === user && uuid(value.action_id) && uuid(value.decision_run_id) && ['PLANNED', 'AUTHORIZED', 'SUBMITTED', 'EXECUTING', 'UNKNOWN', 'SUCCEEDED', 'RECONCILED', 'FAILED', 'INVALIDATED', 'CANCELLED'].includes(value.status as string) && value.autonomy_level === 'ASK_ONCE' && digest(value.effect_hash) && time(value.prepared_at) && time(value.as_of) && (value.bank_status === null || ['PENDING', 'UNKNOWN', 'SETTLED', 'REJECTED', 'FAILED', 'EXECUTING'].includes(value.bank_status as string)));
  const e = value.effect; recoveryCheck(object(e) && e.simulation === true && e.operation_id === value.action_id && e.user_id === user && e.action_type === 'REDEEM_ASSET' && e.position_id === body.position_id && uuid(e.position_account_id) && uuid(e.destination_account_id) && uuid(e.policy_id) && uuid(e.policy_version_id) && ids(e.policy_version_ids) && e.policy_version_ids.includes(e.policy_version_id) && uuid(e.original_policy_version_id) && uuid(e.product_id) && Number.isSafeInteger(e.product_version_number) && Number(e.product_version_number) > 0 && digest(e.terms_digest) && uuid(e.quote_id) && cents(e.amount_cents) && e.amount_cents > 0 && e.fee_cents === 0 && e.loss_cents === 0 && e.net_cents === e.amount_cents && (e.goal_id === null || uuid(e.goal_id)) && (e.settlement_delay_days === 0 || e.settlement_delay_days === 1) && typeof e.business_key === 'string' && e.business_key.length > 0 && Array.isArray(e.cash_uses) && e.cash_uses.length === 0 && Array.isArray(e.income_uses) && e.income_uses.length === 0 && time(e.valid_from) && time(e.expires_at) && time(e.latest_arrival_at) && Date.parse(e.expires_at) > Date.parse(e.valid_from));
  for (const field of ['liability', 'payee_id', 'payee_evidence_id', 'return_account_id', 'purchase_exit']) recoveryCheck(e[field] === null);
  recoveryCheck(value.effect_hash === await hash({ ...e, policy_version_ids: [...e.policy_version_ids].sort() }) && object(value.prepared_validation) && value.prepared_validation.simulation === true && value.prepared_validation.financial_only === true && value.prepared_validation.effect_hash === value.effect_hash && ['READY', 'CONFIRMATION_REQUIRED', 'BLOCKED', 'INSUFFICIENT_EVIDENCE'].includes(value.prepared_validation.status as string));
  if (expected) recoveryCheck(value.action_id === expected.action_id && value.decision_run_id === expected.decision_run_id && value.effect_hash === expected.effect_hash && canonical(e) === canonical(expected.effect));
  if (value.receipt !== null) { const r = value.receipt; recoveryCheck(object(r) && r.simulation === true && r.action_id === value.action_id && uuid(r.receipt_id) && uuid(r.bank_operation_id) && r.executed_cents === e.amount_cents && r.fee_cents === 0 && r.loss_cents === 0 && ids(r.posting_ids) && time(r.occurred_at) && (r.reconciled_at === null || time(r.reconciled_at))); }
  if (['SUCCEEDED', 'RECONCILED'].includes(value.status as string)) recoveryCheck(value.bank_status === 'SETTLED' && object(value.receipt));
  assertMoneyFields(value); return save(value as RecoveryAction, raw);
}
export async function parseRecoveryPreview(value: unknown, body: RecoveryPrepare, user: string, raw?: string): Promise<RecoveryPreview> {
  parseRecoveryPrepare(body); recoveryCheck(uuid(user) && object(value) && value.simulation === true && value.bank_authority === false && value.grants_authority === false && value.preview_only === true && value.user_id === user && canonical(value.original_request) === canonical(body) && strings(value.limitations)); const p = await parseRecoveryProof(value.proof, body, user);
  if (p.status === 'VERIFIED_SCOPE') { recoveryCheck(object(value.execution_effect) && value.execution_effect.position_id === body.position_id && value.execution_effect.user_id === user && value.execution_effect.action_type === 'REDEEM_ASSET' && value.execution_effect.amount_cents === p.candidate.principal_cents && value.execution_effect.fee_cents === 0 && value.execution_effect.loss_cents === 0 && value.execution_effect.net_cents === p.candidate.principal_cents && value.execution_effect.latest_arrival_at !== null && time(value.execution_effect.latest_arrival_at) && p.deadline_at !== null && Date.parse(value.execution_effect.latest_arrival_at) <= Date.parse(p.deadline_at) && digest(p.effect_hash)); const e = value.execution_effect; recoveryCheck(Array.isArray(e.policy_version_ids) && p.effect_hash === await hash({ ...e, policy_version_ids: [...e.policy_version_ids].sort() })); }
  else recoveryCheck(value.execution_effect === null);
  assertMoneyFields(value); return save(value as RecoveryPreview, raw);
}
export async function parseRecoveryIntent(value: unknown): Promise<RecoveryIntent> {
  recoveryCheck(object(value) && exact(value, ['protocol', 'kind', 'user_id', 'prepare_request', 'action', 'path', 'body', 'body_json', 'request_hash']) && value.protocol === 'full-recovery-browser-v1' && uuid(value.user_id) && ['PREPARE', 'CONFIRM', 'EXECUTE'].includes(value.kind as string) && object(value.body) && typeof value.body_json === 'string' && value.body_json === JSON.stringify(value.body) && digest(value.request_hash) && value.request_hash === await hash(value.body)); const prepare = parseRecoveryPrepare(value.prepare_request);
  if (value.kind === 'PREPARE') recoveryCheck(value.action === null && value.path === '/full-recovery-actions/prepare' && canonical(value.body) === canonical(prepare));
  else { const action = await parseRecoveryAction(value.action, prepare, value.user_id); recoveryCheck(value.path === `/full-recovery-actions/actions/${action.action_id}/${value.kind === 'CONFIRM' ? 'confirm' : 'execute'}` && value.body.expected_epoch_id === prepare.expected_epoch_id && value.body.reviewed_effect_hash === action.effect_hash); if (value.kind === 'CONFIRM') recoveryCheck(exact(value.body, ['expected_epoch_id', 'reviewed_effect_hash', 'accepted']) && value.body.accepted === true); else recoveryCheck(exact(value.body, ['expected_epoch_id', 'reviewed_effect_hash'])); }
  return value as RecoveryIntent;
}
export async function parseRecoveryLookup(value: unknown, intent: RecoveryIntent, raw?: string): Promise<RecoveryLookup> {
  await parseRecoveryIntent(intent); recoveryCheck(object(value) && exact(value, ['simulation', 'bank_authority', 'current_authority', 'not_found_is_final', 'user_id', 'idempotency_key', 'status', 'original_request', 'original_action_request', 'client_request_hash', 'server_request_hash', 'action', 'epoch_state', 'original_consent', 'consent_is_current_authority']) && value.simulation === true && value.bank_authority === false && value.current_authority === false && value.not_found_is_final === false && value.consent_is_current_authority === false && value.user_id === intent.user_id && value.idempotency_key === intent.prepare_request.idempotency_key && ['RECORDED', 'NOT_FOUND_NOT_FINAL'].includes(value.status as string) && ['OPEN', 'SEALED', 'MISSING'].includes(value.epoch_state as string));
  if (value.status === 'NOT_FOUND_NOT_FINAL') { for (const field of ['original_request', 'original_action_request', 'client_request_hash', 'server_request_hash', 'action', 'original_consent']) recoveryCheck(value[field] === null); recoveryCheck(value.epoch_state === 'MISSING'); }
  else {
    recoveryCheck(canonical(parseRecoveryPrepare(value.original_request)) === canonical(intent.prepare_request) && value.client_request_hash === await hash(intent.prepare_request) && object(value.original_action_request) && digest(value.server_request_hash) && value.server_request_hash === await hash(value.original_action_request) && value.epoch_state !== 'MISSING');
    const a = await parseRecoveryAction(value.action, intent.prepare_request, intent.user_id, intent.action), original = value.original_action_request, marker = original.full_recovery_execution;
    recoveryCheck(object(marker) && marker.protocol === 'full-recovery-execution-v1' && marker.user_id === intent.user_id && marker.epoch_id === intent.prepare_request.expected_epoch_id && canonical(marker.request) === canonical(intent.prepare_request) && marker.request_hash === value.client_request_hash && marker.effect_hash === a.effect_hash && object(original.execution) && canonical(original.execution.effect) === canonical(a.effect) && original.execution.effect_hash === a.effect_hash && object(original.intent) && original.intent.kind === 'redeem_asset' && original.intent.position_id === intent.prepare_request.position_id);
    const p = await parseRecoveryProof(marker.original_proof, intent.prepare_request, intent.user_id); recoveryCheck(p.status === 'VERIFIED_SCOPE' && p.effect_hash === a.effect_hash && p.candidate.principal_cents === a.effect.amount_cents && p.candidate.destination_account_id === a.effect.destination_account_id && p.candidate.goal_id === a.effect.goal_id && p.candidate.product_id === a.effect.product_id && p.candidate.product_version_number === a.effect.product_version_number && p.candidate.terms_digest === a.effect.terms_digest && p.candidate.original_policy_version_id === a.effect.original_policy_version_id && p.candidate.original_quote?.quote_id === a.effect.quote_id);
    if (value.original_consent !== null) {
      const c = value.original_consent; recoveryCheck(object(c) && c.protocol === 'full-recovery-execution-v1' && c.simulation === true && c.grants_authority === false && c.user_id === intent.user_id && c.epoch_id === intent.prepare_request.expected_epoch_id && c.action_id === a.action_id && c.original_effect_hash === a.effect_hash && uuid(c.original_confirmation_evidence_id) && original.confirmation_evidence_id === c.original_confirmation_evidence_id && time(c.confirmed_at) && Date.parse(c.confirmed_at) >= Date.parse(a.effect.valid_from) && Date.parse(c.confirmed_at) < Date.parse(a.effect.expires_at));
      const actor = c.principal_at_confirmation; recoveryCheck(object(actor) && actor.user_id === intent.user_id && actor.role === 'USER' && actor.authenticated === true && actor.human_identity_verified === false && actor.authentication_source === 'LOCAL_SIGNED_SESSION' && uuid(actor.session_id) && time(actor.issued_at) && time(actor.expires_at) && Date.parse(actor.expires_at) - Date.parse(actor.issued_at) > 0 && Date.parse(actor.expires_at) - Date.parse(actor.issued_at) <= 900_000 && Date.parse(actor.issued_at) <= Date.parse(c.confirmed_at) && Date.parse(c.confirmed_at) < Date.parse(actor.expires_at));
    }
  }
  assertMoneyFields(value); return save(value as RecoveryLookup, raw);
}
export async function previewRecoveryExecution(body: RecoveryPrepare, user: string): Promise<RecoveryPreview> { parseRecoveryPrepare(body); const r = await request<{ simulation: true; value: unknown; raw: string }>('/full-recovery-actions/preview', 'POST', body, (value, raw) => ({ simulation: true, value, raw })); return parseRecoveryPreview(r.value, body, user, r.raw); }
export async function postRecoveryExecution(intent: RecoveryIntent): Promise<RecoveryAction> { await parseRecoveryIntent(intent); const r = await request<{ simulation: true; value: unknown; raw: string }>(intent.path, 'POST', intent.body, (value, raw) => ({ simulation: true, value, raw })); return parseRecoveryAction(r.value, intent.prepare_request, intent.user_id, intent.action, r.raw); }
/** Independent original-key GET only; parsed POST/stored JSON cannot acquire this marker. */
export async function lookupRecoveryExecution(intent: RecoveryIntent): Promise<RecoveryLookup> { await parseRecoveryIntent(intent); const r = await request<{ simulation: true; value: unknown; raw: string }>(`/full-recovery-actions/by-key/${encodeURIComponent(intent.prepare_request.idempotency_key)}`, 'GET', undefined, (value, raw) => ({ simulation: true, value, raw })); const value = await parseRecoveryLookup(r.value, intent, r.raw); reads.add(value); return value; }
