import type { components } from '../../../../packages/contracts/schema';
import { request } from './http';
import { readLocalActorSession, parseLocalActorSession } from './local-actor';
import { object } from '../features/policy-form';
import { assertMoneyFields } from '../features/money';
import { spendingCanonicalJson, spendingHash, spendingUUID as uuid, spendingDigest as digest } from './spending-evidence';
import { releaseUUID5 } from './goal-release-authorizations';
import { parseDynamicAction } from './full-dynamic-goal-execution';
import type { FullJointInput } from './full-joint-planning';

// These aliases refer to the actual Main-generated contract, never a client financial model.
export type JointPrepare = components['schemas']['FullJointGoalPrepareRequest'];
export type JointConfirm = components['schemas']['FullJointGoalConfirmRequest'];
export type JointExecute = components['schemas']['FullJointGoalExecuteRequest'];
export type JointPlan = components['schemas']['FullJointFrozenPlan'];
// parseJointPlan validates these immutable JSON fields before their read-only use.
export const jointAllocationInput = (plan: JointPlan): FullJointInput => plan.allocation_input as FullJointInput;
export type JointPreview = components['schemas']['FullJointGoalPreview'];
export type JointResponse = components['schemas']['FullJointGoalExecutionResponse'];
export type JointLookup = components['schemas']['FullJointGoalLookup'];
export type JointReviewBinding = { protocol: 'joint-goal-original-read-locator-v2'; plan_id: string; user_id: string; epoch_id: string; plan_hash: string; prepared_at: string; expires_at: string; original_request: JointPrepare; total_allocation_cents: number; children: JointPlan['children']; grants_authority: false };
export type JointIntent = { protocol: 'joint-goal-browser-command-v2'; kind: 'PREPARE' | 'CONFIRM' | 'EXECUTE'; user_id: string; plan_id: string | null; path: string; body: JointPrepare | JointConfirm | JointExecute; body_json: string; request_hash: string; reviewed_plan: JointReviewBinding | null };
/** Structural comparison only: arbitrary retained metadata may have floats.
 * JS cannot recover Python's 1.0 token. Never use this function as a server SHA. */
export function jointCanonical(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(jointCanonical).join(',')}]`;
  if (object(value)) return `{${Object.keys(value).sort().map((k) => `${JSON.stringify(k)}:${jointCanonical(value[k])}`).join(',')}}`;
  if (value === null || typeof value === 'string' || typeof value === 'boolean' || typeof value === 'number' && Number.isFinite(value) && (!Number.isInteger(value) || Number.isSafeInteger(value))) return JSON.stringify(value);
  throw new Error('联合原JSON含不能保真显示的值。');
}
export const jointWholeHashVerification = 'SERVER_ORIGINAL_HASH_NOT_INDEPENDENTLY_RECOMPUTED';
export const jointRequestHash = spendingHash;
export function jointCheck(value: unknown): asserts value { if (!value) throw new Error('联合原计划、子动作、明确确认或原body/hash不一致；保留原件，未解除请求。'); }
const exact = (value: Record<string, unknown>, fields: string[]) => Object.keys(value).sort().join('|') === [...fields].sort().join('|');
const time = (value: unknown): value is string => typeof value === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(value) && Number.isFinite(Date.parse(value));
const cents = (value: unknown): value is number => Number.isSafeInteger(value) && Number(value) >= 0;
const key = (value: unknown): value is string => typeof value === 'string' && /^[A-Za-z0-9][A-Za-z0-9_.:-]{0,159}$/.test(value);
const ids = (value: unknown): value is string[] => Array.isArray(value) && value.every(uuid) && new Set(value).size === value.length;
const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every((row) => typeof row === 'string');
const originals = new WeakMap<object, string>(), freshReads = new WeakSet<object>();
export const getOriginalJointExecutionResponse = (value: object) => originals.get(value) ?? null;
export const isFreshJointExecutionRead = (value: object) => freshReads.has(value);
const save = <T extends object>(value: T, raw?: string): T => { if (raw !== undefined) originals.set(value, raw); return value; };
export function jointReviewBinding(plan: JointPlan): JointReviewBinding { return { protocol: 'joint-goal-original-read-locator-v2', plan_id: plan.plan_id, user_id: plan.user_id, epoch_id: plan.epoch_id, plan_hash: plan.plan_hash, prepared_at: plan.prepared_at, expires_at: plan.expires_at, original_request: structuredClone(plan.inputs.request), total_allocation_cents: plan.total_allocation_cents, children: structuredClone(plan.children), grants_authority: false }; }
/** A compact locator contains ALL fixed children. It cannot replace full review
 * or current authority; restored locators require an independent server GET. */
export async function parseJointBinding(value: unknown): Promise<JointReviewBinding> {
  jointCheck(object(value) && exact(value, ['protocol', 'plan_id', 'user_id', 'epoch_id', 'plan_hash', 'prepared_at', 'expires_at', 'original_request', 'total_allocation_cents', 'children', 'grants_authority']) && value.protocol === 'joint-goal-original-read-locator-v2' && value.grants_authority === false && uuid(value.plan_id) && uuid(value.user_id) && uuid(value.epoch_id) && digest(value.plan_hash) && time(value.prepared_at) && time(value.expires_at) && Date.parse(value.expires_at) > Date.parse(value.prepared_at) && Date.parse(value.expires_at) - Date.parse(value.prepared_at) <= 900000 && cents(value.total_allocation_cents) && value.total_allocation_cents > 0);
  const body = parseJointPrepare(value.original_request); jointCheck(body.expected_epoch_id === value.epoch_id && value.plan_id === await releaseUUID5('514aaf21-d405-5f9c-8706-de1684e812e4', await spendingHash({ user: value.user_id, request: body })) && Array.isArray(value.children) && value.children.length >= 1 && value.children.length <= 8 && ids(value.children.map((r) => object(r) ? r.goal_id : null)) && ids(value.children.map((r) => object(r) ? r.action_id : null)));
  let total = 0n;
  for (const [index, child] of value.children.entries()) {
    jointCheck(object(child) && exact(child, ['child_number', 'goal_id', 'action_id', 'bank_idempotency_key', 'command', 'original_model_evidence_id', 'original_model_evidence_hash', 'range_proof_hash']) && child.child_number === index + 1 && child.action_id === await releaseUUID5(value.plan_id, `child:${index + 1}`) && child.bank_idempotency_key === `joint-goal:${value.plan_id}:${index + 1}` && uuid(child.original_model_evidence_id) && digest(child.original_model_evidence_hash) && digest(child.range_proof_hash) && object(child.command) && exact(child.command, ['effect', 'effect_hash']) && digest(child.command.effect_hash) && object(child.command.effect));
    const e = child.command.effect; jointCheck(e.simulation === true && e.operation_id === child.action_id && e.user_id === value.user_id && e.goal_id === child.goal_id && e.action_type === 'ALLOCATE_GOAL' && uuid(e.policy_id) && uuid(e.policy_version_id) && uuid(e.destination_account_id) && cents(e.amount_cents) && e.amount_cents > 0 && e.fee_cents === 0 && e.loss_cents === 0 && e.net_cents === null && e.quote_id === null && e.liability === null && e.settlement_delay_days === 0 && e.latest_arrival_at === null && e.valid_from === value.prepared_at && e.expires_at === value.expires_at && ids(e.policy_version_ids) && jointCanonical(e.policy_version_ids) === jointCanonical([e.policy_version_id]) && Array.isArray(e.cash_uses) && Array.isArray(e.income_uses) && e.cash_uses.length > 0 && e.income_uses.length > 0);
    for (const field of ['payee_id', 'payee_evidence_id', 'product_id', 'product_version_number', 'terms_digest', 'position_id', 'position_account_id', 'return_account_id', 'purchase_exit', 'original_policy_version_id']) jointCheck(e[field] === null);
    let cash = 0n, income = 0n; const accountIds = new Set<string>(), locations = new Set<string>();
    for (const use of e.cash_uses) { jointCheck(object(use) && exact(use, ['account_id', 'amount_cents']) && uuid(use.account_id) && cents(use.amount_cents) && use.amount_cents > 0 && !accountIds.has(use.account_id)); accountIds.add(use.account_id); cash += BigInt(use.amount_cents); }
    for (const use of e.income_uses) { jointCheck(object(use) && exact(use, ['fragment_id', 'origin_transaction_id', 'account_id', 'amount_cents']) && uuid(use.fragment_id) && uuid(use.origin_transaction_id) && uuid(use.account_id) && accountIds.has(use.account_id) && cents(use.amount_cents) && use.amount_cents > 0); const loc = `${use.origin_transaction_id}:${use.account_id}`; jointCheck(!locations.has(loc)); locations.add(loc); income += BigInt(use.amount_cents); }
    jointCheck(cash === BigInt(e.amount_cents) && income === cash && child.command.effect_hash === await spendingHash({ ...e, cash_uses: [...e.cash_uses].sort((a, b) => String(a.account_id).localeCompare(String(b.account_id))), income_uses: [...e.income_uses].sort((a, b) => `${a.origin_transaction_id}:${a.account_id}`.localeCompare(`${b.origin_transaction_id}:${b.account_id}`)), policy_version_ids: [...e.policy_version_ids].sort() })); total += BigInt(e.amount_cents);
  }
  jointCheck(total === BigInt(value.total_allocation_cents)); assertMoneyFields(value); return value as JointReviewBinding;
}
export function parseJointPrepare(value: unknown): JointPrepare {
  jointCheck(object(value) && exact(value, ['full_policy_id', 'expected_full_policy_version_id', 'expected_epoch_id', 'idempotency_key']) && ['full_policy_id', 'expected_full_policy_version_id', 'expected_epoch_id'].every((field) => uuid(value[field])) && key(value.idempotency_key)); return value as JointPrepare;
}
export function parseJointConfirm(value: unknown): JointConfirm {
  jointCheck(object(value) && exact(value, ['accepted', 'reviewed_plan_hash', 'expected_epoch_id', 'idempotency_key']) && value.accepted === true && digest(value.reviewed_plan_hash) && uuid(value.expected_epoch_id) && key(value.idempotency_key)); return value as JointConfirm;
}
export function parseJointExecute(value: unknown): JointExecute {
  jointCheck(object(value) && exact(value, ['accepted', 'reviewed_plan_hash', 'expected_epoch_id', 'expected_child_number', 'expected_action_id']) && value.accepted === true && digest(value.reviewed_plan_hash) && uuid(value.expected_epoch_id) && cents(value.expected_child_number) && value.expected_child_number >= 1 && value.expected_child_number <= 8 && uuid(value.expected_action_id)); return value as JointExecute;
}
/** UI identity/hash checks reuse the original effect reader; the server verifies
 * the optimizer, source provenance, audit and current permission on each call. */
export async function parseJointPlan(value: unknown, user?: string): Promise<JointPlan> {
  jointCheck(object(value) && exact(value, ['protocol', 'simulation', 'bank_authority', 'funds_reserved', 'execution_mode', 'cross_operation_atomicity', 'plan_id', 'user_id', 'epoch_id', 'prepared_at', 'expires_at', 'inputs', 'allocation_input', 'allocation', 'full_binding_hash', 'total_allocation_cents', 'children', 'plan_hash']));
  jointCheck(value.protocol === 'registered-joint-goal-execution-v2' && value.simulation === true && value.bank_authority === false && value.funds_reserved === false && value.execution_mode === 'USER_ASK_FIXED_ORDER' && value.cross_operation_atomicity === 'NOT_AVAILABLE' && uuid(value.plan_id) && uuid(value.user_id) && (!user || value.user_id === user) && uuid(value.epoch_id) && time(value.prepared_at) && time(value.expires_at) && Date.parse(value.expires_at) > Date.parse(value.prepared_at) && Date.parse(value.expires_at) - Date.parse(value.prepared_at) <= 900000 && digest(value.full_binding_hash) && digest(value.plan_hash) && cents(value.total_allocation_cents) && value.total_allocation_cents > 0);
  jointCheck(object(value.inputs) && exact(value.inputs, ['protocol', 'request', 'scope', 'joint']) && value.inputs.protocol === 'joint-goal-execution-input-v2');
  const body = parseJointPrepare(value.inputs.request); jointCheck(body.expected_epoch_id === value.epoch_id);
  jointCheck(object(value.inputs.joint) && object(value.inputs.joint.original_actual_input) && object(value.inputs.joint.original_actual_input.base));
  const actual = value.inputs.joint.original_actual_input, base = actual.base; jointCheck(object(base) && base.user_id === value.user_id && base.epoch_id === value.epoch_id && base.as_of === value.prepared_at && Array.isArray(actual.dynamic_goals));
  jointCheck(value.plan_id === await releaseUUID5('514aaf21-d405-5f9c-8706-de1684e812e4', await spendingHash({ user: value.user_id, request: body })));
  const scope = value.inputs.scope; jointCheck(object(scope) && scope.policy_id === body.full_policy_id && scope.epoch_id === value.epoch_id && scope.template_name === 'GoalAllocationPolicy' && object(scope.current_version) && scope.current_version.version_id === body.expected_full_policy_version_id);
  const input = value.allocation_input, result = value.allocation;
  jointCheck(object(input) && input.schema_version === 'multi-goal-current-period-v1' && input.user_id === value.user_id && input.as_of === value.prepared_at && Array.isArray(input.goals) && input.goals.length >= 2 && input.goals.length <= 8 && Array.isArray(input.hard_protection_points) && input.hard_protection_points.length === 1098 && Array.isArray(input.income_lots) && object(result) && result.status === 'OPTIMAL' && result.purpose === 'CURRENT_PERIOD_PLANNING_ONLY' && result.grants_authority === false && result.input_hash === await spendingHash(input) && Array.isArray(result.goals) && result.goals.length === input.goals.length && Array.isArray(result.income_uses));
  const inputGoals = input.goals, resultGoals = result.goals; jointCheck(ids(inputGoals.map((row) => object(row) ? row.goal_id : null)) && ids(resultGoals.map((row) => object(row) ? row.goal_id : null)) && inputGoals.every((row) => object(row) && resultGoals.some((entry) => object(entry) && entry.goal_id === row.goal_id && entry.effective_policy_version_id === row.effective_policy_version_id && cents(entry.amount_cents))));
  jointCheck(['UTC', 'Asia/Shanghai'].includes(String(input.timezone)));
  const localFirst = new Date(Date.parse(value.prepared_at) + (input.timezone === 'Asia/Shanghai' ? 28800000 : 0)).toISOString().slice(0, 10);
  for (const [index, point] of input.hard_protection_points.entries()) { jointCheck(object(point) && exact(point, ['date', 'cash_cents', 'obligation_floor_cents', 'living_floor_cents', 'emergency_floor_cents', 'owned_goal_cash_cents', 'other_protection_floor_cents', 'source_refs']) && point.date === new Date(Date.parse(localFirst) + Math.floor(index / 3) * 86400000).toISOString().slice(0, 10) && Number.isSafeInteger(point.cash_cents) && ['obligation_floor_cents', 'living_floor_cents', 'emergency_floor_cents', 'owned_goal_cash_cents', 'other_protection_floor_cents'].every((field) => cents(point[field])) && Array.isArray(point.source_refs) && point.source_refs.length > 0 && point.source_refs.every((ref) => object(ref) && ref.user_id === value.user_id && uuid(ref.evidence_id) && digest(ref.content_hash))); }
  jointCheck(Array.isArray(value.children) && value.children.length >= 1 && value.children.length <= 8 && ids(value.children.map((row) => object(row) ? row.goal_id : null)) && ids(value.children.map((row) => object(row) ? row.action_id : null)));
  const positives = result.goals.filter((row) => object(row) && cents(row.amount_cents) && row.amount_cents > 0); jointCheck(positives.length === value.children.length);
  let total = 0n;
  for (const [index, child] of value.children.entries()) {
    jointCheck(object(child) && exact(child, ['child_number', 'goal_id', 'action_id', 'bank_idempotency_key', 'command', 'original_model_evidence_id', 'original_model_evidence_hash', 'range_proof_hash']) && child.child_number === index + 1 && uuid(child.goal_id) && uuid(child.action_id) && uuid(child.original_model_evidence_id) && digest(child.original_model_evidence_hash) && digest(child.range_proof_hash) && child.action_id === await releaseUUID5(value.plan_id, `child:${index + 1}`) && child.bank_idempotency_key === `joint-goal:${value.plan_id}:${index + 1}` && object(child.command) && exact(child.command, ['effect', 'effect_hash']) && digest(child.command.effect_hash));
    const effect = child.command.effect, goal = inputGoals.find((row) => object(row) && row.goal_id === child.goal_id), allocation = positives.find((row) => object(row) && row.goal_id === child.goal_id);
    const source = actual.dynamic_goals.find((row) => object(row) && object(row.data) && object(row.data.request) && row.data.request.goal_id === child.goal_id); jointCheck(object(source) && object(source.data) && source.data.model_evidence_id === child.original_model_evidence_id && source.data.model_evidence_hash === child.original_model_evidence_hash);
    jointCheck(object(effect) && object(goal) && object(allocation) && effect.action_type === 'ALLOCATE_GOAL' && effect.operation_id === child.action_id && effect.user_id === value.user_id && effect.goal_id === child.goal_id && effect.policy_id === goal.policy_id && effect.policy_version_id === goal.effective_policy_version_id && effect.destination_account_id === goal.account_id && effect.amount_cents === allocation.amount_cents && effect.valid_from === value.prepared_at && effect.expires_at === value.expires_at && cents(effect.amount_cents));
    jointCheck(effect.simulation === true && effect.fee_cents === 0 && effect.loss_cents === 0 && effect.net_cents === null && effect.quote_id === null && effect.liability === null && effect.settlement_delay_days === 0 && effect.latest_arrival_at === null && Array.isArray(effect.cash_uses) && effect.cash_uses.length > 0 && Array.isArray(effect.income_uses) && effect.income_uses.length > 0 && ids(effect.policy_version_ids) && jointCanonical(effect.policy_version_ids) === jointCanonical([goal.effective_policy_version_id]));
    for (const field of ['payee_id', 'payee_evidence_id', 'product_id', 'product_version_number', 'terms_digest', 'position_id', 'position_account_id', 'return_account_id', 'purchase_exit', 'original_policy_version_id']) jointCheck(effect[field] === null);
    let cash = 0n, income = 0n; const accounts = new Set<string>(), locations = new Set<string>();
    for (const use of effect.cash_uses) { jointCheck(object(use) && exact(use, ['account_id', 'amount_cents']) && uuid(use.account_id) && cents(use.amount_cents) && use.amount_cents > 0 && !accounts.has(use.account_id)); accounts.add(use.account_id); cash += BigInt(use.amount_cents); }
    for (const use of effect.income_uses) { jointCheck(object(use) && exact(use, ['fragment_id', 'origin_transaction_id', 'account_id', 'amount_cents']) && uuid(use.fragment_id) && uuid(use.origin_transaction_id) && uuid(use.account_id) && cents(use.amount_cents) && use.amount_cents > 0 && accounts.has(use.account_id)); const location = `${use.origin_transaction_id}:${use.account_id}`; jointCheck(!locations.has(location)); locations.add(location); income += BigInt(use.amount_cents); }
    jointCheck(cash === BigInt(effect.amount_cents) && income === cash);
    jointCheck(child.command.effect_hash === await spendingHash({ ...effect, cash_uses: [...effect.cash_uses].sort((a, b) => String(a.account_id).localeCompare(String(b.account_id))), income_uses: [...effect.income_uses].sort((a, b) => `${a.origin_transaction_id}:${a.account_id}`.localeCompare(`${b.origin_transaction_id}:${b.account_id}`)), policy_version_ids: [...effect.policy_version_ids].sort() }));
    total += BigInt(effect.amount_cents);
  }
  jointCheck(total === BigInt(value.total_allocation_cents)); assertMoneyFields(value);
  jointCanonical(value); return value as JointPlan;
}
export async function parseJointPreview(value: unknown, body: JointPrepare, user?: string, raw?: string): Promise<JointPreview> {
  parseJointPrepare(body); jointCheck(object(value) && exact(value, ['simulation', 'bank_authority', 'grants_authority', 'preview_only', 'user_id', 'epoch_id', 'as_of', 'request', 'status', 'registered_goal_ids', 'unresolved_original_action_ids', 'plan', 'input_hash', 'reasons', 'limitations']) && value.simulation === true && value.bank_authority === false && value.grants_authority === false && value.preview_only === true && uuid(value.user_id) && (!user || value.user_id === user) && value.epoch_id === body.expected_epoch_id && time(value.as_of) && spendingCanonicalJson(value.request) === spendingCanonicalJson(body) && ['READY_TO_REVIEW', 'BLOCKED', 'UNKNOWN'].includes(String(value.status)) && ids(value.registered_goal_ids) && ids(value.unresolved_original_action_ids) && digest(value.input_hash) && strings(value.reasons) && strings(value.limitations));
  if (value.status === 'READY_TO_REVIEW') { const plan = await parseJointPlan(value.plan, value.user_id); jointCheck(plan.prepared_at === value.as_of && spendingCanonicalJson(plan.inputs.request) === spendingCanonicalJson(body) && value.reasons.length === 0 && value.unresolved_original_action_ids.length === 0 && jointCanonical([...value.registered_goal_ids].sort()) === jointCanonical(jointAllocationInput(plan).goals.map((row) => row.goal_id).sort())); }
  else jointCheck(value.plan === null && value.reasons.length > 0); return save(value as JointPreview, raw);
}
export async function parseJointResponse(value: unknown, user?: string, expected?: JointReviewBinding | null, raw?: string): Promise<JointResponse> {
  jointCheck(object(value) && exact(value, ['simulation', 'bank_authority', 'current_authority_assessed', 'receipt_is_current_authority', 'economic_experiment_verified', 'funds_reserved', 'reservation_scope', 'user_id', 'epoch_id', 'as_of', 'original_plan', 'original_request_hash', 'original_consent', 'children', 'state']) && value.simulation === true && value.bank_authority === false && value.current_authority_assessed === false && value.receipt_is_current_authority === false && value.economic_experiment_verified === false && value.funds_reserved === false && value.reservation_scope === 'WHOLE_UNRESERVED_CHILDREN_USE_ORIGINAL_CLAIMS' && time(value.as_of) && ['PARTIALLY_PREPARED', 'PREPARED_UNRESERVED', 'CONFIRMED_UNRESERVED', 'PARTIALLY_SETTLED', 'UNRESOLVED', 'ORIGINAL_SERVICE_RECEIPTS_VERIFIED', 'STOPPED', 'RETAINED_HISTORY'].includes(String(value.state)));
  const plan = await parseJointPlan(value.original_plan, user); jointCheck(value.user_id === plan.user_id && value.epoch_id === plan.epoch_id && value.original_request_hash === await spendingHash(plan.inputs.request) && (!expected || jointCanonical(expected) === jointCanonical(jointReviewBinding(plan))) && Array.isArray(value.children) && value.children.length === plan.children.length);
  for (const [index, row] of value.children.entries()) {
    const child = plan.children[index]!; jointCheck(object(row) && exact(row, ['child_number', 'action_id', 'bank_idempotency_key', 'state', 'original_action', 'original_request_hash']) && row.child_number === child.child_number && row.action_id === child.action_id && row.bank_idempotency_key === child.bank_idempotency_key && ['MISSING', 'PLANNED_UNRESERVED', 'AUTHORIZED', 'SUBMITTED', 'UNKNOWN', 'ORIGINAL_RECEIPT_VERIFIED', 'STOPPED'].includes(String(row.state)));
    if (row.original_action === null) { jointCheck(row.state === 'MISSING' && row.original_request_hash === null); continue; }
    jointCheck(digest(row.original_request_hash) && object(row.original_action) && jointCanonical(row.original_action.effect) === jointCanonical(child.command.effect) && row.original_action.effect_hash === child.command.effect_hash && row.original_action.autonomy_level === 'ASK_ONCE');
    await parseDynamicAction(row.original_action, { goal_id: child.goal_id, expected_policy_version_id: child.command.effect.policy_version_id!, expected_model_evidence_id: child.original_model_evidence_id, expected_model_evidence_hash: child.original_model_evidence_hash, expected_epoch_id: plan.epoch_id, idempotency_key: plan.inputs.request.idempotency_key }, plan.user_id);
    const a = row.original_action; const settled = ['SUCCEEDED', 'RECONCILED'].includes(String(a.status)) && a.bank_status === 'SETTLED' && a.receipt !== null;
    jointCheck((row.state === 'ORIGINAL_RECEIPT_VERIFIED') === settled);
    if (row.state === 'PLANNED_UNRESERVED') jointCheck(a.status === 'PLANNED' && a.bank_status === null);
    if (row.state === 'AUTHORIZED') jointCheck(a.status === 'AUTHORIZED' && a.bank_status === null);
    if (row.state === 'SUBMITTED') jointCheck(a.status === 'SUBMITTED' && a.bank_status === null);
    if (row.state === 'UNKNOWN') jointCheck(!settled && (a.status === 'UNKNOWN' || a.status === 'SUBMITTED' || a.bank_status !== null));
  }
  if (value.original_consent !== null) {
    const c = value.original_consent; jointCheck(object(c) && exact(c, ['consent_id', 'user_id', 'plan_id', 'epoch_id', 'original_request', 'request_hash', 'original_evidence', 'evidence_id', 'evidence_hash', 'current_evidence_verified', 'current_evidence_status', 'receipt_is_current_authority']) && uuid(c.consent_id) && c.user_id === plan.user_id && c.plan_id === plan.plan_id && c.epoch_id === plan.epoch_id && uuid(c.evidence_id) && digest(c.evidence_hash) && c.receipt_is_current_authority === false && typeof c.current_evidence_verified === 'boolean' && ['CURRENT_EVIDENCE_MATCHED', 'RETAINED_ORIGINAL_CURRENT_EVIDENCE_MISSING'].includes(String(c.current_evidence_status)) && c.current_evidence_verified === (c.current_evidence_status === 'CURRENT_EVIDENCE_MATCHED'));
    const body = parseJointConfirm(c.original_request); jointCheck(body.expected_epoch_id === plan.epoch_id && body.reviewed_plan_hash === plan.plan_hash && c.request_hash === await spendingHash(body) && object(c.original_evidence));
    const evidence = c.original_evidence, content = evidence.content; jointCheck(evidence.id === c.evidence_id && evidence.user_id === plan.user_id && evidence.source_type === 'USER_JOINT_GOAL_CONFIRMATION' && evidence.source_ref === plan.plan_id && evidence.evidence_level === 'USER_CONFIRMED_ACTION' && evidence.content_hash === c.evidence_hash && object(content) && content.protocol === 'joint-goal-whole-consent-v2' && content.simulation === true && content.user_id === plan.user_id && content.plan_id === plan.plan_id && content.epoch_id === plan.epoch_id && content.plan_hash === plan.plan_hash && content.accepted === true && spendingCanonicalJson(content.original_request) === spendingCanonicalJson(body) && content.request_hash === c.request_hash && time(content.confirmed_at) && time(content.valid_until) && Date.parse(content.confirmed_at) >= Date.parse(plan.prepared_at) && Date.parse(content.confirmed_at) < Date.parse(plan.expires_at) && Date.parse(content.valid_until) === Date.parse(plan.expires_at) && content.actor_role === 'USER' && content.authentication_source === 'LOCAL_SIGNED_SESSION' && content.human_identity_verified === false && object(content.actor));
    const principal = parseLocalActorSession({ simulation: true, principal: content.actor, bank_authority: false, confirms_financial_action: false }).principal; jointCheck(principal && principal.user_id === plan.user_id && principal.role === 'USER' && principal.session_id === content.actor_session_id && Date.parse(principal.issued_at) <= Date.parse(content.confirmed_at) && Date.parse(principal.expires_at) > Date.parse(content.confirmed_at) && c.evidence_hash === await spendingHash(content));
  }
  const states = value.children.map((row) => row.state);
  if (value.state !== 'RETAINED_HISTORY') { const expectedState = states.some((s) => ['UNKNOWN', 'SUBMITTED'].includes(s)) ? 'UNRESOLVED' : states.includes('STOPPED') ? 'STOPPED' : states.includes('MISSING') ? 'PARTIALLY_PREPARED' : states.every((s) => s === 'ORIGINAL_RECEIPT_VERIFIED') ? 'ORIGINAL_SERVICE_RECEIPTS_VERIFIED' : states.includes('ORIGINAL_RECEIPT_VERIFIED') ? 'PARTIALLY_SETTLED' : object(value.original_consent) && value.original_consent.current_evidence_verified ? 'CONFIRMED_UNRESERVED' : 'PREPARED_UNRESERVED'; jointCheck(value.state === expectedState); }
  assertMoneyFields(value); return save(value as JointResponse, raw);
}
export async function parseJointIntent(value: unknown): Promise<JointIntent> {
  jointCheck(object(value) && exact(value, ['protocol', 'kind', 'user_id', 'plan_id', 'path', 'body', 'body_json', 'request_hash', 'reviewed_plan']) && value.protocol === 'joint-goal-browser-command-v2' && ['PREPARE', 'CONFIRM', 'EXECUTE'].includes(String(value.kind)) && uuid(value.user_id) && typeof value.body_json === 'string' && value.body_json === JSON.stringify(value.body) && digest(value.request_hash) && value.request_hash === await spendingHash(value.body));
  if (value.kind === 'PREPARE') { parseJointPrepare(value.body); jointCheck(value.path === '/joint-goal-actions/prepare' && value.plan_id === null && value.reviewed_plan === null); }
  else { const body = value.kind === 'CONFIRM' ? parseJointConfirm(value.body) : parseJointExecute(value.body), plan = await parseJointBinding(value.reviewed_plan); jointCheck(plan.user_id === value.user_id && value.plan_id === plan.plan_id && body.expected_epoch_id === plan.epoch_id && body.reviewed_plan_hash === plan.plan_hash && value.path === `/joint-goal-actions/${plan.plan_id}/${value.kind === 'CONFIRM' ? 'confirm' : 'execute-child'}`); if (value.kind === 'EXECUTE') { const execute = parseJointExecute(body), child = plan.children[execute.expected_child_number - 1]; jointCheck(child?.action_id === execute.expected_action_id); } }
  return value as JointIntent;
}
export async function parseJointLookup(value: unknown, intent: JointIntent, raw?: string): Promise<JointLookup> {
  await parseJointIntent(intent); jointCheck(intent.kind !== 'EXECUTE' && 'idempotency_key' in intent.body && object(value) && exact(value, ['simulation', 'user_id', 'idempotency_key', 'status', 'command_kind', 'original_request', 'original_request_hash', 'original', 'not_found_is_final', 'bank_authority']) && value.simulation === true && value.bank_authority === false && value.not_found_is_final === false && value.user_id === intent.user_id && value.idempotency_key === intent.body.idempotency_key && ['RECORDED', 'NOT_FOUND_NOT_FINAL'].includes(String(value.status)));
  if (value.status === 'NOT_FOUND_NOT_FINAL') jointCheck(value.command_kind === null && value.original_request === null && value.original_request_hash === null && value.original === null);
  else { jointCheck(value.command_kind === intent.kind && spendingCanonicalJson(value.original_request) === spendingCanonicalJson(intent.body) && value.original_request_hash === intent.request_hash && value.original_request_hash === await spendingHash(value.original_request)); const response = await parseJointResponse(value.original, intent.user_id, intent.reviewed_plan, raw); jointCheck(response.epoch_id === intent.body.expected_epoch_id); if (intent.kind === 'PREPARE') jointCheck(spendingCanonicalJson(response.original_plan.inputs.request) === spendingCanonicalJson(intent.body)); else jointCheck(response.original_consent !== null && spendingCanonicalJson(response.original_consent.original_request) === spendingCanonicalJson(intent.body) && response.original_consent.request_hash === intent.request_hash); }
  return save(value as JointLookup, raw);
}
const transport = (path: string, method = 'GET', body?: unknown) => request<{ simulation: true; value: unknown; raw: string }>(path, method, body, (value, raw) => ({ simulation: true, value, raw }));
export async function previewJointExecution(body: JointPrepare, user?: string): Promise<JointPreview> { parseJointPrepare(body); const r = await transport('/joint-goal-actions/preview', 'POST', body); return parseJointPreview(r.value, body, user, r.raw); }
export async function getJointExecution(id: string, user?: string, plan?: JointReviewBinding | null): Promise<JointResponse> { jointCheck(uuid(id)); const r = await transport(`/joint-goal-actions/${id}`); const result = await parseJointResponse(r.value, user, plan, r.raw); jointCheck(result.original_plan.plan_id === id); freshReads.add(result); return result; }
export async function lookupJointExecution(intent: JointIntent): Promise<JointLookup> { await parseJointIntent(intent); jointCheck(intent.kind !== 'EXECUTE' && 'idempotency_key' in intent.body); const r = await transport(`/joint-goal-actions/by-key/${encodeURIComponent(intent.body.idempotency_key)}`); const result = await parseJointLookup(r.value, intent, r.raw); freshReads.add(result); if (result.original) freshReads.add(result.original); return result; }
export async function postJointExecution(intent: JointIntent): Promise<JointResponse> {
  await parseJointIntent(intent); const session = await readLocalActorSession(), actor = session.principal; jointCheck(actor && actor.role === 'USER' && actor.user_id === intent.user_id && actor.authenticated === true && actor.authentication_source === 'LOCAL_SIGNED_SESSION');
  const r = await transport(intent.path, 'POST', intent.body), result = await parseJointResponse(r.value, intent.user_id, intent.reviewed_plan, r.raw);
  if (intent.kind === 'PREPARE') jointCheck(spendingCanonicalJson(result.original_plan.inputs.request) === spendingCanonicalJson(intent.body));
  if (intent.kind === 'CONFIRM') jointCheck(result.original_consent && spendingCanonicalJson(result.original_consent.original_request) === spendingCanonicalJson(intent.body) && result.original_consent.request_hash === intent.request_hash);
  return result;
}
