import { afterEach, describe, expect, it, vi } from 'vitest';
import { adjustmentGoals, adjustmentOwner, adjustmentPreview, adjustmentRead, adjustmentSelection } from '../tests/goal-adjustment-fixture';
import { getGoalAdjustmentOriginals, getOriginalGoalAdjustment, parseGoalAdjustmentPreview, parseGoalAdjustmentRead, parseGoalAdjustmentSelection, previewGoalAdjustments } from './goal-adjustments';

afterEach(() => vi.unstubAllGlobals());
describe('explicit synthetic goal-adjustment contract', () => {
  it('retains original witness maps and rejects fractional or string cents within them', () => { const value = adjustmentRead(); const witness = value.original_conflicts.explanation!.conflict.deletion_checks[0]!.witness_amounts_cents; const key = Object.keys(witness)[0]!; for (const amount of ['1', 1.5, Number.MAX_SAFE_INTEGER + 1]) { const bad = adjustmentRead(); bad.original_conflicts.explanation!.conflict.deletion_checks[0]!.witness_amounts_cents[key] = amount as never; expect(() => parseGoalAdjustmentRead(bad, adjustmentOwner, adjustmentGoals())).toThrow(); } });
  it('keeps original JSON and exact owner/versions while exposing no financial permission', () => { const read = adjustmentRead(); const raw = JSON.stringify(read); const parsed = parseGoalAdjustmentRead(read, adjustmentOwner, adjustmentGoals(), raw); expect(getOriginalGoalAdjustment(parsed)).toBe(raw); const preview = parseGoalAdjustmentPreview(adjustmentPreview(), adjustmentSelection(), adjustmentOwner, adjustmentGoals()); expect(preview.state).toBe('PROPOSAL'); expect(preview.proposal!.original_allow_deferral_unchanged).toBe(true); expect(preview.grants_authority).toBe(false); });
  it.each(['owner', 'version', 'denominator', 'model', 'guarantee', 'unsafe-money', 'authority'])('rejects read corruption %s', (kind) => { const value = adjustmentRead(); if (kind === 'owner') value.user_id = '00000000-0000-0000-0000-000000000999'; if (kind === 'version') value.goals[0]!.current_version_id = '00000000-0000-0000-0000-000000000999'; if (kind === 'denominator') value.goals = []; if (kind === 'model') value.goals[0]!.original_model.bank_authority = true as never; if (kind === 'guarantee') value.goals[0]!.minimum_guarantee_cents += 1; if (kind === 'unsafe-money') value.goals[0]!.current_owned_cents = Number.MAX_SAFE_INTEGER + 1; if (kind === 'authority') value.grants_authority = true as never; expect(() => parseGoalAdjustmentRead(value, adjustmentOwner, adjustmentGoals())).toThrow(); });
  it.each(['grant', 'selection', 'baseline-hash', 'proposal-count', 'unknown-minimality', 'unaffected', 'bank-cap', 'deferral', 'other-goal', 'full-hash', 'confirm-body'])('rejects conditional candidate corruption %s', (kind) => { const value = adjustmentPreview(); const plan = value.proposal!; if (kind === 'grant') plan.identity_refs_are_financial_permissions = true as never; if (kind === 'selection') plan.actual_selection.adjustments[0]!.expected_version_id = '00000000-0000-0000-0000-000000000999'; if (kind === 'baseline-hash') plan.original_baseline_repair.original_input_hash = '0'.repeat(64); if (kind === 'proposal-count') plan.hard_repair.changed_policy_count = 0; if (kind === 'unknown-minimality') plan.hard_repair.hypothetical_allocation!.status = 'UNKNOWN'; if (kind === 'unaffected') plan.hard_repair.unaffected_goal_ids.push(plan.hard_repair.candidates[0]!.goal_id); if (kind === 'bank-cap') plan.hard_repair.candidates[0]!.monthly_max_cents = 999; if (kind === 'deferral') value.version_previews[0]!.actual_existing_preview.full_configuration.allow_deferral = true; if (kind === 'other-goal') value.version_previews[0]!.goal_id = '00000000-0000-0000-0000-000000000999'; if (kind === 'full-hash') value.version_previews[0]!.confirmation_bindings.reviewed_full_hash = '0'.repeat(64); if (kind === 'confirm-body') Object.assign(value.version_previews[0]!.confirmation_bindings, { accepted: true }); expect(() => parseGoalAdjustmentPreview(value, adjustmentSelection(), adjustmentOwner, adjustmentGoals())).toThrow(); });
  it('only accepts selected finite range fields and strict integer soft minima', () => { const original = adjustmentRead(); const selection = adjustmentSelection(); expect(parseGoalAdjustmentSelection(selection, original)).toEqual(selection); const minimum = { ...selection, adjustments: [{ field: 'monthly_min_cents', goal_id: original.goals[0]!.goal_id, expected_version_id: original.goals[0]!.current_version_id, lower_cents: 0, upper_cents: 0 }] }; expect(parseGoalAdjustmentSelection(minimum, original).adjustments[0]!.field).toBe('monthly_min_cents'); for (const change of [{ upper_cents: 2 }, { lower_cents: true }, { lower_cents: '0' }, { bank_authority: true }]) expect(() => parseGoalAdjustmentSelection({ ...minimum, adjustments: [{ ...minimum.adjustments[0]!, ...change }] }, original)).toThrow(); expect(() => parseGoalAdjustmentSelection({ ...selection, adjustments: selection.adjustments.concat(selection.adjustments) }, original)).toThrow(); });
  it('calls the exact read and read-only preview endpoints with no auto confirmation', async () => { const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(adjustmentRead()), { status: 200 })).mockResolvedValueOnce(new Response(JSON.stringify(adjustmentPreview()), { status: 200 })); vi.stubGlobal('fetch', fetch); const read = await getGoalAdjustmentOriginals(adjustmentOwner, adjustmentGoals()); await previewGoalAdjustments(adjustmentSelection(), read, adjustmentGoals()); expect(fetch.mock.calls[0]![0]!).toBe('/api/v1/planning/full-goal-adjustments'); expect(fetch.mock.calls[0]![1]!.method).toBe('GET'); expect(fetch.mock.calls[1]![0]!).toBe('/api/v1/planning/full-goal-adjustments/preview'); expect(JSON.parse(fetch.mock.calls[1]![1]!.body)).toEqual(adjustmentSelection()); expect(fetch).toHaveBeenCalledTimes(2); });
});
