import { afterEach, expect, test, vi } from 'vitest';
import { findOnboardingCompilation, getOnboardingContext, getOnboardingTransactions, onboardingAssetConfiguration, onboardingObligationConfiguration, parseOnboardingCompilation, parseOnboardingDeclaration, parseOnboardingDeclarationLookup, parseOnboardingDiscovery, parseOnboardingReserve, parseOnboardingTransactions, readOnboardingDeclaration, reserveParameters, serverCalendarDate, submitOnboardingIntent } from './onboarding';
import { emptyOnboardingDraft, prepareOnboardingDeclaration, prepareOnboardingIntent } from '../features/onboarding-draft';
import { compilationFixture, declarationFixture, discoveryFixture, emergencyText, onboardingBinding, proposalFixtures, reserveFixture, transactionFixture } from '../tests/onboarding-fixture';
import { dashboardFixture } from '../tests/dashboard-fixture';
import { stateFixture } from '../tests/demo-fixture';
afterEach(() => { vi.unstubAllGlobals(); vi.unstubAllEnvs(); });
test('UTC/上海日期来自server as_of；账号user不一致拒绝合并currentcontext', async () => {
  expect(serverCalendarDate('2026-10-04T18:00:00Z', 'Asia/Shanghai')).toBe('2026-10-05'); expect(serverCalendarDate('2026-10-04T18:00:00Z', 'UTC')).toBe('2026-10-04'); vi.stubEnv('VITE_API_BASE_URL', 'http://unit-onboarding-api.local');
  vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL) => new Response(JSON.stringify(String(input).endsWith('/dashboard') ? dashboardFixture() : String(input).endsWith('/demo/state') ? stateFixture() : { ...dashboardFixture().account_facts.facts, user_id: '74000000-0000-4000-8000-000000000001' })))); await expect(getOnboardingContext()).rejects.toThrow();
});
test('交易保total/offset分母、unsafe钱/重复row/错页拒绝，真实原GET分页', async () => {
  expect(parseOnboardingTransactions(transactionFixture(), 0).total).toBe(61); const bad = transactionFixture(); bad.items[1]!.id = bad.items[0]!.id; expect(() => parseOnboardingTransactions(bad, 0)).toThrow(); expect(() => parseOnboardingTransactions(transactionFixture(50), 0)).toThrow(); const unsafe = transactionFixture(); unsafe.items[0]!.amount_cents = Number.MAX_SAFE_INTEGER + 1; expect(() => parseOnboardingTransactions(unsafe, 0)).toThrow();
  vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(transactionFixture(50))))); expect((await getOnboardingTransactions(50)).items).toHaveLength(11); expect(String(vi.mocked(fetch).mock.calls[0]![0])).toContain('limit=50&offset=50');
});
test('生活估算完整56日/43窗口原分母，INSUFFICIENT不补0；错误参数/候选/分母拒绝', () => {
  const params = reserveParameters(emptyOnboardingDraft().inputs); expect(parseOnboardingReserve(reserveFixture(false), onboardingBinding(), params).estimation.recommended_reserve_cents).toBeNull(); expect(parseOnboardingReserve(reserveFixture(true), onboardingBinding(), params).estimation.window_count).toBe(43);
  const missing = reserveFixture(true); missing.estimation.daily_amounts.pop(); expect(() => parseOnboardingReserve(missing, onboardingBinding(), params)).toThrow(); const zero = reserveFixture(false); zero.estimation.recommended_reserve_cents = 0; expect(() => parseOnboardingReserve(zero, onboardingBinding(), params)).toThrow(); expect(() => reserveParameters({ ...emptyOnboardingDraft().inputs, extra_buffer_yuan: '1e3' })).toThrow(); expect(() => reserveParameters({ ...emptyOnboardingDraft().inputs, horizon_days: '57' })).toThrow();
});
test('编译原user/日期/固定rules版本/双候选字段匹配，未知配置与权限不推断', () => {
  expect(parseOnboardingCompilation(compilationFixture(), onboardingBinding()).proposal_status).toBe('PROPOSED'); expect(parseOnboardingCompilation(compilationFixture(false, true), onboardingBinding()).configuration_hash).toBeNull(); expect(() => parseOnboardingCompilation({ ...compilationFixture(), user_id: 'other' }, onboardingBinding())).toThrow(); const bad = compilationFixture(); bad.compilation.reference_date = '2026-10-05'; expect(() => parseOnboardingCompilation(bad, onboardingBinding())).toThrow();
});
test('发现仅原服务实际返回ID，created/reused重叠或错user不报成功', () => {
  expect(parseOnboardingDiscovery(discoveryFixture(), onboardingBinding()).created_proposal_ids).toHaveLength(1); expect(() => parseOnboardingDiscovery({ ...discoveryFixture(), reused_proposal_ids: discoveryFixture().created_proposal_ids }, onboardingBinding())).toThrow(); expect(() => parseOnboardingDiscovery({ ...discoveryFixture(), user_id: 'someone' }, onboardingBinding())).toThrow();
});
test('丢响应恢复只原GET；唯一原text/日期/编译/提案匹配，跨日/多同文/空不能放行', async () => {
  const intent = prepareOnboardingIntent('EMERGENCY', onboardingBinding(), emergencyText); vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(compilationFixture())))); expect((await findOnboardingCompilation(intent, onboardingBinding(), proposalFixtures())).input_text).toBe(emergencyText); expect(vi.mocked(fetch).mock.calls.every((call) => call[1]?.method === 'GET')).toBe(true);
  await expect(findOnboardingCompilation(intent, { ...onboardingBinding(), reference_date: '2026-10-05' }, proposalFixtures())).rejects.toThrow(); await expect(findOnboardingCompilation(intent, onboardingBinding(), [])).rejects.toThrow(); await expect(findOnboardingCompilation(intent, onboardingBinding(), [...proposalFixtures(), proposalFixtures()[1]!])).rejects.toThrow();
});
test('仅显式提交原body的compile/discover各一次，未附clientclock/user/confirm/grant', async () => {
  vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL) => new Response(JSON.stringify(String(input).endsWith('/discover') ? discoveryFixture() : compilationFixture())))); await submitOnboardingIntent(prepareOnboardingIntent('EMERGENCY', onboardingBinding(), emergencyText)); await submitOnboardingIntent(prepareOnboardingIntent('DISCOVERY', onboardingBinding())); const calls = vi.mocked(fetch).mock.calls; expect(calls).toHaveLength(2); expect(calls[0]![1]!.body).toBe(JSON.stringify({ text: emergencyText, engine: 'rules' })); expect(calls[1]![1]!.body).toBe('{}'); expect(calls.every((call) => !String(call[0]).includes('/confirm'))).toBe(true);
});
test('义务新候选只改明确期限/importance，完整原金额/payee/auto_execute/priority原件保持', () => {
  const source = proposalFixtures()[0]!; const before = structuredClone(source); const inputs = { ...emptyOnboardingDraft().inputs, valid_from: '2026-10-05', valid_until: '2027-10-04', importance: '78' }; const result = onboardingObligationConfiguration(source, inputs); expect(result.priority).toEqual({ ...source.configuration.priority as object, importance: 78 }); expect(result.amount_rule).toEqual(source.configuration.amount_rule); expect(result.payee_id).toBe(source.configuration.payee_id); expect(result.auto_execute).toBe(source.configuration.auto_execute); expect(source).toEqual(before); expect(() => onboardingObligationConfiguration(source, { ...inputs, valid_from: '2026-02-30' })).toThrow(); expect(() => onboardingObligationConfiguration(source, { ...inputs, importance: '101' })).toThrow(); expect(() => onboardingObligationConfiguration(source, { ...inputs, valid_until: '2026-10-01' })).toThrow();
});
test('资产候选保scope/caps/duration/risk/recovery，goal要求真实ID、不默认宽权', () => {
  const inputs = { ...emptyOnboardingDraft().inputs, total_cap_yuan: '1500.03', single_cap_yuan: '670.03' }; const result = onboardingAssetConfiguration(inputs); expect(result).toMatchObject({ type: 'asset_authorization', scope: 'general_idle_funds', goal_id: null, allowed_asset_classes: ['CASH_MGMT_T0'], max_auto_managed_cents: 150003, single_action_cap_cents: 67003, allow_auto_recovery_without_penalty: false, allow_early_withdrawal_with_penalty: false, max_lock_days: 0 });
  for (const changed of [{ asset_scope: 'goal', asset_goal_id: '' }, { single_cap_yuan: '1501' }, { principal_risk: '6' }, { asset_classes: '' }, { asset_classes: 'UNKNOWN_PRODUCT' }, { asset_valid_from: '2026-02-30' }]) expect(() => onboardingAssetConfiguration({ ...inputs, ...changed })).toThrow();
});
test.each(['wrong_body', 'wrong_epoch', 'bad_hash', 'authority', 'claim_receipt', 'invalid_id'])('原声明lookup拒绝 %s，NOT_FOUND无record且不声称最终拒绝', (caseName) => {
  const intent = prepareOnboardingDeclaration('OBLIGATION', onboardingBinding(), proposalFixtures()[0]!.configuration); const record = declarationFixture(intent);
  if (caseName === 'wrong_body') record.original_request = { ...record.original_request, idempotency_key: 'another-key' }; if (caseName === 'wrong_epoch') record.epoch_id = '75000000-0000-4000-8000-000000000003'; if (caseName === 'bad_hash') record.request_hash = 'PASS'; if (caseName === 'authority') (record as unknown as Record<string, unknown>).grants_authority = true; if (caseName === 'claim_receipt') (record as unknown as Record<string, unknown>).receipt_is_current_authority = true; if (caseName === 'invalid_id') record.evidence_id = 'missing';
  expect(() => parseOnboardingDeclaration(record, intent)).toThrow(); const notFound = { simulation: true, grants_authority: false, status: 'NOT_FOUND', not_found_is_final: false, record: null }; expect(parseOnboardingDeclarationLookup(notFound, intent).record).toBeNull(); expect(() => parseOnboardingDeclarationLookup({ ...notFound, not_found_is_final: true }, intent)).toThrow();
});
test('真实声明POST/原keyGET精确body与epoch，含冒号键编码，无confirm/金融请求', async () => {
  const intent = prepareOnboardingDeclaration('OBLIGATION', onboardingBinding(), proposalFixtures()[0]!.configuration, proposalFixtures()[0]!.id); const record = declarationFixture(intent); vi.stubGlobal('fetch', vi.fn(async (_input: RequestInfo | URL, init?: RequestInit) => new Response(JSON.stringify(init?.method === 'POST' ? record : { simulation: true, grants_authority: false, status: 'RECORDED', not_found_is_final: false, record })))); await submitOnboardingIntent(intent); await readOnboardingDeclaration(intent); const calls = vi.mocked(fetch).mock.calls; expect(calls).toHaveLength(2); expect(calls[0]![1]!.body).toBe(intent.body_json); expect(String(calls[1]![0])).toContain(`/policy-declarations/${intent.binding.epoch_id}/by-key/${encodeURIComponent(JSON.parse(intent.body_json).idempotency_key)}`); expect(calls[1]![1]!.method).toBe('GET'); expect(calls.every((call) => !String(call[0]).includes('/confirm') && !String(call[0]).includes('/execute'))).toBe(true);
});
