import { afterEach, expect, test, vi } from 'vitest';
import { webcrypto } from 'node:crypto';
import { getOriginalQuestionResponse, getQuestionSession, lookupQuestionCommand, parseQuestionBody, parseQuestionLookup, parseQuestionResponse, parseQuestionVariables, postQuestionCommand } from './question-workflow';
import { questionIntentFixture, questionLookupFixture, questionResponseFixture, questionSession, questionVariables } from '../tests/question-fixture';
import { installHttpFixture } from '../tests/policy-fixture';
afterEach(() => { vi.unstubAllGlobals(); vi.unstubAllEnvs(); });
test('真实GET路径只读保原JSON，完整世界/分母/一步问题与无授权边界', async () => { const data = questionResponseFixture(); const requests = installHttpFixture(() => data); const result = await getQuestionSession(questionSession); expect(result.current_revision.evaluation.expected_world_count).toBe(2); expect(getOriginalQuestionResponse(result)).toBe(JSON.stringify(data)); expect(requests).toEqual([{ method: 'GET', path: `/api/v1/finite-planning/sessions/${questionSession}`, body: undefined }]); });
test.each(['authority', 'session', 'denominator', 'duplicate_world', 'choice', 'minimax', 'missing_world', 'money', 'old_question'])('响应%s不一致保守拒绝', (field) => {
  const data = questionResponseFixture(); const e = data.current_revision.evaluation;
  if (field === 'authority') (data as unknown as Record<string, unknown>).authority_granted = true; if (field === 'session') data.current_revision.session_id = data.current_revision.user_id; if (field === 'denominator') e.expected_world_count = 1; if (field === 'duplicate_world') e.worlds[1] = structuredClone(e.worlds[0]!); if (field === 'choice') data.pending_question!.choices[0]!.key = 'invented'; if (field === 'minimax') e.minimax_candidates[0]!.worst_residual_signature_count = 999; if (field === 'missing_world') e.worlds.pop(); if (field === 'money') e.worlds[0]!.outcome.effect = { ...(e.worlds[0]!.outcome.effect as object), amount_cents: Number.MAX_SAFE_INTEGER + 1 }; if (field === 'old_question') data.effective_state = 'STALE_RECOMPUTATION_REQUIRED';
  expect(() => parseQuestionResponse(data, questionSession)).toThrow();
});
test('UNKNOWN未计算保原expected和unknown分母；STALE隐藏旧问题，CLOSED无新financial观察', () => {
  const data = questionResponseFixture(); for (const revision of [data.original_receipt, data.current_revision]) { const e = revision.evaluation; Object.assign(e, { status: 'UNKNOWN', complete_within_declared_domain: false, evaluated_world_count: 0, known_world_count: 0, unknown_or_unsupported_world_count: 2, stable: null, should_ask: null, worlds: [], distinct_signatures: [], question: null, minimax_candidates: [] }); revision.state = 'UNKNOWN'; revision.pending_question = null; } data.effective_state = 'UNKNOWN'; data.pending_question = null; expect(parseQuestionResponse(data).current_revision.evaluation.expected_world_count).toBe(2);
  const stale = questionResponseFixture(); stale.effective_state = 'STALE_RECOMPUTATION_REQUIRED'; stale.pending_question = null; stale.current_source_fingerprint = 'c'.repeat(64); expect(parseQuestionResponse(stale).pending_question).toBeNull();
  const closed = questionResponseFixture(); Object.assign(closed.current_revision, { state: 'CLOSED', command_kind: 'CLOSE', revision: 17, previous_run_id: closed.original_receipt.run_id, pending_question: null }); closed.effective_state = 'CLOSED'; closed.pending_question = null; closed.fresh_evaluation_at = null; closed.current_source_fingerprint = null; expect(parseQuestionResponse(closed).current_revision.revision).toBe(17); closed.fresh_evaluation_at = closed.current_revision.as_of; expect(() => parseQuestionResponse(closed)).toThrow();
});
test('精确声明拒bool/额外授权/重复域/未登记source；严格ANSWER和CLOSE body', () => { const bad = structuredClone(questionVariables); (bad[0]!.choices[0]!.value as unknown as Record<string, unknown>).amount_cents = true; expect(() => parseQuestionVariables(bad)).toThrow(); expect(() => parseQuestionVariables([questionVariables[0], questionVariables[0]])).toThrow(); const evidence = structuredClone(questionVariables); evidence[0]!.source = 'REGISTERED_EVIDENCE'; expect(() => parseQuestionVariables(evidence)).toThrow(); expect(() => parseQuestionBody('CLOSE', { expected_epoch_id: questionSession, expected_revision: true, idempotency_key: 'x' })).toThrow(); expect(() => parseQuestionBody('ANSWER', { expected_epoch_id: questionSession, expected_revision: 1, idempotency_key: 'x', question_id: questionSession, choice_key: 'x', accepted: true })).toThrow(); });
test.each(['START', 'ANSWER', 'REFRESH', 'CLOSE'] as const)('真实%s原body/key POST与原键GET路径，latest不替换原回执', async (kind) => {
  vi.stubGlobal('crypto', webcrypto); const intent = await questionIntentFixture(kind); const lookup = questionLookupFixture(intent); const response = questionResponseFixture(); response.original_receipt = structuredClone(lookup.original_receipt!); response.current_revision = structuredClone(lookup.current_revision!); response.effective_state = response.current_revision.state; response.pending_question = response.current_revision.pending_question; if (kind === 'CLOSE') { response.fresh_evaluation_at = null; response.current_source_fingerprint = null; }
  const requests = installHttpFixture((method) => method === 'POST' ? response : lookup); const result = await postQuestionCommand(intent); expect(result.original_receipt.command_hash).toBe(intent.request_hash); expect((await lookupQuestionCommand(intent)).status).toBe('RECORDED'); expect(requests[0]!.body).toEqual(intent.body); expect(requests[1]!.method).toBe('GET'); expect(requests[1]!.path).toContain(kind === 'START' ? `/commands/${intent.body.expected_epoch_id}/by-start-key/` : `/${questionSession}/commands/by-key/`);
  lookup.current_revision!.command_key = 'LATER_REAL_KEY'; lookup.current_revision!.command_hash = 'c'.repeat(64); expect(parseQuestionLookup(lookup, intent).original_receipt!.command_key).toBe(intent.body.idempotency_key);
});
