import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { createSeasonalIntent, lookupSeasonalAdoption, parseSeasonalConfirmation, parseSeasonalIntent, parseSeasonalLookup, parseSeasonalPreview, parseSeasonalProof, parseSeasonalReceipt, parseSeasonalScope, postSeasonalAdoption, previewSeasonalAdoption, readSeasonalAdoption, seasonalCanonicalJson, seasonalHash, seasonalOriginalText, seasonalReviewHash } from './seasonal-reserve-adoptions';
import { seasonalFixture, seasonalIntentFixture, seasonalLookupFixture, seasonalProofFixture, seasonalReceiptFixture, unknownSeasonalPreview } from '../tests/seasonal-adoption-fixture';

beforeEach(() => { vi.stubGlobal('crypto', webcrypto); vi.stubEnv('VITE_API_BASE_URL', 'http://seasonal-reader.local'); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); });
test('仅原seasonal quantile允许精确小数，1.0保Python原字节，其他float/金额仍拒', async () => { expect(seasonalCanonicalJson({ type: 'seasonal_reserve', quantile: 1 })).toBe('{"quantile":1.0,"type":"seasonal_reserve"}'); expect(await seasonalHash({ type: 'seasonal_reserve', quantile: 1 })).toBe('712c48f71e3089adbd5447a4b7c2cbff0547bae3a02f49f5de4416e7f7b63e82'); expect(await seasonalHash({ type: 'seasonal_reserve', quantile: 0.8123 })).toBe('a8ffaefb01d6f04d6fbb8b8a46b14582331b63bf1344d52ddde3b887eebf81c9'); expect(() => seasonalCanonicalJson({ amount_cents: 1.5 })).toThrow(); expect(() => seasonalCanonicalJson({ type: 'other', quantile: 0.8 })).toThrow(); expect(() => seasonalCanonicalJson({ type: 'seasonal_reserve', quantile: 0.81234 })).toThrow(); });
test('原Python摘要/UUID与完整来源、固定金额一致，浏览器不会自行授权', async () => { const { scope, preview } = await seasonalFixture(), intent = await seasonalIntentFixture(), receipt = await seasonalReceiptFixture(intent); expect(scope.adopted_adjustment_cents).toBe(1800); expect(await seasonalReviewHash(scope)).toBe(preview.reviewed_hash); expect(await parseSeasonalReceipt(receipt, intent)).toEqual(receipt); expect(await parseSeasonalProof(seasonalProofFixture('VERIFIED'), scope.user_id, scope.policy_id)).toHaveProperty('bank_authority', false); });
test.each(['accepted', 'amount', 'role', 'epoch', 'reason'])('请求拒绝%s改变，不允许客户端金融输入/角色或空理由', async (bad) => { const value = structuredClone((await seasonalIntentFixture()).body) as unknown as Record<string, unknown>; if (bad === 'accepted') value.accepted = 1; if (bad === 'amount') value.amount_cents = 1800; if (bad === 'role') value.role = 'USER'; if (bad === 'epoch') value.expected_epoch_id = true; if (bad === 'reason') value.reason = ' '; expect(() => parseSeasonalConfirmation(value)).toThrow(); });
test.each(['bool', 'unsafe', 'owner', 'deleted-source', 'modified-source', 'future-income'])('原scope %s篡改拒绝', async (bad) => { const value = structuredClone((await seasonalFixture()).scope) as unknown as Record<string, unknown>; if (bad === 'bool') value.adopted_adjustment_cents = true; if (bad === 'unsafe') value.adopted_adjustment_cents = 9007199254740992; if (bad === 'owner') value.user_id = '00000000-0000-0000-0000-000000000099'; if (bad === 'deleted-source') (value.source_evidence_originals as unknown[]).pop(); if (bad === 'modified-source') (value.source_evidence_originals as { content_hash: string }[])[0]!.content_hash = 'f'.repeat(64); if (bad === 'future-income') value.future_income_in_current_cash_cents = 100; await expect(parseSeasonalScope(value)).rejects.toThrow(); });
test('UNKNOWN保留null和原因、原件与其他策略分母，不升级为零/VERIFIED', async () => { const { scope } = await seasonalFixture(); const unknown = seasonalProofFixture('UNKNOWN'); unknown.actual_adoption_count = 2; unknown.retained_command_ids.push('00000000-0000-0000-0000-000000000099'); expect((await parseSeasonalProof(unknown, scope.user_id, scope.policy_id)).status).toBe('UNKNOWN'); const advice = seasonalProofFixture(); advice.actual_adoption_count = 1; advice.retained_command_ids = ['00000000-0000-0000-0000-000000000099']; expect((await parseSeasonalProof(advice, scope.user_id, scope.policy_id)).actual_adoption_count).toBe(1); const empty = unknownSeasonalPreview(); expect(await parseSeasonalPreview(empty, scope.user_id, scope.policy_id, scope.version_id, scope.window_id)).toEqual(empty); });
test.each(['request', 'scope', 'hash', 'principal'])('完整回执 %s篡改即使外层重新hash仍拒', async (bad) => { const intent = await seasonalIntentFixture(), value = await seasonalReceiptFixture(intent); if (bad === 'request') value.original.original_request.reason = 'changed'; if (bad === 'scope') value.original.scope.adopted_adjustment_cents++; if (bad === 'hash') value.original.source_binding_hash = 'f'.repeat(64); if (bad === 'principal') value.original.principal_at_command.role = 'AGENT'; await expect(parseSeasonalReceipt(value, intent)).rejects.toThrow(); });
test('完整原body/hash/path受损不能恢复，不借不同key回执清门', async () => { const intent = await seasonalIntentFixture(), bad = structuredClone(intent); bad.body_json = '{}'; await expect(parseSeasonalIntent(bad)).rejects.toThrow(); const lookup = await seasonalLookupFixture(intent); lookup.idempotency_key = 'OTHER'; await expect(parseSeasonalLookup(lookup, intent)).rejects.toThrow(); const wrong = await createSeasonalIntent(intent.reviewed_scope, { ...intent.body, reason: 'other' }); await expect(parseSeasonalReceipt(await seasonalReceiptFixture(wrong), intent)).rejects.toThrow(); });
test('所有接口实际path和raw响应保留，CONFIRM只送原请求，不携角色/金额/时钟', async () => { const f = await seasonalFixture(), intent = await seasonalIntentFixture(), calls: { path: string; method: string; body: unknown }[] = []; vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL, options?: RequestInit) => { const path = new URL(String(input)).pathname, method = options?.method ?? 'GET'; calls.push({ path, method, body: options?.body ? JSON.parse(String(options.body)) : null }); const value = path.endsWith('/preview') ? f.preview : path.endsWith('/confirm') ? await seasonalReceiptFixture(intent) : path.includes('/by-key/') ? await seasonalLookupFixture(intent) : seasonalProofFixture(); return new Response(JSON.stringify(value)); })); const preview = await previewSeasonalAdoption(f.scope.user_id, f.scope.policy_id, f.scope.version_id, f.scope.window_id); expect(seasonalOriginalText(preview)).toBe(JSON.stringify(f.preview)); await postSeasonalAdoption(intent); await lookupSeasonalAdoption(intent); await readSeasonalAdoption(f.scope.user_id, f.scope.policy_id); expect(calls.map((c) => c.method)).toEqual(['POST', 'POST', 'GET', 'GET']); expect(calls[1]!.body).toEqual(intent.body); expect(JSON.stringify(calls[1]!.body)).not.toMatch(/amount_cents|actor|role|clock/); });
