import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { paymentActionFixture, paymentConsentFixture, paymentIntentFixture, paymentLookupFixture, paymentPreparedFixture } from '../tests/fixed-payment-fixture';
import type { PaymentIntent, PaymentRead } from '../api/full-payment-relations';
let operation: typeof import('./fixed-payment-operation'), api: typeof import('../api/full-payment-relations');
const endpoint = 'http://unit-fixed-payment.local', key = `bounded-funds-fixed-payment-operation-v1:${endpoint}`;
beforeEach(async () => { vi.resetModules(); vi.stubEnv('VITE_API_BASE_URL', endpoint); vi.stubGlobal('crypto', webcrypto); sessionStorage.clear(); operation = await import('./fixed-payment-operation'); api = await import('../api/full-payment-relations'); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); sessionStorage.clear(); });
async function read(intent: PaymentIntent, result: PaymentRead) { vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(result)))); return api.lookupPaymentIntent(intent); }
async function advance(kind: 'START' | 'CONFIRM' | 'PREPARE' | 'ACTION_CONFIRM', auto = false) { const intent = await paymentIntentFixture(kind, auto); await operation.beginFixedPaymentOperation(intent); operation.endFixedPaymentAttempt(); const result = kind === 'PREPARE' ? await paymentPreparedFixture(intent) : kind === 'ACTION_CONFIRM' ? await paymentConsentFixture(intent) : await paymentLookupFixture(intent); await operation.acceptFixedPaymentRead(intent, await read(intent, result)); return intent; }
async function prepared(auto = false) { await advance('START', auto); await advance('CONFIRM', auto); await advance('PREPARE', auto); }
test('POST前完整body/key/epoch/scope/hash持久，POST对象不清门，独立GET原件匹配才释放', async () => { const intent = await paymentIntentFixture(); await operation.beginFixedPaymentOperation(intent); const saved = JSON.parse(sessionStorage.getItem(key)!); expect(saved.pending).toEqual(intent); expect(saved.pending.body_json).toBe(JSON.stringify(intent.body)); operation.endFixedPaymentAttempt(); await expect(operation.acceptFixedPaymentRead(intent, await paymentLookupFixture(intent))).rejects.toThrow('独立GET'); expect(await operation.acceptFixedPaymentRead(intent, await read(intent, await paymentLookupFixture(intent, false)))).toBe(false); expect(operation.getFixedPaymentOperation().pending).toEqual(intent); await operation.acceptFixedPaymentRead(intent, await read(intent, await paymentLookupFixture(intent))); expect(operation.getFixedPaymentOperation().pending).toBeNull(); expect(operation.getFixedPaymentOperation().workflow.start!.original.idempotency_key).toBe('UNIT_START'); });
test('恢复原件不能自动POST，原body破坏保存储且锁写；只持历史不保存cookie/token/新grant', async () => { const intent = await paymentIntentFixture(); sessionStorage.setItem(key, JSON.stringify({ pending: intent, workflow: { start: null, authorization: null, prepared: null, action: null, consent: null } })); vi.stubGlobal('fetch', vi.fn()); await operation.recoverFixedPaymentOperation(); expect(operation.getFixedPaymentOperation().pending).toEqual(intent); expect(Object.isFrozen(operation.getFixedPaymentOperation().pending!.scope)).toBe(true); expect(fetch).not.toHaveBeenCalled(); expect(sessionStorage.getItem(key)).not.toMatch(/Bearer|secret|token/); });
test('损坏原件不删除或换键，storage fail发送前保原请求', async () => { sessionStorage.setItem(key, '{BROKEN'); await operation.recoverFixedPaymentOperation(); await expect(operation.beginFixedPaymentOperation(await paymentIntentFixture())).rejects.toThrow(); expect(sessionStorage.getItem(key)).toBe('{BROKEN'); });
test('storage set失败保pending不发，原GET核对后删除写失败不解除门', async () => { const intent = await paymentIntentFixture(); const denied = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('SYNTHETIC_STORAGE_DENIED'); }); await expect(operation.beginFixedPaymentOperation(intent)).rejects.toThrow('无法保存'); expect(operation.getFixedPaymentOperation().pending).toEqual(intent); denied.mockRestore(); expect(operation.getFixedPaymentOperation().busy).toBe(false); });
test('完整原START→CONFIRM→PREPARE→ASK同意→执行，每次独立GET前不能推进；UNKNOWN不清身份', async () => { await prepared(); const consent = await advance('ACTION_CONFIRM'), execute = await paymentIntentFixture('EXECUTE'); await operation.beginFixedPaymentOperation(execute); operation.endFixedPaymentAttempt(); const unknown = await paymentActionFixture(execute.scope, 'UNKNOWN'); expect(await operation.acceptFixedPaymentRead(execute, await read(execute, unknown))).toBe(false); expect(operation.getFixedPaymentOperation().pending).toEqual(execute); await expect(operation.beginFixedPaymentOperation(await paymentIntentFixture('START'))).rejects.toThrow(); const done = await paymentActionFixture(execute.scope, 'SUCCEEDED'); expect(await operation.acceptFixedPaymentRead(execute, await read(execute, done))).toBe(true); expect(operation.getFixedPaymentOperation().pending).toBeNull(); expect(operation.getFixedPaymentOperation().workflow.consent!.original!.original_effect_hash).toBe(consent.action!.effect_hash); });
test('ASK没有原签名USER同意不能execute；AUTO仍必须原GET动作、非当前存储授权', async () => { await prepared(); await expect(operation.beginFixedPaymentOperation(await paymentIntentFixture('EXECUTE'))).rejects.toThrow('ASK缺'); const intent = await paymentIntentFixture('PREPARE'); await expect(operation.beginFixedPaymentOperation(intent)).rejects.toThrow('尚未终局'); await expect(operation.beginFixedPaymentOperation(await paymentIntentFixture('START'))).rejects.toThrow('尚未终局'); });
test('外部门或全局inflight阻写，自身原GET不受外部门阻挡', async () => { const intent = await paymentIntentFixture(); await expect(operation.beginFixedPaymentOperation(intent, true)).rejects.toThrow(); await operation.beginFixedPaymentOperation(intent); operation.endFixedPaymentAttempt(); (await import('./write-flight')).beginWriteFlight(); expect(await operation.acceptFixedPaymentRead(intent, await read(intent, await paymentLookupFixture(intent)))).toBe(true); await expect(operation.beginFixedPaymentOperation(await paymentIntentFixture('CONFIRM'))).rejects.toThrow(); });
test('同原银行SETTLED但投影回执缺失仅手动原execute恢复，仍受外部门阻挡且不换body/key', async () => { await prepared(true); const execute = await paymentIntentFixture('EXECUTE', true); await operation.beginFixedPaymentOperation(execute); operation.endFixedPaymentAttempt(); const settled = await paymentActionFixture(execute.scope); settled.status = 'UNKNOWN'; settled.bank_status = 'SETTLED'; expect(await operation.acceptFixedPaymentRead(execute, await read(execute, settled))).toBe(false); await expect(operation.beginFixedPaymentSettlementResume(true)).rejects.toThrow('其他写门'); expect(operation.getFixedPaymentOperation().pending).toEqual(execute); const original = await operation.beginFixedPaymentSettlementResume(); expect(original).toEqual(execute); operation.endFixedPaymentAttempt(); expect(operation.getFixedPaymentOperation().pending).toEqual(execute); });
test('完整工作区刷新只恢复历史，不继承原GET动作标记/执行授权，须重新读原action', async () => { await prepared(true); const saved = sessionStorage.getItem(key); vi.resetModules(); operation = await import('./fixed-payment-operation'); api = await import('../api/full-payment-relations'); await operation.recoverFixedPaymentOperation(); expect(sessionStorage.getItem(key)).toBe(saved); await expect(operation.beginFixedPaymentOperation(await paymentIntentFixture('EXECUTE', true))).rejects.toThrow('独立GET'); const action = operation.getFixedPaymentOperation().workflow.action!, scope = operation.getFixedPaymentOperation().workflow.authorization!.original.scope; vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(await paymentActionFixture(scope))))); await operation.retainFixedPaymentActionRead(await api.readPaymentAction(action, scope)); await operation.beginFixedPaymentOperation(await paymentIntentFixture('EXECUTE', true)); expect(operation.getFixedPaymentOperation().pending!.action!.action_id).toBe(action.action_id); });
test.each(['ADVISE_ONLY', 'BLOCKED'])('实际%s等级不能通过单次同意升级执行', async (level) => { await prepared(true); const action = operation.getFixedPaymentOperation().workflow.action!, scope = operation.getFixedPaymentOperation().workflow.authorization!.original.scope; const current = { ...action, autonomy_level: level }; vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(current)))); await operation.retainFixedPaymentActionRead(await api.readPaymentAction(action, scope)); await expect(operation.beginFixedPaymentOperation(await paymentIntentFixture('EXECUTE', true))).rejects.toThrow('不能用用户同意升级'); });
