import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { fullGoalIntentFixture, fullGoalLookupFixture, fullPreviewFixture, otherGoalId } from '../tests/full-goal-fixture';
let operation: typeof import('./full-goal-operation');
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubEnv('VITE_API_BASE_URL', 'http://unit-full-goal-operation.local'); vi.stubGlobal('crypto', webcrypto); operation = await import('./full-goal-operation'); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); sessionStorage.clear(); });
test('POST前精确保原body/key/user/goal/epoch/双hash，HTTP结束仍pending；NOT_FOUND非终局', async () => {
  const original = await fullGoalIntentFixture(); vi.stubGlobal('fetch', vi.fn()); operation.beginFullGoalOperation(original); expect(sessionStorage.getItem(sessionStorage.key(0)!)).toBe(JSON.stringify(original)); expect(operation.getFullGoalOperation().busy).toBe(true); operation.endFullGoalAttempt(); await expect(operation.clearFullGoalOperationAfterLookup(original, fullGoalLookupFixture(original, false))).rejects.toThrow(); expect(operation.getFullGoalOperation().pending).toEqual(original); expect(fetch).not.toHaveBeenCalled();
});
test('原同键body手动重放；不能新key、goal或配置替换pending', async () => {
  const original = await fullGoalIntentFixture(); operation.beginFullGoalOperation(original); operation.endFullGoalAttempt(); operation.beginFullGoalOperation(original); operation.endFullGoalAttempt(); const changed = await fullGoalIntentFixture('different-key'); expect(() => operation.beginFullGoalOperation(changed)).toThrow('禁止换'); const newGoal = await operation.prepareFullGoalIntent({ user_id: original.user_id, goal_id: otherGoalId, policy_id: original.policy_id, body: original.body }); expect(() => operation.beginFullGoalOperation(newGoal)).toThrow('禁止换'); expect(operation.getFullGoalOperation().pending!.body_json).toBe(original.body_json);
});
test('只完整RECORDED原request/hash/receipt核对释放，本地和原回执不含current授权', async () => {
  const original = await fullGoalIntentFixture(); operation.beginFullGoalOperation(original); operation.endFullGoalAttempt(); await operation.clearFullGoalOperationAfterLookup(original, fullGoalLookupFixture(original)); expect(operation.getFullGoalOperation()).toEqual({ pending: null, busy: false, storage_error: null }); expect(sessionStorage.length).toBe(0);
});
test.each(['key', 'body', 'goal', 'policy', 'epoch', 'expected_version', 'receipt_version', 'full_hash', 'base_hash', 'request_hash', 'authority', 'audit', 'extra_request'])('原lookup %s漂移保持完整记录', async (field) => {
  const original = await fullGoalIntentFixture(); const bad = fullGoalLookupFixture(original); const record = bad.record!;
  if (field === 'key') bad.idempotency_key = 'different-key'; if (field === 'body') record.original_request.reason = 'different-reason'; if (field === 'goal') bad.goal_id = otherGoalId; if (field === 'policy') record.receipt.lifecycle.policy_id = otherGoalId; if (field === 'epoch') record.receipt.epoch_id = otherGoalId; if (field === 'expected_version') record.original_request.expected_version_id = otherGoalId; if (field === 'receipt_version') record.receipt.lifecycle.current_version_id = original.body.expected_version_id; if (field === 'full_hash') record.receipt.full_configuration_hash = '0'.repeat(64); if (field === 'base_hash') record.receipt.base_configuration_hash = '0'.repeat(64); if (field === 'request_hash') record.request_hash = '0'.repeat(64); if (field === 'authority') (bad as unknown as Record<string, unknown>).bank_authority = true; if (field === 'audit') (record as unknown as Record<string, unknown>).audit_chain_verified = false; if (field === 'extra_request') (record.original_request as unknown as Record<string, unknown>).grant = true;
  operation.beginFullGoalOperation(original); operation.endFullGoalAttempt(); const raw = sessionStorage.getItem(sessionStorage.key(0)!); await expect(operation.clearFullGoalOperationAfterLookup(original, bad)).rejects.toThrow(); expect(sessionStorage.getItem(sessionStorage.key(0)!)).toBe(raw);
});
test('原规范化请求hash跨Python协议固定golden，字段顺序不变hash；owner/goal变化改变hash', async () => {
  const original = await fullGoalIntentFixture(); expect(original.request_hash).toBe('ae4a40a6aeb3e0798af773e54ccb4cbbc21b645bacca107c9dff64dbc42b4030'); const sorted = { ...original.body, configuration: Object.fromEntries(Object.entries(original.body.configuration).reverse()) }; expect(await operation.fullGoalRequestHash(original.user_id, original.goal_id, sorted)).toBe(original.request_hash); expect(await operation.fullGoalRequestHash(otherGoalId, original.goal_id, original.body)).not.toBe(original.request_hash); expect(await operation.fullGoalRequestHash(original.user_id, otherGoalId, original.body)).not.toBe(original.request_hash);
});
test('刷新只严格恢复原request不HTTP；未知字段/坏JSON不静默清记录', async () => {
  const original = await fullGoalIntentFixture(); sessionStorage.setItem('bounded-funds-full-goal-operation-v1:http://unit-full-goal-operation.local', JSON.stringify(original)); vi.stubGlobal('fetch', vi.fn()); expect(operation.recoverFullGoalOperation().pending).toEqual(original); expect(Object.isFrozen(operation.getFullGoalOperation().pending!.body)).toBe(true); expect(fetch).not.toHaveBeenCalled(); expect(operation.validFullGoalIntent({ ...original, granted: true })).toBe(false); expect(operation.validFullGoalIntent({ ...original, body_json: '{}' })).toBe(false);
});
test('坏session/读取失败锁新确认并保持原字节', async () => {
  const original = await fullGoalIntentFixture(); const raw = '{malformed-original'; sessionStorage.setItem('bounded-funds-full-goal-operation-v1:http://unit-full-goal-operation.local', raw); expect(operation.recoverFullGoalOperation().storage_error).not.toBeNull(); expect(() => operation.beginFullGoalOperation(original)).toThrow(); expect(sessionStorage.getItem('bounded-funds-full-goal-operation-v1:http://unit-full-goal-operation.local')).toBe(raw);
});
test('存储写失败未进入busy；删除失败即使原lookup匹配仍门关闭', async () => {
  const original = await fullGoalIntentFixture(); const spy = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('UNIT_STORAGE_DENIED'); }); expect(() => operation.beginFullGoalOperation(original)).toThrow('无法保存'); expect(operation.getFullGoalOperation().busy).toBe(false); expect(operation.getFullGoalOperation().pending).toEqual(original); spy.mockRestore(); vi.spyOn(Storage.prototype, 'removeItem').mockImplementation(() => { throw new Error('UNIT_DELETE_DENIED'); }); await expect(operation.clearFullGoalOperationAfterLookup(original, fullGoalLookupFixture(original))).rejects.toThrow('无法删除'); expect(operation.getFullGoalOperation().pending).toEqual(original);
});
test.each(['demo', 'policy', 'onboarding', 'writeflight', 'external'])('他族%s原pending/忙阻止新确认，未生成本族pending', async (family) => {
  const original = await fullGoalIntentFixture();
  if (family === 'demo') sessionStorage.setItem('bounded-funds-demo-operation-v1:http://unit-full-goal-operation.local', JSON.stringify({ kind: 'reset', epoch_id: null, reset_key: 'UNIT_OTHER_ORIGINAL' }));
  if (family === 'policy') { const policy = await import('./full-policy-operation'); const { createFullIntent } = await import('../tests/full-policy-fixture'); policy.beginFullPolicyOperation(createFullIntent()); policy.endFullPolicyAttempt(); }
  if (family === 'onboarding') { const onboarding = await import('./onboarding-draft'); const { onboardingBinding, emergencyText } = await import('../tests/onboarding-fixture'); onboarding.beginOnboardingCommand(onboarding.prepareOnboardingIntent('EMERGENCY', onboardingBinding(), emergencyText)); onboarding.endOnboardingAttempt(); }
  if (family === 'writeflight') (await import('./write-flight')).beginWriteFlight(); expect(() => operation.beginFullGoalOperation(original, family === 'external')).toThrow('其他原请求'); expect(operation.getFullGoalOperation().pending).toBeNull();
});
test('缺crypto能力/未明确接受/长key/跨goalgrant拒绝；本地hash改写不能凭serverflags清门', async () => {
  const original = await fullGoalIntentFixture(); const invalid = { user_id: original.user_id, goal_id: original.goal_id, policy_id: original.policy_id, body: original.body }; await expect(operation.prepareFullGoalIntent({ ...invalid, body: { ...original.body, accepted: false as never } })).rejects.toThrow(); await expect(operation.prepareFullGoalIntent({ ...invalid, body: { ...original.body, idempotency_key: 'x'.repeat(151) } })).rejects.toThrow(); const patch = { ...original, request_hash: '0'.repeat(64) }; const forged = fullGoalLookupFixture(patch); expect(await operation.recordedFullGoalLookupMatches(patch, forged)).toBe(false); const preview = fullPreviewFixture(); await expect(operation.prepareFullGoalIntent({ ...invalid, body: { ...original.body, configuration: { ...preview.full_configuration, cross_goal_reallocation_allowed: true } } })).rejects.toThrow(); vi.stubGlobal('crypto', { randomUUID: () => 'UNIT_ONLY' }); await expect(operation.prepareFullGoalIntent(invalid)).rejects.toThrow('安全摘要');
});
