import { webcrypto } from 'node:crypto';
import { beforeEach, afterEach, expect, test, vi } from 'vitest';
import { recoveryActionFixture, recoveryLookupFixture, recoveryPrepareFixture, recoveryUser } from '../tests/full-recovery-execution-fixture';
let operation: typeof import('./full-recovery-execution-operation'), api: typeof import('../api/full-recovery-execution');
const endpoint = import.meta.env.VITE_API_BASE_URL ?? 'same-origin', key = `bounded-funds-full-recovery-execution-operation-v1:${endpoint}`;
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubGlobal('crypto', webcrypto); api = await import('../api/full-recovery-execution'); operation = await import('./full-recovery-execution-operation'); }); afterEach(() => vi.unstubAllGlobals());
async function read(intent: import('../api/full-recovery-execution').RecoveryIntent, stage: Parameters<typeof recoveryLookupFixture>[1] = 'PREPARED') { vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(recoveryLookupFixture(intent, stage))))); return api.lookupRecoveryExecution(intent); }
test('POST前原body/hash/key深冻结持久化，仅独立原GET释放prepare并保工作区', async () => { const intent = await operation.prepareRecoveryIntent('PREPARE', recoveryUser, recoveryPrepareFixture()); await operation.beginFullRecoveryOperation(intent); expect(sessionStorage.getItem(key)).toBe(JSON.stringify(intent)); expect(Object.isFrozen(operation.getFullRecoveryOperation().pending!.prepare_request)).toBe(true); operation.endFullRecoveryAttempt(); await expect(operation.acceptFullRecoveryRead(intent, await api.parseRecoveryLookup(recoveryLookupFixture(intent), intent))).rejects.toThrow(); expect((await operation.acceptFullRecoveryRead(intent, await read(intent))).complete).toBe(true); expect(operation.getFullRecoveryOperation().workspace?.action).not.toBeNull(); expect(sessionStorage.getItem(key)).toBeNull(); });
test('NOT_FOUND非终局不能更换原键/仓位/轮次，手动同body重放仍同原请求', async () => { const i = await operation.prepareRecoveryIntent('PREPARE', recoveryUser, recoveryPrepareFixture()); await operation.beginFullRecoveryOperation(i); operation.endFullRecoveryAttempt(); expect((await operation.acceptFullRecoveryRead(i, await read(i, 'NOT_FOUND'))).complete).toBe(false); await expect(operation.beginFullRecoveryOperation(await operation.prepareRecoveryIntent('PREPARE', recoveryUser, { ...recoveryPrepareFixture(), idempotency_key: 'SECOND_KEY' }))).rejects.toThrow('不能换'); await operation.beginFullRecoveryOperation(i); expect(operation.getFullRecoveryOperation().pending).toEqual(i); });
test('AUTHORIZED缺独立USER同意不释放确认，原consent完整匹配后才释放', async () => { const i = await operation.prepareRecoveryIntent('CONFIRM', recoveryUser, recoveryPrepareFixture(), recoveryActionFixture()); await operation.beginFullRecoveryOperation(i); operation.endFullRecoveryAttempt(); expect((await operation.acceptFullRecoveryRead(i, await read(i, 'MISSING_CONSENT'))).complete).toBe(false); expect((await operation.acceptFullRecoveryRead(i, await read(i, 'CONFIRMED'))).complete).toBe(true); });
test('银行SETTLED但应用无receipt仍UNKNOWN，执行沿同原Action至原receipt', async () => { const i = await operation.prepareRecoveryIntent('EXECUTE', recoveryUser, recoveryPrepareFixture(), recoveryActionFixture('CONFIRMED')); await operation.beginFullRecoveryOperation(i); operation.endFullRecoveryAttempt(); expect((await operation.acceptFullRecoveryRead(i, await read(i, 'UNKNOWN'))).complete).toBe(false); expect(operation.getFullRecoveryOperation().pending).toEqual(i); expect((await operation.acceptFullRecoveryRead(i, await read(i, 'SETTLED'))).complete).toBe(true); });
test('busy/另一原请求不可用latest清门，原件不变', async () => { const i = await operation.prepareRecoveryIntent('PREPARE', recoveryUser, recoveryPrepareFixture()); await operation.beginFullRecoveryOperation(i); const v = await read(i); await expect(operation.acceptFullRecoveryRead(i, v)).rejects.toThrow(); operation.endFullRecoveryAttempt(); const foreign = await operation.prepareRecoveryIntent('PREPARE', recoveryUser, { ...recoveryPrepareFixture(), idempotency_key: 'FOREIGN' }); await expect(operation.acceptFullRecoveryRead(foreign, v)).rejects.toThrow(); expect(operation.getFullRecoveryOperation().pending).toEqual(i); });
test('刷新严格恢复原body/key/Action，无自动网络或授权，workspace须独立GET', async () => { const i = await operation.prepareRecoveryIntent('EXECUTE', recoveryUser, recoveryPrepareFixture(), recoveryActionFixture('CONFIRMED')); sessionStorage.setItem(key, JSON.stringify(i)); vi.stubGlobal('fetch', vi.fn()); const s = await operation.recoverFullRecoveryOperation(); expect(s.pending).toEqual(i); expect(fetch).not.toHaveBeenCalled(); expect(Object.isFrozen(s.pending!.action!.effect)).toBe(true); });
test.each(['{BROKEN', JSON.stringify({ protocol: 'full-recovery-browser-v1' })])('坏存储保持原bytes并锁住写门 %s', async (raw) => { sessionStorage.setItem(key, raw); expect((await operation.recoverFullRecoveryOperation()).storage_error).not.toBeNull(); await expect(operation.beginFullRecoveryOperation(await operation.prepareRecoveryIntent('PREPARE', recoveryUser, recoveryPrepareFixture()))).rejects.toThrow(); expect(sessionStorage.getItem(key)).toBe(raw); });
test('存储拒绝时无POST；成功GET后remove失败仍保持原门', async () => { const i = await operation.prepareRecoveryIntent('PREPARE', recoveryUser, recoveryPrepareFixture()); vi.stubGlobal('fetch', vi.fn()); const spy = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('TOOL_ONLY_DENIED'); }); await expect(operation.beginFullRecoveryOperation(i)).rejects.toThrow('未发送'); expect(fetch).not.toHaveBeenCalled(); spy.mockRestore(); vi.spyOn(Storage.prototype, 'removeItem').mockImplementation(() => { throw new Error('TOOL_ONLY_DENIED'); }); await expect(operation.acceptFullRecoveryRead(i, await read(i))).rejects.toThrow('无法关闭'); expect(operation.getFullRecoveryOperation().pending).toEqual(i); });
test.each(['external', 'demo', 'dynamic_storage', 'payment_storage', 'writeflight'] as const)('跨族%s阻新写但自身GET不被锁', async (family) => { const i = await operation.prepareRecoveryIntent('PREPARE', recoveryUser, recoveryPrepareFixture()); if (family === 'demo') (await import('./demo-operation')).beginDemoOperation({ kind: 'reset', epoch_id: null, reset_key: 'TOOL_ONLY' }); if (family === 'dynamic_storage') sessionStorage.setItem(`bounded-funds-full-dynamic-goal-operation-v1:${endpoint}`, '{BAD'); if (family === 'payment_storage') sessionStorage.setItem(`bounded-funds-fixed-payment-operation-v1:${endpoint}`, '{BAD'); if (family === 'writeflight') (await import('./write-flight')).beginWriteFlight(); await expect(operation.beginFullRecoveryOperation(i, family === 'external')).rejects.toThrow(); expect((await read(i)).status).toBe('RECORDED'); if (family === 'writeflight') (await import('./write-flight')).endWriteFlight(); });
test('fixed workspace未终局禁第二键，原GET刷新后可明确同一次确认', async () => { const i = await operation.prepareRecoveryIntent('PREPARE', recoveryUser, recoveryPrepareFixture()); await operation.beginFullRecoveryOperation(i); operation.endFullRecoveryAttempt(); await operation.acceptFullRecoveryRead(i, await read(i)); expect(operation.isFullRecoveryWorkspaceUnresolved(operation.getFullRecoveryOperation().workspace!)).toBe(true); await expect(operation.beginFullRecoveryOperation(await operation.prepareRecoveryIntent('PREPARE', recoveryUser, { ...recoveryPrepareFixture(), idempotency_key: 'NEW_KEY' }))).rejects.toThrow('未终局'); const check = await operation.fullRecoveryWorkspaceIntent(); await operation.acceptFullRecoveryWorkspaceRead(check, await read(check)); const confirmation = await operation.prepareRecoveryIntent('CONFIRM', recoveryUser, recoveryPrepareFixture(), operation.getFullRecoveryOperation().workspace!.action); await operation.beginFullRecoveryOperation(confirmation); expect(operation.getFullRecoveryOperation().pending!.kind).toBe('CONFIRM'); });
