import { webcrypto } from 'node:crypto';
import { beforeEach, expect, it, vi } from 'vitest';
import { jointConfirmFixture, jointFixtureId, jointLookupFixture, jointPlanFixture, jointResponseFixture } from '../tests/full-joint-goal-execution-fixture';
const storageKey = 'bounded-funds-joint-goal-operation-v2:same-origin';
beforeEach(() => { vi.resetModules(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.stubGlobal('crypto', webcrypto); vi.stubGlobal('fetch', vi.fn()); sessionStorage.clear(); });
async function modules() { return { api: await import('../api/full-joint-goal-execution'), store: await import('./full-joint-goal-operation') }; }
function serve(value: unknown) { vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(value), { status: 200 }))); }
async function prepared() { const m = await modules(), p = jointPlanFixture(), intent = await m.store.prepareJointIntent('PREPARE', p.user_id, p.inputs.request); await m.store.beginFullJointGoalOperation(intent); m.store.endFullJointGoalAttempt(); serve(jointLookupFixture(intent)); const lookup = await m.api.lookupJointExecution(intent); await m.store.acceptFullJointGoalRead(intent, lookup); return { ...m, p, intent }; }
it('persists exact complete original before sending, every POST outcome leaves pending', async () => { const { store } = await modules(), p = jointPlanFixture(), intent = await store.prepareJointIntent('PREPARE', p.user_id, p.inputs.request); await store.beginFullJointGoalOperation(intent); expect(JSON.parse(sessionStorage.getItem(storageKey)!).pending.body_json).toBe(JSON.stringify(p.inputs.request)); store.endFullJointGoalAttempt(); expect(store.getFullJointGoalOperation().pending?.request_hash).toBe(intent.request_hash); expect(fetch).not.toHaveBeenCalled(); });
it('stored/body-hash tamper and denied storage lock new writes without deleting originals', async () => { const p = jointPlanFixture(), m = await modules(), intent = await m.store.prepareJointIntent('PREPARE', p.user_id, p.inputs.request); sessionStorage.setItem(storageKey, JSON.stringify({ protocol: 'joint-goal-workspace-v2', pending: { ...intent, request_hash: '0'.repeat(64) }, workspace_reference: null })); await m.store.recoverFullJointGoalOperation(); expect(m.store.getFullJointGoalOperation().storage_error).not.toBeNull(); await expect(m.store.beginFullJointGoalOperation(intent)).rejects.toThrow(); expect(sessionStorage.getItem(storageKey)).toContain('000000'); });
it('session quota failure does not send or release new writes', async () => { const { store } = await modules(), p = jointPlanFixture(), intent = await store.prepareJointIntent('PREPARE', p.user_id, p.inputs.request); vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('TOOL_ONLY quota', 'QuotaExceededError'); }); await expect(store.beginFullJointGoalOperation(intent)).rejects.toThrow(); expect(store.getFullJointGoalOperation().pending).not.toBeNull(); expect(store.getFullJointGoalOperation().storage_error).not.toBeNull(); });
it('POST-shaped parse or NOT_FOUND cannot clear original', async () => { const { api, store } = await modules(), p = jointPlanFixture(), intent = await store.prepareJointIntent('PREPARE', p.user_id, p.inputs.request); await store.beginFullJointGoalOperation(intent); store.endFullJointGoalAttempt(); const lookup = jointLookupFixture(intent); await expect(store.acceptFullJointGoalRead(intent, await api.parseJointLookup(lookup, intent))).rejects.toThrow(); serve({ ...lookup, status: 'NOT_FOUND_NOT_FINAL', command_kind: null, original_request: null, original_request_hash: null, original: null }); const result = await store.acceptFullJointGoalRead(intent, await api.lookupJointExecution(intent)); expect(result.complete).toBe(false); expect(store.getFullJointGoalOperation().pending).not.toBeNull(); });
it('successful original key GET retains bounded locator with ALL commands; no full source/1098 truncation on server', async () => { const { store, p } = await prepared(), state = store.getFullJointGoalOperation(); expect(state.pending).toBeNull(); expect(state.workspace_reference?.children).toHaveLength(p.children.length); expect(JSON.stringify(state.workspace_reference)).not.toContain('hard_protection_points'); expect(state.original?.original_plan.allocation_input.hard_protection_points).toHaveLength(1098); expect(sessionStorage.getItem(storageKey)!.length).toBeLessThan(20000); expect(store.isFullJointGoalWorkspaceUnresolved()).toBe(true); });
it('reload restores locator only, performs NO GET/POST, and requires full current invocation GET before confirm', async () => { const { p } = await prepared(); vi.resetModules(); const { api, store } = await modules(); const fetch = vi.fn(); vi.stubGlobal('fetch', fetch); await store.recoverFullJointGoalOperation(); expect(fetch).not.toHaveBeenCalled(); expect(store.getFullJointGoalOperation().original).toBeNull(); const intent = await store.prepareJointIntent('CONFIRM', p.user_id, jointConfirmFixture(), p); await expect(store.beginFullJointGoalOperation(intent)).rejects.toThrow(); serve(jointResponseFixture()); await store.acceptFullJointGoalWorkspaceRead(await api.getJointExecution(p.plan_id, p.user_id, api.jointReviewBinding(p))); await expect(store.beginFullJointGoalOperation(intent)).resolves.toBeUndefined(); });
it('unresolved workspace blocks replacement root key or parent but permits exact original preparation completion', async () => { const { store, p } = await prepared(); const replacement = await store.prepareJointIntent('PREPARE', p.user_id, { ...p.inputs.request, idempotency_key: 'new-root-unsafe' }); await expect(store.beginFullJointGoalOperation(replacement)).rejects.toThrow(); await expect(store.beginFullJointGoalOperation(await store.prepareJointIntent('PREPARE', p.user_id, p.inputs.request))).resolves.toBeUndefined(); });
it('confirmed/UNKNOWN original workspace never releases the cross-family gate', async () => { const { api, store, p } = await prepared(); serve(jointResponseFixture('UNKNOWN')); await store.acceptFullJointGoalWorkspaceRead(await api.getJointExecution(p.plan_id)); expect(store.isFullJointGoalWorkspaceUnresolved()).toBe(true); const other = await store.prepareJointIntent('PREPARE', p.user_id, { ...p.inputs.request, idempotency_key: 'OTHER_001' }); await expect(store.beginFullJointGoalOperation(other)).rejects.toThrow(); });
it('EXECUTE clears only its exact fixed child verified GET, never another settled child or latest', async () => { const { api, store, p } = await prepared(); serve(jointResponseFixture('FIRST_SETTLED')); await store.acceptFullJointGoalWorkspaceRead(await api.getJointExecution(p.plan_id)); const second = p.children[1]!, intent = await store.prepareJointIntent('EXECUTE', p.user_id, { accepted: true, reviewed_plan_hash: p.plan_hash, expected_epoch_id: p.epoch_id, expected_child_number: second.child_number, expected_action_id: second.action_id }, p); await store.beginFullJointGoalOperation(intent); store.endFullJointGoalAttempt(); serve(jointResponseFixture('FIRST_SETTLED')); const firstOnly = await store.acceptFullJointGoalRead(intent, await api.getJointExecution(p.plan_id)); expect(firstOnly.complete).toBe(false); expect(store.getFullJointGoalOperation().pending).not.toBeNull(); serve(jointResponseFixture('SETTLED')); expect((await store.acceptFullJointGoalRead(intent, await api.getJointExecution(p.plan_id))).complete).toBe(true); expect(store.isFullJointGoalWorkspaceUnresolved()).toBe(false); }, 15000);
it('mismatched fixed child/action/body after save cannot bypass original request', async () => { const { store, p } = await prepared(), intent = await store.prepareJointIntent('CONFIRM', p.user_id, jointConfirmFixture(), p); await store.beginFullJointGoalOperation(intent); store.endFullJointGoalAttempt(); const replacement = await store.prepareJointIntent('CONFIRM', p.user_id, { ...jointConfirmFixture(), idempotency_key: 'NEW_CONFIRM' }, p); await expect(store.beginFullJointGoalOperation(replacement)).rejects.toThrow(); const mutated = structuredClone(intent); mutated.user_id = jointFixtureId(99); await expect(store.beginFullJointGoalOperation(mutated)).rejects.toThrow(); });
it('external mutation gate and shared write flight block POST but own independent GET remains available', async () => { const { api, store } = await modules(), p = jointPlanFixture(), intent = await store.prepareJointIntent('PREPARE', p.user_id, p.inputs.request); await expect(store.beginFullJointGoalOperation(intent, true)).rejects.toThrow(); const { beginWriteFlight, endWriteFlight } = await import('./write-flight'); beginWriteFlight(); await expect(store.beginFullJointGoalOperation(intent)).rejects.toThrow(); serve(jointResponseFixture()); expect((await api.getJointExecution(p.plan_id)).original_plan.plan_id).toBe(p.plan_id); endWriteFlight(); });

it('prior unverified child blocks a new explicit later-child request before any POST', async () => { const { store, p } = await prepared(); const child = p.children[1]!; const intent = await store.prepareJointIntent('EXECUTE', p.user_id, { accepted: true, reviewed_plan_hash: p.plan_hash, expected_epoch_id: p.epoch_id, expected_child_number: child.child_number, expected_action_id: child.action_id }, p); await expect(store.beginFullJointGoalOperation(intent)).rejects.toThrow(); expect(store.getFullJointGoalOperation().pending).toBeNull(); });
