import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { releaseIntentFixture, releaseLookupFixture } from '../tests/goal-release-authorization-fixture';
let operation: typeof import('./goal-release-authorization-operation');
const endpoint = 'http://unit-goal-release-operation.local', key = `bounded-funds-goal-release-authorization-operation-v1:${endpoint}`;
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubEnv('VITE_API_BASE_URL', endpoint); vi.stubGlobal('crypto', webcrypto); operation = await import('./goal-release-authorization-operation'); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); sessionStorage.clear(); });
test('发送前保存全部scope/body/key/owner/版本/两hash，HTTP任何结果不清门；原GET匹配才解除', async () => { const intent = await releaseIntentFixture(); vi.stubGlobal('fetch', vi.fn()); await operation.beginGoalReleaseAuthorizationOperation(intent); expect(JSON.parse(sessionStorage.getItem(key)!)).toEqual(intent); expect(operation.getGoalReleaseAuthorizationOperation().busy).toBe(true); operation.endGoalReleaseAuthorizationAttempt(); await expect(operation.clearGoalReleaseAuthorizationAfterLookup(intent, await releaseLookupFixture(intent, false))).rejects.toThrow('不是最终'); expect(operation.getGoalReleaseAuthorizationOperation().pending).toEqual(intent); await operation.clearGoalReleaseAuthorizationAfterLookup(intent, await releaseLookupFixture(intent)); expect(operation.getGoalReleaseAuthorizationOperation().pending).toBeNull(); expect(sessionStorage.getItem(key)).toBeNull(); expect(fetch).not.toHaveBeenCalled(); });
test('同原请求可核，不同key/scope不能代替未知原件；busy期间GET不能清门', async () => { const intent = await releaseIntentFixture(); await operation.beginGoalReleaseAuthorizationOperation(intent); await expect(operation.clearGoalReleaseAuthorizationAfterLookup(intent, await releaseLookupFixture(intent))).rejects.toThrow(); operation.endGoalReleaseAuthorizationAttempt(); const replacement = await releaseIntentFixture('NEW_KEY'); await expect(operation.beginGoalReleaseAuthorizationOperation(replacement)).rejects.toThrow('禁止换键'); expect(operation.getGoalReleaseAuthorizationOperation().pending!.body_json).toBe(intent.body_json); });
test('页面刷新只恢复原请求，无HTTP/自动POST；恶意额外字段、body序列变化或破坏JSON锁住新写', async () => { const intent = await releaseIntentFixture(); sessionStorage.setItem(key, JSON.stringify(intent)); vi.stubGlobal('fetch', vi.fn()); expect(operation.recoverGoalReleaseAuthorizationOperation().pending).toEqual(intent); expect(Object.isFrozen(operation.getGoalReleaseAuthorizationOperation().pending!.reviewed_scope.source_goals)).toBe(true); expect(fetch).not.toHaveBeenCalled(); expect(operation.validGoalReleaseIntent({ ...intent, authority: true })).toBe(false); expect(operation.validGoalReleaseIntent({ ...intent, body_json: '{}' })).toBe(false); });
test('损坏或无读取权限原存储不丢弃，storage_error锁新确认', async () => { const raw = '{BROKEN_ORIGINAL'; sessionStorage.setItem(key, raw); const intent = await releaseIntentFixture(); expect(operation.recoverGoalReleaseAuthorizationOperation().storage_error).not.toBeNull(); await expect(operation.beginGoalReleaseAuthorizationOperation(intent)).rejects.toThrow(); expect(sessionStorage.getItem(key)).toBe(raw); });
test('存储set失败不HTTP；remove失败即使原记录匹配仍保pending', async () => { const intent = await releaseIntentFixture(); const spy = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('SYNTHETIC_DENIED'); }); await expect(operation.beginGoalReleaseAuthorizationOperation(intent)).rejects.toThrow('无法保存'); expect(operation.getGoalReleaseAuthorizationOperation().busy).toBe(false); expect(operation.getGoalReleaseAuthorizationOperation().pending).toEqual(intent); spy.mockRestore(); vi.spyOn(Storage.prototype, 'removeItem').mockImplementation(() => { throw new Error('SYNTHETIC_DELETE_DENIED'); }); await expect(operation.clearGoalReleaseAuthorizationAfterLookup(intent, await releaseLookupFixture(intent))).rejects.toThrow('无法删除'); expect(operation.getGoalReleaseAuthorizationOperation().pending).toEqual(intent); });
test.each(['demo', 'policy', 'goal', 'onboarding', 'question-storage', 'spending-storage', 'intervention-storage', 'writeflight', 'external'])('他族%s阻新授权，未生成替代原key', async (family) => { const intent = await releaseIntentFixture();
  if (family === 'demo') sessionStorage.setItem(`bounded-funds-demo-operation-v1:${endpoint}`, JSON.stringify({ kind: 'reset', epoch_id: null, reset_key: 'UNIT_OTHER' }));
  if (family === 'policy') { const p = await import('./full-policy-operation'), f = await import('../tests/full-policy-fixture'); p.beginFullPolicyOperation(f.createFullIntent()); p.endFullPolicyAttempt(); }
  if (family === 'goal') { const g = await import('./full-goal-operation'), f = await import('../tests/full-goal-fixture'); g.beginFullGoalOperation(await f.fullGoalIntentFixture()); g.endFullGoalAttempt(); }
  if (family === 'onboarding') { const o = await import('./onboarding-draft'), f = await import('../tests/onboarding-fixture'); o.beginOnboardingCommand(o.prepareOnboardingIntent('EMERGENCY', f.onboardingBinding(), f.emergencyText)); o.endOnboardingAttempt(); }
  if (family === 'question-storage') sessionStorage.setItem(`bounded-funds-one-question-operation-v1:${endpoint}`, '{BROKEN');
  if (family === 'spending-storage') sessionStorage.setItem(`bounded-funds-spending-category-operation-v1:${endpoint}`, '{BROKEN');
  if (family === 'intervention-storage') sessionStorage.setItem(`bounded-funds-intervention-operation-v1:${endpoint}`, '{BROKEN');
  if (family === 'writeflight') (await import('./write-flight')).beginWriteFlight();
  await expect(operation.beginGoalReleaseAuthorizationOperation(intent, family === 'external')).rejects.toThrow(); expect(operation.getGoalReleaseAuthorizationOperation().pending).toBeNull();
});
test('伪造本地request/hash或scopehash与服务success不能释放，缺crypto不发送', async () => { const intent = await releaseIntentFixture(); const forged = structuredClone(intent); forged.request_hash = 'a'.repeat(64); expect(await operation.goalReleaseIntentHashMatches(forged)).toBe(false); await expect(operation.beginGoalReleaseAuthorizationOperation(forged)).rejects.toThrow(); await operation.beginGoalReleaseAuthorizationOperation(intent); operation.endGoalReleaseAuthorizationAttempt(); const lookup = await releaseLookupFixture(intent); lookup.original!.original_authorization.original_request.reviewed_scope_hash = 'b'.repeat(64); await expect(operation.clearGoalReleaseAuthorizationAfterLookup(intent, lookup)).rejects.toThrow(); expect(operation.getGoalReleaseAuthorizationOperation().pending).toEqual(intent); vi.stubGlobal('crypto', {}); await expect(operation.goalReleaseIntentHashMatches(intent)).rejects.toThrow('安全摘要'); });
test('STALE/ARCHIVED exact原记录可解决是否记录，不能冒当前资金权限', async () => { const intent = await releaseIntentFixture(); await operation.beginGoalReleaseAuthorizationOperation(intent); operation.endGoalReleaseAuthorizationAttempt(); const lookup = await releaseLookupFixture(intent, true, 'ARCHIVED'); await operation.clearGoalReleaseAuthorizationAfterLookup(intent, lookup); expect(operation.getGoalReleaseAuthorizationOperation().pending).toBeNull(); expect(lookup.original!.current_scope_status).toBe('ARCHIVED'); expect(lookup.original!.execution_support).toBe('NOT_IMPLEMENTED'); });
