import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { questionIntentFixture, questionLookupFixture } from '../tests/question-fixture';
let operation: typeof import('./one-question-operation');
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubEnv('VITE_API_BASE_URL', 'http://unit-question-store.local'); vi.stubGlobal('crypto', webcrypto); operation = await import('./one-question-operation'); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); sessionStorage.clear(); });
test('提交前持原body/hash/key，任意HTTP完成仍pending；NOT_FOUND非终局且不同key不可绕过', async () => { const intent = await questionIntentFixture(); await operation.beginOneQuestionOperation(intent); expect(sessionStorage.getItem(sessionStorage.key(0)!)).toBe(JSON.stringify(intent)); operation.endOneQuestionAttempt(); await expect(operation.clearOneQuestionAfterLookup(intent, questionLookupFixture(intent, false))).rejects.toThrow(); await expect(operation.beginOneQuestionOperation(await questionIntentFixture('START', 'NEW_KEY'))).rejects.toThrow('禁止换键'); expect(operation.getOneQuestionOperation().pending).toEqual(intent); });
test.each(['START', 'ANSWER', 'REFRESH', 'CLOSE'] as const)('%s独立GET完整原件匹配才清；同原请求可手动重放且无自动HTTP', async (kind) => { const intent = await questionIntentFixture(kind); vi.stubGlobal('fetch', vi.fn()); await operation.beginOneQuestionOperation(intent); operation.endOneQuestionAttempt(); await operation.beginOneQuestionOperation(intent); operation.endOneQuestionAttempt(); await operation.clearOneQuestionAfterLookup(intent, questionLookupFixture(intent)); expect(operation.getOneQuestionOperation().pending).toBeNull(); expect(fetch).not.toHaveBeenCalled(); });
test.each(['body', 'owner', 'epoch', 'key', 'hash', 'receipt', 'latest', 'grant', 'previous', 'kind'] as const)('原键%s漂移不清原存储', async (field) => {
  const intent = await questionIntentFixture('ANSWER'); await operation.beginOneQuestionOperation(intent); operation.endOneQuestionAttempt(); const bad = questionLookupFixture(intent); if (field === 'body') (bad.original_command!.request as Record<string, unknown>).choice_key = 'large'; if (field === 'owner') bad.original_command!.user_id = bad.epoch_id; if (field === 'epoch') bad.epoch_id = bad.session_id!; if (field === 'key') bad.idempotency_key = 'OTHER'; if (field === 'hash') bad.request_hash = '0'.repeat(64); if (field === 'receipt') bad.original_receipt!.command_hash = '0'.repeat(64); if (field === 'latest') bad.current_revision!.session_id = bad.epoch_id; if (field === 'grant') (bad as unknown as Record<string, unknown>).authority_granted = true; if (field === 'previous') bad.original_receipt!.previous_run_id = bad.epoch_id; if (field === 'kind') bad.original_command!.kind = 'REFRESH'; const raw = sessionStorage.getItem(sessionStorage.key(0)!); await expect(operation.clearOneQuestionAfterLookup(intent, bad)).rejects.toThrow(); expect(sessionStorage.getItem(sessionStorage.key(0)!)).toBe(raw);
});
test('刷新仅恢复不可变原body；未知字段/坏JSON/存储禁用锁门，不自动POST', async () => { const intent = await questionIntentFixture(); sessionStorage.setItem('bounded-funds-one-question-operation-v1:http://unit-question-store.local', JSON.stringify(intent)); vi.stubGlobal('fetch', vi.fn()); expect(operation.recoverOneQuestionOperation().pending).toEqual(intent); expect(Object.isFrozen(operation.getOneQuestionOperation().pending!.body)).toBe(true); expect(operation.validOneQuestionIntent({ ...intent, authority: true })).toBe(false); expect(fetch).not.toHaveBeenCalled(); });
test('存储读写/删除失败保原件且不发送', async () => { const intent = await questionIntentFixture(); const spy = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('TOOL_ONLY_STORAGE_DENIED'); }); await expect(operation.beginOneQuestionOperation(intent)).rejects.toThrow('无法保存'); expect(operation.getOneQuestionOperation().busy).toBe(false); spy.mockRestore(); vi.spyOn(Storage.prototype, 'removeItem').mockImplementation(() => { throw new Error('TOOL_ONLY_DELETE_DENIED'); }); await expect(operation.clearOneQuestionAfterLookup(intent, questionLookupFixture(intent))).rejects.toThrow('无法删除'); expect(operation.getOneQuestionOperation().pending).toEqual(intent); });
test('原hash按实际Python configuration_hash固定golden；键序不改hash，伪hash不能提交', async () => { const intent = await questionIntentFixture(); expect(intent.request_hash).toBe('88252db764fd1c2f67631d379d0d8cf89cb956e65317914479531c30e72ece63'); const reverse = { ...intent, body: Object.fromEntries(Object.entries(intent.body).reverse()) as typeof intent.body }; reverse.body_json = JSON.stringify(reverse.body); expect(await operation.oneQuestionRequestHash(reverse)).toBe(intent.request_hash); const forged = { ...intent, request_hash: '0'.repeat(64) }; await expect(operation.beginOneQuestionOperation(forged)).rejects.toThrow('body/hash'); expect(operation.getOneQuestionOperation().pending).toBeNull(); });
test('坏原JSON不能静默替换或新键绕过，原存储字节不变', async () => { const original = '{TOOL_ONLY_BAD_ORIGINAL'; const storage = 'bounded-funds-one-question-operation-v1:http://unit-question-store.local'; sessionStorage.setItem(storage, original); expect(operation.recoverOneQuestionOperation().storage_error).not.toBeNull(); await expect(operation.beginOneQuestionOperation(await questionIntentFixture())).rejects.toThrow(); expect(sessionStorage.getItem(storage)).toBe(original); });
test('匹配后只读session定位跨重启恢复，不含授权或自动POST', async () => { const intent = await questionIntentFixture(); await operation.beginOneQuestionOperation(intent); operation.endOneQuestionAttempt(); await operation.clearOneQuestionAfterLookup(intent, questionLookupFixture(intent)); const reference = operation.getOneQuestionOperation().session; expect(reference).toEqual({ protocol: 'one-question-read-reference-v1', user_id: intent.user_id, epoch_id: intent.body.expected_epoch_id, session_id: questionLookupFixture(intent).session_id }); vi.resetModules(); const restored = await import('./one-question-operation'); vi.stubGlobal('fetch', vi.fn()); expect(restored.recoverOneQuestionOperation().session).toEqual(reference); expect(restored.getOneQuestionOperation().pending).toBeNull(); expect(fetch).not.toHaveBeenCalled(); });
test.each(['external', 'writeflight', 'goal', 'corrupt_demo'] as const)('他族%s门阻止新问答', async (family) => { const intent = await questionIntentFixture(); if (family === 'writeflight') (await import('./write-flight')).beginWriteFlight(); if (family === 'goal') { const goal = await import('./full-goal-operation'); const { fullGoalIntentFixture } = await import('../tests/full-goal-fixture'); goal.beginFullGoalOperation(await fullGoalIntentFixture()); goal.endFullGoalAttempt(); } if (family === 'corrupt_demo') sessionStorage.setItem('bounded-funds-demo-operation-v1:http://unit-question-store.local', '{BAD_ORIGINAL'); await expect(operation.beginOneQuestionOperation(intent, family === 'external')).rejects.toThrow('其他原请求'); expect(operation.getOneQuestionOperation().pending).toBeNull(); });
