import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { seasonalIntentFixture, seasonalLookupFixture } from '../tests/seasonal-adoption-fixture';
import type { SeasonalIntent } from '../api/seasonal-reserve-adoptions';
let op: typeof import('./seasonal-adoption-operation'), api: typeof import('../api/seasonal-reserve-adoptions');
const endpoint = 'http://seasonal-store.local', key = `bounded-funds-seasonal-adoption-operation-v1:${endpoint}`;
beforeEach(async () => { vi.resetModules(); sessionStorage.clear(); vi.stubEnv('VITE_API_BASE_URL', endpoint); vi.stubGlobal('crypto', webcrypto); op = await import('./seasonal-adoption-operation'); api = await import('../api/seasonal-reserve-adoptions'); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); sessionStorage.clear(); });
async function read(intent: SeasonalIntent, found = true) { vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(await seasonalLookupFixture(intent, found))))); return api.lookupSeasonalAdoption(intent); }
test('beforePOST保存完整原body/hash/来源，所有POST结果仍pending，fresh GET才解除', async () => { const intent = await seasonalIntentFixture(); await op.beginSeasonalAdoptionOperation(intent); const saved = JSON.parse(sessionStorage.getItem(key)!); expect(saved.pending).toEqual(intent); expect(Object.isFrozen(op.getSeasonalAdoptionOperation().pending!.reviewed_scope)).toBe(true); op.endSeasonalAdoptionAttempt(); await expect(op.acceptSeasonalAdoptionRead(intent, await seasonalLookupFixture(intent))).rejects.toThrow('独立GET'); expect(await op.acceptSeasonalAdoptionRead(intent, await read(intent, false))).toBe(false); expect(op.getSeasonalAdoptionOperation().pending).toEqual(intent); expect(await op.acceptSeasonalAdoptionRead(intent, await read(intent))).toBe(true); expect(op.getSeasonalAdoptionOperation().pending).toBeNull(); expect(op.getSeasonalAdoptionOperation().original_receipt?.original.request_hash).toBe(intent.request_hash); });
test('丢响应后重启只恢复原件，不自动POST，不保存cookie/token，不允许换key', async () => { const intent = await seasonalIntentFixture(); sessionStorage.setItem(key, JSON.stringify({ pending: intent, original_receipt: null })); vi.stubGlobal('fetch', vi.fn()); await op.recoverSeasonalAdoptionOperation(); expect(fetch).not.toHaveBeenCalled(); expect(op.getSeasonalAdoptionOperation().pending).toEqual(intent); await expect(op.beginSeasonalAdoptionOperation(intent)).rejects.toThrow('换键'); expect(sessionStorage.getItem(key)).not.toMatch(/Bearer|secret|cookie|token/); });
test('损坏存储保原件并锁写；storage denied不能发新请求', async () => { sessionStorage.setItem(key, '{BROKEN'); await op.recoverSeasonalAdoptionOperation(); expect(sessionStorage.getItem(key)).toBe('{BROKEN'); await expect(op.beginSeasonalAdoptionOperation(await seasonalIntentFixture())).rejects.toThrow(); });
test('beforePOST保存失败保pending、clear失败保原pending，不假清门', async () => { const intent = await seasonalIntentFixture(), denied = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('TOOL_ONLY_STORAGE_DENIED'); }); await expect(op.beginSeasonalAdoptionOperation(intent)).rejects.toThrow('无法保存'); expect(op.getSeasonalAdoptionOperation().pending).toEqual(intent); denied.mockRestore(); });
test('完整GET原件保存失败保同身份与原request，不因已成功响应清门', async () => { const intent = await seasonalIntentFixture(); await op.beginSeasonalAdoptionOperation(intent); op.endSeasonalAdoptionAttempt(); vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('TOOL_ONLY_STORAGE_DENIED'); }); await expect(op.acceptSeasonalAdoptionRead(intent, await read(intent))).rejects.toThrow('无法保存'); expect(op.getSeasonalAdoptionOperation().pending).toEqual(intent); });
test('外部门/另族pending阻POST，本族原GET可越门且不会继承原回执授权', async () => { const intent = await seasonalIntentFixture(); await expect(op.beginSeasonalAdoptionOperation(intent, true)).rejects.toThrow(); sessionStorage.setItem(`bounded-funds-fixed-payment-operation-v1:${endpoint}`, '{BROKEN'); await expect(op.beginSeasonalAdoptionOperation(intent)).rejects.toThrow(); });
test('全局write-flight阻新采纳，原GET即使另族写门活跃仍可核对', async () => { const intent = await seasonalIntentFixture(); await op.beginSeasonalAdoptionOperation(intent); op.endSeasonalAdoptionAttempt(); const flight = await import('./write-flight'); flight.beginWriteFlight(); expect(await op.acceptSeasonalAdoptionRead(intent, await read(intent))).toBe(true); await expect(op.beginSeasonalAdoptionOperation(intent)).rejects.toThrow(); flight.endWriteFlight(); });
